#!/usr/bin/env python3
"""
=============================================================================
EXPERIMENTAL/FUTURE - NOT USED BY CURRENT v7 PIPELINE
=============================================================================
This file is part of the experimental op_builders system for future IR2 work.
It is NOT called by ck_run_v7.py or the current build pipeline.

Related files: parse_template_v2.py, op_builders_v7.py, op_builders_hybrid_v7.py
Current pipeline uses: build_ir_v7.py with kernel maps directly.
=============================================================================

op_builders_auto.py - Auto-generated Op Builders from Kernel Registry

GENERATED BY: gen_op_builders_from_registry.py
DO NOT EDIT MANUALLY - Changes will be overwritten!

This file is automatically generated from the kernel registry to ensure
perfect alignment between kernels and IR ops.
"""

import sys
from pathlib import Path
from typing import Dict, Any, Optional, List

# Add parent to path for imports
_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from ir_types_v7 import Op
from parse_template_v2 import OpNode


# =============================================================================
# OP CONTEXT: State Tracker
# =============================================================================

class OpContext:
    """
    Tracks state during op building.

    Maintains:
    - Previous op outputs (for input chaining)
    - Op counters (for unique naming)
    - Current tensor (for residual connections)
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.prev_output: Optional[str] = None
        self.residual_input: Optional[str] = None

        # Per-layer counters (reset each layer)
        self.rmsnorm_count = 0
        self.residual_count = 0

    def set_output(self, output: str):
        """Update previous output for next op."""
        self.prev_output = output

    def save_residual(self):
        """Save current output for residual connection."""
        self.residual_input = self.prev_output

    def reset_layer(self):
        """Reset counters for new layer."""
        self.rmsnorm_count = 0
        self.residual_count = 0
        self.residual_input = None


# =============================================================================
# TENSOR NAMING HELPERS
# =============================================================================

def make_tensor_name(op_node: OpNode, suffix: str) -> str:
    """Generate symbolic tensor name."""
    if op_node.phase == "body" and op_node.layer_index is not None:
        return f"layer.{op_node.layer_index}.{suffix}"
    else:
        # Header/footer: global names
        return suffix


def make_weight_name(op_node: OpNode, weight: str) -> str:
    """Generate weight tensor name."""
    if op_node.phase == "body" and op_node.layer_index is not None:
        return f"layer.{op_node.layer_index}.{weight}"
    else:
        return weight


# =============================================================================
# AUTO-GENERATED OP BUILDERS
# =============================================================================

def build_attention_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build attention op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    k_name = make_tensor_name(op_node, 'k')
    v_name = make_tensor_name(op_node, 'v')
    output_name = make_tensor_name(op_node, 'out')
    # No weights

    op = Op(
        op="attention",
        name=make_tensor_name(op_node, "attention"),
        inputs=[input_name, k_name, v_name],
        outputs=[output_name],
        weights=[],
        scratch=['qkv_scratch', 'attn_scratch'],
        params={
        'num_heads': ctx.config.get('num_heads', 0),
        'num_kv_heads': ctx.config.get('num_kv_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_attention_projection_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build attention_projection op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    wo_name = make_tensor_name(op_node, 'wo')
    bo_name = make_tensor_name(op_node, 'bo')
    scratch_name = make_tensor_name(op_node, 'scratch')
    output_name = make_tensor_name(op_node, 'out')
    wo_weight = make_weight_name(op_node, 'wo')

    op = Op(
        op="attention_projection",
        name=make_tensor_name(op_node, "attention_projection"),
        inputs=[input_name, wo_name, bo_name, scratch_name],
        outputs=[output_name],
        weights=[wo_weight],
        scratch=[],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'num_heads': ctx.config.get('num_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_embedding_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build embedding op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    weight_name = make_tensor_name(op_node, 'weight')
    output_name = make_tensor_name(op_node, 'output')
    weight_weight = make_weight_name(op_node, 'weight')

    op = Op(
        op="embedding",
        name=make_tensor_name(op_node, "embedding"),
        inputs=[input_name, weight_name],
        outputs=[output_name],
        weights=[weight_weight],
        scratch=[],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'vocab_size': ctx.config.get('vocab_size', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_fused_attention_block_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build fused_attention_block op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    residual_name = make_tensor_name(op_node, 'residual')
    ln_gamma_name = make_tensor_name(op_node, 'ln_gamma')
    wq_name = make_tensor_name(op_node, 'wq')
    bq_name = make_tensor_name(op_node, 'bq')
    wk_name = make_tensor_name(op_node, 'wk')
    bk_name = make_tensor_name(op_node, 'bk')
    wv_name = make_tensor_name(op_node, 'wv')
    bv_name = make_tensor_name(op_node, 'bv')
    wo_name = make_tensor_name(op_node, 'wo')
    bo_name = make_tensor_name(op_node, 'bo')
    kv_cache_k_name = make_tensor_name(op_node, 'kv_cache_k')
    kv_cache_v_name = make_tensor_name(op_node, 'kv_cache_v')
    rope_cos_name = make_tensor_name(op_node, 'rope_cos')
    rope_sin_name = make_tensor_name(op_node, 'rope_sin')
    output_name = make_tensor_name(op_node, 'output')
    wq_weight = make_weight_name(op_node, 'wq')
    wk_weight = make_weight_name(op_node, 'wk')
    wv_weight = make_weight_name(op_node, 'wv')
    wo_weight = make_weight_name(op_node, 'wo')

    op = Op(
        op="fused_attention_block",
        name=make_tensor_name(op_node, "fused_attention_block"),
        inputs=[input_name, residual_name, ln_gamma_name, wq_name, bq_name, wk_name, bk_name, wv_name, bv_name, wo_name, bo_name, kv_cache_k_name, kv_cache_v_name, rope_cos_name, rope_sin_name],
        outputs=[output_name],
        weights=[wq_weight, wk_weight, wv_weight, wo_weight],
        scratch=['scratch'],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'num_heads': ctx.config.get('num_heads', 0),
        'num_kv_heads': ctx.config.get('num_kv_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_fused_mlp_block_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build fused_mlp_block op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    residual_name = make_tensor_name(op_node, 'residual')
    ln2_gamma_name = make_tensor_name(op_node, 'ln2_gamma')
    wo_name = make_tensor_name(op_node, 'wo')
    bo_name = make_tensor_name(op_node, 'bo')
    w1_name = make_tensor_name(op_node, 'w1')
    b1_name = make_tensor_name(op_node, 'b1')
    w2_name = make_tensor_name(op_node, 'w2')
    b2_name = make_tensor_name(op_node, 'b2')
    output_name = make_tensor_name(op_node, 'output')
    wo_weight = make_weight_name(op_node, 'wo')
    w1_weight = make_weight_name(op_node, 'w1')
    w2_weight = make_weight_name(op_node, 'w2')

    op = Op(
        op="fused_mlp_block",
        name=make_tensor_name(op_node, "fused_mlp_block"),
        inputs=[input_name, residual_name, ln2_gamma_name, wo_name, bo_name, w1_name, b1_name, w2_name, b2_name],
        outputs=[output_name],
        weights=[wo_weight, w1_weight, w2_weight],
        scratch=['scratch'],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'num_heads': ctx.config.get('num_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
        'intermediate_size': ctx.config.get('intermediate_size', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_fused_qkv_block_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build fused_qkv_block op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    ln_gamma_name = make_tensor_name(op_node, 'ln_gamma')
    wq_name = make_tensor_name(op_node, 'wq')
    bq_name = make_tensor_name(op_node, 'bq')
    wk_name = make_tensor_name(op_node, 'wk')
    bk_name = make_tensor_name(op_node, 'bk')
    wv_name = make_tensor_name(op_node, 'wv')
    bv_name = make_tensor_name(op_node, 'bv')
    q_name = make_tensor_name(op_node, 'q')
    k_name = make_tensor_name(op_node, 'k')
    v_name = make_tensor_name(op_node, 'v')
    wq_weight = make_weight_name(op_node, 'wq')
    wk_weight = make_weight_name(op_node, 'wk')
    wv_weight = make_weight_name(op_node, 'wv')

    op = Op(
        op="fused_qkv_block",
        name=make_tensor_name(op_node, "fused_qkv_block"),
        inputs=[input_name, ln_gamma_name, wq_name, bq_name, wk_name, bk_name, wv_name, bv_name],
        outputs=[q_name, k_name, v_name],
        weights=[wq_weight, wk_weight, wv_weight],
        scratch=['temp'],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'num_heads': ctx.config.get('num_heads', 0),
        'num_kv_heads': ctx.config.get('num_kv_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([q_name, k_name, v_name][0] if [q_name, k_name, v_name] else None)
    return op

def build_gemm_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build gemm op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    B_name = make_tensor_name(op_node, 'B')
    bias_name = make_tensor_name(op_node, 'bias')
    output_name = make_tensor_name(op_node, 'C')
    A_weight = make_weight_name(op_node, 'A')
    B_weight = make_weight_name(op_node, 'B')

    op = Op(
        op="gemm",
        name=make_tensor_name(op_node, "gemm"),
        inputs=[input_name, B_name, bias_name],
        outputs=[output_name],
        weights=[A_weight, B_weight],
        scratch=[],
        params={}
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_gemv_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build gemv op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    x_name = make_tensor_name(op_node, 'x')
    output_name = make_tensor_name(op_node, 'y')
    W_weight = make_weight_name(op_node, 'W')

    op = Op(
        op="gemv",
        name=make_tensor_name(op_node, "gemv"),
        inputs=[input_name, x_name],
        outputs=[output_name],
        weights=[W_weight],
        scratch=[],
        params={}
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_qkv_projection_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build qkv_projection op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    wq_name = make_tensor_name(op_node, 'wq')
    bq_name = make_tensor_name(op_node, 'bq')
    wk_name = make_tensor_name(op_node, 'wk')
    bk_name = make_tensor_name(op_node, 'bk')
    wv_name = make_tensor_name(op_node, 'wv')
    bv_name = make_tensor_name(op_node, 'bv')
    q_name = make_tensor_name(op_node, 'q')
    k_name = make_tensor_name(op_node, 'k')
    v_name = make_tensor_name(op_node, 'v')
    wq_weight = make_weight_name(op_node, 'wq')
    wk_weight = make_weight_name(op_node, 'wk')
    wv_weight = make_weight_name(op_node, 'wv')

    op = Op(
        op="qkv_projection",
        name=make_tensor_name(op_node, "qkv_projection"),
        inputs=[input_name, wq_name, bq_name, wk_name, bk_name, wv_name, bv_name],
        outputs=[q_name, k_name, v_name],
        weights=[wq_weight, wk_weight, wv_weight],
        scratch=[],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
        'num_heads': ctx.config.get('num_heads', 0),
        'num_kv_heads': ctx.config.get('num_kv_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([q_name, k_name, v_name][0] if [q_name, k_name, v_name] else None)
    return op

def build_quantize_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build quantize op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    output_name = make_tensor_name(op_node, 'output')
    # No weights

    op = Op(
        op="quantize",
        name=make_tensor_name(op_node, "quantize"),
        inputs=[input_name],
        outputs=[output_name],
        weights=[],
        scratch=[],
        params={}
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_residual_add_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build residual_add op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    b_name = make_tensor_name(op_node, 'b')
    output_name = make_tensor_name(op_node, 'out')
    # No weights

    op = Op(
        op="residual_add",
        name=make_tensor_name(op_node, "residual_add"),
        inputs=[input_name, b_name],
        outputs=[output_name],
        weights=[],
        scratch=[],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op

def build_rmsnorm_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build rmsnorm op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    gamma_name = make_tensor_name(op_node, 'gamma')
    output_name = make_tensor_name(op_node, 'output')
    rstd_name = make_tensor_name(op_node, 'rstd')
    # No weights

    op = Op(
        op="rmsnorm",
        name=make_tensor_name(op_node, "rmsnorm"),
        inputs=[input_name, gamma_name],
        outputs=[output_name, rstd_name],
        weights=[],
        scratch=['mean', 'variance'],
        params={
        'embed_dim': ctx.config.get('embed_dim', 0),
    }
    )
    ctx.set_output([output_name, rstd_name][0] if [output_name, rstd_name] else None)
    return op

def build_rope_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build rope op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    k_name = make_tensor_name(op_node, 'k')
    cos_cache_name = make_tensor_name(op_node, 'cos_cache')
    sin_cache_name = make_tensor_name(op_node, 'sin_cache')
    q_name = make_tensor_name(op_node, 'q')
    k_name = make_tensor_name(op_node, 'k')
    # No weights

    op = Op(
        op="rope",
        name=make_tensor_name(op_node, "rope"),
        inputs=[input_name, k_name, cos_cache_name, sin_cache_name],
        outputs=[q_name, k_name],
        weights=[],
        scratch=[],
        params={
        'num_heads': ctx.config.get('num_heads', 0),
        'num_kv_heads': ctx.config.get('num_kv_heads', 0),
        'head_dim': ctx.config.get('head_dim', 0),
    }
    )
    ctx.set_output([q_name, k_name][0] if [q_name, k_name] else None)
    return op

def build_swiglu_op(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Op:
    """Build swiglu op (auto-generated from kernel registry)."""
    input_name = ctx.prev_output or make_tensor_name(op_node, 'input')
    up_name = make_tensor_name(op_node, 'up')
    output_name = make_tensor_name(op_node, 'out')
    # No weights

    op = Op(
        op="swiglu",
        name=make_tensor_name(op_node, "swiglu"),
        inputs=[input_name, up_name],
        outputs=[output_name],
        weights=[],
        scratch=['gate_activated'],
        params={
        'intermediate_size': ctx.config.get('intermediate_size', 0),
    }
    )
    ctx.set_output([output_name][0] if [output_name] else None)
    return op


# =============================================================================
# OP BUILDER REGISTRY
# =============================================================================

OP_BUILDERS = {
    "attention": build_attention_op,
    "attention_projection": build_attention_projection_op,
    "embedding": build_embedding_op,
    "fused_attention_block": build_fused_attention_block_op,
    "fused_mlp_block": build_fused_mlp_block_op,
    "fused_qkv_block": build_fused_qkv_block_op,
    "gemm": build_gemm_op,
    "gemv": build_gemv_op,
    "qkv_projection": build_qkv_projection_op,
    "quantize": build_quantize_op,
    "residual_add": build_residual_add_op,
    "rmsnorm": build_rmsnorm_op,
    "rope": build_rope_op,
    "swiglu": build_swiglu_op,
}


# =============================================================================
# PUBLIC API
# =============================================================================

def build_op_from_template(op_node: OpNode, ctx: OpContext, manifest: Dict) -> Optional[Op]:
    """
    Build GraphIR Op from template OpNode.

    Args:
        op_node: OpNode from parse_template_v2
        ctx: OpContext for state tracking
        manifest: Weights manifest

    Returns:
        Op object or None if op should be skipped

    Raises:
        ValueError: If op_id has no builder
    """
    if op_node.op_id not in OP_BUILDERS:
        raise ValueError(
            f"No builder for template op: '{op_node.op_id}'. "
            f"Supported ops: {', '.join(sorted(OP_BUILDERS.keys()))}"
        )

    builder = OP_BUILDERS[op_node.op_id]
    return builder(op_node, ctx, manifest)


def get_supported_ops() -> List[str]:
    """Get list of supported template op IDs."""
    return sorted(OP_BUILDERS.keys())


def check_template_ops(template_ops: List[str]) -> List[str]:
    """
    Check which template ops are missing builders.

    Args:
        template_ops: List of op IDs from template

    Returns:
        List of unsupported op IDs
    """
    supported = set(OP_BUILDERS.keys())
    return [op for op in template_ops if op not in supported]
