#!/usr/bin/env python3
"""
ir_types_v6_6.py - v6.6 IR Type Definitions

PURPOSE:
    Defines the data structures (classes, enums, constants) used throughout
    the v6.6 pipeline. This is the "vocabulary" for the IR system.

FILE RELATIONSHIPS:
    ┌─────────────────────────────────────────────────────────────────┐
    │ ir_types_v6_6.py                                                │
    │   - Defines: Op, LayerIR, GraphIR, Buffer, etc.                │
    │   - Auto-generates OpType enum from KERNEL_REGISTRY.json       │
    └─────────────────────────────────────────────────────────────────┘
                                    │
                                    ▼ uses
    ┌─────────────────────────────────────────────────────────────────┐
    │ build_ir_v6_6.py                                                │
    │   - Pipeline orchestration                                      │
    │   - Uses ir_types classes to build IR instances                 │
    └─────────────────────────────────────────────────────────────────┘
                                    │
                                    ▼ reads
    ┌─────────────────────────────────────────────────────────────────┐
    │ kernel_maps/KERNEL_REGISTRY.json                                │
    │   - Canonical list of all available kernels                     │
    │   - Generated by gen_kernel_registry_from_maps.py               │
    └─────────────────────────────────────────────────────────────────┘

USAGE:
    from .ir_types_v6_6 import Op, LayerIR, GraphIR, OpType, resolve_kernel_template

NO BACKWARD COMPATIBILITY:
    v6.6-only. No dependencies on v1-v5 code.

IR PIPELINE STAGES:
    Template + Config → GraphIR → LoweredIR → Layout → Schedule → Codegen
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Any, Iterable
from enum import Enum
import json
import re


# =============================================================================
# SECTION 1: PATH CONSTANTS
# =============================================================================
#
# Path to the kernel registry file.
# Generated by: python version/v6.6/scripts/gen_kernel_registry_from_maps.py

_SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_KERNEL_REGISTRY_PATH = _SCRIPT_DIR.parent / "kernel_maps" / "KERNEL_REGISTRY.json"


# =============================================================================
# SECTION 2: ENUMS
# =============================================================================
#
# Enums define sets of related constants.
# OpType is auto-generated from registry at import time (see end of file).
#
# DType: Data types (native: fp32/fp16, quantized: q5_0/q4_k, etc.)
# Mode: Execution modes (prefill: many tokens, decode: single token, train: forward+backward)


class DType(Enum):
    """Data types."""
    FP32 = "fp32"
    FP16 = "fp16"
    BF16 = "bf16"
    Q8_0 = "q8_0"
    Q5_0 = "q5_0"
    Q4_K = "q4_k"
    Q6_K = "q6_k"
    Q8_K = "q8_k"
    INT8 = "i8"
    INT32 = "int32"


class Mode(Enum):
    """Execution mode."""
    PREFILL = "prefill"
    DECODE = "decode"
    TRAIN = "train"  # Note: pipeline passes mode as "training" string, this is the enum value


# =============================================================================
# SECTION 3: DATA CLASSES (IR TYPES)
# =============================================================================
#
# Core data structures of the IR system.
# These define what information flows through the pipeline.
#
# IR PIPELINE STAGES:
#   GraphIR    - Ops only, no kernel selection yet
#   LoweredIR  - Ops + kernel IDs (after lowering)
#   Layout     - Memory offsets (after layout planning)
#   Schedule   - Execution order (after scheduling)
#
# Example flow:
#   Template + Config → GraphIR → LoweredIR → Layout → Schedule → Codegen (C code)

@dataclass
class Buffer:
    """
    Memory buffer specification.

    A Buffer represents a region of memory that holds data during execution.
    It can be:
      - activation: intermediate computation result (e.g., layer output)
      - weight: model parameter (loaded from BUMP file)
      - scratch: temporary storage used by a kernel

    Example:
        Buffer(
            name="layer.0.ln1_out",
            dtype="fp32",
            shape=["T", "AE"],  # Symbolic: T=tokens, AE=aligned_embed
            role="activation"
        )
    """
    name: str
    dtype: str
    shape: List[str]  # Symbolic dimensions
    role: str = "activation"  # "weight", "activation", "scratch"
    offset: int = 0  # Memory offset (set during layout planning)
    size: int = 0  # Size in bytes (set during layout planning)
    tied_to: Optional[str] = None  # Name of buffer this is tied to


@dataclass
class Weight:
    """
    Weight tensor specification.

    Similar to Buffer but specifically for model parameters.
    Includes quantization metadata.

    Example:
        Weight(
            name="layer.0.wq",  # Q projection weight
            dtype="q5_0",
            shape=["H*AD", "AE"],
            quant="q5_0"  # Quantization format
        )
    """
    name: str
    dtype: str
    shape: List[str]  # Symbolic dimensions
    quant: Optional[str] = None  # Quantization format if applicable


@dataclass
class Op:
    """
    IR Operation.

    Represents ONE operation in the computation graph.
    Corresponds to ONE kernel call in generated C code.

    Before lowering (kernel not yet selected):
        Op(op="qkv_projection", kernel=None, ...)

    After lowering (kernel selected from registry):
        Op(op="qkv_projection", kernel="ck_qkv_project_head_major_quant", ...)

    After fusion (multiple ops merged into one):
        Op(op="fused_attention_block", kernel="mega_fused_attention_prefill",
           fused_from=["rmsnorm", "qkv", "attention", "out_proj", "residual"])
    """
    op: str  # OpType value (e.g., "qkv_projection")
    name: str  # Unique identifier (e.g., "qkv_0_5")
    inputs: List[str]  # Buffer names
    outputs: List[str]  # Buffer names
    weights: List[str] = field(default_factory=list)  # Weight names
    biases: List[str] = field(default_factory=list)  # Bias names
    scratch: List[str] = field(default_factory=list)  # Scratch buffer names
    kernel: Optional[str] = None  # Kernel ID from registry
    params: Dict[str, Any] = field(default_factory=dict)  # Runtime parameters
    fused_from: List[str] = field(default_factory=list)  # Ops merged into this


@dataclass
class LayerIR:
    """
    Per-Layer Intermediate Representation.

    Contains all operations and buffers for a single transformer layer.
    A typical layer has ~11 ops: rmsnorm, qkv, rope, attn, out_proj, residual, etc.
    """
    layer_id: int
    ops: List[Op] = field(default_factory=list)
    buffers: Dict[str, Buffer] = field(default_factory=dict)


@dataclass
class GraphIR:
    """
    Complete Model Intermediate Representation.

    Top-level container for the entire model.
    Contains: model name, config (dims/heads), template, all layers, global buffers, weights.

    OUTPUT of the "graph building" stage - before kernel selection.
    """
    model_name: str
    config: Dict[str, Any]  # Model config (dims, heads, etc.)
    template: Dict[str, Any]  # Template definition
    layers: List[LayerIR] = field(default_factory=list)
    global_buffers: Dict[str, Buffer] = field(default_factory=dict)
    weights: Dict[str, Weight] = field(default_factory=dict)


@dataclass
class LoweredIR:
    """
    IR After Kernel Selection.

    Same as GraphIR but with kernel IDs filled in.
    The "lowering" step maps abstract ops to concrete kernels from registry.

    GraphIR:  Op(op="qkv_projection", kernel=None)
    LoweredIR: Op(op="qkv_projection", kernel="ck_qkv_project_head_major_quant")

    OUTPUT of the "lowering" stage.
    """
    graph: GraphIR
    mode: str  # "prefill" or "decode"
    kernel_map: Dict[str, str] = field(default_factory=dict)  # op_name -> kernel_id


@dataclass
class Layout:
    """
    Memory Layout With Concrete Offsets.

    After kernel selection, we compute where everything lives in memory.
    Stores: buffer_name -> {offset, size, ...}

    MagicHeader at start of BUMP file stores these offsets.
    At runtime, mmap file and jump to offset + base_address.

    OUTPUT of the "layout planning" stage.
    """
    name: str = ""
    config: Optional[Dict] = None
    sections: List = field(default_factory=list)
    buffers: Dict[str, Dict[str, int]] = field(default_factory=dict)
    magic_header_size: int = 64
    total_bytes: int = 0
    weight_bytes: int = 0
    activation_bytes: int = 0
    canary_count: int = 0
    canaries: List = field(default_factory=list)


# Alias for backward compatibility with codegen_v6_6.py
ModelLayout = Layout


@dataclass
class Schedule:
    """
    Execution Schedule.

    Ordered list of kernel calls with their arguments.
    Tells us: execution order, kernel arguments, dependencies.

    Example:
        Schedule(mode="prefill", ops=[
            {"op": "embedding", "kernel": "embedding_forward_q8_0", "args": [...]},
            {"op": "rmsnorm", "kernel": "rmsnorm_forward", "args": [...], "depends_on": ["embedding"]},
            ...
        ])

    Codegen reads Schedule and emits C code.
    OUTPUT of the "scheduling" stage.
    """
    ops: List[Dict[str, Any]] = field(default_factory=list)
    mode: str = "prefill"


# =============================================================================
# SECTION 4: CONSTANTS
# =============================================================================
#
# Physical properties of data types.
# Used for memory layout planning and buffer size calculation.
#
# DTYPE_BYTES: Bytes per element for each dtype.
#   - Native dtypes (fp32): exact byte count
#   - Quantized (q5_0): average bytes/element including metadata
#
# QUANT_BLOCK: Block sizes for quantized formats.
#   - Quantized formats pack elements into blocks with metadata.
#   - Q4_K block size = 256 means: 256 elements + 1 scale per block.

# Magic number for BUMP file header (0x42554D50 = "BUMP" in little endian)
MAGIC_PREFIX = 0x42554D50

DTYPE_BYTES = {
    "fp32": 4,
    "fp16": 2,
    "bf16": 2,
    "i8": 1,
    "int32": 4,
    "q8_0": 1,  # Packed representation
    "q8_k": 1.140625,  # 292 bytes per 256 elements
    "q5_0": 0.6875,  # 22 bytes per 32 elements
    "q4_k": 0.5625,  # 144 bytes per 256 elements
    "q6_k": 0.8203125,  # 210 bytes per 256 elements
}

QUANT_BLOCK = {
    "q8_0": 32,
    "q5_0": 32,
    "q4_k": 256,
    "q6_k": 256,
    "q8_k": 256,
}

# =============================================================================
# SECTION 5: HELPER FUNCTIONS
# =============================================================================
#
# Utility functions used throughout the pipeline.
# All functions are stateless - they don't modify any global state.
#
# Function categories:
#   - Registry loading: _load_registry_json, load_registry_ops, build_op_type_enum
#   - Registry normalization: normalize_kernel_registry
#   - Buffer utilities: make_buffer_name, compute_buffer_size
#   - Kernel selection: resolve_kernel_template

def _enum_member_name(value: str) -> str:
    """Convert op name to valid Python enum member name.

    Examples:
        "qkv_projection" → "QKV_PROJECTION"
        "attention" → "ATTENTION"
        "2d_slice" → "OP_2D_SLICE" (prefixed because starts with digit)
    """
    name = re.sub(r"[^a-zA-Z0-9]+", "_", value).upper()
    if not name:
        return "UNKNOWN"
    if name[0].isdigit():
        name = f"OP_{name}"
    return name


def _load_registry_json(path: Path) -> Dict:
    """Load kernel registry from JSON file.

    Args:
        path: Path to KERNEL_REGISTRY.json

    Returns:
        Parsed JSON as dict

    Raises:
        FileNotFoundError: If registry doesn't exist
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Kernel registry not found: {path}. "
            "Run gen_kernel_registry_from_maps.py first."
        )
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def load_registry_ops(registry: Optional[Any] = None,
                      registry_path: Optional[Path] = None) -> List[str]:
    """Get sorted list of unique op names from kernel registry.

    Used to auto-generate the OpType enum.

    Returns:
        Sorted list like: ["attention", "gemm", "qkv_projection", ...]
    """
    if registry is None:
        registry_path = registry_path or DEFAULT_KERNEL_REGISTRY_PATH
        registry = _load_registry_json(registry_path)

    registry_map = normalize_kernel_registry(registry)
    ops = sorted({entry.get("op") for entry in registry_map.values() if entry.get("op")})
    if not ops:
        raise ValueError("Kernel registry contains no ops.")
    return ops


def build_op_type_enum(registry: Optional[Any] = None,
                       registry_path: Optional[Path] = None) -> Enum:
    """Build OpType enum dynamically from kernel registry.

    This ensures type safety - OpType only contains ops that exist in registry.
    Called at module import time (see end of file).

    Returns:
        Enum class with members: OpType.ATTENTION, OpType.GEMM, etc.
    """
    ops = load_registry_ops(registry=registry, registry_path=registry_path)
    members = {_enum_member_name(op): op for op in ops}
    return Enum("OpType", members)


def normalize_kernel_registry(registry: Any) -> Dict[str, Dict]:
    """Convert registry to standard {kernel_id: entry} format.

    Registry can come in different formats:
      1. Full format: {"kernels": [...], "_meta": {...}}
      2. List format: [...]
      3. Already normalized: {"kernel_id": {...}, ...}
      4. By-id format: {"by_id": {"kernel_id": {...}}}

    Returns:
        Normalized: {"kernel_id": {...kernel entry...}, ...}
    """
    if registry is None:
        return {}

    if isinstance(registry, list):
        return {k.get("name") or k.get("id"): k for k in registry if isinstance(k, dict)}

    if isinstance(registry, dict):
        if "kernels" in registry and isinstance(registry["kernels"], list):
            return {k.get("name") or k.get("id"): k for k in registry["kernels"] if isinstance(k, dict)}
        if "by_id" in registry and isinstance(registry["by_id"], dict):
            return registry["by_id"]
        if all(isinstance(v, dict) for v in registry.values()):
            return registry

    return {}


def make_buffer_name(layer_id: int, op_type: str, suffix: str = "") -> str:
    """Generate buffer name following v6.6 naming convention.

    v6.6 naming:
      - Global: "token_emb", "final_ln_gamma"
      - Layer: "layer.{layer_id}.{op_type}.{suffix}"

    Examples:
        make_buffer_name(0, "ln1")       → "layer.0.ln1"
        make_buffer_name(0, "ln1", "out") → "layer.0.ln1.out"
        make_buffer_name(5, "q")         → "layer.5.q"
    """
    if suffix:
        return f"layer.{layer_id}.{op_type}.{suffix}"
    return f"layer.{layer_id}.{op_type}"


def compute_buffer_size(shape: List[str], dtype: str, dims: Dict[str, int]) -> int:
    """Calculate buffer size in bytes given symbolic shape and concrete dimensions.

    Examples:
        # FP32 tensor
        compute_buffer_size(["T", "AE"], "fp32", {"T": 512, "AE": 2048})
        # Returns: 512 * 2048 * 4 = 4,194,304 bytes

        # Q5_0 quantized tensor
        compute_buffer_size(["H*AD", "AE"], "q5_0", {"H*AD": 896, "AE": 896})
        # Returns: 896 * 896 * 0.6875 ≈ 551,936 bytes

    Used during layout planning to allocate buffers.
    """
    elements = 1
    for s in shape:
        if isinstance(s, int):
            elements *= s
        elif s in dims:
            elements *= dims[s]
        else:
            raise ValueError(f"Unknown dimension: {s}")

    if dtype.startswith("q"):
        # Quantized - use block size
        block_size = QUANT_BLOCK.get(dtype, 32)
        n_blocks = (elements + block_size - 1) // block_size
        # Approximate bytes per element based on format
        bytes_per_elem = DTYPE_BYTES.get(dtype, 0.5)
        return int(elements * bytes_per_elem)
    else:
        # Native dtype
        elem_bytes = DTYPE_BYTES.get(dtype, 4)
        return elements * elem_bytes


def resolve_kernel_template(
    op_type: str,
    weight_dtype: str,
    registry: Optional[Dict] = None
) -> str:
    """Find kernel ID matching (op_type, weight_dtype).

    This is the CORE kernel selection function.
    Maps (op_type, weight_dtype) → kernel_id

    Examples:
        resolve_kernel_template("gemm", "q5_0")
        # Returns: "gemm_nt_q5_0_q8_0"

        resolve_kernel_template("gemm", "q4_k")
        # Returns: "gemm_nt_q4_k_q8_k"

    How it works:
        1. Iterate through all kernels in registry
        2. Filter by op_type
        3. Check weight dtype compatibility (exact, "mixed", or "q5_0|q8_0" list)
        4. Return first matching kernel

    Called during "lowering" stage to select appropriate kernel.
    """
    registry_map = normalize_kernel_registry(registry)
    if not registry_map:
        raise ValueError("Kernel registry required for resolve_kernel_template()")

    weight_dtype = (weight_dtype or "").strip().lower()
    candidates = []

    for kernel_id, entry in registry_map.items():
        if entry.get("op") != op_type:
            continue
        candidates.append(kernel_id)
        quant = entry.get("quant", {}) or {}
        weight_support = (quant.get("weight", "") or "").lower()
        if not weight_dtype:
            if weight_support in ("", "none"):
                return kernel_id
            continue
        if weight_support == "mixed":
            return kernel_id
        if weight_support == weight_dtype:
            return kernel_id
        if "|" in weight_support:
            parts = [p.strip() for p in weight_support.split("|") if p.strip()]
            if weight_dtype in parts:
                return kernel_id

    raise ValueError(
        f"No kernel in registry for op='{op_type}' weight_dtype='{weight_dtype}'\n"
        f"  Available: {candidates}"
    )


# =============================================================================
# SECTION 6: AUTO-GENERATED OPTYPE ENUM
# =============================================================================
#
# Build OpType enum from the registry at import time.
# This ensures OpType always matches KERNEL_REGISTRY.json.
# If you add a new kernel to the registry, OpType updates automatically.
#
# Usage:
#     from ir_types_v6_6 import OpType
#     op = Op(op=OpType.QKV_PROJECTION.value, name="qkv_0", ...)

OpType = build_op_type_enum()


# =============================================================================
# SECTION 6.5: LEGACY COMPATIBILITY FUNCTIONS
# =============================================================================
#
# Functions kept for backward compatibility with code that imports ir_types_v6_6 as v3.
# These are simple wrappers that were previously in compat_ir_v4_v6_6.py.
#
# Usage:
#     import ir_types_v6_6 as v3
#     config = v3.parse_config("config.json")


def parse_config(config_path: str) -> Dict:
    """Load and parse config.json (legacy compatibility function)."""
    with open(config_path, 'r') as f:
        return json.load(f)


def model_id_to_name(model_id: str) -> str:
    """Convert model ID to safe name (legacy compatibility function)."""
    return model_id.replace("/", "--").replace("_", "-").lower()


# =============================================================================
# SECTION 7: EXPORTS
# =============================================================================
#
# Public API - these can be imported directly.
#
# Usage:
#     from .ir_types_v6_6 import Op, LayerIR, OpType, DTYPE_BYTES

__all__ = [
    # Enums
    "OpType",      # Auto-generated from registry
    "DType",       # Data types
    "Mode",        # Execution modes

    # Data classes
    "Buffer",      # Memory buffer spec
    "Weight",      # Weight tensor spec
    "Op",          # IR operation
    "LayerIR",     # Per-layer IR
    "GraphIR",     # Full model IR
    "LoweredIR",   # After kernel selection
    "Layout",      # Memory layout
    "ModelLayout", # Alias for Layout (backward compatibility)
    "Schedule",    # Execution schedule

    # Constants
    "DEFAULT_KERNEL_REGISTRY_PATH",  # Path to registry
    "DTYPE_BYTES",     # Bytes per element
    "QUANT_BLOCK",     # Block sizes

    # Helper functions
    "make_buffer_name",              # Generate buffer names
    "compute_buffer_size",           # Calculate buffer bytes
    "load_registry_ops",             # Get ops from registry
    "build_op_type_enum",            # Build OpType enum
    "normalize_kernel_registry",     # Normalize registry format
    "resolve_kernel_template",       # Find kernel by op + dtype
    "parse_config",                  # Load config.json (legacy compat)
    "model_id_to_name",              # Convert model ID to name (legacy compat)
]
