ck_cli_v6.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ck_cli_v6.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdbool.h>
#include <errno.h>
#include <signal.h>
#include <dlfcn.h>
#include <unistd.h>
#include <time.h>
#include "tokenizer/true_bpe.h"
Macros
#define _GNU_SOURCE
#define CK_CLI_DEFAULT_MAX_TOKENS -1 /* -1 means use model default (stop at EOS) */
#define CK_CLI_EOS_MAX 8
#define CK_CLI_OUTPUT_BUF_SIZE 4096
#define CK_SYSTEM_MAX_SIZE 1024
#define CK_TEMPLATE_MAX_SIZE 16384
Typedefs
typedef int(* decode_t) (int32_t token, float *logits_out)
typedef int(* embed_t) (const int32_t *tokens, int num_tokens)
typedef int(* forward_t) (float *logits_out)
typedef void(* free_t) (void)
typedef int(* get_int_t) (void)
typedef void *(* get_ptr_t) (void)
typedef int(* init_t) (const char *weights_path)
typedef int(* kv_enable_t) (int capacity)
typedef void(* kv_reset_t) (void)
typedef int(* sample_argmax_t) (void)
Functions
static char * apply_chat_template (const char *user_prompt, const char *system_prompt)
static int extract_json_int (const char *json, const char *key)
static int extract_json_int_array (const char *json, const char *key, int32_t *out, int max_count)
static char * extract_json_string (const char *json, const char *key)
static void handle_sigint (int sig)
static bool init_stop_token_table (const int32_t *stop_ids, int count, int vocab_size)
static bool is_stop_token_id (int32_t token_id)
static bool load_chat_template (const char *weights_path)
static bool load_model_api (const char *lib_path, ModelAPI *api)
int main (int argc, char **argv)
static void output_append (char *buf, size_t *len, const char *text)
static void output_flush (char *buf, size_t *len)
static void output_token (char *buf, size_t *len, const char *token)
static bool parse_args (int argc, char **argv, CLIOptions *opt)
static bool parse_eos_ids (const char *arg, CLIOptions *opt)
static void print_help (const char *prog)
static char * read_prompt_file (const char *path)
static bool resolve_symbol (void *handle, const char *name, void **out_ptr, bool required)
static int run_prompt (ModelAPI *api, CKTrueBPE *tokenizer, const CLIOptions *opt, const char *input)
Variables
static char g_chat_template [16384] = {0}
static int g_decode_count = 0
static double g_decode_time_ms = 0.0
static char g_default_system [1024] = {0}
static int32_t g_eos_token_id = -1
static volatile sig_atomic_t g_exit_requested = 0
static bool g_has_template = false
static double g_prefill_time_ms = 0.0
static bool * g_stop_token_table = NULL
static int g_vocab_size = 0
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 9 of file ck_cli_v6.c.
CK_CLI_DEFAULT_MAX_TOKENS
#define CK_CLI_DEFAULT_MAX_TOKENS -1 /* -1 means use model default (stop at EOS) */
Definition at line 23 of file ck_cli_v6.c.
CK_CLI_EOS_MAX
#define CK_CLI_EOS_MAX 8
Definition at line 24 of file ck_cli_v6.c.
CK_CLI_OUTPUT_BUF_SIZE
#define CK_CLI_OUTPUT_BUF_SIZE 4096
Definition at line 25 of file ck_cli_v6.c.
CK_SYSTEM_MAX_SIZE
#define CK_SYSTEM_MAX_SIZE 1024
Definition at line 29 of file ck_cli_v6.c.
CK_TEMPLATE_MAX_SIZE
#define CK_TEMPLATE_MAX_SIZE 16384
Definition at line 28 of file ck_cli_v6.c.
Typedef Documentation
decode_t
typedef int(* decode_t) (int32_t token, float *logits_out)
Definition at line 376 of file ck_cli_v6.c.
embed_t
typedef int(* embed_t) (const int32_t *tokens, int num_tokens)
Definition at line 372 of file ck_cli_v6.c.
forward_t
typedef int(* forward_t) (float *logits_out)
Definition at line 373 of file ck_cli_v6.c.
free_t
typedef void(* free_t) (void)
Definition at line 380 of file ck_cli_v6.c.
get_int_t
typedef int(* get_int_t) (void)
Definition at line 378 of file ck_cli_v6.c.
get_ptr_t
typedef void*(* get_ptr_t) (void)
Definition at line 379 of file ck_cli_v6.c.
init_t
typedef int(* init_t) (const char *weights_path)
Definition at line 371 of file ck_cli_v6.c.
kv_enable_t
typedef int(* kv_enable_t) (int capacity)
Definition at line 374 of file ck_cli_v6.c.
kv_reset_t
typedef void(* kv_reset_t) (void)
Definition at line 375 of file ck_cli_v6.c.
sample_argmax_t
typedef int(* sample_argmax_t) (void)
Definition at line 377 of file ck_cli_v6.c.
Function Documentation
apply_chat_template()
static char* apply_chat_template (const char * user_prompt, const char * system_prompt) static
Apply chat template to user prompt. Returns allocated string (caller must free) or NULL on error.
Definition at line 320 of file ck_cli_v6.c.
{
     if (!user_prompt || !g_has_template) return NULL;
     const char *system = system_prompt ? system_prompt : g_default_system;
     if (!system) system = "";
     const char *tpl = g_chat_template;
     size_t tpl_len = strlen(tpl);
     size_t prompt_len = strlen(user_prompt);
     size_t system_len = strlen(system);
     /* Count placeholders to calculate buffer size */
     int system_count = 0;
     int prompt_count = 0;
     for (const char *p = tpl; *p; p++) {
         if (strncmp(p, "{system}", 8) == 0) { system_count++; p += 7; }
         if (strncmp(p, "{prompt}", 8) == 0) { prompt_count++; p += 7; }
     }
     size_t total = tpl_len
                  - (system_count * 8)   /* Remove {system} */
                  - (prompt_count * 8)   /* Remove {prompt} */
                  + system_len
                  + prompt_len
                  + 1;  /* NULL terminator */
     char *result = (char *)malloc(total);
     if (!result) return NULL;
     /* Build result string */
     char *out = result;
     const char *p = tpl;
     while (*p) {
         if (strncmp(p, "{system}", 8) == 0) {
             memcpy(out, system, system_len);
             out += system_len;
             p += 8;
         } else if (strncmp(p, "{prompt}", 8) == 0) {
             memcpy(out, user_prompt, prompt_len);
             out += prompt_len;
             p += 8;
         } else {
             *out++ = *p++;
         }
     }
     *out = '\0';
     return result;
 }
References g_chat_template, g_default_system, and g_has_template.
Referenced by run_prompt().
extract_json_int()
static int extract_json_int (const char * json, const char * key) static
Simple JSON integer extraction.
Definition at line 92 of file ck_cli_v6.c.
{
     if (!json || !key) return -1;
     char pattern[128];
     snprintf(pattern, sizeof(pattern), "\"%s\"", key);
     const char *p = strstr(json, pattern);
     if (!p) return -1;
     /* Find the colon */
     p = strchr(p, ':');
     if (!p) return -1;
     p++; /* Skip colon */
     /* Skip whitespace including newlines */
     while (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r') p++;
     /* Parse integer */
     int result = atoi(p);
     return result;
 }
Referenced by load_chat_template().
extract_json_int_array()
static int extract_json_int_array (const char * json, const char * key, int32_t * out, int max_count) static
Extract an array of integers from JSON.
Parameters
json JSON string
key Key to find
out Output array
max_count Maximum elements to extract
Returns
Number of elements extracted
Definition at line 122 of file ck_cli_v6.c.
{
     if (!json || !key || !out) return 0;
     char pattern[128];
     snprintf(pattern, sizeof(pattern), "\"%s\"", key);
     const char *p = strstr(json, pattern);
     if (!p) return 0;
     /* Find the opening bracket */
     p = strchr(p, '[');
     if (!p) return 0;
     p++; /* Skip '[' */
     int count = 0;
     while (count < max_count && *p) {
         /* Skip whitespace */
         while (*p == ' ' || *p == '\t' || *p == '\n') p++;
         if (*p == ']' || *p == '\0') break;
         /* Parse integer */
         long val = strtol(p, NULL, 10);
         out[count++] = (int32_t)val;
         /* Skip to next number */
         while (*p && *p != ',' && *p != ']') p++;
         if (*p == ',') p++;
     }
     return count;
 }
Referenced by load_chat_template().
extract_json_string()
static char* extract_json_string (const char * json, const char * key) static
Simple JSON string extraction - finds a key and returns the value string. Returns pointer to malloc'd string (caller must free) or NULL on error.
Definition at line 61 of file ck_cli_v6.c.
{
     if (!json || !key) return NULL;
     char pattern[128];
     snprintf(pattern, sizeof(pattern), "\"%s\"", key);
     const char *p = strstr(json, pattern);
     if (!p) return NULL;
     /* Find the colon and opening quote */
     p = strchr(p, ':');
     if (!p) return NULL;
     p = strchr(p + 1, '"');
     if (!p) return NULL;
     p++; /* Skip opening quote */
     /* Find closing quote */
     const char *end = strchr(p, '"');
     if (!end) return NULL;
     size_t len = (size_t)(end - p);
     char *result = (char *)malloc(len + 1);
     if (!result) return NULL;
     memcpy(result, p, len);
     result[len] = '\0';
     return result;
 }
References end.
Referenced by load_chat_template().
handle_sigint()
static void handle_sigint (int sig) static
Definition at line 48 of file ck_cli_v6.c.
{
     (void)sig;
     g_exit_requested = 1;
 }
References g_exit_requested.
Referenced by main().
init_stop_token_table()
static bool init_stop_token_table (const int32_t * stop_ids, int count, int vocab_size) static
Initialize stop token lookup table from manifest metadata.
Parameters
stop_ids Array of stop token IDs
count Number of stop token IDs
vocab_size Vocab size for table allocation
Returns
true on success
Definition at line 162 of file ck_cli_v6.c.
{
     /* Free any existing table */
     if (g_stop_token_table) {
         free(g_stop_token_table);
         g_stop_token_table = NULL;
     }
     if (count <= 0 || vocab_size <= 0) {
         return false;
     }
     /* Allocate table (zero-initialized) */
     g_stop_token_table = (bool *)calloc((size_t)vocab_size, sizeof(bool));
     if (!g_stop_token_table) {
         fprintf(stderr, "[Error] Failed to allocate stop token table (%d bytes)\n", vocab_size);
         return false;
     }
     g_vocab_size = vocab_size;
     /* Mark stop tokens */
     for (int i = 0; i < count; i++) {
         int id = stop_ids[i];
         if (id >= 0 && id < vocab_size) {
             g_stop_token_table[id] = true;
         }
     }
     fprintf(stderr, "[StopTable] Initialized with %d stop tokens, vocab_size=%d\n", count, vocab_size);
     return true;
 }
References g_stop_token_table, g_vocab_size, id, and vocab_size.
Referenced by load_chat_template().
is_stop_token_id()
static bool is_stop_token_id (int32_t token_id) inline static
Check if token is a stop token (O(1) lookup). Returns true if token should stop generation.
Definition at line 198 of file ck_cli_v6.c.
{
     if (!g_stop_token_table || token_id < 0 || token_id >= g_vocab_size) {
         return false;
     }
     return g_stop_token_table[token_id];
 }
References g_stop_token_table, and g_vocab_size.
Referenced by run_prompt().
load_chat_template()
static bool load_chat_template (const char * weights_path) static
Load chat template from chat_template.json or weights_manifest.json. Returns true if template was loaded, false otherwise.
Definition at line 209 of file ck_cli_v6.c.
{
     char path[4096];
     const char *json_content = NULL;
     char *json_copy = NULL;
     bool success = false;
     /* Try chat_template.json first */
     strncpy(path, weights_path, sizeof(path) - 20);
     char *slash = strrchr(path, '/');
     if (slash) {
         strcpy(slash + 1, "chat_template.json");
     } else {
         strcpy(path, "chat_template.json");
     }
     FILE *f = fopen(path, "r");
     if (f) {
         fseek(f, 0, SEEK_END);
         long size = ftell(f);
         fseek(f, 0, SEEK_SET);
         if (size > 0 && size < (long)sizeof(path)) {
             json_content = path;  /* Reuse buffer */
             size_t n = fread(path, 1, (size_t)size, f);
             path[n] = '\0';
             json_content = path;
         } else if (size > 0 && size < 32768) {
             json_copy = (char *)malloc((size_t)size + 1);
             if (json_copy) {
                 size_t n = fread(json_copy, 1, (size_t)size, f);
                 json_copy[n] = '\0';
                 json_content = json_copy;
             }
         }
         fclose(f);
     }
     /* Try weights_manifest.json if chat_template.json not found */
     if (!json_content) {
         strncpy(path, weights_path, sizeof(path) - 25);
         slash = strrchr(path, '/');
         if (slash) {
             strcpy(slash + 1, "weights_manifest.json");
         } else {
             strcpy(path, "weights_manifest.json");
         }
         f = fopen(path, "r");
         if (f) {
             fseek(f, 0, SEEK_END);
             long size = ftell(f);
             fseek(f, 0, SEEK_SET);
             if (size > 0 && size < 32768) {
                 json_copy = (char *)malloc((size_t)size + 1);
                 if (json_copy) {
                     size_t n = fread(json_copy, 1, (size_t)size, f);
                     json_copy[n] = '\0';
                     json_content = json_copy;
                 }
             }
             fclose(f);
         }
     }
     if (!json_content) {
         return false;
     }
     /* Extract template fields */
     char *template_str = extract_json_string(json_content, "template");
     if (template_str) {
         size_t len = strlen(template_str);
         if (len < CK_TEMPLATE_MAX_SIZE) {
             memcpy(g_chat_template, template_str, len + 1);
             success = true;
         }
         free(template_str);
     }
     char *system_str = extract_json_string(json_content, "default_system");
     if (system_str) {
         size_t len = strlen(system_str);
         if (len < CK_SYSTEM_MAX_SIZE) {
             memcpy(g_default_system, system_str, len + 1);
         }
         free(system_str);
     }
     g_eos_token_id = extract_json_int(json_content, "eos_token_id");
     /* Extract stop_token_ids and vocab_size for lookup table */
     int32_t stop_ids[16];
     int stop_count = extract_json_int_array(json_content, "stop_token_ids", stop_ids, 16);
     int vocab_size = extract_json_int(json_content, "vocab_size");
     if (vocab_size <= 0) {
         vocab_size = 200000;  /* Default fallback */
     }
     /* Initialize stop token lookup table */
     if (stop_count > 0) {
         init_stop_token_table(stop_ids, stop_count, vocab_size);
     }
     free(json_copy);
     g_has_template = (g_chat_template[0] != '\0');
     return g_has_template;
 }
References CK_SYSTEM_MAX_SIZE, CK_TEMPLATE_MAX_SIZE, extract_json_int(), extract_json_int_array(), extract_json_string(), g_chat_template, g_default_system, g_eos_token_id, g_has_template, init_stop_token_table(), and vocab_size.
Referenced by main().
load_model_api()
static bool load_model_api (const char * lib_path, ModelAPI * api) static
Definition at line 519 of file ck_cli_v6.c.
{
     if (!lib_path || !api) return false;
     memset(api, 0, sizeof(*api));
     api->handle = dlopen(lib_path, RTLD_NOW);
     if (!api->handle) {
         fprintf(stderr, "Error: dlopen failed: %s\n", dlerror());
         return false;
     }
     if (!resolve_symbol(api->handle, "ck_model_init", (void **)&api->init, true)) return false;
     if (!resolve_symbol(api->handle, "ck_model_embed_tokens", (void **)&api->embed, true)) return false;
     if (!resolve_symbol(api->handle, "ck_model_forward", (void **)&api->forward, true)) return false;
     if (!resolve_symbol(api->handle, "ck_model_decode", (void **)&api->decode, true)) return false;
     if (!resolve_symbol(api->handle, "ck_model_sample_argmax", (void **)&api->sample, true)) return false;
     resolve_symbol(api->handle, "ck_model_kv_cache_enable", (void **)&api->kv_enable, false);
     resolve_symbol(api->handle, "ck_model_kv_cache_reset", (void **)&api->kv_reset, false);
     resolve_symbol(api->handle, "ck_model_get_context_window", (void **)&api->get_context, false);
     resolve_symbol(api->handle, "ck_model_get_vocab_size", (void **)&api->get_vocab_size, false);
     resolve_symbol(api->handle, "ck_model_get_num_merges", (void **)&api->get_num_merges, false);
     resolve_symbol(api->handle, "ck_model_get_vocab_strings_size", (void **)&api->get_vocab_bytes, false);
     resolve_symbol(api->handle, "ck_model_get_vocab_offsets", (void **)&api->get_offsets, false);
     resolve_symbol(api->handle, "ck_model_get_vocab_strings", (void **)&api->get_strings, false);
     resolve_symbol(api->handle, "ck_model_get_vocab_merges", (void **)&api->get_merges, false);
     resolve_symbol(api->handle, "ck_model_free", (void **)&api->free_fn, false);
     if (!api->get_vocab_size || !api->get_vocab_bytes || !api->get_offsets || !api->get_strings) {
         fprintf(stderr, "Error: vocab accessors missing from model\n");
         return false;
     }
     return true;
 }
References resolve_symbol().
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 746 of file ck_cli_v6.c.
{
     signal(SIGINT, handle_sigint);
     CLIOptions opt;
     if (!parse_args(argc, argv, &opt)) {
         return 1;
     }
     ModelAPI api;
     if (!load_model_api(opt.lib_path, &api)) {
         return 1;
     }
     if (api.init(opt.weights_path) != 0) {
         fprintf(stderr, "Error: ck_model_init failed\n");
         return 1;
     }
     /* Load chat template from weights directory */
     if (load_chat_template(opt.weights_path)) {
         if (g_eos_token_id > 0) {
             fprintf(stderr, "[Template] Loaded: type detected, EOS token ID: %d\n", g_eos_token_id);
         } else {
             fprintf(stderr, "[Template] Loaded: type detected\n");
         }
     }
     int ctx = opt.context_override;
     if (ctx <= 0 && api.get_context) ctx = api.get_context();
     if (api.kv_enable && ctx > 0) {
         api.kv_enable(ctx);
     }
     CKTrueBPE *tokenizer = ck_true_bpe_create();
     if (!tokenizer) {
         fprintf(stderr, "[Tokenizer] failed to create\n");
         return 1;
     }
     int vocab_size = api.get_vocab_size ? api.get_vocab_size() : 0;
     int vocab_bytes = api.get_vocab_bytes ? api.get_vocab_bytes() : 0;
     int num_merges = api.get_num_merges ? api.get_num_merges() : 0;
     const int32_t *offsets = (const int32_t *)api.get_offsets();
     const char *strings = (const char *)api.get_strings();
     const int32_t *merges = api.get_merges ? (const int32_t *)api.get_merges() : NULL;
     if (vocab_size <= 0 || vocab_bytes <= 0 || !offsets || !strings) {
         fprintf(stderr, "[Tokenizer] missing vocab data in model\n");
         ck_true_bpe_free(tokenizer);
         return 1;
     }
     if (ck_true_bpe_load_binary(tokenizer, vocab_size, offsets, strings, num_merges, merges) != 0) {
         fprintf(stderr, "[Tokenizer] failed to load vocab\n");
         ck_true_bpe_free(tokenizer);
         return 1;
     }
     setvbuf(stdout, NULL, _IOFBF, 1 << 20);
     if (opt.prompt_once) {
         char *file_prompt = read_prompt_file(opt.prompt_once);
         const char *prompt_text = file_prompt ? file_prompt : opt.prompt_once;
         run_prompt(&api, tokenizer, &opt, prompt_text);
         free(file_prompt);
     } else {
         char line[4096];
         while (!g_exit_requested) {
             printf("\nYou: ");
             fflush(stdout);
             if (!fgets(line, sizeof(line), stdin)) {
                 if (feof(stdin) || g_exit_requested) {
                     break;
                 }
                 if (errno == EINTR) {
                     break;
                 }
                 continue;
             }
             if (line[0] == '\n' || line[0] == '\0') continue;
             if (!strncmp(line, "/exit", 5) || !strncmp(line, "/quit", 5)) break;
             if (!strncmp(line, "/help", 5)) {
                 print_help(argv[0]);
                 continue;
             }
             if (!strncmp(line, "/reset", 6)) {
                 if (api.kv_reset) api.kv_reset();
                 continue;
             }
             char *file_prompt = read_prompt_file(line);
             const char *prompt_text = file_prompt ? file_prompt : line;
             run_prompt(&api, tokenizer, &opt, prompt_text);
             free(file_prompt);
         }
     }
     ck_true_bpe_free(tokenizer);
     if (api.free_fn) api.free_fn();
     if (api.handle) dlclose(api.handle);
     return 0;
 }
References ck_true_bpe_create(), ck_true_bpe_free(), ck_true_bpe_load_binary(), g_eos_token_id, g_exit_requested, handle_sigint(), load_chat_template(), load_model_api(), merges, num_merges, offsets, parse_args(), print_help(), read_prompt_file(), run_prompt(), strings, and vocab_size.
output_append()
static void output_append (char * buf, size_t * len, const char * text) static
Definition at line 477 of file ck_cli_v6.c.
{
     if (!text || !*text) return;
     size_t n = strlen(text);
     if (*len + n >= CK_CLI_OUTPUT_BUF_SIZE) {
         output_flush(buf, len);
     }
     if (n >= CK_CLI_OUTPUT_BUF_SIZE) {
         fwrite(text, 1, n, stdout);
         return;
     }
     memcpy(buf + *len, text, n);
     *len += n;
 }
References CK_CLI_OUTPUT_BUF_SIZE, output_flush(), and text.
Referenced by output_token().
output_flush()
static void output_flush (char * buf, size_t * len) static
Definition at line 471 of file ck_cli_v6.c.
{
     if (*len == 0) return;
     fwrite(buf, 1, *len, stdout);
     *len = 0;
 }
Referenced by output_append(), and run_prompt().
output_token()
static void output_token (char * buf, size_t * len, const char * token) static
Definition at line 491 of file ck_cli_v6.c.
{
     if (!token || !*token) return;
     const unsigned char *b = (const unsigned char *)token;
     /* "Ġ" prefix (0xC4 0xA0) */
     if (b[0] == 0xC4 && b[1] == 0xA0) {
         output_append(buf, len, " ");
         output_append(buf, len, token + 2);
         return;
     }
     /* "▁" prefix (0xE2 0x96 0x81) */
     if (b[0] == 0xE2 && b[1] == 0x96 && b[2] == 0x81) {
         output_append(buf, len, " ");
         output_append(buf, len, token + 3);
         return;
     }
     output_append(buf, len, token);
 }
References output_append(), and token.
Referenced by run_prompt().
parse_args()
static bool parse_args (int argc, char ** argv, CLIOptions * opt) static
Definition at line 695 of file ck_cli_v6.c.
{
     if (!opt) return false;
     memset(opt, 0, sizeof(*opt));
     opt->max_tokens = CK_CLI_DEFAULT_MAX_TOKENS;
     opt->eos_ids[0] = 151643;
     opt->eos_ids[1] = 151645;
     opt->eos_count = 2;
     for (int i = 1; i < argc; i++) {
         const char *arg = argv[i];
         if (!strcmp(arg, "--help") || !strcmp(arg, "-h")) {
             print_help(argv[0]);
             return false;
         } else if (!strcmp(arg, "--lib") && i + 1 < argc) {
             opt->lib_path = argv[++i];
         } else if (!strcmp(arg, "--weights") && i + 1 < argc) {
             opt->weights_path = argv[++i];
         } else if ((!strcmp(arg, "--prompt") || !strcmp(arg, "-p")) && i + 1 < argc) {
             opt->prompt_once = argv[++i];
         } else if ((!strcmp(arg, "--max-tokens") || !strcmp(arg, "-t")) && i + 1 < argc) {
             opt->max_tokens = atoi(argv[++i]);
         } else if ((!strcmp(arg, "--context") || !strcmp(arg, "-c")) && i + 1 < argc) {
             opt->context_override = atoi(argv[++i]);
         } else if (!strcmp(arg, "--stream") || !strcmp(arg, "-s")) {
             opt->stream = true;
         } else if (!strcmp(arg, "--timing") || !strcmp(arg, "-T")) {
             opt->timing = true;
         } else if (!strcmp(arg, "--eos") && i + 1 < argc) {
             parse_eos_ids(argv[++i], opt);
         } else if (!strcmp(arg, "--ignore-eos")) {
             opt->ignore_eos = true;
         } else if (arg[0] != '-') {
             if (!opt->lib_path) opt->lib_path = arg;
             else if (!opt->weights_path) opt->weights_path = arg;
             else {
                 fprintf(stderr, "Unknown argument: %s\n", arg);
                 return false;
             }
         } else {
             fprintf(stderr, "Unknown option: %s\n", arg);
             return false;
         }
     }
     if (!opt->lib_path || !opt->weights_path) {
         print_help(argv[0]);
         return false;
     }
     return true;
 }
References CK_CLI_DEFAULT_MAX_TOKENS, parse_eos_ids(), and print_help().
Referenced by main().
parse_eos_ids()
static bool parse_eos_ids (const char * arg, CLIOptions * opt) static
Definition at line 456 of file ck_cli_v6.c.
{
     if (!arg || !opt) return false;
     opt->eos_count = 0;
     const char *p = arg;
     while (*p && opt->eos_count < CK_CLI_EOS_MAX) {
         char *end = NULL;
         long v = strtol(p, &end, 10);
         if (end == p) break;
         opt->eos_ids[opt->eos_count++] = (int)v;
         p = end;
         if (*p == ',') p++;
     }
     return opt->eos_count > 0;
 }
References CK_CLI_EOS_MAX, and end.
Referenced by parse_args().
print_help()
static void print_help (const char * prog) static
Definition at line 414 of file ck_cli_v6.c.
{
     fprintf(stderr, "Usage:\n");
     fprintf(stderr, "  %s <libmodel.so> <weights.bump> [options]\n", prog);
     fprintf(stderr, "  %s --lib <libmodel.so> --weights <weights.bump> [options]\n", prog);
     fprintf(stderr, "\nOptions:\n");
     fprintf(stderr, "  --prompt, -p TEXT       Run single prompt (non-interactive)\n");
     fprintf(stderr, "  --max-tokens, -t N       Max tokens to generate (default: %d)\n", CK_CLI_DEFAULT_MAX_TOKENS);
     fprintf(stderr, "  --context, -c N          Override context/KV cache size\n");
     fprintf(stderr, "  --stream, -s             Stream tokens as generated\n");
     fprintf(stderr, "  --timing, -T             Show timing breakdown\n");
     fprintf(stderr, "  --eos IDS               Comma-separated EOS token IDs\n");
     fprintf(stderr, "  --ignore-eos            Do not stop on EOS tokens\n");
     fprintf(stderr, "  --help, -h              Show this help\n");
 }
References CK_CLI_DEFAULT_MAX_TOKENS.
Referenced by main(), and parse_args().
read_prompt_file()
static char* read_prompt_file (const char * path) static
Definition at line 429 of file ck_cli_v6.c.
{
     if (!path || path[0] != '@') {
         return NULL;
     }
     FILE *f = fopen(path + 1, "rb");
     if (!f) {
         fprintf(stderr, "Error: cannot open prompt file: %s\n", path + 1);
         return NULL;
     }
     fseek(f, 0, SEEK_END);
     long size = ftell(f);
     fseek(f, 0, SEEK_SET);
     if (size < 0) {
         fclose(f);
         return NULL;
     }
     char *buf = (char *)malloc((size_t)size + 1);
     if (!buf) {
         fclose(f);
         return NULL;
     }
     size_t n = fread(buf, 1, (size_t)size, f);
     buf[n] = '\0';
     fclose(f);
     return buf;
 }
Referenced by main().
resolve_symbol()
static bool resolve_symbol (void * handle, const char * name, void ** out_ptr, bool required) static
Definition at line 509 of file ck_cli_v6.c.
{
     void *sym = dlsym(handle, name);
     if (!sym && required) {
         fprintf(stderr, "Error: missing symbol %s\n", name);
         return false;
     }
     if (out_ptr) *out_ptr = sym;
     return true;
 }
Referenced by load_model_api().
run_prompt()
static int run_prompt (ModelAPI * api, CKTrueBPE * tokenizer, const CLIOptions * opt, const char * input) static
Definition at line 551 of file ck_cli_v6.c.
{
     if (!api || !tokenizer || !opt || !input) return -1;
     if (g_exit_requested) return -1;
     int ctx = opt->context_override;
     if (ctx <= 0 && api->get_context) {
         ctx = api->get_context();
     }
     if (ctx <= 0) ctx = 4096;
     /* max_tokens: if -1 (default), use a very large number and let EOS stop us
        if > 0, use that limit */
     int max_decode_tokens = (opt->max_tokens > 0) ? opt->max_tokens : 8192;  /* generous limit */
     /* Apply chat template if available */
     char *formatted_input = NULL;
     const char *input_to_tokenize = input;
     if (g_has_template) {
         formatted_input = apply_chat_template(input, NULL);
         if (formatted_input) {
             input_to_tokenize = formatted_input;
             if (!opt->timing) {
                 /* Optional: show that template was applied */
             }
         }
     }
     int32_t *ids = (int32_t *)malloc((size_t)ctx * sizeof(int32_t));
     if (!ids) {
         free(formatted_input);
         fprintf(stderr, "Error: failed to allocate token buffer\n");
         return -1;
     }
     int n = ck_true_bpe_encode(tokenizer, input_to_tokenize, -1, ids, ctx);
     free(formatted_input);  /* Free formatted input after tokenization */
     if (n <= 0) {
         fprintf(stderr, "[Tokenizer] failed to encode prompt\n");
         free(ids);
         return -1;
     }
     if (n > ctx) n = ctx;
     /* Reset timing globals */
     g_prefill_time_ms = 0.0;
     g_decode_time_ms = 0.0;
     g_decode_count = 0;
     if (api->kv_reset) {
         api->kv_reset();
     }
     if (api->embed(ids, n) != 0) {
         fprintf(stderr, "[Model] embed failed\n");
         free(ids);
         return -1;
     }
     /* Time prefill (forward) */
     struct timespec t0, t1;
     clock_gettime(CLOCK_MONOTONIC, &t0);
     if (api->forward(NULL) != 0) {
         fprintf(stderr, "[Model] forward failed\n");
         free(ids);
         return -1;
     }
     clock_gettime(CLOCK_MONOTONIC, &t1);
     g_prefill_time_ms = (t1.tv_sec - t0.tv_sec) * 1000.0 +
                         (t1.tv_nsec - t0.tv_nsec) / 1000000.0;
     int next_token = api->sample();
     char out_buf[CK_CLI_OUTPUT_BUF_SIZE];
     size_t out_len = 0;
     if (!opt->timing) {
         printf("Assistant: ");
         fflush(stdout);
     }
     for (int generated = 0; generated < max_decode_tokens && !g_exit_requested; generated++) {
         if (next_token < 0) break;
         /* CHECK STOP TOKEN FIRST using O(1) lookup table - don't decode or print stop tokens */
         if (is_stop_token_id(next_token)) {
             break;
         }
         /* Only decode and print if NOT a stop token */
         const char *word = ck_true_bpe_id_to_token(tokenizer, next_token);
         output_token(out_buf, &out_len, word);
         /* Flush immediately if streaming enabled */
         if (opt->stream) {
             output_flush(out_buf, &out_len);
             fflush(stdout);
         } else if (out_len > (CK_CLI_OUTPUT_BUF_SIZE / 2)) {
             output_flush(out_buf, &out_len);
             fflush(stdout);
         }
         if (generated + 1 >= max_decode_tokens) break;
         /* Time decode */
         clock_gettime(CLOCK_MONOTONIC, &t0);
         if (api->decode(next_token, NULL) != 0) {
             fprintf(stderr, "\n[Model] decode failed\n");
             break;
         }
         clock_gettime(CLOCK_MONOTONIC, &t1);
         g_decode_time_ms += (t1.tv_sec - t0.tv_sec) * 1000.0 +
                             (t1.tv_nsec - t0.tv_nsec) / 1000000.0;
         g_decode_count++;
         next_token = api->sample();
     }
     output_flush(out_buf, &out_len);
     /* Print timing if requested */
     if (opt->timing) {
         printf("\n");
         double total_ms = g_prefill_time_ms + g_decode_time_ms;
         double prefill_rate = n / (g_prefill_time_ms / 1000.0);
         double decode_rate = g_decode_count / (g_decode_time_ms / 1000.0);
         double avg_decode = g_decode_count > 0 ? g_decode_time_ms / g_decode_count : 0.0;
         printf("Timing:\n");
         printf("  Prefill:  %3d tokens in %7.2f ms (%6.2f tok/s)\n",
                n, g_prefill_time_ms, prefill_rate);
         printf("  Decode:   %3d tokens in %7.2f ms (%6.2f tok/s) avg %.2f ms/tok\n",
                g_decode_count, g_decode_time_ms, decode_rate, avg_decode);
         printf("  Total:    %3d tokens in %7.2f ms\n",
                n + g_decode_count, total_ms);
     } else {
         printf("\n");
     }
     fflush(stdout);
     free(ids);
     return 0;
 }
References apply_chat_template(), CK_CLI_OUTPUT_BUF_SIZE, ck_true_bpe_encode(), ck_true_bpe_id_to_token(), g_decode_count, g_decode_time_ms, g_exit_requested, g_has_template, g_prefill_time_ms, ids, is_stop_token_id(), out_len, output_flush(), and output_token().
Referenced by main().
Variable Documentation
g_chat_template
char g_chat_template[16384] = {0} static
Definition at line 34 of file ck_cli_v6.c.
Referenced by apply_chat_template(), and load_chat_template().
g_decode_count
int g_decode_count = 0 static
Definition at line 46 of file ck_cli_v6.c.
Referenced by run_prompt().
g_decode_time_ms
double g_decode_time_ms = 0.0 static
Definition at line 45 of file ck_cli_v6.c.
Referenced by run_prompt().
g_default_system
char g_default_system[1024] = {0} static
Definition at line 35 of file ck_cli_v6.c.
Referenced by apply_chat_template(), and load_chat_template().
g_eos_token_id
int32_t g_eos_token_id = -1 static
Definition at line 36 of file ck_cli_v6.c.
Referenced by load_chat_template(), and main().
g_exit_requested
volatile sig_atomic_t g_exit_requested = 0 static
Definition at line 31 of file ck_cli_v6.c.
Referenced by handle_sigint(), main(), and run_prompt().
g_has_template
bool g_has_template = false static
Definition at line 37 of file ck_cli_v6.c.
Referenced by apply_chat_template(), load_chat_template(), and run_prompt().
g_prefill_time_ms
double g_prefill_time_ms = 0.0 static
Definition at line 44 of file ck_cli_v6.c.
Referenced by run_prompt().
g_stop_token_table
bool* g_stop_token_table = NULL static
Definition at line 40 of file ck_cli_v6.c.
Referenced by init_stop_token_table(), and is_stop_token_id().
g_vocab_size
int g_vocab_size = 0 static
Definition at line 41 of file ck_cli_v6.c.
Referenced by init_stop_token_table(), and is_stop_token_id().