tokenizer.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
tokenizer.h File Reference
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "tokenizer/murmurhash3.h"
#include "tokenizer/memory_pool.h"
#include "tokenizer/hash_table.h"
#include "tokenizer/utf8.h"
#include "data_structures/tries/trie.h"
Data Structures
struct CKTokenizer
struct CKTokenizerConfig
struct CKTokenizerToken
Macros
#define CK_TOKENIZER_API __attribute__((visibility("default")))
#define CK_TOKENIZER_DEFAULT_HT_SIZE 65536
#define CK_TOKENIZER_MAX_TOKEN_LEN 256
#define CK_TOKENIZER_MAX_VOCAB_SIZE 256000
Enumerations
enum CKTokenizerType { CK_TOKENIZER_BPE = 0 , CK_TOKENIZER_WORDPIECE = 1 , CK_TOKENIZER_SPM = 2 }
Functions
__attribute__ ((visibility("default"))) CKTokenizer *ck_tokenizer_create(CKTokenizerType type)
int ck_tokenizer_add_merge (CKTokenizer *tok, int32_t left_id, int32_t right_id, int32_t merged_id, int32_t priority)
int ck_tokenizer_add_special_token (CKTokenizer *tok, const char *name, int32_t id)
int ck_tokenizer_add_token (CKTokenizer *tok, const char *token, int32_t id, float score)
static CKTokenizer * ck_tokenizer_create_bpe (void)
static CKTokenizer * ck_tokenizer_create_spm (void)
static CKTokenizer * ck_tokenizer_create_wordpiece (void)
int ck_tokenizer_decode (const CKTokenizer *tok, const int32_t *ids, int num_ids, char *text, int max_len)
int ck_tokenizer_encode (const CKTokenizer *tok, const char *text, int text_len, int32_t *ids, int max_ids)
int ck_tokenizer_encode_tokens (const CKTokenizer *tok, const char *text, int text_len, const char **out_tokens, int max_tokens)
int ck_tokenizer_encode_with_special (CKTokenizer *tok, const char *text, int text_len, int32_t *ids, int max_ids, bool add_special)
int ck_tokenizer_load_binary (CKTokenizer *tok, int vocab_size, const int32_t *offsets, const char *strings, int num_merges, const int32_t *merges)
int ck_tokenizer_load_gguf (CKTokenizer *tok, const char *path)
int ck_tokenizer_load_json (CKTokenizer *tok, const char *path)
int ck_tokenizer_load_merges (CKTokenizer *tok, const char *path)
int ck_tokenizer_load_text (CKTokenizer *tok, const char *path)
static size_t ck_tokenizer_vocab_size (const CKTokenizer *tok)
Variables
int32_t int32_t bos
int32_t int32_t int32_t eos
int32_t id
const int32_t * ids
bool lowercase
int32_t int32_t int32_t int32_t int32_t mask
const int32_t int num_ids
const int32_t int int * out_len
int32_t int32_t int32_t int32_t pad
int32_t float * score
const char * text
const char * token
int32_t unk
bool use_trie
Macro Definition Documentation
CK_TOKENIZER_API
#define CK_TOKENIZER_API __attribute__((visibility("default")))
Definition at line 40 of file tokenizer.h.
CK_TOKENIZER_DEFAULT_HT_SIZE
#define CK_TOKENIZER_DEFAULT_HT_SIZE 65536
Definition at line 50 of file tokenizer.h.
CK_TOKENIZER_MAX_TOKEN_LEN
#define CK_TOKENIZER_MAX_TOKEN_LEN 256
Definition at line 44 of file tokenizer.h.
CK_TOKENIZER_MAX_VOCAB_SIZE
#define CK_TOKENIZER_MAX_VOCAB_SIZE 256000
Definition at line 47 of file tokenizer.h.
Enumeration Type Documentation
CKTokenizerType
enum CKTokenizerType
Enumerator
CK_TOKENIZER_BPE
CK_TOKENIZER_WORDPIECE
CK_TOKENIZER_SPM
Definition at line 53 of file tokenizer.h.
              {
     CK_TOKENIZER_BPE = 0,        /* Byte-Pair Encoding (GPT-2, LLaMA, Qwen) */
     CK_TOKENIZER_WORDPIECE = 1,  /* WordPiece (BERT, RoBERTa) */
     CK_TOKENIZER_SPM = 2         /* SentencePiece (unigram) */
 } CKTokenizerType;
Function Documentation
__attribute__()
__attribute__ ((visibility("default")))
Create a new tokenizer.
Parameters
type Tokenizer type (BPE, WordPiece, SPM)
Returns
Newly allocated tokenizer, or NULL on error
Free a tokenizer.
Parameters
tok Tokenizer to free
Reset tokenizer state (clear vocab but keep config).
Parameters
tok Tokenizer to reset
Set special token IDs.
Parameters
tok Tokenizer
unk Unknown token ID
bos Beginning-of-sequence token ID
eos End-of-sequence token ID
pad Padding token ID
mask Mask token ID
Set whether to lowercase input text before tokenizing.
Parameters
tok Tokenizer
lowercase If true, convert text to lowercase
Set lookup method (trie vs hash table).
Parameters
tok Tokenizer
use_trie If true, use trie (faster for longest-match), false = hash table
Look up token ID by string.
Parameters
tok Tokenizer
token Token string
Returns
Token ID, or unk_id if not found
Get token string by ID.
Parameters
tok Tokenizer
id Token ID
Returns
Token string, or NULL if invalid
Get token info by ID.
Parameters
tok Tokenizer
id Token ID
score Output: token score
Returns
Token string, or NULL if invalid
Decode to buffer allocated by caller.
Parameters
tok Tokenizer
ids Input token IDs
num_ids Number of IDs
out_len Output: length of decoded string
Returns
Newly allocated string, or NULL on error
Get the tokenizer type name.
Parameters
tok Tokenizer
Returns
Type name string
Check if token is special.
Parameters
tok Tokenizer
id Token ID
Returns
true if special token
Estimate encoded token count.
Parameters
tok Tokenizer
text Input text
Returns
Estimated number of tokens
Get last error message.
Returns
Last error message, or NULL if no error
Referenced by fused_mlp_swiglu_decode(), fused_mlp_swiglu_decode_tiled(), fused_mlp_swiglu_decode_v2(), gelu_backward_exact(), gelu_backward_fast(), gelu_fast_inplace(), swiglu_backward(), and swiglu_forward().
ck_tokenizer_add_merge()
int ck_tokenizer_add_merge (CKTokenizer * tok, int32_t left_id, int32_t right_id, int32_t merged_id, int32_t priority)
Add a BPE merge rule.
Parameters
tok Tokenizer
left_id Left token ID
right_id Right token ID
merged_id Merged token ID
priority Lower = higher priority (applied first)
Returns
0 on success, -1 on error
Definition at line 400 of file tokenizer.c.
{
     (void)tok; (void)left; (void)right; (void)merged; (void)priority; return 0;
 }
ck_tokenizer_add_special_token()
int ck_tokenizer_add_special_token (CKTokenizer * tok, const char * name, int32_t id)
Add special token (UNK, BOS, EOS, PAD, MASK).
Parameters
tok Tokenizer
name Special token name ("unk", "bos", "eos", "pad", "mask")
id Token ID
Returns
0 on success, -1 on error
Definition at line 220 of file tokenizer.c.
{
     if (!tok || !name) return -1;
     if (ck_tokenizer_add_token(tok, name, id, -1e10f) != 0) return -1;
     TokenInfo *info = (TokenInfo *)ck_tokenizer_hash_table_lookup(tok->vocab, name);
     if (info) info->is_special = true;
     /* Also add to trie as special */
     if (tok->vocab_trie) {
         ck_trie_insert(tok->vocab_trie, name, id, true, 0);
     }
     if (strcmp(name, "<unk>") == 0 || strcmp(name, "[UNK]") == 0) tok->unk_id = id;
     else if (strcmp(name, "<s>") == 0 || strcmp(name, "<bos>") == 0 || strcmp(name, "[BOS]") == 0) tok->bos_id = id;
     else if (strcmp(name, "</s>") == 0 || strcmp(name, "<eos>") == 0 || strcmp(name, "[EOS]") == 0) tok->eos_id = id;
     else if (strcmp(name, "<pad>") == 0 || strcmp(name, "[PAD]") == 0) tok->pad_id = id;
     return 0;
 }
References CKTokenizer::bos_id, ck_tokenizer_add_token(), ck_tokenizer_hash_table_lookup(), ck_trie_insert(), CKTokenizer::eos_id, id, CKTokenizer::pad_id, CKTokenizer::unk_id, CKTokenizer::vocab, and CKTokenizer::vocab_trie.
Referenced by main().
ck_tokenizer_add_token()
int ck_tokenizer_add_token (CKTokenizer * tok, const char * token, int32_t id, float score)
Add a token to vocabulary.
Parameters
tok Tokenizer
token Token string
id Token ID
score Token score (for SPM)
Returns
0 on success, -1 on error
Definition at line 164 of file tokenizer.c.
{
     if (!tok || !token) {
         return -1;
     }
     /* Ensure we have space in reverse vocab */
     if (id >= (int32_t)tok->vocab_capacity) {
         size_t new_cap = tok->vocab_capacity * 2;
         while (new_cap <= (size_t)id) {
             new_cap *= 2;
         }
         char **new_array = (char **)realloc(tok->id_to_token, new_cap * sizeof(char *));
         if (!new_array) {
             return -1;
         }
         memset(new_array + tok->vocab_capacity, 0, (new_cap - tok->vocab_capacity) * sizeof(char *));
         tok->id_to_token = new_array;
         tok->vocab_capacity = new_cap;
     }
     /* Check if token already exists */
     TokenInfo *existing = (TokenInfo *)ck_tokenizer_hash_table_lookup(tok->vocab, token);
     if (existing) {
         existing->id = id;
         existing->score = score;
         if (id >= (int32_t)tok->vocab_size) tok->vocab_size = id + 1;
         if (tok->id_to_token[id]) free(tok->id_to_token[id]);
         tok->id_to_token[id] = strdup(token);
         return 0;
     }
     /* Create new token info */
     TokenInfo *info = (TokenInfo *)malloc(sizeof(TokenInfo));
     if (!info) return -1;
     info->id = id;
     info->score = score;
     info->is_special = false;
     if (ck_tokenizer_hash_table_insert(tok->vocab, token, info) != 0) {
         free(info);
         return -1;
     }
     /* Also add to trie for fast longest-match lookups */
     if (tok->vocab_trie) {
         ck_trie_insert(tok->vocab_trie, token, id, false, 0);
     }
     if (id >= (int32_t)tok->vocab_size) tok->vocab_size = id + 1;
     if (tok->id_to_token[id]) free(tok->id_to_token[id]);
     tok->id_to_token[id] = strdup(token);
     return 0;
 }
References ck_tokenizer_hash_table_insert(), ck_tokenizer_hash_table_lookup(), ck_trie_insert(), id, CKTokenizer::id_to_token, score, token, CKTokenizer::vocab, CKTokenizer::vocab_capacity, CKTokenizer::vocab_size, and CKTokenizer::vocab_trie.
Referenced by ck_tokenizer_add_special_token(), and ck_tokenizer_load_binary().
ck_tokenizer_create_bpe()
static CKTokenizer* ck_tokenizer_create_bpe (void) inline static
Create tokenizer with default BPE config.
Definition at line 130 of file tokenizer.h.
{
     return ck_tokenizer_create(CK_TOKENIZER_BPE);
 }
References CK_TOKENIZER_BPE, and ck_tokenizer_create().
Referenced by main().
ck_tokenizer_create_spm()
static CKTokenizer* ck_tokenizer_create_spm (void) inline static
Create tokenizer with default SPM config.
Definition at line 144 of file tokenizer.h.
{
     return ck_tokenizer_create(CK_TOKENIZER_SPM);
 }
References ck_tokenizer_create(), and CK_TOKENIZER_SPM.
ck_tokenizer_create_wordpiece()
static CKTokenizer* ck_tokenizer_create_wordpiece (void) inline static
Create tokenizer with default WordPiece config.
Definition at line 137 of file tokenizer.h.
{
     return ck_tokenizer_create(CK_TOKENIZER_WORDPIECE);
 }
References ck_tokenizer_create(), and CK_TOKENIZER_WORDPIECE.
ck_tokenizer_decode()
int ck_tokenizer_decode (const CKTokenizer * tok, const int32_t * ids, int num_ids, char * text, int max_len)
Decode token IDs to text.
Parameters
tok Tokenizer
ids Input token IDs
num_ids Number of IDs
text Output text buffer
max_len Maximum text length
Returns
Number of bytes written
Definition at line 717 of file ck_tokenizer.c.
{
     int len = 0;
     for (int i = 0; i < num_ids; i++) {
         /* Skip special tokens */
         if (ids[i] == tok->bos_id || ids[i] == tok->eos_id || ids[i] == tok->pad_id) {
             continue;
         }
         const char *token = ck_tokenizer_id_to_token(tok, ids[i]);
         if (!token) continue;
         int token_len = (int)strlen(token);
         /* Handle byte tokens <0xXX> */
         if (token_len == 6 && token[0] == '<' && token[1] == '0' && token[2] == 'x') {
             char hex[3] = {token[3], token[4], 0};
             unsigned int byte = (unsigned int)strtol(hex, NULL, 16);
             if (len < max_len - 1) {
                 text[len++] = (char)byte;
             }
             continue;
         }
         /* Handle GPT-style space prefix (Ġ = 0xC4 0xA0 in UTF-8) */
         const char *src = token;
         if ((unsigned char)token[0] == 0xC4 && (unsigned char)token[1] == 0xA0) {
             if (len < max_len - 1) {
                 text[len++] = ' ';
             }
             src = token + 2;
             token_len -= 2;
         }
         /* Copy token */
         for (int j = 0; j < token_len && len < max_len - 1; j++) {
             text[len++] = src[j];
         }
     }
     text[len] = '\0';
     return len;
 }
References ck_tokenizer_id_to_token(), ids, num_ids, text, and token.
ck_tokenizer_encode()
int ck_tokenizer_encode (const CKTokenizer * tok, const char * text, int text_len, int32_t * ids, int max_ids)
Encode text to token IDs using greedy longest-match.
For BPE: applies merge rules iteratively. For WordPiece/SPM: greedy longest-match from vocabulary.
Parameters
tok Tokenizer
text Input text
text_len Text length, or -1 for null-terminated
ids Output token IDs
max_ids Maximum IDs to write
Returns
Number of tokens written
Definition at line 618 of file ck_tokenizer.c.
{
     if (text_len < 0) text_len = (int)strlen(text);
     /* Pre-tokenize: split on whitespace, keep spaces as tokens */
     /* For simplicity, treat each byte as initial token, then apply BPE */
     /* Initial tokens: one per byte */
     int32_t *tokens = (int32_t *)malloc(text_len * sizeof(int32_t));
     int num_tokens = 0;
     for (int i = 0; i < text_len; i++) {
         /* Look up single-character token */
         char c[2] = {text[i], '\0'};
         int32_t id = ck_tokenizer_lookup(tok, c, 1);
         /* Handle special byte tokens like <0xXX> */
         if (id == tok->unk_id) {
             char byte_token[8];
             snprintf(byte_token, sizeof(byte_token), "<0x%02X>", (unsigned char)text[i]);
             id = ck_tokenizer_lookup(tok, byte_token, -1);
         }
         /* Try UTF-8 multi-byte sequences */
         if (id == tok->unk_id && (unsigned char)text[i] >= 0x80) {
             int utf8_len = 1;
             if ((text[i] & 0xE0) == 0xC0) utf8_len = 2;
             else if ((text[i] & 0xF0) == 0xE0) utf8_len = 3;
             else if ((text[i] & 0xF8) == 0xF0) utf8_len = 4;
             if (i + utf8_len <= text_len) {
                 id = ck_tokenizer_lookup(tok, text + i, utf8_len);
                 if (id != tok->unk_id) {
                     tokens[num_tokens++] = id;
                     i += utf8_len - 1;
                     continue;
                 }
             }
         }
         tokens[num_tokens++] = id;
     }
     /* Apply BPE merges iteratively */
     bool changed = true;
     while (changed && num_tokens > 1) {
         changed = false;
         /* Find best merge (lowest priority = earliest in merge list) */
         int best_pos = -1;
         int best_priority = tok->num_merges;
         for (int i = 0; i < num_tokens - 1; i++) {
             int merge_idx = ck_tokenizer_lookup_merge(tok, tokens[i], tokens[i + 1]);
             if (merge_idx >= 0 && tok->merges[merge_idx].priority < best_priority) {
                 best_pos = i;
                 best_priority = tok->merges[merge_idx].priority;
             }
         }
         if (best_pos >= 0) {
             int merge_idx = ck_tokenizer_lookup_merge(tok, tokens[best_pos], tokens[best_pos + 1]);
             tokens[best_pos] = tok->merges[merge_idx].merged;
             /* Shift remaining tokens */
             for (int i = best_pos + 1; i < num_tokens - 1; i++) {
                 tokens[i] = tokens[i + 1];
             }
             num_tokens--;
             changed = true;
         }
     }
     /* Copy to output */
     int out_len = 0;
     if (tok->add_bos && out_len < max_ids) {
         ids[out_len++] = tok->bos_id;
     }
     for (int i = 0; i < num_tokens && out_len < max_ids; i++) {
         ids[out_len++] = tokens[i];
     }
     if (tok->add_eos && out_len < max_ids) {
         ids[out_len++] = tok->eos_id;
     }
     free(tokens);
     return out_len;
 }
References CKTokenizerConfig::add_bos, CKTokenizerConfig::add_eos, CKTokenizer::bos_id, CK_TOKENIZER_WORDPIECE, CKTokenizer::config, CKTokenizer::eos_id, find_longest_match(), id, ids, text, CKTokenizerConfig::type, and CKTokenizer::unk_id.
ck_tokenizer_encode_tokens()
int ck_tokenizer_encode_tokens (const CKTokenizer * tok, const char * text, int text_len, const char ** out_tokens, int max_tokens)
Encode and return tokens as array of strings.
Parameters
tok Tokenizer
text Input text
text_len Text length
out_tokens Output token strings (caller must free each)
max_tokens Maximum tokens
Returns
Number of tokens written
ck_tokenizer_encode_with_special()
int ck_tokenizer_encode_with_special (CKTokenizer * tok, const char * text, int text_len, int32_t * ids, int max_ids, bool add_special)
Encode with special token handling.
Parameters
tok Tokenizer
text Input text
text_len Text length, or -1 for null-terminated
ids Output token IDs
max_ids Maximum IDs to write
add_special Add BOS/EOS tokens
Returns
Number of tokens written
ck_tokenizer_load_binary()
int ck_tokenizer_load_binary (CKTokenizer * tok, int vocab_size, const int32_t * offsets, const char * strings, int num_merges, const int32_t * merges)
Load vocabulary from memory-mapped binary data.
Parameters
tok Tokenizer
vocab_size Number of tokens
offsets Array of offsets into strings pool
strings String pool containing null-terminated tokens
num_merges Number of BPE merges
merges Merge rules as (left, right, merged) triplets
Returns
0 on success, -1 on error
Definition at line 18 of file ck_tokenizer_v2.c.
{
     if (!tok || !offsets || !strings) return -1;
     // We assume ck_tokenizer_init was already called to alloc hash tables
     tok->vocab_size = 0;
     for (int i = 0; i < vocab_size; i++) {
         const char *token = strings + offsets[i];
         int len = (int)strlen(token);
         CKVocabEntry *entry = (CKVocabEntry *)ck_pool_alloc(&tok->pool, sizeof(CKVocabEntry));
         entry->token = (char *)token;
         entry->token_len = len;
         entry->id = i;
         uint32_t bucket = hash_string(token, len) % tok->vocab_hash_size;
         entry->next = tok->vocab_hash[bucket];
         tok->vocab_hash[bucket] = entry;
         tok->id_to_token[i] = entry->token;
         tok->vocab_size++;
     }
     if (merges && num_merges > 0) {
         for (int i = 0; i < num_merges; i++) {
             int32_t left = merges[i*3 + 0];
             int32_t right = merges[i*3 + 1];
             int32_t merged = merges[i*3 + 2];
             ck_tokenizer_add_merge(tok, left, right, merged);
         }
     }
     return 0;
 }
References ck_pool_alloc(), ck_tokenizer_add_merge(), ck_tokenizer_add_token(), ck_tokenizer_reset(), hash_string(), CKVocabEntry::id, CKTokenizer::id_to_token, CKVocabEntry::next, CKTokenizer::pool, CKVocabEntry::token, token, CKVocabEntry::token_len, CKTokenizer::vocab_hash, CKTokenizer::vocab_hash_size, and CKTokenizer::vocab_size.
Referenced by main().
ck_tokenizer_load_gguf()
int ck_tokenizer_load_gguf (CKTokenizer * tok, const char * path)
Load vocabulary from GGUF file.
Parameters
tok Tokenizer
path Path to GGUF file
Returns
0 on success, -1 on error
Definition at line 396 of file tokenizer.c.
 { (void)tok; (void)path; return -1; }
ck_tokenizer_load_json()
int ck_tokenizer_load_json (CKTokenizer * tok, const char * path)
Load vocabulary from JSON file (HuggingFace format).
Parameters
tok Tokenizer
path Path to vocab.json or tokenizer.json
Returns
0 on success, -1 on error
Definition at line 397 of file tokenizer.c.
 { (void)tok; (void)path; return -1; }
ck_tokenizer_load_merges()
int ck_tokenizer_load_merges (CKTokenizer * tok, const char * path)
Load BPE merges from text file.
Format: token1 token2 (one merge per line)
Parameters
tok Tokenizer
path Path to merges.txt
Returns
0 on success, -1 on error
Definition at line 399 of file tokenizer.c.
 { (void)tok; (void)path; return -1; }
ck_tokenizer_load_text()
int ck_tokenizer_load_text (CKTokenizer * tok, const char * path)
Load vocabulary from text file (one token per line).
Format: token_string [id] [score] Lines starting with # are comments.
Parameters
tok Tokenizer
path Path to vocabulary file
Returns
0 on success, -1 on error
Definition at line 398 of file tokenizer.c.
 { (void)tok; (void)path; return -1; }
ck_tokenizer_vocab_size()
static size_t ck_tokenizer_vocab_size (const CKTokenizer * tok) inline static
Get vocabulary size.
Definition at line 258 of file tokenizer.h.
{
     return tok ? tok->vocab_size : 0;
 }
References CKTokenizer::vocab_size.
Variable Documentation
bos
int32_t int32_t bos
Definition at line 204 of file tokenizer.h.
Referenced by ck_tokenizer_set_special_ids().
eos
int32_t int32_t int32_t eos
Definition at line 205 of file tokenizer.h.
Referenced by ck_tokenizer_set_special_ids().
id
int32_t id
Definition at line 241 of file tokenizer.h.
Referenced by ck_tokenizer_add_special_token(), ck_tokenizer_add_token(), ck_tokenizer_encode(), ck_tokenizer_id_to_token(), ck_tokenizer_load(), and topology_discover_cpu().
ids
const int32_t* ids
Definition at line 369 of file tokenizer.h.
Referenced by ck_tokenizer_decode(), ck_tokenizer_encode(), and main().
lowercase
bool lowercase
Definition at line 215 of file tokenizer.h.
mask
int32_t int32_t int32_t int32_t int32_t mask
Definition at line 207 of file tokenizer.h.
Referenced by ck_dtype_supported(), ck_tokenizer_set_special_ids(), relu_backward(), and topology_discover_affinity().
num_ids
const int32_t int num_ids
Definition at line 370 of file tokenizer.h.
Referenced by ck_tokenizer_decode(), and main().
out_len
const int32_t int int* out_len
Definition at line 371 of file tokenizer.h.
Referenced by ck_tokenizer_encode(), ck_utf8_next_char(), and find_object_range().
pad
int32_t int32_t int32_t int32_t pad
Definition at line 206 of file tokenizer.h.
Referenced by ck_tokenizer_set_special_ids().
score
int32_t float* score
Definition at line 253 of file tokenizer.h.
Referenced by attention_flash_query_causal(), and ck_tokenizer_add_token().
text
const char* text
Definition at line 464 of file tokenizer.h.
Referenced by ck_tokenizer_decode(), ck_tokenizer_encode(), ck_trie_find_longest(), ck_trie_has_prefix(), find_longest_match(), find_longest_match_hash(), find_longest_match_trie(), and main().
token
const char* token
Definition at line 232 of file tokenizer.h.
Referenced by ck_tokenizer_add_token(), ck_tokenizer_decode(), ck_tokenizer_load(), ck_tokenizer_load_binary(), ck_tokenizer_lookup(), ck_trie_insert(), main(), and topology_discover_numa().
unk
int32_t unk
Definition at line 203 of file tokenizer.h.
Referenced by ck_tokenizer_set_special_ids().
use_trie
bool use_trie
Definition at line 223 of file tokenizer.h.
Referenced by ck_tokenizer_set_use_trie().