#!/usr/bin/env python3
"""
test_ir_stitch_validate.py - Static IR stitching + layout validation for Lower 3.

PURPOSE:
    Validates that the IR (Intermediate Representation) generated by the lowering
    pipeline is structurally correct before code generation. This catches issues
    with kernel stitching, buffer layout, and dimension compatibility.

WHAT IT CHECKS:
    1. NULL pointer arguments - Detects missing required arguments
    2. Weight vs activation macro mismatches - Ensures weight args don't use
       activation macros (A_*) and vice versa
    3. RMSNorm ordering - Verifies LN1 comes before LN2 within each layer
    4. Core dimension sanity - Validates M/K/N dimensions for q/k/v projections,
       out_proj, and MLP layers match expected model dimensions
    5. Head-major binding sanity - For prefill kernels, checks that head count
       and head_dim bindings are correct

USAGE:
    python test_ir_stitch_validate.py                           # Check both decode/prefill
    python test_ir_stitch_validate.py --mode decode             # Decode only
    python test_ir_stitch_validate.py --mode prefill            # Prefill only
    python test_ir_stitch_validate.py --model-dir /path/to/model # Custom model

EXIT CODES:
    0 = PASS (all validations passed)
    1 = FAIL (validation errors found)

FILES REQUIRED (in model-dir):
    - lowered_decode_call.json
    - lowered_prefill_call.json
"""

import argparse
import json
import sys
from pathlib import Path

DEFAULT_MODEL_DIR = Path.home() / ".cache/ck-engine-v6.6/models/Qwen--Qwen2-0.5B-Instruct-GGUF"


def _load_ir(path: Path) -> dict:
    with path.open("r") as f:
        return json.load(f)


def _resolve_dim(expr: str, config: dict) -> int | None:
    expr = str(expr).strip()
    if expr.isdigit():
        return int(expr)
    macro_map = {
        "EMBED_DIM": config.get("embed_dim"),
        "INTERMEDIATE_SIZE": config.get("intermediate_size"),
        "HEAD_DIM": config.get("head_dim"),
        "NUM_HEADS": config.get("num_heads"),
        "NUM_KV_HEADS": config.get("num_kv_heads"),
        "MAX_SEQ_LEN": config.get("context_len", config.get("max_seq_len")),
    }
    return macro_map.get(expr)


def _is_weight_source(src: str) -> bool:
    return src.startswith("weight") or src.startswith("dtype_weight")


def _is_activation_source(src: str) -> bool:
    return src.startswith("activation") or src.startswith("output") or src.startswith("scratch")


def _check_rmsnorm_order(ops: list, errors: list) -> None:
    by_layer = {}
    optional_null = {"rstd_cache", "rstd", "pos_embeddings"}
    for op in ops:
        if op.get("op") == "rmsnorm" and op.get("section") == "body":
            by_layer.setdefault(op.get("layer", -1), []).append(op)
    for layer, layer_ops in by_layer.items():
        if len(layer_ops) < 2:
            errors.append(f"layer {layer}: expected 2 rmsnorm ops, found {len(layer_ops)}")
            continue
        first = layer_ops[0]
        second = layer_ops[1]
        first_gamma = next((a for a in first.get("args", []) if a.get("name") == "gamma"), None)
        second_gamma = next((a for a in second.get("args", []) if a.get("name") == "gamma"), None)
        if first_gamma and "LN1" not in first_gamma.get("expr", ""):
            errors.append(f"layer {layer}: first rmsnorm gamma is not LN1 ({first_gamma.get('expr')})")
        if second_gamma and "LN2" not in second_gamma.get("expr", ""):
            errors.append(f"layer {layer}: second rmsnorm gamma is not LN2 ({second_gamma.get('expr')})")


def _check_dims(op: dict, config: dict, errors: list) -> None:
    op_type = op.get("op")
    func = op.get("function", op.get("kernel", ""))
    args = op.get("args", [])
    dims = {a.get("name"): _resolve_dim(a.get("expr", ""), config) for a in args if a.get("name") in {"M", "K", "N",
                                                                                                       "aligned_embed_dim",
                                                                                                       "aligned_head_dim",
                                                                                                       "num_heads",
                                                                                                       "num_kv_heads"}}
    embed_dim = config.get("embed_dim", 0)
    head_dim = config.get("head_dim", 0)
    num_kv_heads = config.get("num_kv_heads", 0)
    num_heads = config.get("num_heads", 0)
    kv_dim = head_dim * num_kv_heads if head_dim and num_kv_heads else None
    interm = config.get("intermediate_size", 0)

    is_gemm = func.startswith("gemm_nt_")
    is_gemv = func.startswith("gemv_")

    if op_type == "q_proj" and is_gemv:
        if dims.get("M") and dims["M"] != embed_dim:
            errors.append(f"q_proj M={dims['M']} != embed_dim {embed_dim}")
        if dims.get("K") and dims["K"] != embed_dim:
            errors.append(f"q_proj K={dims['K']} != embed_dim {embed_dim}")
    elif op_type in ("k_proj", "v_proj") and is_gemv:
        if kv_dim and dims.get("M") and dims["M"] != kv_dim:
            errors.append(f"{op_type} M={dims['M']} != kv_dim {kv_dim}")
        if dims.get("K") and dims["K"] != embed_dim:
            errors.append(f"{op_type} K={dims['K']} != embed_dim {embed_dim}")
    elif op_type == "out_proj" and is_gemv:
        if dims.get("M") and dims["M"] != embed_dim:
            errors.append(f"out_proj M={dims['M']} != embed_dim {embed_dim}")
        if dims.get("K") and dims["K"] != embed_dim:
            errors.append(f"out_proj K={dims['K']} != embed_dim {embed_dim}")
    elif op_type == "mlp_gate_up":
        expected = interm * 2 if interm else None
        if is_gemv:
            if expected and dims.get("M") and dims["M"] != expected:
                errors.append(f"mlp_gate_up M={dims['M']} != 2*intermediate_size {expected}")
            if dims.get("K") and dims["K"] != embed_dim:
                errors.append(f"mlp_gate_up K={dims['K']} != embed_dim {embed_dim}")
        elif is_gemm:
            if expected and dims.get("N") and dims["N"] != expected:
                errors.append(f"mlp_gate_up N={dims['N']} != 2*intermediate_size {expected}")
            if dims.get("K") and dims["K"] != embed_dim:
                errors.append(f"mlp_gate_up K={dims['K']} != embed_dim {embed_dim}")
    elif op_type == "mlp_down":
        if is_gemv:
            if dims.get("M") and dims["M"] != embed_dim:
                errors.append(f"mlp_down M={dims['M']} != embed_dim {embed_dim}")
            if dims.get("K") and dims["K"] != interm:
                errors.append(f"mlp_down K={dims['K']} != intermediate_size {interm}")
        elif is_gemm:
            if dims.get("N") and dims["N"] != embed_dim:
                errors.append(f"mlp_down N={dims['N']} != embed_dim {embed_dim}")
            if dims.get("K") and dims["K"] != interm:
                errors.append(f"mlp_down K={dims['K']} != intermediate_size {interm}")
    elif op_type == "qkv_proj":
        # Head-major prefill kernels (static params)
        if dims.get("aligned_embed_dim") and dims["aligned_embed_dim"] != embed_dim:
            errors.append(f"qkv_proj aligned_embed_dim={dims['aligned_embed_dim']} != embed_dim {embed_dim}")
        if dims.get("num_heads") and dims["num_heads"] != num_heads:
            errors.append(f"qkv_proj num_heads={dims['num_heads']} != num_heads {num_heads}")
        if dims.get("num_kv_heads") and dims["num_kv_heads"] != num_kv_heads:
            errors.append(f"qkv_proj num_kv_heads={dims['num_kv_heads']} != num_kv_heads {num_kv_heads}")
        if dims.get("aligned_head_dim") and dims["aligned_head_dim"] != head_dim:
            errors.append(f"qkv_proj aligned_head_dim={dims['aligned_head_dim']} != head_dim {head_dim}")


def _validate_ir(ir: dict) -> tuple[list, list]:
    errors = []
    warnings = []

    ops = ir.get("operations", ir.get("ops", []))
    config = ir.get("config", {})
    optional_null = {"rstd_cache", "rstd", "pos_embeddings"}

    # Basic IR health
    if ir.get("errors"):
        errors.extend([f"IR errors: {e}" for e in ir.get("errors", [])[:5]])

    for op in ops:
        # Missing args
        if "args" not in op:
            errors.append(f"Op {op.get('idx')} missing args")
            continue

        for arg in op.get("args", []):
            expr = arg.get("expr", "")
            src = arg.get("source", "")
            if "NULL" in expr:
                if arg.get("name") == "bias":
                    warnings.append(f"Op {op.get('idx')} {op.get('op')} bias is NULL")
                    continue
                if arg.get("name") in optional_null:
                    continue
                errors.append(f"Op {op.get('idx')} {op.get('op')} arg {arg.get('name')} is NULL")
                continue

            # Weight vs activation macro mismatch
            if _is_weight_source(src):
                if "A_" in expr:
                    errors.append(f"Op {op.get('idx')} {op.get('op')} weight arg uses activation macro: {expr}")
            if _is_activation_source(src):
                if "W_" in expr:
                    errors.append(f"Op {op.get('idx')} {op.get('op')} activation arg uses weight macro: {expr}")

        _check_dims(op, config, errors)

    _check_rmsnorm_order(ops, errors)

    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser(description="IR stitching validator (Lower 3)")
    parser.add_argument("--model-dir", type=Path, default=DEFAULT_MODEL_DIR)
    parser.add_argument("--mode", choices=["decode", "prefill", "both"], default="both")
    args = parser.parse_args()

    model_dir = args.model_dir
    errors = []
    warnings = []

    def _check_one(name: str) -> None:
        path = model_dir / f"lowered_{name}_call.json"
        if not path.exists():
            warnings.append(f"missing {path}")
            return
        ir = _load_ir(path)
        e, w = _validate_ir(ir)
        if e:
            errors.append(f"[{name}] " + "; ".join(e))
        warnings.extend([f"[{name}] {x}" for x in w])

    if args.mode in ("decode", "both"):
        _check_one("decode")
    if args.mode in ("prefill", "both"):
        _check_one("prefill")

    print("=" * 72)
    print("IR STITCH VALIDATION")
    print("=" * 72)
    print(f"Model dir: {model_dir}")
    if warnings:
        print(f"Warnings: {len(warnings)}")
        for w in warnings[:5]:
            print(f"  {w}")
    if errors:
        print(f"Errors: {len(errors)}")
        for e in errors[:5]:
            print(f"  {e}")
        print("FAIL")
        return 1

    print("PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
