/*
 * Auto-generated by codegen_train_runtime_v7.py
 *
 * Compile-ready v7 training runtime skeleton.
 * Source: IR2 backward artifact (forward + backward op chains).
 */

#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include "ckernel_engine.h"

#ifndef CK_NUM_TOKENS
#define CK_NUM_TOKENS 1
#endif
#ifndef CK_TENSOR_CAP_F32
#define CK_TENSOR_CAP_F32 4096
#endif
#ifndef CK_TENSOR_CAP_I32
#define CK_TENSOR_CAP_I32 512
#endif

/* Fallback declarations for kernels with incomplete registry declarations. */
/* adamw_update_f32 -> adamw_update_f32 */
void adamw_update_f32(const float *grad, float *weight, float *m, float *v, size_t numel, float lr, float beta1, float beta2, float eps, float weight_decay, int step);
/* attention_backward_causal_head_major_gqa -> attention_backward_causal_head_major_gqa */
void attention_backward_causal_head_major_gqa(const float *d_output, const float *q, const float *k, const float *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window);
/* attention_forward_causal_head_major_gqa_flash_strided -> attention_forward_causal_head_major_gqa_flash_strided */
void attention_forward_causal_head_major_gqa_flash_strided(const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens);
/* ck_residual_add_token_major -> ck_residual_add_token_major */
void ck_residual_add_token_major(const float *a, const float *b, float *out, int tokens, int aligned_embed_dim);
/* dense_embedding_lookup -> embedding_forward */
void embedding_forward(const int32_t *token_ids, int token_count, int vocab_size, const float *token_embeddings, const float *pos_embeddings, float *output, int embed_dim, int aligned_embed_dim, int context_window, int add_pos);
/* embedding_backward_f32 -> embedding_backward */
void embedding_backward(const int32_t *token_ids, int token_count, const float *d_output, float *d_token_embeddings, float *d_pos_embeddings, int vocab_size, int embed_dim, int aligned_embed_dim, int context_window, int add_pos);
/* gemm_backward_f32 -> fc2_backward_kernel */
void fc2_backward_kernel(const float *d_output, const float *fc2_input, const float *W_fc2, float *d_input, float *d_W_fc2, float *d_b_fc2, int T, int aligned_in, int aligned_out, int num_threads);
/* gemm_blocked_serial -> gemm_blocked_serial */
void gemm_blocked_serial(const float *A, const float *B, const float *bias, float *C, int M, int N, int K);
/* gradient_accumulate_f32 -> gradient_accumulate_f32 */
void gradient_accumulate_f32(float *dst, const float *src, size_t numel);
/* qk_norm_backward_f32 -> qk_norm_backward */
void qk_norm_backward(const float *d_q_out, const float *d_k_out, const float *q_in, const float *k_in, const float *q_gamma, const float *k_gamma, float *d_q_in, float *d_k_in, float *d_q_gamma, float *d_k_gamma, int num_heads, int num_kv_heads, int num_tokens, int head_dim, float eps);
/* qk_norm_forward -> qk_norm_forward */
void qk_norm_forward(float *q, float *k, const float *q_gamma, const float *k_gamma, int num_heads, int num_kv_heads, int num_tokens, int head_dim, float eps);
/* residual_add_backward_f32 -> ck_residual_add_backward */
void ck_residual_add_backward(const float *d_out, float *d_a, float *d_b, int tokens, int aligned_embed_dim);
/* rmsnorm_backward -> rmsnorm_backward */
void rmsnorm_backward(const float *d_output, const float *input, const float *gamma, const float *rstd_cache, float *d_input, float *d_gamma, int tokens, int d_model, int aligned_embed_dim);
/* rmsnorm_forward -> rmsnorm_forward */
void rmsnorm_forward(const float *input, const float *gamma, float *output, float *rstd_cache, int tokens, int d_model, int aligned_embed_dim, float eps);
/* rope_backward_qk_f32 -> rope_backward_qk */
void rope_backward_qk(const float *d_q_out, const float *d_k_out, float *d_q, float *d_k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset);
/* rope_forward_qk -> rope_forward_qk_with_rotary_dim */
void rope_forward_qk_with_rotary_dim(float *q, float *k, const float *cos_cache, const float *sin_cache, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int pos_offset, int rotary_dim);
/* softmax_cross_entropy_loss -> softmax_cross_entropy_loss */
void softmax_cross_entropy_loss(const float *logits, const int32_t *targets, int tokens, int vocab_size, float *d_logits, float *loss_out);
/* swiglu_backward_exact -> swiglu_backward_exact */
void swiglu_backward_exact(const float *input, const float *d_output, float *d_input, int tokens, int dim);
/* swiglu_forward -> swiglu_forward */
void swiglu_forward(const float *input, float *output, int tokens, int dim);

static float g_dummy_f32[CK_TENSOR_CAP_F32];
static int32_t g_dummy_i32[CK_TENSOR_CAP_I32];
static float g_loss_scalar[1];

static float act_L0_attn_0_out[CK_TENSOR_CAP_F32]; /* act.L0.attn.0.out */
static float act_L0_k_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L0.k_proj.0.y */
static float act_L0_mlp_down_0_y[CK_TENSOR_CAP_F32]; /* act.L0.mlp_down.0.y */
static float act_L0_mlp_gate_up_0_y[CK_TENSOR_CAP_F32]; /* act.L0.mlp_gate_up.0.y */
static float act_L0_out_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L0.out_proj.0.y */
static float act_L0_q_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L0.q_proj.0.y */
static float act_L0_qk_norm_0_k[CK_TENSOR_CAP_F32]; /* act.L0.qk_norm.0.k */
static float act_L0_qk_norm_0_q[CK_TENSOR_CAP_F32]; /* act.L0.qk_norm.0.q */
static float act_L0_residual_add_0_out[CK_TENSOR_CAP_F32]; /* act.L0.residual_add.0.out */
static float act_L0_residual_add_1_out[CK_TENSOR_CAP_F32]; /* act.L0.residual_add.1.out */
static float act_L0_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* act.L0.rmsnorm.0.output */
static float act_L0_rmsnorm_0_rstd_cache[CK_TENSOR_CAP_F32]; /* act.L0.rmsnorm.0.rstd_cache */
static float act_L0_rmsnorm_1_output[CK_TENSOR_CAP_F32]; /* act.L0.rmsnorm.1.output */
static float act_L0_rmsnorm_1_rstd_cache[CK_TENSOR_CAP_F32]; /* act.L0.rmsnorm.1.rstd_cache */
static float act_L0_rope_qk_0_k[CK_TENSOR_CAP_F32]; /* act.L0.rope_qk.0.k */
static float act_L0_rope_qk_0_q[CK_TENSOR_CAP_F32]; /* act.L0.rope_qk.0.q */
static float act_L0_silu_mul_0_out[CK_TENSOR_CAP_F32]; /* act.L0.silu_mul.0.out */
static float act_L0_v_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L0.v_proj.0.y */
static float act_L1_attn_0_out[CK_TENSOR_CAP_F32]; /* act.L1.attn.0.out */
static float act_L1_k_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L1.k_proj.0.y */
static float act_L1_mlp_down_0_y[CK_TENSOR_CAP_F32]; /* act.L1.mlp_down.0.y */
static float act_L1_mlp_gate_up_0_y[CK_TENSOR_CAP_F32]; /* act.L1.mlp_gate_up.0.y */
static float act_L1_out_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L1.out_proj.0.y */
static float act_L1_q_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L1.q_proj.0.y */
static float act_L1_qk_norm_0_k[CK_TENSOR_CAP_F32]; /* act.L1.qk_norm.0.k */
static float act_L1_qk_norm_0_q[CK_TENSOR_CAP_F32]; /* act.L1.qk_norm.0.q */
static float act_L1_residual_add_0_out[CK_TENSOR_CAP_F32]; /* act.L1.residual_add.0.out */
static float act_L1_residual_add_1_out[CK_TENSOR_CAP_F32]; /* act.L1.residual_add.1.out */
static float act_L1_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* act.L1.rmsnorm.0.output */
static float act_L1_rmsnorm_0_rstd_cache[CK_TENSOR_CAP_F32]; /* act.L1.rmsnorm.0.rstd_cache */
static float act_L1_rmsnorm_1_output[CK_TENSOR_CAP_F32]; /* act.L1.rmsnorm.1.output */
static float act_L1_rmsnorm_1_rstd_cache[CK_TENSOR_CAP_F32]; /* act.L1.rmsnorm.1.rstd_cache */
static float act_L1_rope_qk_0_k[CK_TENSOR_CAP_F32]; /* act.L1.rope_qk.0.k */
static float act_L1_rope_qk_0_q[CK_TENSOR_CAP_F32]; /* act.L1.rope_qk.0.q */
static float act_L1_silu_mul_0_out[CK_TENSOR_CAP_F32]; /* act.L1.silu_mul.0.out */
static float act_L1_v_proj_0_y[CK_TENSOR_CAP_F32]; /* act.L1.v_proj.0.y */
static float act_Sfooter_logits_0_y[CK_TENSOR_CAP_F32]; /* act.Sfooter.logits.0.y */
static float act_Sfooter_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* act.Sfooter.rmsnorm.0.output */
static float act_Sfooter_rmsnorm_0_rstd_cache[CK_TENSOR_CAP_F32]; /* act.Sfooter.rmsnorm.0.rstd_cache */
static float act_Sheader_dense_embedding_lookup_0_out[CK_TENSOR_CAP_F32]; /* act.Sheader.dense_embedding_lookup.0.out */
static float aux_d_bias[CK_TENSOR_CAP_F32]; /* aux.d_bias */
static float aux_d_pos_embeddings[CK_TENSOR_CAP_F32]; /* aux.d_pos_embeddings */
static float aux_d_scores[CK_TENSOR_CAP_F32]; /* aux.d_scores */
static float aux_loss[CK_TENSOR_CAP_F32]; /* aux.loss */
static float grad_act_act_L0_attn_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.attn.0.out */
static float grad_act_act_L0_k_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.k_proj.0.y */
static float grad_act_act_L0_mlp_down_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.mlp_down.0.y */
static float grad_act_act_L0_mlp_gate_up_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.mlp_gate_up.0.y */
static float grad_act_act_L0_out_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.out_proj.0.y */
static float grad_act_act_L0_q_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.q_proj.0.y */
static float grad_act_act_L0_qk_norm_0_k[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.qk_norm.0.k */
static float grad_act_act_L0_qk_norm_0_q[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.qk_norm.0.q */
static float grad_act_act_L0_residual_add_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.residual_add.0.out */
static float grad_act_act_L0_residual_add_1_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.residual_add.1.out */
static float grad_act_act_L0_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.rmsnorm.0.output */
static float grad_act_act_L0_rmsnorm_1_output[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.rmsnorm.1.output */
static float grad_act_act_L0_rope_qk_0_k[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.rope_qk.0.k */
static float grad_act_act_L0_rope_qk_0_q[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.rope_qk.0.q */
static float grad_act_act_L0_silu_mul_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.silu_mul.0.out */
static float grad_act_act_L0_v_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L0.v_proj.0.y */
static float grad_act_act_L1_attn_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.attn.0.out */
static float grad_act_act_L1_k_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.k_proj.0.y */
static float grad_act_act_L1_mlp_down_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.mlp_down.0.y */
static float grad_act_act_L1_mlp_gate_up_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.mlp_gate_up.0.y */
static float grad_act_act_L1_out_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.out_proj.0.y */
static float grad_act_act_L1_q_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.q_proj.0.y */
static float grad_act_act_L1_qk_norm_0_k[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.qk_norm.0.k */
static float grad_act_act_L1_qk_norm_0_q[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.qk_norm.0.q */
static float grad_act_act_L1_residual_add_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.residual_add.0.out */
static float grad_act_act_L1_residual_add_1_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.residual_add.1.out */
static float grad_act_act_L1_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.rmsnorm.0.output */
static float grad_act_act_L1_rmsnorm_1_output[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.rmsnorm.1.output */
static float grad_act_act_L1_rope_qk_0_k[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.rope_qk.0.k */
static float grad_act_act_L1_rope_qk_0_q[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.rope_qk.0.q */
static float grad_act_act_L1_silu_mul_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.silu_mul.0.out */
static float grad_act_act_L1_v_proj_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.L1.v_proj.0.y */
static float grad_act_act_Sfooter_logits_0_y[CK_TENSOR_CAP_F32]; /* grad.act.act.Sfooter.logits.0.y */
static float grad_act_act_Sfooter_rmsnorm_0_output[CK_TENSOR_CAP_F32]; /* grad.act.act.Sfooter.rmsnorm.0.output */
static float grad_act_act_Sheader_dense_embedding_lookup_0_out[CK_TENSOR_CAP_F32]; /* grad.act.act.Sheader.dense_embedding_lookup.0.out */
static float grad_weight_final_ln_weight[CK_TENSOR_CAP_F32]; /* grad.weight.final_ln_weight */
static float grad_weight_layer_0_b1[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.b1 */
static float grad_weight_layer_0_b2[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.b2 */
static float grad_weight_layer_0_bk[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.bk */
static float grad_weight_layer_0_bo[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.bo */
static float grad_weight_layer_0_bq[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.bq */
static float grad_weight_layer_0_bv[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.bv */
static float grad_weight_layer_0_k_norm[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.k_norm */
static float grad_weight_layer_0_ln1_gamma[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.ln1_gamma */
static float grad_weight_layer_0_ln2_gamma[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.ln2_gamma */
static float grad_weight_layer_0_q_norm[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.q_norm */
static float grad_weight_layer_0_w1[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.w1 */
static float grad_weight_layer_0_w2[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.w2 */
static float grad_weight_layer_0_wk[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.wk */
static float grad_weight_layer_0_wo[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.wo */
static float grad_weight_layer_0_wq[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.wq */
static float grad_weight_layer_0_wv[CK_TENSOR_CAP_F32]; /* grad.weight.layer.0.wv */
static float grad_weight_layer_1_b1[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.b1 */
static float grad_weight_layer_1_b2[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.b2 */
static float grad_weight_layer_1_bk[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.bk */
static float grad_weight_layer_1_bo[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.bo */
static float grad_weight_layer_1_bq[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.bq */
static float grad_weight_layer_1_bv[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.bv */
static float grad_weight_layer_1_k_norm[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.k_norm */
static float grad_weight_layer_1_ln1_gamma[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.ln1_gamma */
static float grad_weight_layer_1_ln2_gamma[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.ln2_gamma */
static float grad_weight_layer_1_q_norm[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.q_norm */
static float grad_weight_layer_1_w1[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.w1 */
static float grad_weight_layer_1_w2[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.w2 */
static float grad_weight_layer_1_wk[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.wk */
static float grad_weight_layer_1_wo[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.wo */
static float grad_weight_layer_1_wq[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.wq */
static float grad_weight_layer_1_wv[CK_TENSOR_CAP_F32]; /* grad.weight.layer.1.wv */
static float grad_weight_token_emb[CK_TENSOR_CAP_F32]; /* grad.weight.token_emb */
static float saved_op22_attn_weights[CK_TENSOR_CAP_F32]; /* saved.op22.attn_weights */
static float saved_op8_attn_weights[CK_TENSOR_CAP_F32]; /* saved.op8.attn_weights */
static float tmp_grad_act_op10_a[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op10.a */
static float tmp_grad_act_op10_b[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op10.b */
static float tmp_grad_act_op11_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op11.input */
static float tmp_grad_act_op12_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op12.input */
static float tmp_grad_act_op13_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op13.input */
static float tmp_grad_act_op14_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op14.input */
static float tmp_grad_act_op15_a[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op15.a */
static float tmp_grad_act_op15_b[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op15.b */
static float tmp_grad_act_op16_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op16.input */
static float tmp_grad_act_op17_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op17.input */
static float tmp_grad_act_op18_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op18.input */
static float tmp_grad_act_op19_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op19.input */
static float tmp_grad_act_op20_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op20.k */
static float tmp_grad_act_op20_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op20.q */
static float tmp_grad_act_op21_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op21.k */
static float tmp_grad_act_op21_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op21.q */
static float tmp_grad_act_op22_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op22.k */
static float tmp_grad_act_op22_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op22.q */
static float tmp_grad_act_op22_v[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op22.v */
static float tmp_grad_act_op23_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op23.input */
static float tmp_grad_act_op24_a[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op24.a */
static float tmp_grad_act_op24_b[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op24.b */
static float tmp_grad_act_op25_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op25.input */
static float tmp_grad_act_op26_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op26.input */
static float tmp_grad_act_op27_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op27.input */
static float tmp_grad_act_op28_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op28.input */
static float tmp_grad_act_op29_a[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op29.a */
static float tmp_grad_act_op29_b[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op29.b */
static float tmp_grad_act_op2_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op2.input */
static float tmp_grad_act_op30_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op30.input */
static float tmp_grad_act_op32_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op32.input */
static float tmp_grad_act_op3_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op3.input */
static float tmp_grad_act_op4_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op4.input */
static float tmp_grad_act_op5_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op5.input */
static float tmp_grad_act_op6_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op6.k */
static float tmp_grad_act_op6_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op6.q */
static float tmp_grad_act_op7_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op7.k */
static float tmp_grad_act_op7_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op7.q */
static float tmp_grad_act_op8_k[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op8.k */
static float tmp_grad_act_op8_q[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op8.q */
static float tmp_grad_act_op8_v[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op8.v */
static float tmp_grad_act_op9_input[CK_TENSOR_CAP_F32]; /* tmp.grad.act.op9.input */
static float tmp_grad_weight_op11_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op11.gamma */
static float tmp_grad_weight_op12_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op12.W */
static float tmp_grad_weight_op12_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op12.bias */
static float tmp_grad_weight_op14_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op14.W */
static float tmp_grad_weight_op14_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op14.bias */
static float tmp_grad_weight_op16_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op16.gamma */
static float tmp_grad_weight_op17_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op17.W */
static float tmp_grad_weight_op17_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op17.bias */
static float tmp_grad_weight_op18_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op18.W */
static float tmp_grad_weight_op18_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op18.bias */
static float tmp_grad_weight_op19_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op19.W */
static float tmp_grad_weight_op19_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op19.bias */
static float tmp_grad_weight_op1_weight[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op1.weight */
static float tmp_grad_weight_op20_k_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op20.k_gamma */
static float tmp_grad_weight_op20_q_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op20.q_gamma */
static float tmp_grad_weight_op23_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op23.W */
static float tmp_grad_weight_op23_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op23.bias */
static float tmp_grad_weight_op25_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op25.gamma */
static float tmp_grad_weight_op26_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op26.W */
static float tmp_grad_weight_op26_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op26.bias */
static float tmp_grad_weight_op28_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op28.W */
static float tmp_grad_weight_op28_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op28.bias */
static float tmp_grad_weight_op2_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op2.gamma */
static float tmp_grad_weight_op30_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op30.gamma */
static float tmp_grad_weight_op32_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op32.W */
static float tmp_grad_weight_op3_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op3.W */
static float tmp_grad_weight_op3_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op3.bias */
static float tmp_grad_weight_op4_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op4.W */
static float tmp_grad_weight_op4_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op4.bias */
static float tmp_grad_weight_op5_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op5.W */
static float tmp_grad_weight_op5_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op5.bias */
static float tmp_grad_weight_op6_k_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op6.k_gamma */
static float tmp_grad_weight_op6_q_gamma[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op6.q_gamma */
static float tmp_grad_weight_op9_W[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op9.W */
static float tmp_grad_weight_op9_bias[CK_TENSOR_CAP_F32]; /* tmp.grad.weight.op9.bias */
static float weight_final_ln_weight[CK_TENSOR_CAP_F32]; /* weight.final_ln_weight */
static float weight_layer_0_b1[CK_TENSOR_CAP_F32]; /* weight.layer.0.b1 */
static float weight_layer_0_b2[CK_TENSOR_CAP_F32]; /* weight.layer.0.b2 */
static float weight_layer_0_bk[CK_TENSOR_CAP_F32]; /* weight.layer.0.bk */
static float weight_layer_0_bo[CK_TENSOR_CAP_F32]; /* weight.layer.0.bo */
static float weight_layer_0_bq[CK_TENSOR_CAP_F32]; /* weight.layer.0.bq */
static float weight_layer_0_bv[CK_TENSOR_CAP_F32]; /* weight.layer.0.bv */
static float weight_layer_0_k_norm[CK_TENSOR_CAP_F32]; /* weight.layer.0.k_norm */
static float weight_layer_0_ln1_gamma[CK_TENSOR_CAP_F32]; /* weight.layer.0.ln1_gamma */
static float weight_layer_0_ln2_gamma[CK_TENSOR_CAP_F32]; /* weight.layer.0.ln2_gamma */
static float weight_layer_0_q_norm[CK_TENSOR_CAP_F32]; /* weight.layer.0.q_norm */
static float weight_layer_0_w1[CK_TENSOR_CAP_F32]; /* weight.layer.0.w1 */
static float weight_layer_0_w2[CK_TENSOR_CAP_F32]; /* weight.layer.0.w2 */
static float weight_layer_0_wk[CK_TENSOR_CAP_F32]; /* weight.layer.0.wk */
static float weight_layer_0_wo[CK_TENSOR_CAP_F32]; /* weight.layer.0.wo */
static float weight_layer_0_wq[CK_TENSOR_CAP_F32]; /* weight.layer.0.wq */
static float weight_layer_0_wv[CK_TENSOR_CAP_F32]; /* weight.layer.0.wv */
static float weight_layer_1_b1[CK_TENSOR_CAP_F32]; /* weight.layer.1.b1 */
static float weight_layer_1_b2[CK_TENSOR_CAP_F32]; /* weight.layer.1.b2 */
static float weight_layer_1_bk[CK_TENSOR_CAP_F32]; /* weight.layer.1.bk */
static float weight_layer_1_bo[CK_TENSOR_CAP_F32]; /* weight.layer.1.bo */
static float weight_layer_1_bq[CK_TENSOR_CAP_F32]; /* weight.layer.1.bq */
static float weight_layer_1_bv[CK_TENSOR_CAP_F32]; /* weight.layer.1.bv */
static float weight_layer_1_k_norm[CK_TENSOR_CAP_F32]; /* weight.layer.1.k_norm */
static float weight_layer_1_ln1_gamma[CK_TENSOR_CAP_F32]; /* weight.layer.1.ln1_gamma */
static float weight_layer_1_ln2_gamma[CK_TENSOR_CAP_F32]; /* weight.layer.1.ln2_gamma */
static float weight_layer_1_q_norm[CK_TENSOR_CAP_F32]; /* weight.layer.1.q_norm */
static float weight_layer_1_w1[CK_TENSOR_CAP_F32]; /* weight.layer.1.w1 */
static float weight_layer_1_w2[CK_TENSOR_CAP_F32]; /* weight.layer.1.w2 */
static float weight_layer_1_wk[CK_TENSOR_CAP_F32]; /* weight.layer.1.wk */
static float weight_layer_1_wo[CK_TENSOR_CAP_F32]; /* weight.layer.1.wo */
static float weight_layer_1_wq[CK_TENSOR_CAP_F32]; /* weight.layer.1.wq */
static float weight_layer_1_wv[CK_TENSOR_CAP_F32]; /* weight.layer.1.wv */
static float weight_token_emb[CK_TENSOR_CAP_F32]; /* weight.token_emb */
static int32_t input_targets[CK_TENSOR_CAP_I32]; /* input.targets */
static int32_t input_token_ids[CK_TENSOR_CAP_I32]; /* input.token_ids */

/* Optimizer state (AdamW moments) */
static float m_final_ln_weight[CK_TENSOR_CAP_F32];
static float v_final_ln_weight[CK_TENSOR_CAP_F32];
static float m_layer_0_b1[CK_TENSOR_CAP_F32];
static float v_layer_0_b1[CK_TENSOR_CAP_F32];
static float m_layer_0_b2[CK_TENSOR_CAP_F32];
static float v_layer_0_b2[CK_TENSOR_CAP_F32];
static float m_layer_0_bk[CK_TENSOR_CAP_F32];
static float v_layer_0_bk[CK_TENSOR_CAP_F32];
static float m_layer_0_bo[CK_TENSOR_CAP_F32];
static float v_layer_0_bo[CK_TENSOR_CAP_F32];
static float m_layer_0_bq[CK_TENSOR_CAP_F32];
static float v_layer_0_bq[CK_TENSOR_CAP_F32];
static float m_layer_0_bv[CK_TENSOR_CAP_F32];
static float v_layer_0_bv[CK_TENSOR_CAP_F32];
static float m_layer_0_k_norm[CK_TENSOR_CAP_F32];
static float v_layer_0_k_norm[CK_TENSOR_CAP_F32];
static float m_layer_0_ln1_gamma[CK_TENSOR_CAP_F32];
static float v_layer_0_ln1_gamma[CK_TENSOR_CAP_F32];
static float m_layer_0_ln2_gamma[CK_TENSOR_CAP_F32];
static float v_layer_0_ln2_gamma[CK_TENSOR_CAP_F32];
static float m_layer_0_q_norm[CK_TENSOR_CAP_F32];
static float v_layer_0_q_norm[CK_TENSOR_CAP_F32];
static float m_layer_1_b1[CK_TENSOR_CAP_F32];
static float v_layer_1_b1[CK_TENSOR_CAP_F32];
static float m_layer_1_b2[CK_TENSOR_CAP_F32];
static float v_layer_1_b2[CK_TENSOR_CAP_F32];
static float m_layer_1_bk[CK_TENSOR_CAP_F32];
static float v_layer_1_bk[CK_TENSOR_CAP_F32];
static float m_layer_1_bo[CK_TENSOR_CAP_F32];
static float v_layer_1_bo[CK_TENSOR_CAP_F32];
static float m_layer_1_bq[CK_TENSOR_CAP_F32];
static float v_layer_1_bq[CK_TENSOR_CAP_F32];
static float m_layer_1_bv[CK_TENSOR_CAP_F32];
static float v_layer_1_bv[CK_TENSOR_CAP_F32];
static float m_layer_1_k_norm[CK_TENSOR_CAP_F32];
static float v_layer_1_k_norm[CK_TENSOR_CAP_F32];
static float m_layer_1_ln1_gamma[CK_TENSOR_CAP_F32];
static float v_layer_1_ln1_gamma[CK_TENSOR_CAP_F32];
static float m_layer_1_ln2_gamma[CK_TENSOR_CAP_F32];
static float v_layer_1_ln2_gamma[CK_TENSOR_CAP_F32];
static float m_layer_1_q_norm[CK_TENSOR_CAP_F32];
static float v_layer_1_q_norm[CK_TENSOR_CAP_F32];
static int g_opt_step = 0;

void ck_train_reset_buffers(void) {
    memset(act_L0_attn_0_out, 0, sizeof(act_L0_attn_0_out));
    memset(act_L0_k_proj_0_y, 0, sizeof(act_L0_k_proj_0_y));
    memset(act_L0_mlp_down_0_y, 0, sizeof(act_L0_mlp_down_0_y));
    memset(act_L0_mlp_gate_up_0_y, 0, sizeof(act_L0_mlp_gate_up_0_y));
    memset(act_L0_out_proj_0_y, 0, sizeof(act_L0_out_proj_0_y));
    memset(act_L0_q_proj_0_y, 0, sizeof(act_L0_q_proj_0_y));
    memset(act_L0_qk_norm_0_k, 0, sizeof(act_L0_qk_norm_0_k));
    memset(act_L0_qk_norm_0_q, 0, sizeof(act_L0_qk_norm_0_q));
    memset(act_L0_residual_add_0_out, 0, sizeof(act_L0_residual_add_0_out));
    memset(act_L0_residual_add_1_out, 0, sizeof(act_L0_residual_add_1_out));
    memset(act_L0_rmsnorm_0_output, 0, sizeof(act_L0_rmsnorm_0_output));
    memset(act_L0_rmsnorm_0_rstd_cache, 0, sizeof(act_L0_rmsnorm_0_rstd_cache));
    memset(act_L0_rmsnorm_1_output, 0, sizeof(act_L0_rmsnorm_1_output));
    memset(act_L0_rmsnorm_1_rstd_cache, 0, sizeof(act_L0_rmsnorm_1_rstd_cache));
    memset(act_L0_rope_qk_0_k, 0, sizeof(act_L0_rope_qk_0_k));
    memset(act_L0_rope_qk_0_q, 0, sizeof(act_L0_rope_qk_0_q));
    memset(act_L0_silu_mul_0_out, 0, sizeof(act_L0_silu_mul_0_out));
    memset(act_L0_v_proj_0_y, 0, sizeof(act_L0_v_proj_0_y));
    memset(act_L1_attn_0_out, 0, sizeof(act_L1_attn_0_out));
    memset(act_L1_k_proj_0_y, 0, sizeof(act_L1_k_proj_0_y));
    memset(act_L1_mlp_down_0_y, 0, sizeof(act_L1_mlp_down_0_y));
    memset(act_L1_mlp_gate_up_0_y, 0, sizeof(act_L1_mlp_gate_up_0_y));
    memset(act_L1_out_proj_0_y, 0, sizeof(act_L1_out_proj_0_y));
    memset(act_L1_q_proj_0_y, 0, sizeof(act_L1_q_proj_0_y));
    memset(act_L1_qk_norm_0_k, 0, sizeof(act_L1_qk_norm_0_k));
    memset(act_L1_qk_norm_0_q, 0, sizeof(act_L1_qk_norm_0_q));
    memset(act_L1_residual_add_0_out, 0, sizeof(act_L1_residual_add_0_out));
    memset(act_L1_residual_add_1_out, 0, sizeof(act_L1_residual_add_1_out));
    memset(act_L1_rmsnorm_0_output, 0, sizeof(act_L1_rmsnorm_0_output));
    memset(act_L1_rmsnorm_0_rstd_cache, 0, sizeof(act_L1_rmsnorm_0_rstd_cache));
    memset(act_L1_rmsnorm_1_output, 0, sizeof(act_L1_rmsnorm_1_output));
    memset(act_L1_rmsnorm_1_rstd_cache, 0, sizeof(act_L1_rmsnorm_1_rstd_cache));
    memset(act_L1_rope_qk_0_k, 0, sizeof(act_L1_rope_qk_0_k));
    memset(act_L1_rope_qk_0_q, 0, sizeof(act_L1_rope_qk_0_q));
    memset(act_L1_silu_mul_0_out, 0, sizeof(act_L1_silu_mul_0_out));
    memset(act_L1_v_proj_0_y, 0, sizeof(act_L1_v_proj_0_y));
    memset(act_Sfooter_logits_0_y, 0, sizeof(act_Sfooter_logits_0_y));
    memset(act_Sfooter_rmsnorm_0_output, 0, sizeof(act_Sfooter_rmsnorm_0_output));
    memset(act_Sfooter_rmsnorm_0_rstd_cache, 0, sizeof(act_Sfooter_rmsnorm_0_rstd_cache));
    memset(act_Sheader_dense_embedding_lookup_0_out, 0, sizeof(act_Sheader_dense_embedding_lookup_0_out));
    memset(aux_d_bias, 0, sizeof(aux_d_bias));
    memset(aux_d_pos_embeddings, 0, sizeof(aux_d_pos_embeddings));
    memset(aux_d_scores, 0, sizeof(aux_d_scores));
    memset(aux_loss, 0, sizeof(aux_loss));
    memset(grad_act_act_L0_attn_0_out, 0, sizeof(grad_act_act_L0_attn_0_out));
    memset(grad_act_act_L0_k_proj_0_y, 0, sizeof(grad_act_act_L0_k_proj_0_y));
    memset(grad_act_act_L0_mlp_down_0_y, 0, sizeof(grad_act_act_L0_mlp_down_0_y));
    memset(grad_act_act_L0_mlp_gate_up_0_y, 0, sizeof(grad_act_act_L0_mlp_gate_up_0_y));
    memset(grad_act_act_L0_out_proj_0_y, 0, sizeof(grad_act_act_L0_out_proj_0_y));
    memset(grad_act_act_L0_q_proj_0_y, 0, sizeof(grad_act_act_L0_q_proj_0_y));
    memset(grad_act_act_L0_qk_norm_0_k, 0, sizeof(grad_act_act_L0_qk_norm_0_k));
    memset(grad_act_act_L0_qk_norm_0_q, 0, sizeof(grad_act_act_L0_qk_norm_0_q));
    memset(grad_act_act_L0_residual_add_0_out, 0, sizeof(grad_act_act_L0_residual_add_0_out));
    memset(grad_act_act_L0_residual_add_1_out, 0, sizeof(grad_act_act_L0_residual_add_1_out));
    memset(grad_act_act_L0_rmsnorm_0_output, 0, sizeof(grad_act_act_L0_rmsnorm_0_output));
    memset(grad_act_act_L0_rmsnorm_1_output, 0, sizeof(grad_act_act_L0_rmsnorm_1_output));
    memset(grad_act_act_L0_rope_qk_0_k, 0, sizeof(grad_act_act_L0_rope_qk_0_k));
    memset(grad_act_act_L0_rope_qk_0_q, 0, sizeof(grad_act_act_L0_rope_qk_0_q));
    memset(grad_act_act_L0_silu_mul_0_out, 0, sizeof(grad_act_act_L0_silu_mul_0_out));
    memset(grad_act_act_L0_v_proj_0_y, 0, sizeof(grad_act_act_L0_v_proj_0_y));
    memset(grad_act_act_L1_attn_0_out, 0, sizeof(grad_act_act_L1_attn_0_out));
    memset(grad_act_act_L1_k_proj_0_y, 0, sizeof(grad_act_act_L1_k_proj_0_y));
    memset(grad_act_act_L1_mlp_down_0_y, 0, sizeof(grad_act_act_L1_mlp_down_0_y));
    memset(grad_act_act_L1_mlp_gate_up_0_y, 0, sizeof(grad_act_act_L1_mlp_gate_up_0_y));
    memset(grad_act_act_L1_out_proj_0_y, 0, sizeof(grad_act_act_L1_out_proj_0_y));
    memset(grad_act_act_L1_q_proj_0_y, 0, sizeof(grad_act_act_L1_q_proj_0_y));
    memset(grad_act_act_L1_qk_norm_0_k, 0, sizeof(grad_act_act_L1_qk_norm_0_k));
    memset(grad_act_act_L1_qk_norm_0_q, 0, sizeof(grad_act_act_L1_qk_norm_0_q));
    memset(grad_act_act_L1_residual_add_0_out, 0, sizeof(grad_act_act_L1_residual_add_0_out));
    memset(grad_act_act_L1_residual_add_1_out, 0, sizeof(grad_act_act_L1_residual_add_1_out));
    memset(grad_act_act_L1_rmsnorm_0_output, 0, sizeof(grad_act_act_L1_rmsnorm_0_output));
    memset(grad_act_act_L1_rmsnorm_1_output, 0, sizeof(grad_act_act_L1_rmsnorm_1_output));
    memset(grad_act_act_L1_rope_qk_0_k, 0, sizeof(grad_act_act_L1_rope_qk_0_k));
    memset(grad_act_act_L1_rope_qk_0_q, 0, sizeof(grad_act_act_L1_rope_qk_0_q));
    memset(grad_act_act_L1_silu_mul_0_out, 0, sizeof(grad_act_act_L1_silu_mul_0_out));
    memset(grad_act_act_L1_v_proj_0_y, 0, sizeof(grad_act_act_L1_v_proj_0_y));
    memset(grad_act_act_Sfooter_logits_0_y, 0, sizeof(grad_act_act_Sfooter_logits_0_y));
    memset(grad_act_act_Sfooter_rmsnorm_0_output, 0, sizeof(grad_act_act_Sfooter_rmsnorm_0_output));
    memset(grad_act_act_Sheader_dense_embedding_lookup_0_out, 0, sizeof(grad_act_act_Sheader_dense_embedding_lookup_0_out));
    memset(grad_weight_final_ln_weight, 0, sizeof(grad_weight_final_ln_weight));
    memset(grad_weight_layer_0_b1, 0, sizeof(grad_weight_layer_0_b1));
    memset(grad_weight_layer_0_b2, 0, sizeof(grad_weight_layer_0_b2));
    memset(grad_weight_layer_0_bk, 0, sizeof(grad_weight_layer_0_bk));
    memset(grad_weight_layer_0_bo, 0, sizeof(grad_weight_layer_0_bo));
    memset(grad_weight_layer_0_bq, 0, sizeof(grad_weight_layer_0_bq));
    memset(grad_weight_layer_0_bv, 0, sizeof(grad_weight_layer_0_bv));
    memset(grad_weight_layer_0_k_norm, 0, sizeof(grad_weight_layer_0_k_norm));
    memset(grad_weight_layer_0_ln1_gamma, 0, sizeof(grad_weight_layer_0_ln1_gamma));
    memset(grad_weight_layer_0_ln2_gamma, 0, sizeof(grad_weight_layer_0_ln2_gamma));
    memset(grad_weight_layer_0_q_norm, 0, sizeof(grad_weight_layer_0_q_norm));
    memset(grad_weight_layer_0_w1, 0, sizeof(grad_weight_layer_0_w1));
    memset(grad_weight_layer_0_w2, 0, sizeof(grad_weight_layer_0_w2));
    memset(grad_weight_layer_0_wk, 0, sizeof(grad_weight_layer_0_wk));
    memset(grad_weight_layer_0_wo, 0, sizeof(grad_weight_layer_0_wo));
    memset(grad_weight_layer_0_wq, 0, sizeof(grad_weight_layer_0_wq));
    memset(grad_weight_layer_0_wv, 0, sizeof(grad_weight_layer_0_wv));
    memset(grad_weight_layer_1_b1, 0, sizeof(grad_weight_layer_1_b1));
    memset(grad_weight_layer_1_b2, 0, sizeof(grad_weight_layer_1_b2));
    memset(grad_weight_layer_1_bk, 0, sizeof(grad_weight_layer_1_bk));
    memset(grad_weight_layer_1_bo, 0, sizeof(grad_weight_layer_1_bo));
    memset(grad_weight_layer_1_bq, 0, sizeof(grad_weight_layer_1_bq));
    memset(grad_weight_layer_1_bv, 0, sizeof(grad_weight_layer_1_bv));
    memset(grad_weight_layer_1_k_norm, 0, sizeof(grad_weight_layer_1_k_norm));
    memset(grad_weight_layer_1_ln1_gamma, 0, sizeof(grad_weight_layer_1_ln1_gamma));
    memset(grad_weight_layer_1_ln2_gamma, 0, sizeof(grad_weight_layer_1_ln2_gamma));
    memset(grad_weight_layer_1_q_norm, 0, sizeof(grad_weight_layer_1_q_norm));
    memset(grad_weight_layer_1_w1, 0, sizeof(grad_weight_layer_1_w1));
    memset(grad_weight_layer_1_w2, 0, sizeof(grad_weight_layer_1_w2));
    memset(grad_weight_layer_1_wk, 0, sizeof(grad_weight_layer_1_wk));
    memset(grad_weight_layer_1_wo, 0, sizeof(grad_weight_layer_1_wo));
    memset(grad_weight_layer_1_wq, 0, sizeof(grad_weight_layer_1_wq));
    memset(grad_weight_layer_1_wv, 0, sizeof(grad_weight_layer_1_wv));
    memset(grad_weight_token_emb, 0, sizeof(grad_weight_token_emb));
    memset(saved_op22_attn_weights, 0, sizeof(saved_op22_attn_weights));
    memset(saved_op8_attn_weights, 0, sizeof(saved_op8_attn_weights));
    memset(tmp_grad_act_op10_a, 0, sizeof(tmp_grad_act_op10_a));
    memset(tmp_grad_act_op10_b, 0, sizeof(tmp_grad_act_op10_b));
    memset(tmp_grad_act_op11_input, 0, sizeof(tmp_grad_act_op11_input));
    memset(tmp_grad_act_op12_input, 0, sizeof(tmp_grad_act_op12_input));
    memset(tmp_grad_act_op13_input, 0, sizeof(tmp_grad_act_op13_input));
    memset(tmp_grad_act_op14_input, 0, sizeof(tmp_grad_act_op14_input));
    memset(tmp_grad_act_op15_a, 0, sizeof(tmp_grad_act_op15_a));
    memset(tmp_grad_act_op15_b, 0, sizeof(tmp_grad_act_op15_b));
    memset(tmp_grad_act_op16_input, 0, sizeof(tmp_grad_act_op16_input));
    memset(tmp_grad_act_op17_input, 0, sizeof(tmp_grad_act_op17_input));
    memset(tmp_grad_act_op18_input, 0, sizeof(tmp_grad_act_op18_input));
    memset(tmp_grad_act_op19_input, 0, sizeof(tmp_grad_act_op19_input));
    memset(tmp_grad_act_op20_k, 0, sizeof(tmp_grad_act_op20_k));
    memset(tmp_grad_act_op20_q, 0, sizeof(tmp_grad_act_op20_q));
    memset(tmp_grad_act_op21_k, 0, sizeof(tmp_grad_act_op21_k));
    memset(tmp_grad_act_op21_q, 0, sizeof(tmp_grad_act_op21_q));
    memset(tmp_grad_act_op22_k, 0, sizeof(tmp_grad_act_op22_k));
    memset(tmp_grad_act_op22_q, 0, sizeof(tmp_grad_act_op22_q));
    memset(tmp_grad_act_op22_v, 0, sizeof(tmp_grad_act_op22_v));
    memset(tmp_grad_act_op23_input, 0, sizeof(tmp_grad_act_op23_input));
    memset(tmp_grad_act_op24_a, 0, sizeof(tmp_grad_act_op24_a));
    memset(tmp_grad_act_op24_b, 0, sizeof(tmp_grad_act_op24_b));
    memset(tmp_grad_act_op25_input, 0, sizeof(tmp_grad_act_op25_input));
    memset(tmp_grad_act_op26_input, 0, sizeof(tmp_grad_act_op26_input));
    memset(tmp_grad_act_op27_input, 0, sizeof(tmp_grad_act_op27_input));
    memset(tmp_grad_act_op28_input, 0, sizeof(tmp_grad_act_op28_input));
    memset(tmp_grad_act_op29_a, 0, sizeof(tmp_grad_act_op29_a));
    memset(tmp_grad_act_op29_b, 0, sizeof(tmp_grad_act_op29_b));
    memset(tmp_grad_act_op2_input, 0, sizeof(tmp_grad_act_op2_input));
    memset(tmp_grad_act_op30_input, 0, sizeof(tmp_grad_act_op30_input));
    memset(tmp_grad_act_op32_input, 0, sizeof(tmp_grad_act_op32_input));
    memset(tmp_grad_act_op3_input, 0, sizeof(tmp_grad_act_op3_input));
    memset(tmp_grad_act_op4_input, 0, sizeof(tmp_grad_act_op4_input));
    memset(tmp_grad_act_op5_input, 0, sizeof(tmp_grad_act_op5_input));
    memset(tmp_grad_act_op6_k, 0, sizeof(tmp_grad_act_op6_k));
    memset(tmp_grad_act_op6_q, 0, sizeof(tmp_grad_act_op6_q));
    memset(tmp_grad_act_op7_k, 0, sizeof(tmp_grad_act_op7_k));
    memset(tmp_grad_act_op7_q, 0, sizeof(tmp_grad_act_op7_q));
    memset(tmp_grad_act_op8_k, 0, sizeof(tmp_grad_act_op8_k));
    memset(tmp_grad_act_op8_q, 0, sizeof(tmp_grad_act_op8_q));
    memset(tmp_grad_act_op8_v, 0, sizeof(tmp_grad_act_op8_v));
    memset(tmp_grad_act_op9_input, 0, sizeof(tmp_grad_act_op9_input));
    memset(tmp_grad_weight_op11_gamma, 0, sizeof(tmp_grad_weight_op11_gamma));
    memset(tmp_grad_weight_op12_W, 0, sizeof(tmp_grad_weight_op12_W));
    memset(tmp_grad_weight_op12_bias, 0, sizeof(tmp_grad_weight_op12_bias));
    memset(tmp_grad_weight_op14_W, 0, sizeof(tmp_grad_weight_op14_W));
    memset(tmp_grad_weight_op14_bias, 0, sizeof(tmp_grad_weight_op14_bias));
    memset(tmp_grad_weight_op16_gamma, 0, sizeof(tmp_grad_weight_op16_gamma));
    memset(tmp_grad_weight_op17_W, 0, sizeof(tmp_grad_weight_op17_W));
    memset(tmp_grad_weight_op17_bias, 0, sizeof(tmp_grad_weight_op17_bias));
    memset(tmp_grad_weight_op18_W, 0, sizeof(tmp_grad_weight_op18_W));
    memset(tmp_grad_weight_op18_bias, 0, sizeof(tmp_grad_weight_op18_bias));
    memset(tmp_grad_weight_op19_W, 0, sizeof(tmp_grad_weight_op19_W));
    memset(tmp_grad_weight_op19_bias, 0, sizeof(tmp_grad_weight_op19_bias));
    memset(tmp_grad_weight_op1_weight, 0, sizeof(tmp_grad_weight_op1_weight));
    memset(tmp_grad_weight_op20_k_gamma, 0, sizeof(tmp_grad_weight_op20_k_gamma));
    memset(tmp_grad_weight_op20_q_gamma, 0, sizeof(tmp_grad_weight_op20_q_gamma));
    memset(tmp_grad_weight_op23_W, 0, sizeof(tmp_grad_weight_op23_W));
    memset(tmp_grad_weight_op23_bias, 0, sizeof(tmp_grad_weight_op23_bias));
    memset(tmp_grad_weight_op25_gamma, 0, sizeof(tmp_grad_weight_op25_gamma));
    memset(tmp_grad_weight_op26_W, 0, sizeof(tmp_grad_weight_op26_W));
    memset(tmp_grad_weight_op26_bias, 0, sizeof(tmp_grad_weight_op26_bias));
    memset(tmp_grad_weight_op28_W, 0, sizeof(tmp_grad_weight_op28_W));
    memset(tmp_grad_weight_op28_bias, 0, sizeof(tmp_grad_weight_op28_bias));
    memset(tmp_grad_weight_op2_gamma, 0, sizeof(tmp_grad_weight_op2_gamma));
    memset(tmp_grad_weight_op30_gamma, 0, sizeof(tmp_grad_weight_op30_gamma));
    memset(tmp_grad_weight_op32_W, 0, sizeof(tmp_grad_weight_op32_W));
    memset(tmp_grad_weight_op3_W, 0, sizeof(tmp_grad_weight_op3_W));
    memset(tmp_grad_weight_op3_bias, 0, sizeof(tmp_grad_weight_op3_bias));
    memset(tmp_grad_weight_op4_W, 0, sizeof(tmp_grad_weight_op4_W));
    memset(tmp_grad_weight_op4_bias, 0, sizeof(tmp_grad_weight_op4_bias));
    memset(tmp_grad_weight_op5_W, 0, sizeof(tmp_grad_weight_op5_W));
    memset(tmp_grad_weight_op5_bias, 0, sizeof(tmp_grad_weight_op5_bias));
    memset(tmp_grad_weight_op6_k_gamma, 0, sizeof(tmp_grad_weight_op6_k_gamma));
    memset(tmp_grad_weight_op6_q_gamma, 0, sizeof(tmp_grad_weight_op6_q_gamma));
    memset(tmp_grad_weight_op9_W, 0, sizeof(tmp_grad_weight_op9_W));
    memset(tmp_grad_weight_op9_bias, 0, sizeof(tmp_grad_weight_op9_bias));
    memset(weight_final_ln_weight, 0, sizeof(weight_final_ln_weight));
    memset(weight_layer_0_b1, 0, sizeof(weight_layer_0_b1));
    memset(weight_layer_0_b2, 0, sizeof(weight_layer_0_b2));
    memset(weight_layer_0_bk, 0, sizeof(weight_layer_0_bk));
    memset(weight_layer_0_bo, 0, sizeof(weight_layer_0_bo));
    memset(weight_layer_0_bq, 0, sizeof(weight_layer_0_bq));
    memset(weight_layer_0_bv, 0, sizeof(weight_layer_0_bv));
    memset(weight_layer_0_k_norm, 0, sizeof(weight_layer_0_k_norm));
    memset(weight_layer_0_ln1_gamma, 0, sizeof(weight_layer_0_ln1_gamma));
    memset(weight_layer_0_ln2_gamma, 0, sizeof(weight_layer_0_ln2_gamma));
    memset(weight_layer_0_q_norm, 0, sizeof(weight_layer_0_q_norm));
    memset(weight_layer_0_w1, 0, sizeof(weight_layer_0_w1));
    memset(weight_layer_0_w2, 0, sizeof(weight_layer_0_w2));
    memset(weight_layer_0_wk, 0, sizeof(weight_layer_0_wk));
    memset(weight_layer_0_wo, 0, sizeof(weight_layer_0_wo));
    memset(weight_layer_0_wq, 0, sizeof(weight_layer_0_wq));
    memset(weight_layer_0_wv, 0, sizeof(weight_layer_0_wv));
    memset(weight_layer_1_b1, 0, sizeof(weight_layer_1_b1));
    memset(weight_layer_1_b2, 0, sizeof(weight_layer_1_b2));
    memset(weight_layer_1_bk, 0, sizeof(weight_layer_1_bk));
    memset(weight_layer_1_bo, 0, sizeof(weight_layer_1_bo));
    memset(weight_layer_1_bq, 0, sizeof(weight_layer_1_bq));
    memset(weight_layer_1_bv, 0, sizeof(weight_layer_1_bv));
    memset(weight_layer_1_k_norm, 0, sizeof(weight_layer_1_k_norm));
    memset(weight_layer_1_ln1_gamma, 0, sizeof(weight_layer_1_ln1_gamma));
    memset(weight_layer_1_ln2_gamma, 0, sizeof(weight_layer_1_ln2_gamma));
    memset(weight_layer_1_q_norm, 0, sizeof(weight_layer_1_q_norm));
    memset(weight_layer_1_w1, 0, sizeof(weight_layer_1_w1));
    memset(weight_layer_1_w2, 0, sizeof(weight_layer_1_w2));
    memset(weight_layer_1_wk, 0, sizeof(weight_layer_1_wk));
    memset(weight_layer_1_wo, 0, sizeof(weight_layer_1_wo));
    memset(weight_layer_1_wq, 0, sizeof(weight_layer_1_wq));
    memset(weight_layer_1_wv, 0, sizeof(weight_layer_1_wv));
    memset(weight_token_emb, 0, sizeof(weight_token_emb));
    memset(input_targets, 0, sizeof(input_targets));
    memset(input_token_ids, 0, sizeof(input_token_ids));
    memset(m_final_ln_weight, 0, sizeof(m_final_ln_weight));
    memset(v_final_ln_weight, 0, sizeof(v_final_ln_weight));
    memset(m_layer_0_b1, 0, sizeof(m_layer_0_b1));
    memset(v_layer_0_b1, 0, sizeof(v_layer_0_b1));
    memset(m_layer_0_b2, 0, sizeof(m_layer_0_b2));
    memset(v_layer_0_b2, 0, sizeof(v_layer_0_b2));
    memset(m_layer_0_bk, 0, sizeof(m_layer_0_bk));
    memset(v_layer_0_bk, 0, sizeof(v_layer_0_bk));
    memset(m_layer_0_bo, 0, sizeof(m_layer_0_bo));
    memset(v_layer_0_bo, 0, sizeof(v_layer_0_bo));
    memset(m_layer_0_bq, 0, sizeof(m_layer_0_bq));
    memset(v_layer_0_bq, 0, sizeof(v_layer_0_bq));
    memset(m_layer_0_bv, 0, sizeof(m_layer_0_bv));
    memset(v_layer_0_bv, 0, sizeof(v_layer_0_bv));
    memset(m_layer_0_k_norm, 0, sizeof(m_layer_0_k_norm));
    memset(v_layer_0_k_norm, 0, sizeof(v_layer_0_k_norm));
    memset(m_layer_0_ln1_gamma, 0, sizeof(m_layer_0_ln1_gamma));
    memset(v_layer_0_ln1_gamma, 0, sizeof(v_layer_0_ln1_gamma));
    memset(m_layer_0_ln2_gamma, 0, sizeof(m_layer_0_ln2_gamma));
    memset(v_layer_0_ln2_gamma, 0, sizeof(v_layer_0_ln2_gamma));
    memset(m_layer_0_q_norm, 0, sizeof(m_layer_0_q_norm));
    memset(v_layer_0_q_norm, 0, sizeof(v_layer_0_q_norm));
    memset(m_layer_1_b1, 0, sizeof(m_layer_1_b1));
    memset(v_layer_1_b1, 0, sizeof(v_layer_1_b1));
    memset(m_layer_1_b2, 0, sizeof(m_layer_1_b2));
    memset(v_layer_1_b2, 0, sizeof(v_layer_1_b2));
    memset(m_layer_1_bk, 0, sizeof(m_layer_1_bk));
    memset(v_layer_1_bk, 0, sizeof(v_layer_1_bk));
    memset(m_layer_1_bo, 0, sizeof(m_layer_1_bo));
    memset(v_layer_1_bo, 0, sizeof(v_layer_1_bo));
    memset(m_layer_1_bq, 0, sizeof(m_layer_1_bq));
    memset(v_layer_1_bq, 0, sizeof(v_layer_1_bq));
    memset(m_layer_1_bv, 0, sizeof(m_layer_1_bv));
    memset(v_layer_1_bv, 0, sizeof(v_layer_1_bv));
    memset(m_layer_1_k_norm, 0, sizeof(m_layer_1_k_norm));
    memset(v_layer_1_k_norm, 0, sizeof(v_layer_1_k_norm));
    memset(m_layer_1_ln1_gamma, 0, sizeof(m_layer_1_ln1_gamma));
    memset(v_layer_1_ln1_gamma, 0, sizeof(v_layer_1_ln1_gamma));
    memset(m_layer_1_ln2_gamma, 0, sizeof(m_layer_1_ln2_gamma));
    memset(v_layer_1_ln2_gamma, 0, sizeof(v_layer_1_ln2_gamma));
    memset(m_layer_1_q_norm, 0, sizeof(m_layer_1_q_norm));
    memset(v_layer_1_q_norm, 0, sizeof(v_layer_1_q_norm));
    g_opt_step = 0;
    g_loss_scalar[0] = 0.0f;
}

int ck_train_forward_step(void) {
    /* forward ops: 33 */
    int call_count = 0;
    /* skip op_id=0 (bpe_tokenizer): missing kernel_id */
    /* op_id=1 op=dense_embedding_lookup kernel_id=dense_embedding_lookup */
    embedding_forward(input_token_ids, CK_NUM_TOKENS, 151936, weight_token_emb, weight_token_emb, act_Sheader_dense_embedding_lookup_0_out, 1024, 1024, 128, 0);
    call_count++;
    /* op_id=2 op=rmsnorm kernel_id=rmsnorm_forward */
    rmsnorm_forward(act_Sheader_dense_embedding_lookup_0_out, weight_layer_0_ln1_gamma, act_L0_rmsnorm_0_output, act_L0_rmsnorm_0_rstd_cache, CK_NUM_TOKENS, 1024, 1024, 1e-5f);
    call_count++;
    /* op_id=3 op=q_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_rmsnorm_0_output, act_L0_rmsnorm_0_output, weight_layer_0_bq, act_L0_q_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=4 op=k_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_rmsnorm_0_output, act_L0_rmsnorm_0_output, weight_layer_0_bk, act_L0_k_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=5 op=v_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_rmsnorm_0_output, act_L0_rmsnorm_0_output, weight_layer_0_bv, act_L0_v_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=6 op=qk_norm kernel_id=qk_norm_forward */
    qk_norm_forward(act_L0_q_proj_0_y, act_L0_k_proj_0_y, weight_layer_0_q_norm, weight_layer_0_k_norm, 16, 8, CK_NUM_TOKENS, 128, 1e-5f);
    call_count++;
    /* op_id=7 op=rope_qk kernel_id=rope_forward_qk */
    rope_forward_qk_with_rotary_dim(act_L0_qk_norm_0_q, act_L0_qk_norm_0_k, act_L0_qk_norm_0_q, act_L0_qk_norm_0_q, 16, 8, CK_NUM_TOKENS, 128, 128, 0, 128);
    call_count++;
    /* op_id=8 op=attn kernel_id=attention_forward_causal_head_major_gqa_flash_strided */
    attention_forward_causal_head_major_gqa_flash_strided(act_L0_rope_qk_0_q, act_L0_rope_qk_0_k, act_L0_v_proj_0_y, act_L0_attn_0_out, 16, 8, CK_NUM_TOKENS, 128, 128, CK_NUM_TOKENS);
    call_count++;
    /* op_id=9 op=out_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_attn_0_out, act_L0_attn_0_out, weight_layer_0_bo, act_L0_out_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=10 op=residual_add kernel_id=ck_residual_add_token_major */
    ck_residual_add_token_major(act_L0_out_proj_0_y, act_Sheader_dense_embedding_lookup_0_out, act_L0_residual_add_0_out, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=11 op=rmsnorm kernel_id=rmsnorm_forward */
    rmsnorm_forward(act_L0_residual_add_0_out, weight_layer_0_ln2_gamma, act_L0_rmsnorm_1_output, act_L0_rmsnorm_1_rstd_cache, CK_NUM_TOKENS, 1024, 1024, 1e-5f);
    call_count++;
    /* op_id=12 op=mlp_gate_up kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_rmsnorm_1_output, act_L0_rmsnorm_1_output, weight_layer_0_b1, act_L0_mlp_gate_up_0_y, 1, 1, 1);
    call_count++;
    /* op_id=13 op=silu_mul kernel_id=swiglu_forward */
    swiglu_forward(act_L0_mlp_gate_up_0_y, act_L0_silu_mul_0_out, CK_NUM_TOKENS, 1);
    call_count++;
    /* op_id=14 op=mlp_down kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L0_silu_mul_0_out, act_L0_silu_mul_0_out, weight_layer_0_b2, act_L0_mlp_down_0_y, 1, 1, 1);
    call_count++;
    /* op_id=15 op=residual_add kernel_id=ck_residual_add_token_major */
    ck_residual_add_token_major(act_L0_mlp_down_0_y, act_L0_residual_add_0_out, act_L0_residual_add_1_out, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=16 op=rmsnorm kernel_id=rmsnorm_forward */
    rmsnorm_forward(act_L0_residual_add_1_out, weight_layer_1_ln1_gamma, act_L1_rmsnorm_0_output, act_L1_rmsnorm_0_rstd_cache, CK_NUM_TOKENS, 1024, 1024, 1e-5f);
    call_count++;
    /* op_id=17 op=q_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_rmsnorm_0_output, act_L1_rmsnorm_0_output, weight_layer_1_bq, act_L1_q_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=18 op=k_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_rmsnorm_0_output, act_L1_rmsnorm_0_output, weight_layer_1_bk, act_L1_k_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=19 op=v_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_rmsnorm_0_output, act_L1_rmsnorm_0_output, weight_layer_1_bv, act_L1_v_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=20 op=qk_norm kernel_id=qk_norm_forward */
    qk_norm_forward(act_L1_q_proj_0_y, act_L1_k_proj_0_y, weight_layer_1_q_norm, weight_layer_1_k_norm, 16, 8, CK_NUM_TOKENS, 128, 1e-5f);
    call_count++;
    /* op_id=21 op=rope_qk kernel_id=rope_forward_qk */
    rope_forward_qk_with_rotary_dim(act_L1_qk_norm_0_q, act_L1_qk_norm_0_k, act_L1_qk_norm_0_q, act_L1_qk_norm_0_q, 16, 8, CK_NUM_TOKENS, 128, 128, 0, 128);
    call_count++;
    /* op_id=22 op=attn kernel_id=attention_forward_causal_head_major_gqa_flash_strided */
    attention_forward_causal_head_major_gqa_flash_strided(act_L1_rope_qk_0_q, act_L1_rope_qk_0_k, act_L1_v_proj_0_y, act_L1_attn_0_out, 16, 8, CK_NUM_TOKENS, 128, 128, CK_NUM_TOKENS);
    call_count++;
    /* op_id=23 op=out_proj kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_attn_0_out, act_L1_attn_0_out, weight_layer_1_bo, act_L1_out_proj_0_y, 1, 1, 1);
    call_count++;
    /* op_id=24 op=residual_add kernel_id=ck_residual_add_token_major */
    ck_residual_add_token_major(act_L1_out_proj_0_y, act_L0_residual_add_1_out, act_L1_residual_add_0_out, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=25 op=rmsnorm kernel_id=rmsnorm_forward */
    rmsnorm_forward(act_L1_residual_add_0_out, weight_layer_1_ln2_gamma, act_L1_rmsnorm_1_output, act_L1_rmsnorm_1_rstd_cache, CK_NUM_TOKENS, 1024, 1024, 1e-5f);
    call_count++;
    /* op_id=26 op=mlp_gate_up kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_rmsnorm_1_output, act_L1_rmsnorm_1_output, weight_layer_1_b1, act_L1_mlp_gate_up_0_y, 1, 1, 1);
    call_count++;
    /* op_id=27 op=silu_mul kernel_id=swiglu_forward */
    swiglu_forward(act_L1_mlp_gate_up_0_y, act_L1_silu_mul_0_out, CK_NUM_TOKENS, 1);
    call_count++;
    /* op_id=28 op=mlp_down kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_L1_silu_mul_0_out, act_L1_silu_mul_0_out, weight_layer_1_b2, act_L1_mlp_down_0_y, 1, 1, 1);
    call_count++;
    /* op_id=29 op=residual_add kernel_id=ck_residual_add_token_major */
    ck_residual_add_token_major(act_L1_mlp_down_0_y, act_L1_residual_add_0_out, act_L1_residual_add_1_out, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=30 op=rmsnorm kernel_id=rmsnorm_forward */
    rmsnorm_forward(act_L1_residual_add_1_out, weight_final_ln_weight, act_Sfooter_rmsnorm_0_output, act_Sfooter_rmsnorm_0_rstd_cache, CK_NUM_TOKENS, 1024, 1024, 1e-5f);
    call_count++;
    /* skip op_id=31 (lm_head): missing kernel_id */
    /* op_id=32 op=logits kernel_id=gemm_blocked_serial */
    gemm_blocked_serial(act_Sfooter_rmsnorm_0_output, act_Sfooter_rmsnorm_0_output, act_Sfooter_rmsnorm_0_output, act_Sfooter_logits_0_y, 1, 1, 1);
    call_count++;
    return call_count;
}

int ck_train_backward_step(void) {
    /* backward ops: 109 */
    int call_count = 0;
    /* op_id=33 op=loss_backward kernel_id=softmax_cross_entropy_loss */
    softmax_cross_entropy_loss(act_Sfooter_logits_0_y, input_targets, CK_NUM_TOKENS, 151936, grad_act_act_Sfooter_logits_0_y, aux_loss);
    call_count++;
    /* op_id=34 op=logits_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_Sfooter_logits_0_y, grad_act_act_Sfooter_logits_0_y, grad_act_act_Sfooter_logits_0_y, tmp_grad_act_op32_input, tmp_grad_act_op32_input, tmp_grad_act_op32_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=35 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_Sfooter_rmsnorm_0_output, tmp_grad_act_op32_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=36 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_token_emb, tmp_grad_weight_op32_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=37 op=rmsnorm_backward_core kernel_id=rmsnorm_backward */
    rmsnorm_backward(grad_act_act_Sfooter_rmsnorm_0_output, grad_act_act_Sfooter_rmsnorm_0_output, grad_act_act_Sfooter_rmsnorm_0_output, grad_act_act_Sfooter_rmsnorm_0_output, tmp_grad_act_op30_input, tmp_grad_weight_op30_gamma, CK_NUM_TOKENS, 1024, 1024);
    call_count++;
    /* op_id=38 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_residual_add_1_out, tmp_grad_act_op30_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=39 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_final_ln_weight, tmp_grad_weight_op30_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=40 op=residual_add_backward_core kernel_id=residual_add_backward_f32 */
    ck_residual_add_backward(grad_act_act_L1_residual_add_1_out, tmp_grad_act_op29_a, tmp_grad_act_op29_b, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=41 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_mlp_down_0_y, tmp_grad_act_op29_a, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=42 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_residual_add_0_out, tmp_grad_act_op29_b, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=43 op=mlp_down_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_mlp_down_0_y, grad_act_act_L1_mlp_down_0_y, grad_act_act_L1_mlp_down_0_y, tmp_grad_act_op28_input, tmp_grad_act_op28_input, tmp_grad_act_op28_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=44 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_silu_mul_0_out, tmp_grad_act_op28_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=45 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_w2, tmp_grad_weight_op28_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=46 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_b2, tmp_grad_weight_op28_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=47 op=silu_mul_backward_core kernel_id=swiglu_backward_exact */
    swiglu_backward_exact(grad_act_act_L1_silu_mul_0_out, grad_act_act_L1_silu_mul_0_out, tmp_grad_act_op27_input, CK_NUM_TOKENS, 1);
    call_count++;
    /* op_id=48 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_mlp_gate_up_0_y, tmp_grad_act_op27_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=49 op=mlp_gate_up_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_mlp_gate_up_0_y, grad_act_act_L1_mlp_gate_up_0_y, grad_act_act_L1_mlp_gate_up_0_y, tmp_grad_act_op26_input, tmp_grad_act_op26_input, tmp_grad_act_op26_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=50 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rmsnorm_1_output, tmp_grad_act_op26_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=51 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_w1, tmp_grad_weight_op26_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=52 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_b1, tmp_grad_weight_op26_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=53 op=rmsnorm_backward_core kernel_id=rmsnorm_backward */
    rmsnorm_backward(grad_act_act_L1_rmsnorm_1_output, grad_act_act_L1_rmsnorm_1_output, grad_act_act_L1_rmsnorm_1_output, grad_act_act_L1_rmsnorm_1_output, tmp_grad_act_op25_input, tmp_grad_weight_op25_gamma, CK_NUM_TOKENS, 1024, 1024);
    call_count++;
    /* op_id=54 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_residual_add_0_out, tmp_grad_act_op25_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=55 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_ln2_gamma, tmp_grad_weight_op25_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=56 op=residual_add_backward_core kernel_id=residual_add_backward_f32 */
    ck_residual_add_backward(grad_act_act_L1_residual_add_0_out, tmp_grad_act_op24_a, tmp_grad_act_op24_b, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=57 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_out_proj_0_y, tmp_grad_act_op24_a, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=58 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_residual_add_1_out, tmp_grad_act_op24_b, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=59 op=out_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_out_proj_0_y, grad_act_act_L1_out_proj_0_y, grad_act_act_L1_out_proj_0_y, tmp_grad_act_op23_input, tmp_grad_act_op23_input, tmp_grad_act_op23_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=60 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_attn_0_out, tmp_grad_act_op23_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=61 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_wo, tmp_grad_weight_op23_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=62 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_bo, tmp_grad_weight_op23_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=63 op=attn_backward_core kernel_id=attention_backward_causal_head_major_gqa */
    attention_backward_causal_head_major_gqa(grad_act_act_L1_attn_0_out, grad_act_act_L1_attn_0_out, grad_act_act_L1_attn_0_out, grad_act_act_L1_attn_0_out, grad_act_act_L1_attn_0_out, tmp_grad_act_op22_q, tmp_grad_act_op22_k, tmp_grad_act_op22_v, aux_d_scores, 16, 8, CK_NUM_TOKENS, 128, 128, 128);
    call_count++;
    /* op_id=64 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rope_qk_0_q, tmp_grad_act_op22_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=65 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rope_qk_0_k, tmp_grad_act_op22_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=66 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_v_proj_0_y, tmp_grad_act_op22_v, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=67 op=rope_qk_backward_core kernel_id=rope_backward_qk_f32 */
    rope_backward_qk(grad_act_act_L1_rope_qk_0_q, grad_act_act_L1_rope_qk_0_q, tmp_grad_act_op21_q, tmp_grad_act_op21_k, grad_act_act_L1_rope_qk_0_q, grad_act_act_L1_rope_qk_0_q, 16, 8, CK_NUM_TOKENS, 128, 128, 0);
    call_count++;
    /* op_id=68 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_qk_norm_0_q, tmp_grad_act_op21_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=69 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_qk_norm_0_k, tmp_grad_act_op21_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=70 op=qk_norm_backward_core kernel_id=qk_norm_backward_f32 */
    qk_norm_backward(grad_act_act_L1_qk_norm_0_q, grad_act_act_L1_qk_norm_0_q, grad_act_act_L1_qk_norm_0_q, grad_act_act_L1_qk_norm_0_q, grad_act_act_L1_qk_norm_0_q, grad_act_act_L1_qk_norm_0_q, tmp_grad_act_op20_q, tmp_grad_act_op20_q, tmp_grad_weight_op20_q_gamma, tmp_grad_weight_op20_k_gamma, 16, 8, CK_NUM_TOKENS, 128, 1e-5f);
    call_count++;
    /* op_id=71 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_q_proj_0_y, tmp_grad_act_op20_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=72 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_k_proj_0_y, tmp_grad_act_op20_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=73 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_q_norm, tmp_grad_weight_op20_q_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=74 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_k_norm, tmp_grad_weight_op20_k_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=75 op=v_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_v_proj_0_y, grad_act_act_L1_v_proj_0_y, grad_act_act_L1_v_proj_0_y, tmp_grad_act_op19_input, tmp_grad_act_op19_input, tmp_grad_act_op19_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=76 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rmsnorm_0_output, tmp_grad_act_op19_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=77 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_wv, tmp_grad_weight_op19_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=78 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_bv, tmp_grad_weight_op19_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=79 op=k_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_k_proj_0_y, grad_act_act_L1_k_proj_0_y, grad_act_act_L1_k_proj_0_y, tmp_grad_act_op18_input, tmp_grad_act_op18_input, tmp_grad_act_op18_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=80 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rmsnorm_0_output, tmp_grad_act_op18_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=81 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_wk, tmp_grad_weight_op18_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=82 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_bk, tmp_grad_weight_op18_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=83 op=q_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L1_q_proj_0_y, grad_act_act_L1_q_proj_0_y, grad_act_act_L1_q_proj_0_y, tmp_grad_act_op17_input, tmp_grad_act_op17_input, tmp_grad_act_op17_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=84 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L1_rmsnorm_0_output, tmp_grad_act_op17_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=85 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_wq, tmp_grad_weight_op17_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=86 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_bq, tmp_grad_weight_op17_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=87 op=rmsnorm_backward_core kernel_id=rmsnorm_backward */
    rmsnorm_backward(grad_act_act_L1_rmsnorm_0_output, grad_act_act_L1_rmsnorm_0_output, grad_act_act_L1_rmsnorm_0_output, grad_act_act_L1_rmsnorm_0_output, tmp_grad_act_op16_input, tmp_grad_weight_op16_gamma, CK_NUM_TOKENS, 1024, 1024);
    call_count++;
    /* op_id=88 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_residual_add_1_out, tmp_grad_act_op16_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=89 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_1_ln1_gamma, tmp_grad_weight_op16_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=90 op=residual_add_backward_core kernel_id=residual_add_backward_f32 */
    ck_residual_add_backward(grad_act_act_L0_residual_add_1_out, tmp_grad_act_op15_a, tmp_grad_act_op15_b, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=91 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_mlp_down_0_y, tmp_grad_act_op15_a, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=92 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_residual_add_0_out, tmp_grad_act_op15_b, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=93 op=mlp_down_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_mlp_down_0_y, grad_act_act_L0_mlp_down_0_y, grad_act_act_L0_mlp_down_0_y, tmp_grad_act_op14_input, tmp_grad_act_op14_input, tmp_grad_act_op14_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=94 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_silu_mul_0_out, tmp_grad_act_op14_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=95 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_w2, tmp_grad_weight_op14_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=96 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_b2, tmp_grad_weight_op14_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=97 op=silu_mul_backward_core kernel_id=swiglu_backward_exact */
    swiglu_backward_exact(grad_act_act_L0_silu_mul_0_out, grad_act_act_L0_silu_mul_0_out, tmp_grad_act_op13_input, CK_NUM_TOKENS, 1);
    call_count++;
    /* op_id=98 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_mlp_gate_up_0_y, tmp_grad_act_op13_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=99 op=mlp_gate_up_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_mlp_gate_up_0_y, grad_act_act_L0_mlp_gate_up_0_y, grad_act_act_L0_mlp_gate_up_0_y, tmp_grad_act_op12_input, tmp_grad_act_op12_input, tmp_grad_act_op12_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=100 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rmsnorm_1_output, tmp_grad_act_op12_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=101 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_w1, tmp_grad_weight_op12_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=102 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_b1, tmp_grad_weight_op12_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=103 op=rmsnorm_backward_core kernel_id=rmsnorm_backward */
    rmsnorm_backward(grad_act_act_L0_rmsnorm_1_output, grad_act_act_L0_rmsnorm_1_output, grad_act_act_L0_rmsnorm_1_output, grad_act_act_L0_rmsnorm_1_output, tmp_grad_act_op11_input, tmp_grad_weight_op11_gamma, CK_NUM_TOKENS, 1024, 1024);
    call_count++;
    /* op_id=104 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_residual_add_0_out, tmp_grad_act_op11_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=105 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_ln2_gamma, tmp_grad_weight_op11_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=106 op=residual_add_backward_core kernel_id=residual_add_backward_f32 */
    ck_residual_add_backward(grad_act_act_L0_residual_add_0_out, tmp_grad_act_op10_a, tmp_grad_act_op10_b, CK_NUM_TOKENS, 1024);
    call_count++;
    /* op_id=107 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_out_proj_0_y, tmp_grad_act_op10_a, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=108 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_Sheader_dense_embedding_lookup_0_out, tmp_grad_act_op10_b, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=109 op=out_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_out_proj_0_y, grad_act_act_L0_out_proj_0_y, grad_act_act_L0_out_proj_0_y, tmp_grad_act_op9_input, tmp_grad_act_op9_input, tmp_grad_act_op9_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=110 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_attn_0_out, tmp_grad_act_op9_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=111 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_wo, tmp_grad_weight_op9_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=112 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_bo, tmp_grad_weight_op9_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=113 op=attn_backward_core kernel_id=attention_backward_causal_head_major_gqa */
    attention_backward_causal_head_major_gqa(grad_act_act_L0_attn_0_out, grad_act_act_L0_attn_0_out, grad_act_act_L0_attn_0_out, grad_act_act_L0_attn_0_out, grad_act_act_L0_attn_0_out, tmp_grad_act_op8_q, tmp_grad_act_op8_k, tmp_grad_act_op8_v, aux_d_scores, 16, 8, CK_NUM_TOKENS, 128, 128, 128);
    call_count++;
    /* op_id=114 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rope_qk_0_q, tmp_grad_act_op8_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=115 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rope_qk_0_k, tmp_grad_act_op8_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=116 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_v_proj_0_y, tmp_grad_act_op8_v, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=117 op=rope_qk_backward_core kernel_id=rope_backward_qk_f32 */
    rope_backward_qk(grad_act_act_L0_rope_qk_0_q, grad_act_act_L0_rope_qk_0_q, tmp_grad_act_op7_q, tmp_grad_act_op7_k, grad_act_act_L0_rope_qk_0_q, grad_act_act_L0_rope_qk_0_q, 16, 8, CK_NUM_TOKENS, 128, 128, 0);
    call_count++;
    /* op_id=118 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_qk_norm_0_q, tmp_grad_act_op7_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=119 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_qk_norm_0_k, tmp_grad_act_op7_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=120 op=qk_norm_backward_core kernel_id=qk_norm_backward_f32 */
    qk_norm_backward(grad_act_act_L0_qk_norm_0_q, grad_act_act_L0_qk_norm_0_q, grad_act_act_L0_qk_norm_0_q, grad_act_act_L0_qk_norm_0_q, grad_act_act_L0_qk_norm_0_q, grad_act_act_L0_qk_norm_0_q, tmp_grad_act_op6_q, tmp_grad_act_op6_q, tmp_grad_weight_op6_q_gamma, tmp_grad_weight_op6_k_gamma, 16, 8, CK_NUM_TOKENS, 128, 1e-5f);
    call_count++;
    /* op_id=121 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_q_proj_0_y, tmp_grad_act_op6_q, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=122 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_k_proj_0_y, tmp_grad_act_op6_k, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=123 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_q_norm, tmp_grad_weight_op6_q_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=124 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_k_norm, tmp_grad_weight_op6_k_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=125 op=v_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_v_proj_0_y, grad_act_act_L0_v_proj_0_y, grad_act_act_L0_v_proj_0_y, tmp_grad_act_op5_input, tmp_grad_act_op5_input, tmp_grad_act_op5_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=126 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rmsnorm_0_output, tmp_grad_act_op5_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=127 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_wv, tmp_grad_weight_op5_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=128 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_bv, tmp_grad_weight_op5_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=129 op=k_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_k_proj_0_y, grad_act_act_L0_k_proj_0_y, grad_act_act_L0_k_proj_0_y, tmp_grad_act_op4_input, tmp_grad_act_op4_input, tmp_grad_act_op4_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=130 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rmsnorm_0_output, tmp_grad_act_op4_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=131 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_wk, tmp_grad_weight_op4_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=132 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_bk, tmp_grad_weight_op4_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=133 op=q_proj_backward_core kernel_id=gemm_backward_f32 */
    fc2_backward_kernel(grad_act_act_L0_q_proj_0_y, grad_act_act_L0_q_proj_0_y, grad_act_act_L0_q_proj_0_y, tmp_grad_act_op3_input, tmp_grad_act_op3_input, tmp_grad_act_op3_input, CK_NUM_TOKENS, 1024, 1024, 1);
    call_count++;
    /* op_id=134 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_L0_rmsnorm_0_output, tmp_grad_act_op3_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=135 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_wq, tmp_grad_weight_op3_W, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=136 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_bq, tmp_grad_weight_op3_bias, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=137 op=rmsnorm_backward_core kernel_id=rmsnorm_backward */
    rmsnorm_backward(grad_act_act_L0_rmsnorm_0_output, grad_act_act_L0_rmsnorm_0_output, grad_act_act_L0_rmsnorm_0_output, grad_act_act_L0_rmsnorm_0_output, tmp_grad_act_op2_input, tmp_grad_weight_op2_gamma, CK_NUM_TOKENS, 1024, 1024);
    call_count++;
    /* op_id=138 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_act_act_Sheader_dense_embedding_lookup_0_out, tmp_grad_act_op2_input, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=139 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_layer_0_ln1_gamma, tmp_grad_weight_op2_gamma, CK_TENSOR_CAP_F32);
    call_count++;
    /* op_id=140 op=dense_embedding_lookup_backward_core kernel_id=embedding_backward_f32 */
    embedding_backward(input_token_ids, CK_NUM_TOKENS, grad_act_act_Sheader_dense_embedding_lookup_0_out, tmp_grad_weight_op1_weight, aux_d_pos_embeddings, 151936, 1024, 1024, 128, 0);
    call_count++;
    /* op_id=141 op=grad_accumulate kernel_id=gradient_accumulate_f32 */
    gradient_accumulate_f32(grad_weight_token_emb, tmp_grad_weight_op1_weight, CK_TENSOR_CAP_F32);
    call_count++;
    return call_count;
}

int ck_train_optimizer_step(float lr) {
    const float beta1 = 0.9f;
    const float beta2 = 0.999f;
    const float eps = 1e-8f;
    const float weight_decay = 0.01f;
    int call_count = 0;
    g_opt_step += 1;
    /* skipped non-fp32 optimizer params: 13 */
    /* AdamW update: final_ln_weight */
    adamw_update_f32(grad_weight_final_ln_weight, weight_final_ln_weight, m_final_ln_weight, v_final_ln_weight, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.b1 */
    adamw_update_f32(grad_weight_layer_0_b1, weight_layer_0_b1, m_layer_0_b1, v_layer_0_b1, (size_t)6144, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.b2 */
    adamw_update_f32(grad_weight_layer_0_b2, weight_layer_0_b2, m_layer_0_b2, v_layer_0_b2, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.bk */
    adamw_update_f32(grad_weight_layer_0_bk, weight_layer_0_bk, m_layer_0_bk, v_layer_0_bk, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.bo */
    adamw_update_f32(grad_weight_layer_0_bo, weight_layer_0_bo, m_layer_0_bo, v_layer_0_bo, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.bq */
    adamw_update_f32(grad_weight_layer_0_bq, weight_layer_0_bq, m_layer_0_bq, v_layer_0_bq, (size_t)2048, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.bv */
    adamw_update_f32(grad_weight_layer_0_bv, weight_layer_0_bv, m_layer_0_bv, v_layer_0_bv, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.k_norm */
    adamw_update_f32(grad_weight_layer_0_k_norm, weight_layer_0_k_norm, m_layer_0_k_norm, v_layer_0_k_norm, (size_t)128, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.ln1_gamma */
    adamw_update_f32(grad_weight_layer_0_ln1_gamma, weight_layer_0_ln1_gamma, m_layer_0_ln1_gamma, v_layer_0_ln1_gamma, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.ln2_gamma */
    adamw_update_f32(grad_weight_layer_0_ln2_gamma, weight_layer_0_ln2_gamma, m_layer_0_ln2_gamma, v_layer_0_ln2_gamma, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.0.q_norm */
    adamw_update_f32(grad_weight_layer_0_q_norm, weight_layer_0_q_norm, m_layer_0_q_norm, v_layer_0_q_norm, (size_t)128, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.b1 */
    adamw_update_f32(grad_weight_layer_1_b1, weight_layer_1_b1, m_layer_1_b1, v_layer_1_b1, (size_t)6144, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.b2 */
    adamw_update_f32(grad_weight_layer_1_b2, weight_layer_1_b2, m_layer_1_b2, v_layer_1_b2, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.bk */
    adamw_update_f32(grad_weight_layer_1_bk, weight_layer_1_bk, m_layer_1_bk, v_layer_1_bk, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.bo */
    adamw_update_f32(grad_weight_layer_1_bo, weight_layer_1_bo, m_layer_1_bo, v_layer_1_bo, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.bq */
    adamw_update_f32(grad_weight_layer_1_bq, weight_layer_1_bq, m_layer_1_bq, v_layer_1_bq, (size_t)2048, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.bv */
    adamw_update_f32(grad_weight_layer_1_bv, weight_layer_1_bv, m_layer_1_bv, v_layer_1_bv, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.k_norm */
    adamw_update_f32(grad_weight_layer_1_k_norm, weight_layer_1_k_norm, m_layer_1_k_norm, v_layer_1_k_norm, (size_t)128, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.ln1_gamma */
    adamw_update_f32(grad_weight_layer_1_ln1_gamma, weight_layer_1_ln1_gamma, m_layer_1_ln1_gamma, v_layer_1_ln1_gamma, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.ln2_gamma */
    adamw_update_f32(grad_weight_layer_1_ln2_gamma, weight_layer_1_ln2_gamma, m_layer_1_ln2_gamma, v_layer_1_ln2_gamma, (size_t)1024, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    /* AdamW update: layer.1.q_norm */
    adamw_update_f32(grad_weight_layer_1_q_norm, weight_layer_1_q_norm, m_layer_1_q_norm, v_layer_1_q_norm, (size_t)128, lr, beta1, beta2, eps, weight_decay, g_opt_step);
    call_count++;
    return call_count;
}

int ck_train_step(const int32_t *token_ids, const int32_t *targets, float *loss_out, float lr) {
    if (token_ids != NULL) {
        memcpy(g_dummy_i32, token_ids, sizeof(int32_t) * CK_NUM_TOKENS);
    }
    if (targets != NULL) {
        memcpy(g_dummy_i32, targets, sizeof(int32_t) * CK_NUM_TOKENS);
    }
    int fwd = ck_train_forward_step();
    int bwd = ck_train_backward_step();
    int opt = ck_train_optimizer_step(lr);
    if (loss_out != NULL) {
        *loss_out = g_loss_scalar[0];
    }
    return fwd + bwd + opt;
}
