attention_kernels.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
attention_kernels.c File Reference
Attention score/softmax/output kernels with SIMD (SSE/AVX/AVX512)
#include "bf16_utils.h"
#include "attention_oracle_ggml.h"
#include "ckernel_engine.h"
#include "../../llama.cpp/ggml/include/ggml.h"
#include <dlfcn.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
Macros
#define CK_GGML_FA_TILE_KV 64
#define CK_GGML_FA_TILE_Q 64
#define CK_MADD128(x, y, z) _mm_add_ps(_mm_mul_ps(x, y), z)
#define CK_NMADD128(x, y, z) _mm_sub_ps(z, _mm_mul_ps(x, y))
#define CK_NOINLINE
#define CK_OPTNONE
#define FLASH_QUERY_IMPL attention_flash_query_causal
#define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal
Typedefs
typedef void(* ck_ggml_build_forward_expand_fn) (struct ggml_cgraph *, struct ggml_tensor *)
typedef void(* ck_ggml_compute_forward_mul_mat_fn) (const struct ggml_compute_params *, struct ggml_tensor *)
typedef void(* ck_ggml_compute_forward_soft_max_fn) (const struct ggml_compute_params *, struct ggml_tensor *)
typedef void(* ck_ggml_cpu_init_fn) (void)
typedef void(* ck_ggml_free_fn) (struct ggml_context *)
typedef enum ggml_status(* ck_ggml_graph_compute_with_ctx_fn) (struct ggml_context *, struct ggml_cgraph *, int)
typedef struct ggml_context *(* ck_ggml_init_fn) (struct ggml_init_params)
typedef struct ggml_tensor *(* ck_ggml_mul_mat_graph_fn) (struct ggml_context *, struct ggml_tensor *, struct ggml_tensor *)
typedef struct ggml_cgraph *(* ck_ggml_new_graph_fn) (struct ggml_context *)
typedef struct ggml_tensor *(* ck_ggml_new_tensor_2d_fn) (struct ggml_context *, enum ggml_type, int64_t, int64_t)
typedef void(* ck_ggml_set_input_fn) (struct ggml_tensor *)
typedef void(* ck_ggml_vec_dot_f32_fn) (int, float *, size_t, const float *, size_t, const float *, size_t, int)
typedef double(* ck_ggml_vec_soft_max_f32_fn) (int, float *, const float *, float)
Functions
void attention_backward_causal_head_major (const float *d_output, const float *q, const float *k, const float *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_backward_causal_head_major_gqa (const float *d_output, const float *q, const float *k, const float *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_backward_causal_head_major_gqa_bf16 (const uint16_t *d_output, float *d_x, const uint16_t *q, const uint16_t *k, const uint16_t *v, const float *attn_weights, float *d_q, float *d_k, float *d_v, float *d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window, float *scratch_d_output, float *scratch_q, float *scratch_k, float *scratch_v)
static void attention_flash_query_causal (const float *q_vec, const float *k_head, const float *v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *out_vec)
static void attention_flash_query_causal_exact (const float *q_vec, const float *k_head, const float *v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *out_vec)
static void attention_flash_query_causal_exact_f16kv (const float *q_vec, const float *k_head, const float *v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *out_vec)
void attention_forward_causal_head_major (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_exact (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa_bf16 (const uint16_t *q, const uint16_t *k, const uint16_t *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window, float *scratch_q, float *scratch_k, float *scratch_v)
void attention_forward_causal_head_major_gqa_exact (const float *q, const float *k, const float *v, float *scores, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
void attention_forward_causal_head_major_gqa_flash (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
void attention_forward_causal_head_major_gqa_flash_strided (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
void attention_forward_causal_head_major_gqa_flash_strided_f16kv (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
void attention_forward_decode_head_major_gqa_flash (const float *q_token, const float *k_cache, const float *v_cache, float *out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
void attention_forward_decode_head_major_gqa_flash_f16kv (const float *q_token, const float *k_cache, const float *v_cache, float *out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
void attention_forward_decode_head_major_gqa_regular (const float *q_token, const float *k_cache, const float *v_cache, float *out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
WARNING: This is NOT true flash attention!
void attention_forward_full_head_major_gqa_exact_strided (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
void attention_forward_full_head_major_gqa_flash (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
void attention_forward_full_head_major_gqa_flash_strided (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
void attention_forward_full_head_major_gqa_ggml_strided (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
static void attention_forward_full_head_major_gqa_ggml_tiled_strict (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
static void attention_forward_head_major_gqa_flash_impl (const float *q, const float *k, const float *v, float *output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens, int causal)
static int attention_head_full_dyn_ggml_regular_graph_out (const float *q_head, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *prob_row, float *out_head, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, int layer_id, int head_id)
static int attention_out_mul_mat_graph_block (const float *v_cols, const float *prob_block, int kv_tokens, int head_dim, int query_block, float *out_block)
static void attention_query_full_dyn_ggml_regular (const float *q_vec, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *prob_row, float *out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, int layer_id, int head_id, int query_id)
static void attention_query_full_dyn_ggml_regular_matmul_out (const float *q_vec, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *prob_row, float *out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, ck_ggml_compute_forward_mul_mat_fn mul_mat_fn, int layer_id, int head_id, int query_id)
static void attention_query_full_exact_regular (const float *q_vec, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *out_vec, int layer_id, int head_id, int query_id)
static void attention_query_full_ggml_compute_regular (const float *q_vec, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *prob_row, float *out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_compute_forward_mul_mat_fn mul_mat_fn, ck_ggml_compute_forward_soft_max_fn softmax_compute_fn)
static void attention_query_full_ggml_regular (const float *q_vec, const float *k_head, const float *v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float *score_row, float *out_vec, int layer_id, int head_id, int query_id)
static int ck_attention_ggml_out_graph_enabled (void)
static void ck_attention_matmul_f32_accum (float *c, const float *a, const float *b, int m, int k, int n)
static int ck_attention_reverse_out_dot_enabled (void)
static float ck_attention_strict_scale_f32 (int head_dim)
static void ck_attention_trace (const char *branch, int layer_id, int head_id)
static void ck_attention_trace_float (const char *tag, int layer_id, int head_id, float value)
static void ck_attention_trace_query (const char *tag, int layer_id, int head_id, int query_id, int value)
static int ck_attention_vec_dump_enabled (void)
static int ck_attention_vec_dump_next_layer_id (void)
static int ck_attention_vec_dump_parse_env_int (const char *name, int *out)
static void ck_attention_vec_dump_selected_query (const float *raw_scores, const float *probs, const float *out_vec, const float *v_cols, int kv_tokens, int head_dim, int layer_id, int head_id, int query_id)
static int ck_attention_vec_dump_should_emit (int layer_id, int head_id, int query_id)
static void ck_attention_vec_dump_tensor (const char *name, int layer_id, int query_id, const float *data, size_t elem_count)
static int ck_attention_vec_dump_vcols_enabled (void)
static void ck_ggml_init_tensor_f32 (struct ggml_tensor *t, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3, size_t nb0, size_t nb1, size_t nb2, size_t nb3, void *data)
static float ck_ggml_vec_dot_f32_contig (const float *x, const float *y, int n)
static double ck_ggml_vec_soft_max_row (int n, float *y, const float *x, float max)
static float ck_hsum128_ps (__m128 v)
static ck_ggml_build_forward_expand_fn ck_resolve_ggml_build_forward_expand (void)
static ck_ggml_compute_forward_mul_mat_fn ck_resolve_ggml_compute_forward_mul_mat (void)
static ck_ggml_compute_forward_soft_max_fn ck_resolve_ggml_compute_forward_soft_max (void)
static ck_ggml_cpu_init_fn ck_resolve_ggml_cpu_init (void)
static void * ck_resolve_ggml_cpu_so_handle (void)
static ck_ggml_free_fn ck_resolve_ggml_free (void)
static ck_ggml_graph_compute_with_ctx_fn ck_resolve_ggml_graph_compute_with_ctx (void)
static ck_ggml_init_fn ck_resolve_ggml_init (void)
static ck_ggml_mul_mat_graph_fn ck_resolve_ggml_mul_mat_graph (void)
static ck_ggml_new_graph_fn ck_resolve_ggml_new_graph (void)
static ck_ggml_new_tensor_2d_fn ck_resolve_ggml_new_tensor_2d (void)
static ck_ggml_set_input_fn ck_resolve_ggml_set_input (void)
static void * ck_resolve_ggml_symbol (const char *name)
static ck_ggml_vec_dot_f32_fn ck_resolve_ggml_vec_dot_f32 (void)
static ck_ggml_vec_soft_max_f32_fn ck_resolve_ggml_vec_soft_max_f32 (void)
static float ck_round_fp16_scalar (float x)
static float ck_vec_dot_f32_reverse_strict (const float *x, const float *y, int n)
static float ck_vec_dot_f32_strict (const float *x, const float *y, int n)
static float ck_vec_dot_f32x_f32_to_f32_via_f64 (const float *x, const float *y, int n)
static float ck_vec_max_f32_contig (const float *x, int n)
static void ck_vec_scale_f32_inplace (float *x, int n, float scale)
static void convert_bf16_tensor_to_buf (const uint16_t *src, float *dst, size_t count)
static size_t qkv_index (int h, int t, int d, int num_tokens, int aligned_head_dim)
static size_t score_index (int h, int i, int j, int aligned_context_window)
Variables
static int ck_attention_vec_dump_layer_seq = 0
static const char ck_attention_vec_dump_magic [8] = {'C', 'K', 'D', 'M', 'P', '\0', '\0', '\0'}
static const uint32_t ck_attention_vec_dump_version = 1u
Detailed Description
Attention score/softmax/output kernels with SIMD (SSE/AVX/AVX512)
CK-ENGINE KERNEL RULES:
NO malloc/free - memory via bump allocator, pointers passed in
NO OpenMP - parallelization at orchestrator/codegen layer
API must define: inputs, outputs, workspace, and memory layouts
Pure computation - deterministic, no side effects
After changes: make test && make llamacpp-parity-full
Attention: softmax(Q @ K^T / sqrt(d)) @ V Supports GQA (grouped-query attention) with head broadcasting.
Definition in file attention_kernels.c.
Macro Definition Documentation
CK_GGML_FA_TILE_KV
#define CK_GGML_FA_TILE_KV 64
Definition at line 2269 of file attention_kernels.c.
CK_GGML_FA_TILE_Q
#define CK_GGML_FA_TILE_Q 64
Definition at line 2268 of file attention_kernels.c.
CK_MADD128
#define CK_MADD128 (x, y, z) _mm_add_ps(_mm_mul_ps(x, y), z)
Definition at line 569 of file attention_kernels.c.
CK_NMADD128
#define CK_NMADD128 (x, y, z) _mm_sub_ps(z, _mm_mul_ps(x, y))
Definition at line 570 of file attention_kernels.c.
CK_NOINLINE
#define CK_NOINLINE
Definition at line 58 of file attention_kernels.c.
CK_OPTNONE
#define CK_OPTNONE
Definition at line 66 of file attention_kernels.c.
FLASH_QUERY_IMPL
#define FLASH_QUERY_IMPL attention_flash_query_causal
FLASH_QUERY_IMPL_DECODE
#define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal
Typedef Documentation
ck_ggml_build_forward_expand_fn
typedef void(* ck_ggml_build_forward_expand_fn) (struct ggml_cgraph *, struct ggml_tensor *)
Definition at line 340 of file attention_kernels.c.
ck_ggml_compute_forward_mul_mat_fn
typedef void(* ck_ggml_compute_forward_mul_mat_fn) (const struct ggml_compute_params *, struct ggml_tensor *)
Definition at line 332 of file attention_kernels.c.
ck_ggml_compute_forward_soft_max_fn
typedef void(* ck_ggml_compute_forward_soft_max_fn) (const struct ggml_compute_params *, struct ggml_tensor *)
Definition at line 333 of file attention_kernels.c.
ck_ggml_cpu_init_fn
typedef void(* ck_ggml_cpu_init_fn) (void)
Definition at line 334 of file attention_kernels.c.
ck_ggml_free_fn
typedef void(* ck_ggml_free_fn) (struct ggml_context *)
Definition at line 336 of file attention_kernels.c.
ck_ggml_graph_compute_with_ctx_fn
typedef enum ggml_status(* ck_ggml_graph_compute_with_ctx_fn) (struct ggml_context *, struct ggml_cgraph *, int)
Definition at line 340 of file attention_kernels.c.
ck_ggml_init_fn
typedef struct ggml_context *(* ck_ggml_init_fn) (struct ggml_init_params)
Definition at line 334 of file attention_kernels.c.
ck_ggml_mul_mat_graph_fn
typedef struct ggml_tensor *(* ck_ggml_mul_mat_graph_fn) (struct ggml_context *, struct ggml_tensor *, struct ggml_tensor *)
Definition at line 336 of file attention_kernels.c.
ck_ggml_new_graph_fn
typedef struct ggml_cgraph *(* ck_ggml_new_graph_fn) (struct ggml_context *)
Definition at line 336 of file attention_kernels.c.
ck_ggml_new_tensor_2d_fn
typedef struct ggml_tensor *(* ck_ggml_new_tensor_2d_fn) (struct ggml_context *, enum ggml_type, int64_t, int64_t)
Definition at line 336 of file attention_kernels.c.
ck_ggml_set_input_fn
typedef void(* ck_ggml_set_input_fn) (struct ggml_tensor *)
Definition at line 342 of file attention_kernels.c.
ck_ggml_vec_dot_f32_fn
typedef void(* ck_ggml_vec_dot_f32_fn) (int, float *, size_t, const float *, size_t, const float *, size_t, int)
Definition at line 330 of file attention_kernels.c.
ck_ggml_vec_soft_max_f32_fn
typedef double(* ck_ggml_vec_soft_max_f32_fn) (int, float *, const float *, float)
Definition at line 331 of file attention_kernels.c.
Function Documentation
attention_backward_causal_head_major()
void attention_backward_causal_head_major (const float * d_output, const float * q, const float * k, const float * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Causal attention backward (non-GQA version)
Test:
test_attention_backward.py::TestAttentionBackward::test_backward
test_attention_backward.py::TestAttentionBackward::test_backward_vs_separate
test_parity.py::test_attention_backward_parity
Non-GQA version where num_heads == num_kv_heads. Simpler than GQA, no head broadcasting needed.
After changes: make test && make llamacpp-parity-full
Definition at line 3589 of file attention_kernels.c.
{
    attention_backward_causal_head_major_gqa(
        d_output, q, k, v, attn_weights,
        d_q, d_k, d_v, d_scores,
        num_heads, num_heads,  // num_kv_heads == num_heads
        num_tokens, head_dim, aligned_head_dim, aligned_context_window);
}
References attention_backward_causal_head_major_gqa().
attention_backward_causal_head_major_gqa()
void attention_backward_causal_head_major_gqa (const float * d_output, const float * q, const float * k, const float * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
GQA causal attention backward (score-matrix version)
Test:
test_attention_backward.py::TestAttentionBackwardGQA::test_gqa_backward
test_attention_backward.py::TestAttentionBackwardGQA::test_gqa_vs_separate
test_parity.py::test_attention_backward_parity
Computes dQ, dK, dV given dOutput and attention weights. Supports grouped-query attention with head broadcasting.
After changes: make test && make llamacpp-parity-full
Definition at line 3450 of file attention_kernels.c.
{
    const float scale = 1.0f / sqrtf((float)head_dim);
    int T = num_tokens;
    int H = num_heads;
    int H_kv = num_kv_heads;
    int hd = head_dim;
    int ad = aligned_head_dim;
    int aw = aligned_context_window;
    const size_t d_q_elems = (size_t)H * (size_t)T * (size_t)ad;
    const size_t kv_elems = (size_t)H_kv * (size_t)T * (size_t)ad;
    /* Zero the aligned outputs so padded lanes never leak garbage to downstream GEMMs. */
    for (size_t idx = 0; idx < d_q_elems; ++idx) {
        d_q[idx] = 0.0f;
    }
    for (size_t idx = 0; idx < kv_elems; ++idx) {
        d_k[idx] = 0.0f;
        d_v[idx] = 0.0f;
    }
    // Process each query head
    for (int h = 0; h < H; ++h) {
        // Which KV head does this query head use?
        int kv_h = (int)((long long)h * (long long)H_kv / (long long)H);
        // ----------------------------------------------------------------
        // Step 1: d_weights = d_output @ V^T  and  d_v += weights^T @ d_output
        // ----------------------------------------------------------------
        // For each query position i, compute d_weights[i, j] for j <= i
        // and accumulate d_v[j] contributions
        for (int i = 0; i < T; ++i) {
            size_t d_out_base = qkv_index(h, i, 0, T, ad);
            for (int j = 0; j <= i; ++j) {
                size_t v_base = qkv_index(kv_h, j, 0, T, ad);
                size_t w_idx = score_index(h, i, j, aw);
                float w = attn_weights[w_idx];
                // d_weights[h, i, j] = d_output[h, i, :] @ v[kv_h, j, :]^T
                float dot = 0.0f;
                for (int dd = 0; dd < hd; ++dd) {
                    dot += d_output[d_out_base + dd] * v[v_base + dd];
                }
                d_scores[w_idx] = dot;
                // d_v[kv_h, j, :] += weights[h, i, j] * d_output[h, i, :]
                for (int dd = 0; dd < hd; ++dd) {
                    d_v[v_base + dd] += w * d_output[d_out_base + dd];
                }
            }
            // Zero out upper triangle of d_scores
            for (int j = i + 1; j < T; ++j) {
                d_scores[score_index(h, i, j, aw)] = 0.0f;
            }
            /* Scores scratch uses aligned_context_window, zero the padded columns. */
            for (int j = T; j < aw; ++j) {
                d_scores[score_index(h, i, j, aw)] = 0.0f;
            }
        }
        // ----------------------------------------------------------------
        // Step 2: Backward through softmax (in-place on d_scores for this head)
        // ----------------------------------------------------------------
        // d_scores = softmax_backward(d_scores, attn_weights)
        // Formula: d_score[i,j] = w[i,j] * (d_w[i,j] - sum_k(w[i,k] * d_w[i,k]))
        for (int i = 0; i < T; ++i) {
            int base = h * aw * aw + i * aw;
            // Compute dot product: sum_j w[i,j] * d_w[i,j]
            float dot_product = 0.0f;
            for (int j = 0; j <= i; ++j) {
                float wt = attn_weights[base + j];
                float dw = d_scores[base + j];
                dot_product += wt * dw;
            }
            // Apply softmax backward formula
            for (int j = 0; j <= i; ++j) {
                float wt = attn_weights[base + j];
                float dw = d_scores[base + j];
                d_scores[base + j] = wt * (dw - dot_product);
            }
        }
        // ----------------------------------------------------------------
        // Step 3: d_q = d_scores @ K * scale
        //         d_k += d_scores^T @ Q * scale
        // ----------------------------------------------------------------
        for (int i = 0; i < T; ++i) {
            size_t d_q_base = qkv_index(h, i, 0, T, ad);
            size_t q_base = qkv_index(h, i, 0, T, ad);
            // d_q[h, i, :] = sum_j d_scores[h, i, j] * k[kv_h, j, :] * scale
            // d_k[kv_h, j, :] += d_scores[h, i, j] * q[h, i, :] * scale
            for (int j = 0; j <= i; ++j) {
                size_t k_base = qkv_index(kv_h, j, 0, T, ad);
                size_t d_k_base = qkv_index(kv_h, j, 0, T, ad);
                float ds = d_scores[score_index(h, i, j, aw)] * scale;
                for (int dd = 0; dd < hd; ++dd) {
                    d_q[d_q_base + dd] += ds * k[k_base + dd];
                    d_k[d_k_base + dd] += ds * q[q_base + dd];
                }
            }
        }
    }
}
References qkv_index(), and score_index().
Referenced by attention_backward_causal_head_major(), attention_backward_causal_head_major_gqa_bf16(), and ck_layer_backward_rmsnorm_swiglu().
attention_backward_causal_head_major_gqa_bf16()
void attention_backward_causal_head_major_gqa_bf16 (const uint16_t * d_output, float * d_x, const uint16_t * q, const uint16_t * k, const uint16_t * v, const float * attn_weights, float * d_q, float * d_k, float * d_v, float * d_scores, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window, float * scratch_d_output, float * scratch_q, float * scratch_k, float * scratch_v)
BF16 attention backward with caller-provided scratch buffers
Test:
bf16/test_attention_bf16.py::TestAttentionBF16::test_bf16_backward
Accepts BF16 inputs, converts to FP32, runs FP32 backward. Caller provides scratch buffers (no per-call malloc).
After changes: make test
Definition at line 3397 of file attention_kernels.c.
{
    (void)d_x;
    const size_t head_elems = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
    const size_t kv_elems = (size_t)num_kv_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
    if (!scratch_d_output || !scratch_q || !scratch_k || !scratch_v) return;
    convert_bf16_tensor_to_buf(d_output, scratch_d_output, head_elems);
    convert_bf16_tensor_to_buf(q, scratch_q, head_elems);
    convert_bf16_tensor_to_buf(k, scratch_k, kv_elems);
    convert_bf16_tensor_to_buf(v, scratch_v, kv_elems);
    attention_backward_causal_head_major_gqa(scratch_d_output, scratch_q, scratch_k, scratch_v,
                                             attn_weights,
                                             d_q, d_k, d_v, d_scores,
                                             num_heads, num_kv_heads,
                                             num_tokens, head_dim,
                                             aligned_head_dim, aligned_context_window);
    /* No free - caller owns scratch buffers */
}
References attention_backward_causal_head_major_gqa(), and convert_bf16_tensor_to_buf().
attention_flash_query_causal()
static void attention_flash_query_causal (const float * q_vec, const float * k_head, const float * v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * out_vec) static
Definition at line 1503 of file attention_kernels.c.
{
    // Online softmax:
    //   m = running max, s = running sum(exp(score - m))
    //   out = sum(exp(score - m) * v)
    float m = -INFINITY;
    float s = 0.0f;
    for (int d = 0; d < head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t)j * (size_t)aligned_head_dim;
        const float *v_vec = v_head + (size_t)j * (size_t)aligned_head_dim;
        float dot = 0.0f;
        for (int d = 0; d < head_dim; ++d) {
            dot += q_vec[d] * k_vec[d];
        }
        float score = dot * scale;
        if (score > m) {
            float exp_m = (m == -INFINITY) ? 0.0f : expf(m - score);
            s *= exp_m;
            for (int d = 0; d < head_dim; ++d) {
                out_vec[d] *= exp_m;
            }
            s += 1.0f;
            for (int d = 0; d < head_dim; ++d) {
                out_vec[d] += v_vec[d];
            }
            m = score;
        } else {
            float e = expf(score - m);
            s += e;
            for (int d = 0; d < head_dim; ++d) {
                out_vec[d] += e * v_vec[d];
            }
        }
    }
    float inv_s = 1.0f / s;
    for (int d = 0; d < head_dim; ++d) {
        out_vec[d] *= inv_s;
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
}
References score.
attention_flash_query_causal_exact()
static void attention_flash_query_causal_exact (const float * q_vec, const float * k_head, const float * v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * out_vec) static
Definition at line 1565 of file attention_kernels.c.
{
    if (kv_tokens <= 0) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int d = 0; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    float max_score = -INFINITY;
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t)j * (size_t)aligned_head_dim;
        float dot = 0.0f;
        for (int d = 0; d < head_dim; ++d) {
            dot += q_vec[d] * k_vec[d];
        }
        float score = dot * scale;
        if (score > max_score) {
            max_score = score;
        }
    }
    float sum = 0.0f;
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t)j * (size_t)aligned_head_dim;
        const float *v_vec = v_head + (size_t)j * (size_t)aligned_head_dim;
        float dot = 0.0f;
        for (int d = 0; d < head_dim; ++d) {
            dot += q_vec[d] * k_vec[d];
        }
        float score = dot * scale;
        float w = expf(score - max_score);
        sum += w;
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] += w * v_vec[d];
        }
    }
    if (sum > 0.0f) {
        float inv_sum = 1.0f / sum;
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] *= inv_sum;
        }
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
}
References score.
Referenced by attention_forward_head_major_gqa_flash_impl().
attention_flash_query_causal_exact_f16kv()
static void attention_flash_query_causal_exact_f16kv (const float * q_vec, const float * k_head, const float * v_head, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * out_vec) static
Definition at line 1630 of file attention_kernels.c.
{
    if (kv_tokens <= 0) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int d = 0; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    // Mirror llama.cpp GGML flash-attention more closely:
    // - Q is converted through FP16 before the KQ dot
    // - V accumulation is rounded through FP16 at each update
    // - the softmax accumulator uses the online max/sum form
    float sum = 0.0f;
    float max_score = -INFINITY;
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t)j * (size_t)aligned_head_dim;
        const float *v_vec = v_head + (size_t)j * (size_t)aligned_head_dim;
        float dot = 0.0f;
        for (int d = 0; d < head_dim; ++d) {
            dot += ck_round_fp16_scalar(q_vec[d]) * ck_round_fp16_scalar(k_vec[d]);
        }
        float score = dot * scale;
        const float prev_max = max_score;
        float max_scale = 1.0f;
        float value_scale = 1.0f;
        if (score > max_score) {
            max_score = score;
            max_scale = isfinite(prev_max) ? expf(prev_max - max_score) : 0.0f;
            for (int d = 0; d < head_dim; ++d) {
                out_vec[d] = ck_round_fp16_scalar(out_vec[d] * max_scale);
            }
        } else {
            value_scale = expf(score - max_score);
        }
        for (int d = 0; d < head_dim; ++d) {
            const float v_rounded = ck_round_fp16_scalar(v_vec[d]);
            const float updated = out_vec[d] + value_scale * v_rounded;
            out_vec[d] = ck_round_fp16_scalar(updated);
        }
        sum = sum * max_scale + value_scale;
    }
    if (sum > 0.0f) {
        float inv_sum = 1.0f / sum;
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] *= inv_sum;
        }
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
}
References ck_round_fp16_scalar(), and score.
Referenced by attention_forward_causal_head_major_gqa_flash_strided_f16kv(), and attention_forward_decode_head_major_gqa_flash_f16kv().
attention_forward_causal_head_major()
void attention_forward_causal_head_major (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Causal attention forward (score-matrix version)
Test:
test_attention.py::TestAttentionForward::test_causal_forward
test_attention.py::TestAttentionForward::test_gqa_broadcast
test_attention.py::TestAttentionForward::test_exact_vs_fast
test_parity.py::test_attention_parity
Computes softmax(Q @ K^T / sqrt(d)) @ V with causal masking. Uses O(N^2) memory for scores matrix.
After changes: make test && make llamacpp-parity-full
Definition at line 843 of file attention_kernels.c.
{
    const float scale = 1.0f / sqrtf((float)head_dim);
    // Phase 1: compute scaled dot-product scores Q·K^T / sqrt(d_k),
    // lower triangle only (j <= i).
    for (int h = 0; h < num_heads; ++h) {
        for (int i = 0; i < num_tokens; ++i) {
            for (int j = 0; j <= i; ++j) {
                float dot = 0.0f;
                size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                size_t base_k = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    dot += q[base_q + d] * k[base_k + d];
                }
                scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
            }
            // Ensure upper triangle is zeroed so there are no stale values
            // before the softmax kernel runs.
            for (int j = i + 1; j < num_tokens; ++j) {
                scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
            }
        }
    }
    // Phase 2: apply causal row-wise softmax in-place over j <= i.
    causal_softmax_head_major(scores,
                              num_heads,
                              num_tokens,
                              aligned_context_window);
    // Phase 3: attention weights · V.
    for (int h = 0; h < num_heads; ++h) {
        for (int i = 0; i < num_tokens; ++i) {
            size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
            // Zero the full aligned head slice so padded dims stay clean.
            for (int d = 0; d < aligned_head_dim; ++d) {
                output[out_base + d] = 0.0f;
            }
            // Weighted sum over causal positions.
            for (int j = 0; j <= i; ++j) {
                float w = scores[score_index(h, i, j, aligned_context_window)];
                size_t v_base = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    output[out_base + d] += w * v[v_base + d];
                }
            }
        }
    }
}
References causal_softmax_head_major(), qkv_index(), and score_index().
attention_forward_causal_head_major_exact()
void attention_forward_causal_head_major_exact (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
Causal attention forward (exact version using stdlib expf)
Test:
test_attention.py::TestAttentionForward::test_exact_single
test_attention.py::TestAttentionForward::test_exact_vs_fast
Uses standard library expf for numerical accuracy reference. Slower but provides maximum accuracy.
After changes: make test
Definition at line 919 of file attention_kernels.c.
{
    const float scale = 1.0f / sqrtf((float)head_dim);
    // Phase 1: compute scaled dot-product scores Q·K^T / sqrt(d_k),
    // lower triangle only (j <= i).
    for (int h = 0; h < num_heads; ++h) {
        for (int i = 0; i < num_tokens; ++i) {
            for (int j = 0; j <= i; ++j) {
                float dot = 0.0f;
                size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                size_t base_k = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    dot += q[base_q + d] * k[base_k + d];
                }
                scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
            }
            // Ensure upper triangle is zeroed so there are no stale values
            // before the softmax kernel runs.
            for (int j = i + 1; j < num_tokens; ++j) {
                scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
            }
        }
    }
    // Phase 2: apply causal row-wise softmax using exact expf.
    causal_softmax_head_major_exact(scores,
                                     num_heads,
                                     num_tokens,
                                     aligned_context_window);
    // Phase 3: attention weights · V.
    for (int h = 0; h < num_heads; ++h) {
        for (int i = 0; i < num_tokens; ++i) {
            size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
            // Zero the full aligned head slice so padded dims stay clean.
            for (int d = 0; d < aligned_head_dim; ++d) {
                output[out_base + d] = 0.0f;
            }
            // Weighted sum over causal positions.
            for (int j = 0; j <= i; ++j) {
                float w = scores[score_index(h, i, j, aligned_context_window)];
                size_t v_base = qkv_index(h, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    output[out_base + d] += w * v[v_base + d];
                }
            }
        }
    }
}
References causal_softmax_head_major_exact(), qkv_index(), and score_index().
attention_forward_causal_head_major_gqa()
void attention_forward_causal_head_major_gqa (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
GQA causal attention forward (score-matrix version)
Test:
test_attention.py::TestAttentionForward::test_gqa_forward
test_attention.py::TestAttentionForward::test_gqa_broadcast
test_attention_backward.py::TestAttentionBackwardGQA::test_gqa_backward
test_parity.py::test_attention_gqa_parity
Grouped-query attention: Q has num_heads, K/V have num_kv_heads. Each query head maps to a KV head via ratio.
After changes: make test && make llamacpp-parity-full
Definition at line 997 of file attention_kernels.c.
{
    const float scale = 1.0f / sqrtf((float)head_dim);
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        for (int i = 0; i < num_tokens; ++i) {
            for (int j = 0; j <= i; ++j) {
                float dot = 0.0f;
                size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                size_t base_k = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    dot += q[base_q + d] * k[base_k + d];
                }
                scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
            }
            for (int j = i + 1; j < num_tokens; ++j) {
                scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
            }
        }
    }
    causal_softmax_head_major(scores,
                              num_heads,
                              num_tokens,
                              aligned_context_window);
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        for (int i = 0; i < num_tokens; ++i) {
            size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
            for (int d = 0; d < aligned_head_dim; ++d) {
                output[out_base + d] = 0.0f;
            }
            for (int j = 0; j <= i; ++j) {
                float w = scores[score_index(h, i, j, aligned_context_window)];
                size_t v_base = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    output[out_base + d] += w * v[v_base + d];
                }
            }
        }
    }
}
References causal_softmax_head_major(), qkv_index(), and score_index().
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), and ck_layer_forward_rmsnorm_swiglu_ref().
attention_forward_causal_head_major_gqa_bf16()
void attention_forward_causal_head_major_gqa_bf16 (const uint16_t * q, const uint16_t * k, const uint16_t * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window, float * scratch_q, float * scratch_k, float * scratch_v)
BF16 GQA causal attention forward
Test:
bf16/test_attention_bf16.py::TestAttentionBF16::test_bf16_forward
bf16/test_attention_bf16.py::TestAttentionBF16::test_bf16_gqa
bf16/test_attention_bf16.py::TestAttentionBF16::test_bf16_flash
Accepts BF16 inputs, converts to FP32, uses exact softmax. Caller provides scratch buffers (no per-call malloc).
After changes: make test
Definition at line 1139 of file attention_kernels.c.
{
    const size_t q_elems = (size_t)num_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
    const size_t kv_elems = (size_t)num_kv_heads * (size_t)num_tokens * (size_t)aligned_head_dim;
    if (!scratch_q || !scratch_k || !scratch_v) return;
    convert_bf16_tensor_to_buf(q, scratch_q, q_elems);
    convert_bf16_tensor_to_buf(k, scratch_k, kv_elems);
    convert_bf16_tensor_to_buf(v, scratch_v, kv_elems);
    // Use exact version to avoid fast exp approximation error accumulating
    // with BF16 precision loss.
    attention_forward_causal_head_major_gqa_exact(scratch_q, scratch_k, scratch_v,
                                                   scores, output,
                                                   num_heads, num_kv_heads,
                                                   num_tokens, head_dim,
                                                   aligned_head_dim, aligned_context_window);
    /* No free - caller owns scratch buffers */
}
References attention_forward_causal_head_major_gqa_exact(), and convert_bf16_tensor_to_buf().
attention_forward_causal_head_major_gqa_exact()
void attention_forward_causal_head_major_gqa_exact (const float * q, const float * k, const float * v, float * scores, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int aligned_context_window)
GQA causal attention forward (exact version using stdlib expf)
Test:
test_attention.py::TestAttentionForward::test_gqa_exact
bf16/test_attention_bf16.py::TestAttentionBF16::test_bf16_gqa
Uses standard library expf for numerical accuracy reference. Used by BF16 wrapper to avoid approximation error accumulation.
After changes: make test
Definition at line 1067 of file attention_kernels.c.
{
    const float scale = 1.0f / sqrtf((float)head_dim);
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        for (int i = 0; i < num_tokens; ++i) {
            for (int j = 0; j <= i; ++j) {
                float dot = 0.0f;
                size_t base_q = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
                size_t base_k = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    dot += q[base_q + d] * k[base_k + d];
                }
                scores[score_index(h, i, j, aligned_context_window)] = dot * scale;
            }
            for (int j = i + 1; j < num_tokens; ++j) {
                scores[score_index(h, i, j, aligned_context_window)] = 0.0f;
            }
        }
    }
    // Use exact softmax with standard library expf
    causal_softmax_head_major_exact(scores,
                                     num_heads,
                                     num_tokens,
                                     aligned_context_window);
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        for (int i = 0; i < num_tokens; ++i) {
            size_t out_base = qkv_index(h, i, 0, num_tokens, aligned_head_dim);
            for (int d = 0; d < aligned_head_dim; ++d) {
                output[out_base + d] = 0.0f;
            }
            for (int j = 0; j <= i; ++j) {
                float w = scores[score_index(h, i, j, aligned_context_window)];
                size_t v_base = qkv_index(kv_head, j, 0, num_tokens, aligned_head_dim);
                for (int d = 0; d < head_dim; ++d) {
                    output[out_base + d] += w * v[v_base + d];
                }
            }
        }
    }
}
References causal_softmax_head_major_exact(), qkv_index(), and score_index().
Referenced by attention_forward_causal_head_major_gqa_bf16(), ck_layer_forward_rmsnorm_swiglu(), and ck_layer_forward_rmsnorm_swiglu_ref().
attention_forward_causal_head_major_gqa_flash()
void attention_forward_causal_head_major_gqa_flash (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
Definition at line 2826 of file attention_kernels.c.
{
    attention_forward_head_major_gqa_flash_impl(q, k, v, output,
                                                num_heads, num_kv_heads,
                                                num_tokens, head_dim,
                                                aligned_head_dim,
                                                /*kv_stride_tokens=*/num_tokens,
                                                /*causal=*/1);
}
References attention_forward_head_major_gqa_flash_impl().
Referenced by ck_layer_forward_rmsnorm_swiglu(), ck_layer_forward_rmsnorm_swiglu_q4_k(), ck_layer_forward_rmsnorm_swiglu_quant(), ck_layer_forward_rmsnorm_swiglu_ref(), qwen2_0_5b_decode_layer_0_prefill(), qwen2_0_5b_decode_layer_0_prefill(), qwen2_0_5b_decode_layer_10_prefill(), qwen2_0_5b_decode_layer_10_prefill(), qwen2_0_5b_decode_layer_11_prefill(), qwen2_0_5b_decode_layer_11_prefill(), qwen2_0_5b_decode_layer_12_prefill(), qwen2_0_5b_decode_layer_12_prefill(), qwen2_0_5b_decode_layer_13_prefill(), qwen2_0_5b_decode_layer_13_prefill(), qwen2_0_5b_decode_layer_14_prefill(), qwen2_0_5b_decode_layer_14_prefill(), qwen2_0_5b_decode_layer_15_prefill(), qwen2_0_5b_decode_layer_15_prefill(), qwen2_0_5b_decode_layer_16_prefill(), qwen2_0_5b_decode_layer_16_prefill(), qwen2_0_5b_decode_layer_17_prefill(), qwen2_0_5b_decode_layer_17_prefill(), qwen2_0_5b_decode_layer_18_prefill(), qwen2_0_5b_decode_layer_18_prefill(), qwen2_0_5b_decode_layer_19_prefill(), qwen2_0_5b_decode_layer_19_prefill(), qwen2_0_5b_decode_layer_1_prefill(), qwen2_0_5b_decode_layer_1_prefill(), qwen2_0_5b_decode_layer_20_prefill(), qwen2_0_5b_decode_layer_20_prefill(), qwen2_0_5b_decode_layer_21_prefill(), qwen2_0_5b_decode_layer_21_prefill(), qwen2_0_5b_decode_layer_22_prefill(), qwen2_0_5b_decode_layer_22_prefill(), qwen2_0_5b_decode_layer_23_prefill(), qwen2_0_5b_decode_layer_23_prefill(), qwen2_0_5b_decode_layer_2_prefill(), qwen2_0_5b_decode_layer_2_prefill(), qwen2_0_5b_decode_layer_3_prefill(), qwen2_0_5b_decode_layer_3_prefill(), qwen2_0_5b_decode_layer_4_prefill(), qwen2_0_5b_decode_layer_4_prefill(), qwen2_0_5b_decode_layer_5_prefill(), qwen2_0_5b_decode_layer_5_prefill(), qwen2_0_5b_decode_layer_6_prefill(), qwen2_0_5b_decode_layer_6_prefill(), qwen2_0_5b_decode_layer_7_prefill(), qwen2_0_5b_decode_layer_7_prefill(), qwen2_0_5b_decode_layer_8_prefill(), qwen2_0_5b_decode_layer_8_prefill(), qwen2_0_5b_decode_layer_9_prefill(), and qwen2_0_5b_decode_layer_9_prefill().
attention_forward_causal_head_major_gqa_flash_strided()
void attention_forward_causal_head_major_gqa_flash_strided (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
Flash attention forward with custom KV stride (for KV cache)
Test:
test_flash_attention.py::TestFlashAttention::test_flash_strided
test_kv_cache_attention.py::TestKVCacheAttention::test_flash_attention
Variant with configurable kv_stride_tokens for KV cache layouts where K/V may not be contiguous in memory.
After changes: make test
Definition at line 2872 of file attention_kernels.c.
{
    attention_forward_head_major_gqa_flash_impl(q, k, v, output,
                                                num_heads, num_kv_heads,
                                                num_tokens, head_dim,
                                                aligned_head_dim,
                                                kv_stride_tokens,
                                                /*causal=*/1);
}
References attention_forward_head_major_gqa_flash_impl().
Referenced by attention_forward_causal_head_major_gqa_flash_strided_sliding(), ck_test_attention_causal(), mega_fused_attention_prefill(), mega_fused_attention_prefill_q8_0(), model_layer_0_prefill(), model_layer_0_prefill(), model_layer_0_prefill(), model_layer_0_prefill(), model_layer_10_prefill(), model_layer_10_prefill(), model_layer_10_prefill(), model_layer_10_prefill(), model_layer_11_prefill(), model_layer_11_prefill(), model_layer_11_prefill(), model_layer_11_prefill(), model_layer_12_prefill(), model_layer_12_prefill(), model_layer_12_prefill(), model_layer_12_prefill(), model_layer_13_prefill(), model_layer_13_prefill(), model_layer_13_prefill(), model_layer_13_prefill(), model_layer_14_prefill(), model_layer_14_prefill(), model_layer_14_prefill(), model_layer_14_prefill(), model_layer_15_prefill(), model_layer_15_prefill(), model_layer_15_prefill(), model_layer_15_prefill(), model_layer_16_prefill(), model_layer_16_prefill(), model_layer_16_prefill(), model_layer_16_prefill(), model_layer_17_prefill(), model_layer_17_prefill(), model_layer_17_prefill(), model_layer_17_prefill(), model_layer_18_prefill(), model_layer_18_prefill(), model_layer_18_prefill(), model_layer_18_prefill(), model_layer_19_prefill(), model_layer_19_prefill(), model_layer_19_prefill(), model_layer_19_prefill(), model_layer_1_prefill(), model_layer_1_prefill(), model_layer_1_prefill(), model_layer_1_prefill(), model_layer_20_prefill(), model_layer_20_prefill(), model_layer_20_prefill(), model_layer_20_prefill(), model_layer_21_prefill(), model_layer_21_prefill(), model_layer_21_prefill(), model_layer_21_prefill(), model_layer_22_prefill(), model_layer_22_prefill(), model_layer_22_prefill(), model_layer_22_prefill(), model_layer_23_prefill(), model_layer_23_prefill(), model_layer_23_prefill(), model_layer_23_prefill(), model_layer_2_prefill(), model_layer_2_prefill(), model_layer_2_prefill(), model_layer_2_prefill(), model_layer_3_prefill(), model_layer_3_prefill(), model_layer_3_prefill(), model_layer_3_prefill(), model_layer_4_prefill(), model_layer_4_prefill(), model_layer_4_prefill(), model_layer_4_prefill(), model_layer_5_prefill(), model_layer_5_prefill(), model_layer_5_prefill(), model_layer_5_prefill(), model_layer_6_prefill(), model_layer_6_prefill(), model_layer_6_prefill(), model_layer_6_prefill(), model_layer_7_prefill(), model_layer_7_prefill(), model_layer_7_prefill(), model_layer_7_prefill(), model_layer_8_prefill(), model_layer_8_prefill(), model_layer_8_prefill(), model_layer_8_prefill(), model_layer_9_prefill(), model_layer_9_prefill(), model_layer_9_prefill(), model_layer_9_prefill(), qwen2_0_5b_decode_layer_0_prefill(), qwen2_0_5b_decode_layer_0_prefill(), qwen2_0_5b_decode_layer_10_prefill(), qwen2_0_5b_decode_layer_10_prefill(), qwen2_0_5b_decode_layer_11_prefill(), qwen2_0_5b_decode_layer_11_prefill(), qwen2_0_5b_decode_layer_12_prefill(), qwen2_0_5b_decode_layer_12_prefill(), qwen2_0_5b_decode_layer_13_prefill(), qwen2_0_5b_decode_layer_13_prefill(), qwen2_0_5b_decode_layer_14_prefill(), qwen2_0_5b_decode_layer_14_prefill(), qwen2_0_5b_decode_layer_15_prefill(), qwen2_0_5b_decode_layer_15_prefill(), qwen2_0_5b_decode_layer_16_prefill(), qwen2_0_5b_decode_layer_16_prefill(), qwen2_0_5b_decode_layer_17_prefill(), qwen2_0_5b_decode_layer_17_prefill(), qwen2_0_5b_decode_layer_18_prefill(), qwen2_0_5b_decode_layer_18_prefill(), qwen2_0_5b_decode_layer_19_prefill(), qwen2_0_5b_decode_layer_19_prefill(), qwen2_0_5b_decode_layer_1_prefill(), qwen2_0_5b_decode_layer_1_prefill(), qwen2_0_5b_decode_layer_20_prefill(), qwen2_0_5b_decode_layer_20_prefill(), qwen2_0_5b_decode_layer_21_prefill(), qwen2_0_5b_decode_layer_21_prefill(), qwen2_0_5b_decode_layer_22_prefill(), qwen2_0_5b_decode_layer_22_prefill(), qwen2_0_5b_decode_layer_23_prefill(), qwen2_0_5b_decode_layer_23_prefill(), qwen2_0_5b_decode_layer_2_prefill(), qwen2_0_5b_decode_layer_2_prefill(), qwen2_0_5b_decode_layer_3_prefill(), qwen2_0_5b_decode_layer_3_prefill(), qwen2_0_5b_decode_layer_4_prefill(), qwen2_0_5b_decode_layer_4_prefill(), qwen2_0_5b_decode_layer_5_prefill(), qwen2_0_5b_decode_layer_5_prefill(), qwen2_0_5b_decode_layer_6_prefill(), qwen2_0_5b_decode_layer_6_prefill(), qwen2_0_5b_decode_layer_7_prefill(), qwen2_0_5b_decode_layer_7_prefill(), qwen2_0_5b_decode_layer_8_prefill(), qwen2_0_5b_decode_layer_8_prefill(), qwen2_0_5b_decode_layer_9_prefill(), and qwen2_0_5b_decode_layer_9_prefill().
attention_forward_causal_head_major_gqa_flash_strided_f16kv()
void attention_forward_causal_head_major_gqa_flash_strided_f16kv (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
Definition at line 2910 of file attention_kernels.c.
{
    if (!q || !k || !v || !output) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || num_tokens <= 0) {
        return;
    }
    if (kv_stride_tokens < num_tokens) {
        return;
    }
    const float scale = 1.0f / sqrtf((float)head_dim);
    const int T = num_tokens;
    const size_t kv_head_stride = (size_t)kv_stride_tokens * (size_t)aligned_head_dim;
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        const float *k_head = k + (size_t)kv_head * kv_head_stride;
        const float *v_head = v + (size_t)kv_head * kv_head_stride;
        for (int i = 0; i < T; ++i) {
            const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
            float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
            attention_flash_query_causal_exact_f16kv(q_vec, k_head, v_head,
                                                     /*kv_tokens=*/i + 1,
                                                     head_dim, aligned_head_dim,
                                                     scale, out_vec);
        }
    }
}
References attention_flash_query_causal_exact_f16kv(), and qkv_index().
attention_forward_decode_head_major_gqa_flash()
void attention_forward_decode_head_major_gqa_flash (const float * q_token, const float * k_cache, const float * v_cache, float * out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
Flash attention decode (single token attends to KV cache)
Test:
test_flash_attention.py::TestFlashAttention::test_flash_decode
test_kv_cache_attention.py::TestKVCacheAttention::test_flash_decode
test_fused_attention_decode.py::TestFusedAttentionDecode::test_flash_decode
test_attention.py::TestAttentionForward::test_flash_decode
Single query token attends to kv_tokens in KV cache. Uses true flash attention from attention_flash_true.c.
After changes: make test && make llamacpp-parity-full
Definition at line 3203 of file attention_kernels.c.
{
    if (!q_token || !k_cache || !v_cache || !out_token) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || kv_tokens <= 0 || cache_capacity <= 0) {
        return;
    }
    if (kv_tokens > cache_capacity || head_dim <= 0 || aligned_head_dim <= 0) {
        return;
    }
    const float scale = 1.0f / sqrtf((float)head_dim);
    const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        const float *q_head = q_token + (size_t)h * (size_t)aligned_head_dim;
        const float *k_head = k_cache + (size_t)kv_head * head_stride;
        const float *v_head = v_cache + (size_t)kv_head * head_stride;
        float *out_head = out_token + (size_t)h * (size_t)aligned_head_dim;
        attention_flash_decode(out_head,
                               q_head,
                               k_head,
                               v_head,
                               1,
                               kv_tokens,
                               1,
                               aligned_head_dim,
                               scale);
    }
}
References attention_flash_decode().
Referenced by attention_forward_decode_head_major_gqa_flash_sliding(), mega_fused_attention_decode_q5_0(), mega_fused_attention_decode_q5_0_parallel_simd(), model_layer_0_decode(), model_layer_0_decode(), model_layer_0_decode(), model_layer_0_decode(), model_layer_10_decode(), model_layer_10_decode(), model_layer_10_decode(), model_layer_10_decode(), model_layer_11_decode(), model_layer_11_decode(), model_layer_11_decode(), model_layer_11_decode(), model_layer_12_decode(), model_layer_12_decode(), model_layer_12_decode(), model_layer_12_decode(), model_layer_13_decode(), model_layer_13_decode(), model_layer_13_decode(), model_layer_13_decode(), model_layer_14_decode(), model_layer_14_decode(), model_layer_14_decode(), model_layer_14_decode(), model_layer_15_decode(), model_layer_15_decode(), model_layer_15_decode(), model_layer_15_decode(), model_layer_16_decode(), model_layer_16_decode(), model_layer_16_decode(), model_layer_16_decode(), model_layer_17_decode(), model_layer_17_decode(), model_layer_17_decode(), model_layer_17_decode(), model_layer_18_decode(), model_layer_18_decode(), model_layer_18_decode(), model_layer_18_decode(), model_layer_19_decode(), model_layer_19_decode(), model_layer_19_decode(), model_layer_19_decode(), model_layer_1_decode(), model_layer_1_decode(), model_layer_1_decode(), model_layer_1_decode(), model_layer_20_decode(), model_layer_20_decode(), model_layer_20_decode(), model_layer_20_decode(), model_layer_21_decode(), model_layer_21_decode(), model_layer_21_decode(), model_layer_21_decode(), model_layer_22_decode(), model_layer_22_decode(), model_layer_22_decode(), model_layer_22_decode(), model_layer_23_decode(), model_layer_23_decode(), model_layer_23_decode(), model_layer_23_decode(), model_layer_2_decode(), model_layer_2_decode(), model_layer_2_decode(), model_layer_2_decode(), model_layer_3_decode(), model_layer_3_decode(), model_layer_3_decode(), model_layer_3_decode(), model_layer_4_decode(), model_layer_4_decode(), model_layer_4_decode(), model_layer_4_decode(), model_layer_5_decode(), model_layer_5_decode(), model_layer_5_decode(), model_layer_5_decode(), model_layer_6_decode(), model_layer_6_decode(), model_layer_6_decode(), model_layer_6_decode(), model_layer_7_decode(), model_layer_7_decode(), model_layer_7_decode(), model_layer_7_decode(), model_layer_8_decode(), model_layer_8_decode(), model_layer_8_decode(), model_layer_8_decode(), model_layer_9_decode(), model_layer_9_decode(), model_layer_9_decode(), model_layer_9_decode(), qwen2_0_5b_decode_layer_0_decode(), qwen2_0_5b_decode_layer_0_decode(), qwen2_0_5b_decode_layer_10_decode(), qwen2_0_5b_decode_layer_10_decode(), qwen2_0_5b_decode_layer_11_decode(), qwen2_0_5b_decode_layer_11_decode(), qwen2_0_5b_decode_layer_12_decode(), qwen2_0_5b_decode_layer_12_decode(), qwen2_0_5b_decode_layer_13_decode(), qwen2_0_5b_decode_layer_13_decode(), qwen2_0_5b_decode_layer_14_decode(), qwen2_0_5b_decode_layer_14_decode(), qwen2_0_5b_decode_layer_15_decode(), qwen2_0_5b_decode_layer_15_decode(), qwen2_0_5b_decode_layer_16_decode(), qwen2_0_5b_decode_layer_16_decode(), qwen2_0_5b_decode_layer_17_decode(), qwen2_0_5b_decode_layer_17_decode(), qwen2_0_5b_decode_layer_18_decode(), qwen2_0_5b_decode_layer_18_decode(), qwen2_0_5b_decode_layer_19_decode(), qwen2_0_5b_decode_layer_19_decode(), qwen2_0_5b_decode_layer_1_decode(), qwen2_0_5b_decode_layer_1_decode(), qwen2_0_5b_decode_layer_20_decode(), qwen2_0_5b_decode_layer_20_decode(), qwen2_0_5b_decode_layer_21_decode(), qwen2_0_5b_decode_layer_21_decode(), qwen2_0_5b_decode_layer_22_decode(), qwen2_0_5b_decode_layer_22_decode(), qwen2_0_5b_decode_layer_23_decode(), qwen2_0_5b_decode_layer_23_decode(), qwen2_0_5b_decode_layer_2_decode(), qwen2_0_5b_decode_layer_2_decode(), qwen2_0_5b_decode_layer_3_decode(), qwen2_0_5b_decode_layer_3_decode(), qwen2_0_5b_decode_layer_4_decode(), qwen2_0_5b_decode_layer_4_decode(), qwen2_0_5b_decode_layer_5_decode(), qwen2_0_5b_decode_layer_5_decode(), qwen2_0_5b_decode_layer_6_decode(), qwen2_0_5b_decode_layer_6_decode(), qwen2_0_5b_decode_layer_7_decode(), qwen2_0_5b_decode_layer_7_decode(), qwen2_0_5b_decode_layer_8_decode(), qwen2_0_5b_decode_layer_8_decode(), qwen2_0_5b_decode_layer_9_decode(), and qwen2_0_5b_decode_layer_9_decode().
attention_forward_decode_head_major_gqa_flash_f16kv()
void attention_forward_decode_head_major_gqa_flash_f16kv (const float * q_token, const float * k_cache, const float * v_cache, float * out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
Definition at line 3246 of file attention_kernels.c.
{
    if (!q_token || !k_cache || !v_cache || !out_token) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || kv_tokens <= 0 || cache_capacity <= 0) {
        return;
    }
    if (kv_tokens > cache_capacity || head_dim <= 0 || aligned_head_dim <= 0) {
        return;
    }
    const float scale = 1.0f / sqrtf((float)head_dim);
    const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        const float *q_head = q_token + (size_t)h * (size_t)aligned_head_dim;
        const float *k_head = k_cache + (size_t)kv_head * head_stride;
        const float *v_head = v_cache + (size_t)kv_head * head_stride;
        float *out_head = out_token + (size_t)h * (size_t)aligned_head_dim;
        attention_flash_query_causal_exact_f16kv(q_head,
                                                 k_head,
                                                 v_head,
                                                 kv_tokens,
                                                 head_dim,
                                                 aligned_head_dim,
                                                 scale,
                                                 out_head);
    }
}
References attention_flash_query_causal_exact_f16kv().
attention_forward_decode_head_major_gqa_regular()
void attention_forward_decode_head_major_gqa_regular (const float * q_token, const float * k_cache, const float * v_cache, float * out_token, int num_heads, int num_kv_heads, int kv_tokens, int cache_capacity, int head_dim, int aligned_head_dim)
WARNING: This is NOT true flash attention!
This function is named "flash" but implements regular attention with O(n) complexity. It's kept for reference and as a fallback.
TRUE flash attention is implemented in attention_flash_true.c
Test:
test_kv_cache_attention.py::TestKVCacheAttention::test_regular_decode
test_attention.py::TestAttentionForward::test_regular_decode
Regular attention decode (score-matrix version) for fallback.
After changes: make test
Definition at line 3302 of file attention_kernels.c.
{
    if (!q_token || !k_cache || !v_cache || !out_token) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || kv_tokens <= 0 || cache_capacity <= 0) {
        return;
    }
    if (kv_tokens > cache_capacity) {
        return;
    }
    const float scale = 1.0f / sqrtf((float)head_dim);
    const size_t head_stride = (size_t)cache_capacity * (size_t)aligned_head_dim;
    // Select SIMD implementation based on compile-time CPU features
#if defined(__AVX512F__)
    #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx512
#elif defined(__AVX2__)
    #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx2
#elif defined(__AVX__)
    #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal_avx
#else
    #define FLASH_QUERY_IMPL_DECODE attention_flash_query_causal
#endif
#pragma omp parallel for schedule(static) if(num_heads > 1)
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        const float *q_vec = q_token + (size_t)h * (size_t)aligned_head_dim;
        const float *k_head = k_cache + (size_t)kv_head * head_stride;
        const float *v_head = v_cache + (size_t)kv_head * head_stride;
        float *out_vec = out_token + (size_t)h * (size_t)aligned_head_dim;
        FLASH_QUERY_IMPL_DECODE(q_vec, k_head, v_head,
                                 kv_tokens, head_dim, aligned_head_dim,
                                 scale, out_vec);
    }
#undef FLASH_QUERY_IMPL_DECODE
}
References FLASH_QUERY_IMPL_DECODE.
Referenced by ck_attention_flash_decode_wrapper(), ck_layer_forward_rmsnorm_swiglu_decode_fused_attn_impl(), ck_layer_forward_rmsnorm_swiglu_decode_q4_k(), qwen2_0_5b_decode_layer_0_decode(), qwen2_0_5b_decode_layer_0_decode(), qwen2_0_5b_decode_layer_0_decode(), qwen2_0_5b_decode_layer_10_decode(), qwen2_0_5b_decode_layer_10_decode(), qwen2_0_5b_decode_layer_10_decode(), qwen2_0_5b_decode_layer_11_decode(), qwen2_0_5b_decode_layer_11_decode(), qwen2_0_5b_decode_layer_11_decode(), qwen2_0_5b_decode_layer_12_decode(), qwen2_0_5b_decode_layer_12_decode(), qwen2_0_5b_decode_layer_12_decode(), qwen2_0_5b_decode_layer_13_decode(), qwen2_0_5b_decode_layer_13_decode(), qwen2_0_5b_decode_layer_13_decode(), qwen2_0_5b_decode_layer_14_decode(), qwen2_0_5b_decode_layer_14_decode(), qwen2_0_5b_decode_layer_14_decode(), qwen2_0_5b_decode_layer_15_decode(), qwen2_0_5b_decode_layer_15_decode(), qwen2_0_5b_decode_layer_15_decode(), qwen2_0_5b_decode_layer_16_decode(), qwen2_0_5b_decode_layer_16_decode(), qwen2_0_5b_decode_layer_16_decode(), qwen2_0_5b_decode_layer_17_decode(), qwen2_0_5b_decode_layer_17_decode(), qwen2_0_5b_decode_layer_17_decode(), qwen2_0_5b_decode_layer_18_decode(), qwen2_0_5b_decode_layer_18_decode(), qwen2_0_5b_decode_layer_18_decode(), qwen2_0_5b_decode_layer_19_decode(), qwen2_0_5b_decode_layer_19_decode(), qwen2_0_5b_decode_layer_19_decode(), qwen2_0_5b_decode_layer_1_decode(), qwen2_0_5b_decode_layer_1_decode(), qwen2_0_5b_decode_layer_1_decode(), qwen2_0_5b_decode_layer_20_decode(), qwen2_0_5b_decode_layer_20_decode(), qwen2_0_5b_decode_layer_20_decode(), qwen2_0_5b_decode_layer_21_decode(), qwen2_0_5b_decode_layer_21_decode(), qwen2_0_5b_decode_layer_21_decode(), qwen2_0_5b_decode_layer_22_decode(), qwen2_0_5b_decode_layer_22_decode(), qwen2_0_5b_decode_layer_22_decode(), qwen2_0_5b_decode_layer_23_decode(), qwen2_0_5b_decode_layer_23_decode(), qwen2_0_5b_decode_layer_23_decode(), qwen2_0_5b_decode_layer_2_decode(), qwen2_0_5b_decode_layer_2_decode(), qwen2_0_5b_decode_layer_2_decode(), qwen2_0_5b_decode_layer_3_decode(), qwen2_0_5b_decode_layer_3_decode(), qwen2_0_5b_decode_layer_3_decode(), qwen2_0_5b_decode_layer_4_decode(), qwen2_0_5b_decode_layer_4_decode(), qwen2_0_5b_decode_layer_4_decode(), qwen2_0_5b_decode_layer_5_decode(), qwen2_0_5b_decode_layer_5_decode(), qwen2_0_5b_decode_layer_5_decode(), qwen2_0_5b_decode_layer_6_decode(), qwen2_0_5b_decode_layer_6_decode(), qwen2_0_5b_decode_layer_6_decode(), qwen2_0_5b_decode_layer_7_decode(), qwen2_0_5b_decode_layer_7_decode(), qwen2_0_5b_decode_layer_7_decode(), qwen2_0_5b_decode_layer_8_decode(), qwen2_0_5b_decode_layer_8_decode(), qwen2_0_5b_decode_layer_8_decode(), qwen2_0_5b_decode_layer_9_decode(), qwen2_0_5b_decode_layer_9_decode(), and qwen2_0_5b_decode_layer_9_decode().
attention_forward_full_head_major_gqa_exact_strided()
void attention_forward_full_head_major_gqa_exact_strided (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
Definition at line 2951 of file attention_kernels.c.
{
    if (!q || !k || !v || !output) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || num_tokens <= 0) {
        return;
    }
    if (kv_stride_tokens < num_tokens) {
        return;
    }
    const float scale = ck_strict_parity_enabled()
        ? ck_attention_strict_scale_f32(head_dim)
        : 1.0f / sqrtf((float) head_dim);
    const int T = num_tokens;
    const size_t kv_head_stride = (size_t) kv_stride_tokens * (size_t) aligned_head_dim;
    const int debug_layer_id = ck_strict_parity_enabled() ? ck_attention_vec_dump_next_layer_id() : -1;
    float *score_row = (float *) alloca((size_t) T * sizeof(float));
    float *v_cols = (float *) alloca((size_t) head_dim * (size_t) T * sizeof(float));
    for (int h = 0; h < num_heads; ++h) {
        const int kv_head = (int) ((long long) h * (long long) num_kv_heads / (long long) num_heads);
        const float *k_head = k + (size_t) kv_head * kv_head_stride;
        const float *v_head = v + (size_t) kv_head * kv_head_stride;
        float *out_head = output + (size_t) h * (size_t) T * (size_t) aligned_head_dim;
        if (ck_strict_parity_enabled() &&
            ck_attention_head_full_ggml_graph_oracle_regular(
                q + (size_t) h * (size_t) T * (size_t) aligned_head_dim,
                k_head,
                v_head,
                out_head,
                T,
                head_dim,
                aligned_head_dim,
                scale)) {
            ck_attention_trace("regular_graph_oracle", debug_layer_id, h);
            continue;
        }
        for (int d = 0; d < head_dim; ++d) {
            float *dst_col = v_cols + (size_t) d * (size_t) T;
            for (int j = 0; j < T; ++j) {
                dst_col[j] = v_head[(size_t) j * (size_t) aligned_head_dim + (size_t) d];
            }
        }
        for (int i = 0; i < T; ++i) {
            const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
            float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
            attention_query_full_exact_regular(q_vec,
                                               k_head,
                                               v_cols,
                                               T,
                                               head_dim,
                                               aligned_head_dim,
                                               scale,
                                               score_row,
                                               out_vec,
                                               debug_layer_id,
                                               h,
                                               i);
        }
    }
}
References attention_query_full_exact_regular(), ck_attention_head_full_ggml_graph_oracle_regular(), ck_attention_strict_scale_f32(), ck_attention_trace(), ck_attention_vec_dump_next_layer_id(), ck_strict_parity_enabled(), and qkv_index().
attention_forward_full_head_major_gqa_flash()
void attention_forward_full_head_major_gqa_flash (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim)
Definition at line 2844 of file attention_kernels.c.
{
    attention_forward_head_major_gqa_flash_impl(q, k, v, output,
                                                num_heads, num_kv_heads,
                                                num_tokens, head_dim,
                                                aligned_head_dim,
                                                /*kv_stride_tokens=*/num_tokens,
                                                /*causal=*/0);
}
References attention_forward_head_major_gqa_flash_impl().
attention_forward_full_head_major_gqa_flash_strided()
void attention_forward_full_head_major_gqa_flash_strided (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
Definition at line 2891 of file attention_kernels.c.
{
    attention_forward_head_major_gqa_flash_impl(q, k, v, output,
                                                num_heads, num_kv_heads,
                                                num_tokens, head_dim,
                                                aligned_head_dim,
                                                kv_stride_tokens,
                                                /*causal=*/0);
}
References attention_forward_head_major_gqa_flash_impl().
attention_forward_full_head_major_gqa_ggml_strided()
void attention_forward_full_head_major_gqa_ggml_strided (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens)
Definition at line 3026 of file attention_kernels.c.
{
    if (!q || !k || !v || !output) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || num_tokens <= 0) {
        return;
    }
    if (kv_stride_tokens < num_tokens) {
        return;
    }
    const float scale = ck_strict_parity_enabled()
        ? ck_attention_strict_scale_f32(head_dim)
        : 1.0f / sqrtf((float) head_dim);
    const int T = num_tokens;
    const size_t kv_head_stride = (size_t) kv_stride_tokens * (size_t) aligned_head_dim;
    const int debug_layer_id = ck_strict_parity_enabled() ? ck_attention_vec_dump_next_layer_id() : -1;
    float *score_row = (float *) alloca((size_t) T * sizeof(float));
    float *prob_row = (float *) alloca((size_t) T * sizeof(float));
    float *v_cols = (float *) alloca((size_t) head_dim * (size_t) T * sizeof(float));
    ck_ggml_vec_dot_f32_fn dot_fn = NULL;
    ck_ggml_vec_soft_max_f32_fn softmax_fn = NULL;
    ck_ggml_compute_forward_mul_mat_fn mul_mat_fn = NULL;
    ck_ggml_compute_forward_soft_max_fn softmax_compute_fn = NULL;
    if (ck_strict_parity_enabled()) {
        if (ck_attention_full_ggml_graph_oracle_multihead(q,
                                                          k,
                                                          v,
                                                          output,
                                                          num_heads,
                                                          num_kv_heads,
                                                          num_tokens,
                                                          head_dim,
                                                          aligned_head_dim,
                                                          kv_stride_tokens,
                                                          scale)) {
            return;
        }
        dot_fn = ck_resolve_ggml_vec_dot_f32();
        softmax_fn = ck_resolve_ggml_vec_soft_max_f32();
        mul_mat_fn = ck_resolve_ggml_compute_forward_mul_mat();
        softmax_compute_fn = ck_resolve_ggml_compute_forward_soft_max();
    }
    for (int h = 0; h < num_heads; ++h) {
        const int kv_head = (int) ((long long) h * (long long) num_kv_heads / (long long) num_heads);
        const float *k_head = k + (size_t) kv_head * kv_head_stride;
        const float *v_head = v + (size_t) kv_head * kv_head_stride;
        float *out_head = output + (size_t) h * (size_t) T * (size_t) aligned_head_dim;
        if (ck_strict_parity_enabled() &&
            ck_attention_head_full_ggml_graph_oracle_regular(
                q + (size_t) h * (size_t) T * (size_t) aligned_head_dim,
                k_head,
                v_head,
                out_head,
                T,
                head_dim,
                aligned_head_dim,
                scale)) {
            continue;
        }
        for (int d = 0; d < head_dim; ++d) {
            float *dst_col = v_cols + (size_t) d * (size_t) T;
            for (int j = 0; j < T; ++j) {
                dst_col[j] = v_head[(size_t) j * (size_t) aligned_head_dim + (size_t) d];
            }
        }
        if (dot_fn && softmax_fn && ck_attention_ggml_out_graph_enabled()) {
            if (attention_head_full_dyn_ggml_regular_graph_out(
                    q + (size_t) h * (size_t) T * (size_t) aligned_head_dim,
                    k_head,
                    v_cols,
                    T,
                    head_dim,
                    aligned_head_dim,
                    scale,
                    score_row,
                    prob_row,
                    out_head,
                    dot_fn,
                    softmax_fn,
                    debug_layer_id,
                    h)) {
                if (T > 0) {
                    ck_attention_trace("dyn_ggml_regular_graph_out", debug_layer_id, h);
                    ck_attention_trace_float("scale", debug_layer_id, h, scale);
                }
                continue;
            }
        }
        for (int i = 0; i < T; ++i) {
            const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
            float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
            if (dot_fn && softmax_fn) {
                if (i == 0) {
                    ck_attention_trace("dyn_ggml_regular", debug_layer_id, h);
                    ck_attention_trace_float("scale", debug_layer_id, h, scale);
                }
                attention_query_full_dyn_ggml_regular(q_vec,
                                                      k_head,
                                                      v_cols,
                                                      T,
                                                      head_dim,
                                                      aligned_head_dim,
                                                      scale,
                                                      score_row,
                                                      prob_row,
                                                      out_vec,
                                                      dot_fn,
                                                      softmax_fn,
                                                      debug_layer_id,
                                                      h,
                                                      i);
            } else if (dot_fn && mul_mat_fn && softmax_compute_fn) {
                if (i == 0) {
                    ck_attention_trace("ggml_compute_regular", debug_layer_id, h);
                }
                attention_query_full_ggml_compute_regular(q_vec,
                                                          k_head,
                                                          v_cols,
                                                          T,
                                                          head_dim,
                                                          aligned_head_dim,
                                                          scale,
                                                          score_row,
                                                          prob_row,
                                                          out_vec,
                                                          dot_fn,
                                                          mul_mat_fn,
                                                          softmax_compute_fn);
            } else {
                if (i == 0) {
                    ck_attention_trace("ggml_regular", debug_layer_id, h);
                }
                attention_query_full_ggml_regular(q_vec,
                                                  k_head,
                                                  v_cols,
                                                  T,
                                                  head_dim,
                                                  aligned_head_dim,
                                                  scale,
                                                  score_row,
                                                  out_vec,
                                                  debug_layer_id,
                                                  h,
                                                  i);
            }
        }
    }
}
References attention_head_full_dyn_ggml_regular_graph_out(), attention_query_full_dyn_ggml_regular(), attention_query_full_ggml_compute_regular(), attention_query_full_ggml_regular(), ck_attention_full_ggml_graph_oracle_multihead(), ck_attention_ggml_out_graph_enabled(), ck_attention_head_full_ggml_graph_oracle_regular(), ck_attention_strict_scale_f32(), ck_attention_trace(), ck_attention_trace_float(), ck_attention_vec_dump_next_layer_id(), ck_resolve_ggml_compute_forward_mul_mat(), ck_resolve_ggml_compute_forward_soft_max(), ck_resolve_ggml_vec_dot_f32(), ck_resolve_ggml_vec_soft_max_f32(), ck_strict_parity_enabled(), and qkv_index().
attention_forward_full_head_major_gqa_ggml_tiled_strict()
static void attention_forward_full_head_major_gqa_ggml_tiled_strict (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens) static
Definition at line 2617 of file attention_kernels.c.
{
    const float scale = ck_strict_parity_enabled()
        ? ck_attention_strict_scale_f32(head_dim)
        : 1.0f / sqrtf((float) head_dim);
    const int T = num_tokens;
    const size_t kv_head_stride = (size_t) kv_stride_tokens * (size_t) aligned_head_dim;
    float *q_tile = (float *) alloca((size_t) CK_GGML_FA_TILE_Q * (size_t) head_dim * sizeof(float));
    float *k_tile = (float *) alloca((size_t) head_dim * (size_t) CK_GGML_FA_TILE_KV * sizeof(float));
    float *v_tile = (float *) alloca((size_t) CK_GGML_FA_TILE_KV * (size_t) head_dim * sizeof(float));
    float *kq = (float *) alloca((size_t) CK_GGML_FA_TILE_Q * (size_t) CK_GGML_FA_TILE_KV * sizeof(float));
    float *vkq = (float *) alloca((size_t) CK_GGML_FA_TILE_Q * (size_t) head_dim * sizeof(float));
    for (int h = 0; h < num_heads; ++h) {
        const int kv_head = (int) ((long long) h * (long long) num_kv_heads / (long long) num_heads);
        const float *k_head = k + (size_t) kv_head * kv_head_stride;
        const float *v_head = v + (size_t) kv_head * kv_head_stride;
        for (int iq = 0; iq < T; iq += CK_GGML_FA_TILE_Q) {
            const int tile_rows = (T - iq) < CK_GGML_FA_TILE_Q ? (T - iq) : CK_GGML_FA_TILE_Q;
            float sum_row[CK_GGML_FA_TILE_Q];
            float max_row[CK_GGML_FA_TILE_Q];
            for (int tq = 0; tq < CK_GGML_FA_TILE_Q; ++tq) {
                sum_row[tq] = 0.0f;
                max_row[tq] = -INFINITY;
            }
            memset(vkq, 0, (size_t) CK_GGML_FA_TILE_Q * (size_t) head_dim * sizeof(float));
            memset(q_tile, 0, (size_t) CK_GGML_FA_TILE_Q * (size_t) head_dim * sizeof(float));
            memset(v_tile, 0, (size_t) CK_GGML_FA_TILE_KV * (size_t) head_dim * sizeof(float));
            for (int tq = 0; tq < tile_rows; ++tq) {
                const float *q_vec = q + qkv_index(h, iq + tq, 0, T, aligned_head_dim);
                memcpy(q_tile + (size_t) tq * (size_t) head_dim, q_vec, (size_t) head_dim * sizeof(float));
            }
            for (int ik = 0; ik < T; ik += CK_GGML_FA_TILE_KV) {
                const int kv_tile = (T - ik) < CK_GGML_FA_TILE_KV ? (T - ik) : CK_GGML_FA_TILE_KV;
                memset(kq, 0, (size_t) CK_GGML_FA_TILE_Q * (size_t) CK_GGML_FA_TILE_KV * sizeof(float));
                for (int tk = 0; tk < kv_tile; ++tk) {
                    const float *k_vec = k_head + (size_t) (ik + tk) * (size_t) aligned_head_dim;
                    const float *v_vec = v_head + (size_t) (ik + tk) * (size_t) aligned_head_dim;
                    for (int d = 0; d < head_dim; ++d) {
                        k_tile[(size_t) d * (size_t) CK_GGML_FA_TILE_KV + (size_t) tk] = k_vec[d];
                        v_tile[(size_t) tk * (size_t) head_dim + (size_t) d] = v_vec[d];
                    }
                }
                ck_attention_matmul_f32_accum(kq,
                                              q_tile,
                                              k_tile,
                                              CK_GGML_FA_TILE_Q,
                                              head_dim,
                                              CK_GGML_FA_TILE_KV);
                ck_vec_scale_f32_inplace(kq,
                                         CK_GGML_FA_TILE_Q * CK_GGML_FA_TILE_KV,
                                         scale);
                if (kv_tile < CK_GGML_FA_TILE_KV) {
                    for (int tq = 0; tq < CK_GGML_FA_TILE_Q; ++tq) {
                        float *kq_row = kq + (size_t) tq * (size_t) CK_GGML_FA_TILE_KV;
                        for (int tk = kv_tile; tk < CK_GGML_FA_TILE_KV; ++tk) {
                            kq_row[tk] = -INFINITY;
                        }
                    }
                }
                for (int tq = 0; tq < tile_rows; ++tq) {
                    float *kq_row = kq + (size_t) tq * (size_t) CK_GGML_FA_TILE_KV;
                    const float tile_max = ck_vec_max_f32_contig(kq_row, CK_GGML_FA_TILE_KV);
                    if (tile_max == -INFINITY) {
                        memset(kq_row, 0, (size_t) CK_GGML_FA_TILE_KV * sizeof(float));
                        continue;
                    }
                    const float old_max = max_row[tq];
                    const float new_max = old_max > tile_max ? old_max : tile_max;
                    if (new_max > old_max) {
                        const float ms = expf(old_max - new_max);
                        ck_vec_scale_f32_inplace(vkq + (size_t) tq * (size_t) head_dim,
                                                 head_dim,
                                                 ms);
                        sum_row[tq] *= ms;
                    }
                    max_row[tq] = new_max;
                    sum_row[tq] += (float) ck_ggml_vec_soft_max_row(CK_GGML_FA_TILE_KV, kq_row, kq_row, new_max);
                }
                ck_attention_matmul_f32_accum(vkq,
                                              kq,
                                              v_tile,
                                              CK_GGML_FA_TILE_Q,
                                              CK_GGML_FA_TILE_KV,
                                              head_dim);
            }
            for (int tq = 0; tq < tile_rows; ++tq) {
                float *out_vec = output + qkv_index(h, iq + tq, 0, T, aligned_head_dim);
                const float inv_sum = sum_row[tq] == 0.0f ? 0.0f : (1.0f / sum_row[tq]);
                for (int d = 0; d < head_dim; ++d) {
                    out_vec[d] = vkq[(size_t) tq * (size_t) head_dim + (size_t) d] * inv_sum;
                }
                for (int d = head_dim; d < aligned_head_dim; ++d) {
                    out_vec[d] = 0.0f;
                }
            }
        }
    }
}
References ck_attention_matmul_f32_accum(), ck_attention_strict_scale_f32(), CK_GGML_FA_TILE_KV, CK_GGML_FA_TILE_Q, ck_ggml_vec_soft_max_row(), ck_strict_parity_enabled(), ck_vec_max_f32_contig(), ck_vec_scale_f32_inplace(), and qkv_index().
attention_forward_head_major_gqa_flash_impl()
static void attention_forward_head_major_gqa_flash_impl (const float * q, const float * k, const float * v, float * output, int num_heads, int num_kv_heads, int num_tokens, int head_dim, int aligned_head_dim, int kv_stride_tokens, int causal) static
Flash attention forward for GQA (prefill, no score materialization)
Test:
test_flash_attention.py::TestFlashAttention::test_flash_forward
test_flash_attention.py::TestFlashAttention::test_flash_vs_score_matrix
test_flash_attention.py::TestFlashAttention::test_flash_gqa
test_attention.py::TestAttentionForward::test_flash_forward
Online softmax with streaming KV. O(N) memory instead of O(N^2). For prefill: all tokens attend to previous tokens.
After changes: make test && make llamacpp-parity-full
Definition at line 2751 of file attention_kernels.c.
{
    if (!q || !k || !v || !output) {
        return;
    }
    if (num_heads <= 0 || num_kv_heads <= 0 || num_tokens <= 0) {
        return;
    }
    if (kv_stride_tokens < num_tokens) {
        return;
    }
    const float scale = 1.0f / sqrtf((float)head_dim);
    const int T = num_tokens;
    const size_t kv_head_stride = (size_t)kv_stride_tokens * (size_t)aligned_head_dim;
    if (ck_strict_parity_enabled()) {
        for (int h = 0; h < num_heads; ++h) {
            int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
            const float *k_head = k + (size_t)kv_head * kv_head_stride;
            const float *v_head = v + (size_t)kv_head * kv_head_stride;
            for (int i = 0; i < T; ++i) {
                const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
                float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
                const int kv_tokens = causal ? (i + 1) : T;
                attention_flash_query_causal_exact(q_vec, k_head, v_head,
                                                   kv_tokens,
                                                   head_dim, aligned_head_dim,
                                                   scale, out_vec);
            }
        }
        return;
    }
    // Select SIMD implementation based on compile-time CPU features
#if defined(__AVX512F__)
    #define FLASH_QUERY_IMPL attention_flash_query_causal_avx512
#elif defined(__AVX2__)
    #define FLASH_QUERY_IMPL attention_flash_query_causal_avx2
#elif defined(__AVX__)
    #define FLASH_QUERY_IMPL attention_flash_query_causal_avx
#else
    #define FLASH_QUERY_IMPL attention_flash_query_causal
#endif
    for (int h = 0; h < num_heads; ++h) {
        int kv_head = (int)((long long)h * (long long)num_kv_heads / (long long)num_heads);
        const float *k_head = k + (size_t)kv_head * kv_head_stride;
        const float *v_head = v + (size_t)kv_head * kv_head_stride;
        for (int i = 0; i < T; ++i) {
            const float *q_vec = q + qkv_index(h, i, 0, T, aligned_head_dim);
            float *out_vec = output + qkv_index(h, i, 0, T, aligned_head_dim);
            const int kv_tokens = causal ? (i + 1) : T;
            FLASH_QUERY_IMPL(q_vec, k_head, v_head,
                             kv_tokens,
                             head_dim, aligned_head_dim,
                             scale, out_vec);
        }
    }
#undef FLASH_QUERY_IMPL
}
References attention_flash_query_causal_exact(), ck_strict_parity_enabled(), FLASH_QUERY_IMPL, and qkv_index().
Referenced by attention_forward_causal_head_major_gqa_flash(), attention_forward_causal_head_major_gqa_flash_strided(), attention_forward_full_head_major_gqa_flash(), and attention_forward_full_head_major_gqa_flash_strided().
attention_head_full_dyn_ggml_regular_graph_out()
static int attention_head_full_dyn_ggml_regular_graph_out (const float * q_head, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * prob_row, float * out_head, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, int layer_id, int head_id) static
Definition at line 1972 of file attention_kernels.c.
{
    if (!q_head || !k_head || !v_cols || !out_head || !dot_fn || !softmax_fn ||
        kv_tokens <= 0 || head_dim <= 0 || aligned_head_dim < head_dim) {
        return 0;
    }
    enum { CK_STRICT_OUT_BLOCK = 64 };
    float *prob_block = (float *) alloca((size_t) CK_STRICT_OUT_BLOCK * (size_t) kv_tokens * sizeof(float));
    float *out_block = (float *) alloca((size_t) CK_STRICT_OUT_BLOCK * (size_t) head_dim * sizeof(float));
    float *raw_dump = (float *) alloca((size_t) kv_tokens * sizeof(float));
    for (int q0 = 0; q0 < kv_tokens; q0 += CK_STRICT_OUT_BLOCK) {
        const int qn = (q0 + CK_STRICT_OUT_BLOCK <= kv_tokens) ? CK_STRICT_OUT_BLOCK : (kv_tokens - q0);
        float *block_probs = prob_block;
        float *block_out = out_block;
        int have_raw_dump = 0;
        int dump_query = -1;
        int dump_qi = -1;
        for (int qi = 0; qi < qn; ++qi) {
            const int query_id = q0 + qi;
            const float *q_vec = q_head + (size_t) query_id * (size_t) aligned_head_dim;
            float *prob_col = block_probs + (size_t) qi * (size_t) kv_tokens;
            for (int j = 0; j < kv_tokens; ++j) {
                const float *k_vec = k_head + (size_t) j * (size_t) aligned_head_dim;
                float dot = 0.0f;
                dot_fn(head_dim, &dot, 0, q_vec, 0, k_vec, 0, 1);
                score_row[j] = dot;
            }
            if (ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
                memcpy(raw_dump, score_row, (size_t) kv_tokens * sizeof(float));
                have_raw_dump = 1;
                dump_query = query_id;
                dump_qi = qi;
            }
            memcpy(prob_row, score_row, (size_t) kv_tokens * sizeof(float));
            ck_vec_scale_f32_inplace(prob_row, kv_tokens, scale);
            const float max_score = ck_vec_max_f32_contig(prob_row, kv_tokens);
            const double sum = softmax_fn(kv_tokens, prob_col, prob_row, max_score);
            if (sum > 0.0) {
                const float inv_sum = (float) (1.0 / sum);
                ck_vec_scale_f32_inplace(prob_col, kv_tokens, inv_sum);
            } else {
                memset(prob_col, 0, (size_t) kv_tokens * sizeof(float));
            }
        }
        if (!attention_out_mul_mat_graph_block(v_cols, block_probs, kv_tokens, head_dim, qn, block_out)) {
            return 0;
        }
        for (int qi = 0; qi < qn; ++qi) {
            float *dst = out_head + (size_t) (q0 + qi) * (size_t) aligned_head_dim;
            const float *src = block_out + (size_t) qi * (size_t) head_dim;
            memcpy(dst, src, (size_t) head_dim * sizeof(float));
            for (int d = head_dim; d < aligned_head_dim; ++d) {
                dst[d] = 0.0f;
            }
        }
        if (have_raw_dump && dump_qi >= 0) {
            ck_attention_vec_dump_selected_query(raw_dump,
                                                 block_probs + (size_t) dump_qi * (size_t) kv_tokens,
                                                 block_out + (size_t) dump_qi * (size_t) head_dim,
                                                 v_cols,
                                                 kv_tokens,
                                                 head_dim,
                                                 layer_id,
                                                 head_id,
                                                 dump_query);
        }
    }
    return 1;
}
References attention_out_mul_mat_graph_block(), ck_attention_vec_dump_selected_query(), ck_attention_vec_dump_should_emit(), ck_vec_max_f32_contig(), and ck_vec_scale_f32_inplace().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
attention_out_mul_mat_graph_block()
static int attention_out_mul_mat_graph_block (const float * v_cols, const float * prob_block, int kv_tokens, int head_dim, int query_block, float * out_block) static
Definition at line 1903 of file attention_kernels.c.
{
    ck_ggml_cpu_init_fn ggml_cpu_init_fn = ck_resolve_ggml_cpu_init();
    ck_ggml_init_fn ggml_init_fn = ck_resolve_ggml_init();
    ck_ggml_free_fn ggml_free_fn = ck_resolve_ggml_free();
    ck_ggml_new_tensor_2d_fn ggml_new_tensor_2d_fn = ck_resolve_ggml_new_tensor_2d();
    ck_ggml_mul_mat_graph_fn ggml_mul_mat_fn = ck_resolve_ggml_mul_mat_graph();
    ck_ggml_new_graph_fn ggml_new_graph_fn = ck_resolve_ggml_new_graph();
    ck_ggml_build_forward_expand_fn ggml_build_forward_expand_fn = ck_resolve_ggml_build_forward_expand();
    ck_ggml_graph_compute_with_ctx_fn ggml_graph_compute_with_ctx_fn = ck_resolve_ggml_graph_compute_with_ctx();
    ck_ggml_set_input_fn ggml_set_input_fn = ck_resolve_ggml_set_input();
    if (!ggml_cpu_init_fn || !ggml_init_fn || !ggml_free_fn ||
        !ggml_new_tensor_2d_fn || !ggml_mul_mat_fn || !ggml_new_graph_fn ||
        !ggml_build_forward_expand_fn || !ggml_graph_compute_with_ctx_fn ||
        !ggml_set_input_fn || !v_cols || !prob_block || !out_block ||
        kv_tokens <= 0 || head_dim <= 0 || query_block <= 0) {
        return 0;
    }
    ggml_cpu_init_fn();
    const size_t out_bytes = (size_t) head_dim * (size_t) query_block * sizeof(float);
    const size_t mem_size = (size_t) 8 * 1024 * 1024 + out_bytes + (size_t) 512 * 1024;
    struct ggml_init_params params = {
        .mem_size = mem_size,
        .mem_buffer = NULL,
        .no_alloc = false,
    };
    struct ggml_context *ctx = ggml_init_fn(params);
    if (!ctx) {
        return 0;
    }
    int ok = 0;
    struct ggml_tensor *v_tensor = ggml_new_tensor_2d_fn(ctx, GGML_TYPE_F32, kv_tokens, head_dim);
    struct ggml_tensor *prob_tensor = ggml_new_tensor_2d_fn(ctx, GGML_TYPE_F32, kv_tokens, query_block);
    if (!v_tensor || !prob_tensor) {
        ggml_free_fn(ctx);
        return 0;
    }
    v_tensor->data = (void *) v_cols;
    prob_tensor->data = (void *) prob_block;
    ggml_set_input_fn(v_tensor);
    ggml_set_input_fn(prob_tensor);
    struct ggml_tensor *out_tensor = ggml_mul_mat_fn(ctx, v_tensor, prob_tensor);
    struct ggml_cgraph *gf = out_tensor ? ggml_new_graph_fn(ctx) : NULL;
    if (!out_tensor || !gf) {
        ggml_free_fn(ctx);
        return 0;
    }
    ggml_build_forward_expand_fn(gf, out_tensor);
    if (ggml_graph_compute_with_ctx_fn(ctx, gf, 1) == GGML_STATUS_SUCCESS) {
        memcpy(out_block, out_tensor->data, out_bytes);
        ok = 1;
    }
    ggml_free_fn(ctx);
    return ok;
}
References ck_resolve_ggml_build_forward_expand(), ck_resolve_ggml_cpu_init(), ck_resolve_ggml_free(), ck_resolve_ggml_graph_compute_with_ctx(), ck_resolve_ggml_init(), ck_resolve_ggml_mul_mat_graph(), ck_resolve_ggml_new_graph(), ck_resolve_ggml_new_tensor_2d(), and ck_resolve_ggml_set_input().
Referenced by attention_head_full_dyn_ggml_regular_graph_out().
attention_query_full_dyn_ggml_regular()
static void attention_query_full_dyn_ggml_regular (const float * q_vec, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * prob_row, float * out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, int layer_id, int head_id, int query_id) static
Definition at line 1832 of file attention_kernels.c.
{
    if (kv_tokens <= 0 || !dot_fn || !softmax_fn || !score_row || !prob_row) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t) j * (size_t) aligned_head_dim;
        float dot = 0.0f;
        dot_fn(head_dim, &dot, 0, q_vec, 0, k_vec, 0, 1);
        score_row[j] = dot;
    }
    float *raw_dump = NULL;
    if (ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
        raw_dump = (float *) alloca((size_t) kv_tokens * sizeof(float));
        memcpy(raw_dump, score_row, (size_t) kv_tokens * sizeof(float));
    }
    // Mirror ggml_compute_forward_soft_max_f32:
    // copy raw scores to scratch, scale the scratch buffer, compute the max from
    // that scaled buffer, then emit exp/logits into a separate output buffer.
    memcpy(prob_row, score_row, (size_t) kv_tokens * sizeof(float));
    ck_vec_scale_f32_inplace(prob_row, kv_tokens, scale);
    const float max_score = ck_vec_max_f32_contig(prob_row, kv_tokens);
    const double sum = softmax_fn(kv_tokens, score_row, prob_row, max_score);
    if (sum > 0.0) {
        const float inv_sum = (float) (1.0 / sum);
        ck_vec_scale_f32_inplace(score_row, kv_tokens, inv_sum);
        const int reverse_out_dot = ck_attention_reverse_out_dot_enabled();
        for (int d = 0; d < head_dim; ++d) {
            const float *v_col = v_cols + (size_t) d * (size_t) kv_tokens;
            if (reverse_out_dot) {
                out_vec[d] = ck_vec_dot_f32_reverse_strict(score_row, v_col, kv_tokens);
            } else {
                float dot = 0.0f;
                dot_fn(kv_tokens, &dot, 0, score_row, 0, v_col, 0, 1);
                out_vec[d] = dot;
            }
        }
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    if (raw_dump) {
        ck_attention_vec_dump_selected_query(raw_dump, score_row, out_vec, v_cols, kv_tokens, head_dim,
                                             layer_id, head_id, query_id);
    }
}
References ck_attention_reverse_out_dot_enabled(), ck_attention_vec_dump_selected_query(), ck_attention_vec_dump_should_emit(), ck_vec_dot_f32_reverse_strict(), ck_vec_max_f32_contig(), and ck_vec_scale_f32_inplace().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
attention_query_full_dyn_ggml_regular_matmul_out()
static void attention_query_full_dyn_ggml_regular_matmul_out (const float * q_vec, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * prob_row, float * out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_vec_soft_max_f32_fn softmax_fn, ck_ggml_compute_forward_mul_mat_fn mul_mat_fn, int layer_id, int head_id, int query_id) static
Definition at line 2064 of file attention_kernels.c.
{
    if (kv_tokens <= 0 || !dot_fn || !softmax_fn || !mul_mat_fn || !score_row || !prob_row) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t) j * (size_t) aligned_head_dim;
        float dot = 0.0f;
        dot_fn(head_dim, &dot, 0, q_vec, 0, k_vec, 0, 1);
        score_row[j] = dot;
    }
    float *raw_dump = NULL;
    if (ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
        raw_dump = (float *) alloca((size_t) kv_tokens * sizeof(float));
        memcpy(raw_dump, score_row, (size_t) kv_tokens * sizeof(float));
    }
    memcpy(prob_row, score_row, (size_t) kv_tokens * sizeof(float));
    ck_vec_scale_f32_inplace(prob_row, kv_tokens, scale);
    const float max_score = ck_vec_max_f32_contig(prob_row, kv_tokens);
    const double sum = softmax_fn(kv_tokens, score_row, prob_row, max_score);
    if (sum > 0.0) {
        const float inv_sum = (float) (1.0 / sum);
        ck_vec_scale_f32_inplace(score_row, kv_tokens, inv_sum);
        const size_t prob_row_bytes = (size_t) kv_tokens * sizeof(float);
        const size_t out_row_bytes = (size_t) head_dim * sizeof(float);
        struct ggml_tensor v_tensor;
        struct ggml_tensor prob_tensor;
        struct ggml_tensor out_tensor;
        ck_ggml_init_tensor_f32(&v_tensor,
                                kv_tokens, head_dim, 1, 1,
                                sizeof(float),
                                prob_row_bytes,
                                prob_row_bytes * (size_t) head_dim,
                                prob_row_bytes * (size_t) head_dim,
                                (void *) v_cols);
        ck_ggml_init_tensor_f32(&prob_tensor,
                                kv_tokens, 1, 1, 1,
                                sizeof(float),
                                prob_row_bytes,
                                prob_row_bytes,
                                prob_row_bytes,
                                score_row);
        ck_ggml_init_tensor_f32(&out_tensor,
                                head_dim, 1, 1, 1,
                                sizeof(float),
                                out_row_bytes,
                                out_row_bytes,
                                out_row_bytes,
                                out_vec);
        out_tensor.src[0] = &v_tensor;
        out_tensor.src[1] = &prob_tensor;
        memset(out_vec, 0, (size_t) head_dim * sizeof(float));
        struct ggml_compute_params mul_params = {
            .ith = 0,
            .nth = 1,
            .wsize = 0,
            .wdata = NULL,
            .threadpool = NULL,
            .use_ref = false,
        };
        mul_mat_fn(&mul_params, &out_tensor);
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    if (raw_dump) {
        ck_attention_vec_dump_selected_query(raw_dump, score_row, out_vec, v_cols, kv_tokens, head_dim,
                                             layer_id, head_id, query_id);
    }
}
References ck_attention_vec_dump_selected_query(), ck_attention_vec_dump_should_emit(), ck_ggml_init_tensor_f32(), ck_vec_max_f32_contig(), and ck_vec_scale_f32_inplace().
attention_query_full_exact_regular()
static void attention_query_full_exact_regular (const float * q_vec, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * out_vec, int layer_id, int head_id, int query_id) static
Definition at line 1703 of file attention_kernels.c.
{
    if (kv_tokens <= 0) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t) j * (size_t) aligned_head_dim;
        score_row[j] = ck_vec_dot_f32_strict(q_vec, k_vec, head_dim);
    }
    float *raw_dump = NULL;
    if (ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
        raw_dump = (float *) alloca((size_t) kv_tokens * sizeof(float));
        memcpy(raw_dump, score_row, (size_t) kv_tokens * sizeof(float));
    }
    float max_score = -INFINITY;
    for (int j = 0; j < kv_tokens; ++j) {
        const float score = score_row[j] * scale;
        score_row[j] = score;
        if (score > max_score) {
            max_score = score;
        }
    }
    double sum = 0.0;
    for (int j = 0; j < kv_tokens; ++j) {
        const float w = expf(score_row[j] - max_score);
        score_row[j] = w;
        volatile double next = sum + (double) w;
        sum = next;
    }
    if (sum > 0.0) {
        const float inv_sum = (float) (1.0 / sum);
        for (int j = 0; j < kv_tokens; ++j) {
            score_row[j] *= inv_sum;
        }
        for (int d = 0; d < head_dim; ++d) {
            const float *v_col = v_cols + (size_t) d * (size_t) kv_tokens;
            const float dot = ck_vec_dot_f32x_f32_to_f32_via_f64(score_row, v_col, kv_tokens);
            out_vec[d] = dot;
        }
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    if (raw_dump) {
        ck_attention_vec_dump_selected_query(raw_dump, score_row, out_vec, v_cols, kv_tokens, head_dim,
                                             layer_id, head_id, query_id);
    }
}
References ck_attention_vec_dump_selected_query(), ck_attention_vec_dump_should_emit(), ck_vec_dot_f32_strict(), ck_vec_dot_f32x_f32_to_f32_via_f64(), and score.
Referenced by attention_forward_full_head_major_gqa_exact_strided().
attention_query_full_ggml_compute_regular()
static void attention_query_full_ggml_compute_regular (const float * q_vec, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * prob_row, float * out_vec, ck_ggml_vec_dot_f32_fn dot_fn, ck_ggml_compute_forward_mul_mat_fn mul_mat_fn, ck_ggml_compute_forward_soft_max_fn softmax_compute_fn) static
Definition at line 2164 of file attention_kernels.c.
{
    if (kv_tokens <= 0 || !dot_fn || !mul_mat_fn || !softmax_compute_fn) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    const size_t k_row_bytes = (size_t) aligned_head_dim * sizeof(float);
    const size_t q_row_bytes = (size_t) head_dim * sizeof(float);
    const size_t score_row_bytes = (size_t) kv_tokens * sizeof(float);
    const size_t softmax_work_elems = (size_t) kv_tokens + 16u;
    float *softmax_work = (float *) alloca(softmax_work_elems * sizeof(float));
    struct ggml_tensor k_tensor;
    struct ggml_tensor q_tensor;
    struct ggml_tensor score_tensor;
    struct ggml_tensor soft_tensor;
    ck_ggml_init_tensor_f32(&k_tensor,
                            head_dim, kv_tokens, 1, 1,
                            sizeof(float),
                            k_row_bytes,
                            k_row_bytes * (size_t) kv_tokens,
                            k_row_bytes * (size_t) kv_tokens,
                            (void *) k_head);
    ck_ggml_init_tensor_f32(&q_tensor,
                            head_dim, 1, 1, 1,
                            sizeof(float),
                            q_row_bytes,
                            q_row_bytes,
                            q_row_bytes,
                            (void *) q_vec);
    ck_ggml_init_tensor_f32(&score_tensor,
                            kv_tokens, 1, 1, 1,
                            sizeof(float),
                            score_row_bytes,
                            score_row_bytes,
                            score_row_bytes,
                            score_row);
    score_tensor.src[0] = &k_tensor;
    score_tensor.src[1] = &q_tensor;
    struct ggml_compute_params mul_params = {
        .ith = 0,
        .nth = 1,
        .wsize = 0,
        .wdata = NULL,
        .threadpool = NULL,
        .use_ref = false,
    };
    mul_mat_fn(&mul_params, &score_tensor);
    ck_ggml_init_tensor_f32(&soft_tensor,
                            kv_tokens, 1, 1, 1,
                            sizeof(float),
                            score_row_bytes,
                            score_row_bytes,
                            score_row_bytes,
                            prob_row);
    soft_tensor.src[0] = &score_tensor;
    {
        const float max_bias = 0.0f;
        memcpy((char *) soft_tensor.op_params + 0, &scale, sizeof(float));
        memcpy((char *) soft_tensor.op_params + sizeof(float), &max_bias, sizeof(float));
    }
    struct ggml_compute_params soft_params = {
        .ith = 0,
        .nth = 1,
        .wsize = softmax_work_elems * sizeof(float),
        .wdata = softmax_work,
        .threadpool = NULL,
        .use_ref = false,
    };
    softmax_compute_fn(&soft_params, &soft_tensor);
    for (int d = 0; d < head_dim; ++d) {
        const float *v_col = v_cols + (size_t) d * (size_t) kv_tokens;
        float dot = 0.0f;
        dot_fn(kv_tokens, &dot, 0, prob_row, 0, v_col, 0, 1);
        out_vec[d] = dot;
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
}
References ck_ggml_init_tensor_f32().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
attention_query_full_ggml_regular()
static void attention_query_full_ggml_regular (const float * q_vec, const float * k_head, const float * v_cols, int kv_tokens, int head_dim, int aligned_head_dim, float scale, float * score_row, float * out_vec, int layer_id, int head_id, int query_id) static
Definition at line 1775 of file attention_kernels.c.
{
    if (kv_tokens <= 0) {
        for (int d = 0; d < aligned_head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
        return;
    }
    for (int j = 0; j < kv_tokens; ++j) {
        const float *k_vec = k_head + (size_t) j * (size_t) aligned_head_dim;
        score_row[j] = ck_ggml_vec_dot_f32_contig(q_vec, k_vec, head_dim);
    }
    float *raw_dump = NULL;
    if (ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
        raw_dump = (float *) alloca((size_t) kv_tokens * sizeof(float));
        memcpy(raw_dump, score_row, (size_t) kv_tokens * sizeof(float));
    }
    float *logit_row = (float *) alloca((size_t) kv_tokens * sizeof(float));
    memcpy(logit_row, score_row, (size_t) kv_tokens * sizeof(float));
    ck_vec_scale_f32_inplace(logit_row, kv_tokens, scale);
    const float max_score = ck_vec_max_f32_contig(logit_row, kv_tokens);
    const double sum = ck_ggml_vec_soft_max_row(kv_tokens, score_row, logit_row, max_score);
    if (sum > 0.0) {
        const float inv_sum = (float) (1.0 / sum);
        ck_vec_scale_f32_inplace(score_row, kv_tokens, inv_sum);
        for (int d = 0; d < head_dim; ++d) {
            const float *v_col = v_cols + (size_t) d * (size_t) kv_tokens;
            out_vec[d] = ck_ggml_vec_dot_f32_contig(score_row, v_col, kv_tokens);
        }
    } else {
        for (int d = 0; d < head_dim; ++d) {
            out_vec[d] = 0.0f;
        }
    }
    for (int d = head_dim; d < aligned_head_dim; ++d) {
        out_vec[d] = 0.0f;
    }
    if (raw_dump) {
        ck_attention_vec_dump_selected_query(raw_dump, score_row, out_vec, v_cols, kv_tokens, head_dim,
                                             layer_id, head_id, query_id);
    }
}
References ck_attention_vec_dump_selected_query(), ck_attention_vec_dump_should_emit(), ck_ggml_vec_dot_f32_contig(), ck_ggml_vec_soft_max_row(), ck_vec_max_f32_contig(), and ck_vec_scale_f32_inplace().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_attention_ggml_out_graph_enabled()
static int ck_attention_ggml_out_graph_enabled (void) static
Definition at line 149 of file attention_kernels.c.
{
    const char *v = getenv("CK_STRICT_ATTN_GGML_OUT_GRAPH");
    return v && v[0] && strcmp(v, "0") != 0;
}
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_attention_matmul_f32_accum()
static void ck_attention_matmul_f32_accum (float * c, const float * a, const float * b, int m, int k, int n) static
Definition at line 2596 of file attention_kernels.c.
{
    for (int i = 0; i < m; ++i) {
        float *c_row = c + (size_t) i * (size_t) n;
        const float *a_row = a + (size_t) i * (size_t) k;
        for (int kk = 0; kk < k; ++kk) {
            const float a_ik = a_row[kk];
            const float *b_row = b + (size_t) kk * (size_t) n;
            for (int j = 0; j < n; ++j) {
                c_row[j] += a_ik * b_row[j];
            }
        }
    }
}
Referenced by attention_forward_full_head_major_gqa_ggml_tiled_strict().
ck_attention_reverse_out_dot_enabled()
static int ck_attention_reverse_out_dot_enabled (void) static
Definition at line 143 of file attention_kernels.c.
{
    const char *v = getenv("CK_STRICT_ATTN_REVERSE_OUT_DOT");
    return v && v[0] && strcmp(v, "0") != 0;
}
Referenced by attention_query_full_dyn_ggml_regular().
ck_attention_strict_scale_f32()
static float ck_attention_strict_scale_f32 (int head_dim) static
Definition at line 760 of file attention_kernels.c.
{
    // Keep strict parity on the precise libm sqrtf path. icx -O3 on AVX2 was
    // lowering 1/sqrtf(d) to a slightly smaller effective scale, which is
    // enough to move layer-0 vision softmax by ~2e-7 and snowball later.
    volatile float hd = (float) head_dim;
    float (*sqrtf_fn)(float) = sqrtf;
    volatile float root = sqrtf_fn(hd);
    volatile float one = 1.0f;
    volatile float scale = one / root;
    return scale;
}
Referenced by attention_forward_full_head_major_gqa_exact_strided(), attention_forward_full_head_major_gqa_ggml_strided(), and attention_forward_full_head_major_gqa_ggml_tiled_strict().
ck_attention_trace()
static void ck_attention_trace (const char * branch, int layer_id, int head_id) static
Definition at line 245 of file attention_kernels.c.
{
    const char *enabled = getenv("CK_STRICT_ATTN_TRACE");
    const char *dir = getenv("CK_PARITY_DIR");
    if (!enabled || !enabled[0] || strcmp(enabled, "0") == 0 || !dir || !dir[0] || !branch || !branch[0]) {
        return;
    }
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, "strict_trace.txt");
    FILE *f = fopen(path, "a");
    if (!f) {
        return;
    }
    fprintf(f, "layer=%d head=%d branch=%s\n", layer_id, head_id, branch);
    fclose(f);
}
Referenced by attention_forward_full_head_major_gqa_exact_strided(), and attention_forward_full_head_major_gqa_ggml_strided().
ck_attention_trace_float()
static void ck_attention_trace_float (const char * tag, int layer_id, int head_id, float value) static
Definition at line 283 of file attention_kernels.c.
{
    const char *enabled = getenv("CK_STRICT_ATTN_TRACE");
    const char *dir = getenv("CK_PARITY_DIR");
    if (!enabled || !enabled[0] || strcmp(enabled, "0") == 0 || !dir || !dir[0] || !tag || !tag[0]) {
        return;
    }
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, "strict_trace.txt");
    FILE *f = fopen(path, "a");
    if (!f) {
        return;
    }
    fprintf(f, "layer=%d head=%d tag=%s float=%.17g\n", layer_id, head_id, tag, (double) value);
    fclose(f);
}
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_attention_trace_query()
static void ck_attention_trace_query (const char * tag, int layer_id, int head_id, int query_id, int value) static
Definition at line 262 of file attention_kernels.c.
{
    const char *enabled = getenv("CK_STRICT_ATTN_TRACE");
    const char *dir = getenv("CK_PARITY_DIR");
    if (!enabled || !enabled[0] || strcmp(enabled, "0") == 0 || !dir || !dir[0] || !tag || !tag[0]) {
        return;
    }
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, "strict_trace.txt");
    FILE *f = fopen(path, "a");
    if (!f) {
        return;
    }
    fprintf(f, "layer=%d head=%d query=%d tag=%s value=%d\n", layer_id, head_id, query_id, tag, value);
    fclose(f);
}
Referenced by ck_attention_vec_dump_selected_query(), and ck_attention_vec_dump_should_emit().
ck_attention_vec_dump_enabled()
static int ck_attention_vec_dump_enabled (void) static
Definition at line 131 of file attention_kernels.c.
{
    const char *v = getenv("CK_STRICT_ATTN_VEC_DUMP");
    return v && v[0] && strcmp(v, "0") != 0;
}
Referenced by ck_attention_vec_dump_should_emit().
ck_attention_vec_dump_next_layer_id()
static int ck_attention_vec_dump_next_layer_id (void) static
Definition at line 203 of file attention_kernels.c.
{
    const int layer_id = ck_attention_vec_dump_layer_seq;
    ck_attention_vec_dump_layer_seq += 1;
    return layer_id;
}
References ck_attention_vec_dump_layer_seq.
Referenced by attention_forward_full_head_major_gqa_exact_strided(), and attention_forward_full_head_major_gqa_ggml_strided().
ck_attention_vec_dump_parse_env_int()
static int ck_attention_vec_dump_parse_env_int (const char * name, int * out) static
Definition at line 155 of file attention_kernels.c.
{
    const char *v = getenv(name);
    if (!v || !v[0]) {
        return 0;
    }
    char *end = NULL;
    long parsed = strtol(v, &end, 10);
    if (end == v || (end && *end != '\0') || parsed < 0 || parsed > INT32_MAX) {
        return 0;
    }
    if (out) {
        *out = (int) parsed;
    }
    return 1;
}
References end.
Referenced by ck_attention_vec_dump_should_emit().
ck_attention_vec_dump_selected_query()
static void ck_attention_vec_dump_selected_query (const float * raw_scores, const float * probs, const float * out_vec, const float * v_cols, int kv_tokens, int head_dim, int layer_id, int head_id, int query_id) static
Definition at line 303 of file attention_kernels.c.
{
    if (!ck_attention_vec_dump_should_emit(layer_id, head_id, query_id)) {
        return;
    }
    ck_attention_trace_query("vec_dump_selected_query", layer_id, head_id, query_id, 1);
    char name[32];
    snprintf(name, sizeof(name), "kq_scores_h%d_q%d", head_id, query_id);
    ck_attention_vec_dump_tensor(name, layer_id, query_id, raw_scores, (size_t) kv_tokens);
    snprintf(name, sizeof(name), "kq_soft_h%d_q%d", head_id, query_id);
    ck_attention_vec_dump_tensor(name, layer_id, query_id, probs, (size_t) kv_tokens);
    snprintf(name, sizeof(name), "kqv_out_h%d_q%d", head_id, query_id);
    ck_attention_vec_dump_tensor(name, layer_id, query_id, out_vec, (size_t) head_dim);
    if (v_cols && ck_attention_vec_dump_vcols_enabled()) {
        snprintf(name, sizeof(name), "vcols_h%d_q%d", head_id, query_id);
        ck_attention_vec_dump_tensor(name, layer_id, query_id, v_cols, (size_t) kv_tokens * (size_t) head_dim);
    }
}
References ck_attention_trace_query(), ck_attention_vec_dump_should_emit(), ck_attention_vec_dump_tensor(), and ck_attention_vec_dump_vcols_enabled().
Referenced by attention_head_full_dyn_ggml_regular_graph_out(), attention_query_full_dyn_ggml_regular(), attention_query_full_dyn_ggml_regular_matmul_out(), attention_query_full_exact_regular(), and attention_query_full_ggml_regular().
ck_attention_vec_dump_should_emit()
static int ck_attention_vec_dump_should_emit (int layer_id, int head_id, int query_id) static
Definition at line 172 of file attention_kernels.c.
{
    if (!ck_attention_vec_dump_enabled()) {
        return 0;
    }
    int want_layer = -1;
    int want_head = -1;
    int want_query = -1;
    if (!ck_attention_vec_dump_parse_env_int("CK_STRICT_ATTN_DUMP_LAYER", &want_layer)) {
        return 0;
    }
    const int have_head = ck_attention_vec_dump_parse_env_int("CK_STRICT_ATTN_DUMP_HEAD", &want_head);
    const int have_query = ck_attention_vec_dump_parse_env_int("CK_STRICT_ATTN_DUMP_QUERY", &want_query);
    const int trace_target = layer_id == want_layer &&
                             (!have_head || head_id == want_head) &&
                             (!have_query || query_id == want_query);
    if (layer_id != want_layer) {
        return 0;
    }
    if (have_head && head_id != want_head) {
        return 0;
    }
    if (have_query && query_id != want_query) {
        return 0;
    }
    if (trace_target) {
        ck_attention_trace_query("vec_dump_should_emit", layer_id, head_id, query_id, 1);
    }
    return 1;
}
References ck_attention_trace_query(), ck_attention_vec_dump_enabled(), and ck_attention_vec_dump_parse_env_int().
Referenced by attention_head_full_dyn_ggml_regular_graph_out(), attention_query_full_dyn_ggml_regular(), attention_query_full_dyn_ggml_regular_matmul_out(), attention_query_full_exact_regular(), attention_query_full_ggml_regular(), and ck_attention_vec_dump_selected_query().
ck_attention_vec_dump_tensor()
static void ck_attention_vec_dump_tensor (const char * name, int layer_id, int query_id, const float * data, size_t elem_count) static
Definition at line 210 of file attention_kernels.c.
{
    const char *dir = getenv("CK_PARITY_DIR");
    if (!dir || !dir[0] || !name || !name[0] || !data || elem_count == 0) {
        return;
    }
    char path[4096];
    snprintf(path, sizeof(path), "%s/%s", dir, "strict_internal.bin");
    FILE *f = fopen(path, "ab");
    if (!f) {
        return;
    }
    ck_attention_vec_dump_header_t h;
    memset(&h, 0, sizeof(h));
    memcpy(h.magic, ck_attention_vec_dump_magic, sizeof(ck_attention_vec_dump_magic));
    h.version = ck_attention_vec_dump_version;
    h.layer_id = layer_id;
    strncpy(h.op_name, name, sizeof(h.op_name) - 1);
    h.dtype = 0u;
    h.rank = 1u;
    h.shape[0] = (int64_t) elem_count;
    h.elem_count = (uint32_t) elem_count;
    h.token_id = query_id;
    fwrite(&h, sizeof(h), 1, f);
    fwrite(data, sizeof(float), elem_count, f);
    fclose(f);
}
References ck_attention_vec_dump_magic, and ck_attention_vec_dump_version.
Referenced by ck_attention_vec_dump_selected_query().
ck_attention_vec_dump_vcols_enabled()
static int ck_attention_vec_dump_vcols_enabled (void) static
Definition at line 137 of file attention_kernels.c.
{
    const char *v = getenv("CK_STRICT_ATTN_DUMP_VCOLS");
    return v && v[0] && strcmp(v, "0") != 0;
}
Referenced by ck_attention_vec_dump_selected_query().
ck_ggml_init_tensor_f32()
static void ck_ggml_init_tensor_f32 (struct ggml_tensor * t, int64_t ne0, int64_t ne1, int64_t ne2, int64_t ne3, size_t nb0, size_t nb1, size_t nb2, size_t nb3, void * data) inline static
Definition at line 539 of file attention_kernels.c.
{
    memset(t, 0, sizeof(*t));
    t->type = GGML_TYPE_F32;
    t->buffer = NULL;
    t->ne[0] = ne0;
    t->ne[1] = ne1;
    t->ne[2] = ne2;
    t->ne[3] = ne3;
    t->nb[0] = nb0;
    t->nb[1] = nb1;
    t->nb[2] = nb2;
    t->nb[3] = nb3;
    t->op = GGML_OP_NONE;
    t->data = data;
}
Referenced by attention_query_full_dyn_ggml_regular_matmul_out(), and attention_query_full_ggml_compute_regular().
ck_ggml_vec_dot_f32_contig()
static float ck_ggml_vec_dot_f32_contig (const float * x, const float * y, int n) static
Definition at line 671 of file attention_kernels.c.
{
    // Keep this a literal port of ggml_vec_dot_f32 so strict parity can match
    // llama.cpp's CPU attention path instead of merely approximating it.
#if defined(__AVX__)
    float sumf = 0.0f;
    const int np = (n & ~31);
    __m256 sum[4] = {
        _mm256_setzero_ps(),
        _mm256_setzero_ps(),
        _mm256_setzero_ps(),
        _mm256_setzero_ps(),
    };
    for (int i = 0; i < np; i += 32) {
        for (int j = 0; j < 4; ++j) {
            const __m256 ax = _mm256_loadu_ps(x + i + j * 8);
            const __m256 ay = _mm256_loadu_ps(y + i + j * 8);
#if defined(__FMA__)
            sum[j] = _mm256_fmadd_ps(ax, ay, sum[j]);
#else
            sum[j] = _mm256_add_ps(_mm256_mul_ps(ax, ay), sum[j]);
#endif
        }
    }
    sum[0] = _mm256_add_ps(sum[0], sum[2]);
    sum[1] = _mm256_add_ps(sum[1], sum[3]);
    sum[0] = _mm256_add_ps(sum[0], sum[1]);
    const __m128 t0 = _mm_add_ps(_mm256_castps256_ps128(sum[0]),
                                 _mm256_extractf128_ps(sum[0], 1));
    const __m128 t1 = _mm_hadd_ps(t0, t0);
    sumf = _mm_cvtss_f32(_mm_hadd_ps(t1, t1));
    for (int i = np; i < n; ++i) {
        sumf += x[i] * y[i];
    }
    return sumf;
#elif defined(__SSE2__)
    float sumf = 0.0f;
    const int np = (n & ~15);
    __m128 sum[4] = {
        _mm_setzero_ps(),
        _mm_setzero_ps(),
        _mm_setzero_ps(),
        _mm_setzero_ps(),
    };
    for (int i = 0; i < np; i += 16) {
        for (int j = 0; j < 4; ++j) {
            const __m128 ax = _mm_loadu_ps(x + i + j * 4);
            const __m128 ay = _mm_loadu_ps(y + i + j * 4);
#if defined(__FMA__)
            sum[j] = _mm_fmadd_ps(ax, ay, sum[j]);
#else
            sum[j] = _mm_add_ps(_mm_mul_ps(ax, ay), sum[j]);
#endif
        }
    }
    sum[0] = _mm_add_ps(sum[0], sum[2]);
    sum[1] = _mm_add_ps(sum[1], sum[3]);
    sum[0] = _mm_add_ps(sum[0], sum[1]);
#if defined(__AVX__) || defined(__AVX2__) || defined(__AVX512F__)
    sum[0] = _mm_add_ps(sum[0], _mm_movehl_ps(sum[0], sum[0]));
    sum[0] = _mm_add_ss(sum[0], _mm_movehdup_ps(sum[0]));
#else
    __m128 tmp = _mm_shuffle_ps(sum[0], sum[0], _MM_SHUFFLE(2, 3, 0, 1));
    sum[0] = _mm_add_ps(sum[0], tmp);
    tmp = _mm_movehl_ps(tmp, sum[0]);
    sum[0] = _mm_add_ss(sum[0], tmp);
#endif
    sumf = _mm_cvtss_f32(sum[0]);
    for (int i = np; i < n; ++i) {
        sumf += x[i] * y[i];
    }
    return sumf;
#else
    double sumf = 0.0;
    for (int i = 0; i < n; ++i) {
        sumf += (double) (x[i] * y[i]);
    }
    return (float) sumf;
#endif
}
Referenced by attention_query_full_ggml_regular().
ck_ggml_vec_soft_max_row()
static double ck_ggml_vec_soft_max_row (int n, float * y, const float * x, float max) static
Definition at line 773 of file attention_kernels.c.
{
    int i = 0;
    double sum = 0.0;
#if defined(__AVX2__) && defined(__FMA__)
    for (; i + 7 < n; i += 8) {
        const __m256 val = ck_ggml_v_expf256(
            _mm256_sub_ps(_mm256_loadu_ps(x + i), _mm256_set1_ps(max)));
        _mm256_storeu_ps(y + i, val);
        __m128 val2 = _mm_add_ps(_mm256_extractf128_ps(val, 1),
                                 _mm256_castps256_ps128(val));
        val2 = _mm_add_ps(val2, _mm_movehl_ps(val2, val2));
        val2 = _mm_add_ss(val2, _mm_movehdup_ps(val2));
        sum += (double) _mm_cvtss_f32(val2);
    }
#elif defined(__SSE2__)
    for (; i + 3 < n; i += 4) {
        const __m128 val = ck_ggml_v_expf128(
            _mm_sub_ps(_mm_loadu_ps(x + i), _mm_set1_ps(max)));
        _mm_storeu_ps(y + i, val);
#if defined(__AVX__) || defined(__AVX2__) || defined(__AVX512F__)
        __m128 acc = _mm_add_ps(val, _mm_movehl_ps(val, val));
        acc = _mm_add_ss(acc, _mm_movehdup_ps(acc));
#else
        __m128 tmp = _mm_shuffle_ps(val, val, _MM_SHUFFLE(2, 3, 0, 1));
        __m128 acc = _mm_add_ps(val, tmp);
        tmp = _mm_movehl_ps(tmp, acc);
        acc = _mm_add_ss(acc, tmp);
#endif
        sum += (double) _mm_cvtss_f32(acc);
    }
#endif
    for (; i < n; ++i) {
        const float val = expf(x[i] - max);
        y[i] = val;
        sum += (double) val;
    }
    return sum;
}
Referenced by attention_forward_full_head_major_gqa_ggml_tiled_strict(), and attention_query_full_ggml_regular().
ck_hsum128_ps()
static float ck_hsum128_ps (__m128 v) inline static
Definition at line 573 of file attention_kernels.c.
{
    v = _mm_add_ps(v, _mm_movehl_ps(v, v));
    v = _mm_add_ss(v, _mm_movehdup_ps(v));
    return _mm_cvtss_f32(v);
}
ck_resolve_ggml_build_forward_expand()
static ck_ggml_build_forward_expand_fn ck_resolve_ggml_build_forward_expand (void) static
Definition at line 506 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_build_forward_expand_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_build_forward_expand_fn) ck_resolve_ggml_symbol("ggml_build_forward_expand");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_compute_forward_mul_mat()
static ck_ggml_compute_forward_mul_mat_fn ck_resolve_ggml_compute_forward_mul_mat (void) static
Definition at line 418 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_compute_forward_mul_mat_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_compute_forward_mul_mat_fn) ck_resolve_ggml_symbol("ggml_compute_forward_mul_mat");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_resolve_ggml_compute_forward_soft_max()
static ck_ggml_compute_forward_soft_max_fn ck_resolve_ggml_compute_forward_soft_max (void) static
Definition at line 429 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_compute_forward_soft_max_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_compute_forward_soft_max_fn) ck_resolve_ggml_symbol("ggml_compute_forward_soft_max");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_resolve_ggml_cpu_init()
static ck_ggml_cpu_init_fn ck_resolve_ggml_cpu_init (void) static
Definition at line 440 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_cpu_init_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_cpu_init_fn) ck_resolve_ggml_symbol("ggml_cpu_init");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_cpu_so_handle()
static void * ck_resolve_ggml_cpu_so_handle (void) static
Definition at line 356 of file attention_kernels.c.
{
    static int tried = 0;
    static void *handle = NULL;
    if (!tried) {
        tried = 1;
        const char *env_path = getenv("CK_GGML_CPU_SO");
        const char *candidates[] = {
            env_path && env_path[0] ? env_path : NULL,
            "libggml-cpu.so",
            "libggml-cpu.so.0",
            "./llama.cpp/build/bin/libggml-cpu.so",
            "./llama.cpp/build/bin/libggml-cpu.so.0",
            "llama.cpp/build/bin/libggml-cpu.so",
            "llama.cpp/build/bin/libggml-cpu.so.0",
            NULL,
        };
        for (int i = 0; candidates[i] != NULL; ++i) {
            handle = dlopen(candidates[i], RTLD_NOW | RTLD_LOCAL);
            if (handle) {
                break;
            }
        }
    }
    return handle;
}
Referenced by ck_resolve_ggml_symbol().
ck_resolve_ggml_free()
static ck_ggml_free_fn ck_resolve_ggml_free (void) static
Definition at line 462 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_free_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_free_fn) ck_resolve_ggml_symbol("ggml_free");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_graph_compute_with_ctx()
static ck_ggml_graph_compute_with_ctx_fn ck_resolve_ggml_graph_compute_with_ctx (void) static
Definition at line 517 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_graph_compute_with_ctx_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_graph_compute_with_ctx_fn) ck_resolve_ggml_symbol("ggml_graph_compute_with_ctx");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_init()
static ck_ggml_init_fn ck_resolve_ggml_init (void) static
Definition at line 451 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_init_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_init_fn) ck_resolve_ggml_symbol("ggml_init");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_mul_mat_graph()
static ck_ggml_mul_mat_graph_fn ck_resolve_ggml_mul_mat_graph (void) static
Definition at line 484 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_mul_mat_graph_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_mul_mat_graph_fn) ck_resolve_ggml_symbol("ggml_mul_mat");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_new_graph()
static ck_ggml_new_graph_fn ck_resolve_ggml_new_graph (void) static
Definition at line 495 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_new_graph_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_new_graph_fn) ck_resolve_ggml_symbol("ggml_new_graph");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_new_tensor_2d()
static ck_ggml_new_tensor_2d_fn ck_resolve_ggml_new_tensor_2d (void) static
Definition at line 473 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_new_tensor_2d_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_new_tensor_2d_fn) ck_resolve_ggml_symbol("ggml_new_tensor_2d");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_set_input()
static ck_ggml_set_input_fn ck_resolve_ggml_set_input (void) static
Definition at line 528 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_set_input_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_set_input_fn) ck_resolve_ggml_symbol("ggml_set_input");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_out_mul_mat_graph_block().
ck_resolve_ggml_symbol()
static void * ck_resolve_ggml_symbol (const char * name) static
Definition at line 383 of file attention_kernels.c.
{
    void *sym = dlsym(RTLD_DEFAULT, name);
    if (sym) {
        return sym;
    }
    void *handle = ck_resolve_ggml_cpu_so_handle();
    if (!handle) {
        return NULL;
    }
    return dlsym(handle, name);
}
References ck_resolve_ggml_cpu_so_handle().
Referenced by ck_resolve_ggml_build_forward_expand(), ck_resolve_ggml_compute_forward_mul_mat(), ck_resolve_ggml_compute_forward_soft_max(), ck_resolve_ggml_cpu_init(), ck_resolve_ggml_free(), ck_resolve_ggml_graph_compute_with_ctx(), ck_resolve_ggml_init(), ck_resolve_ggml_mul_mat_graph(), ck_resolve_ggml_new_graph(), ck_resolve_ggml_new_tensor_2d(), ck_resolve_ggml_set_input(), ck_resolve_ggml_vec_dot_f32(), and ck_resolve_ggml_vec_soft_max_f32().
ck_resolve_ggml_vec_dot_f32()
static ck_ggml_vec_dot_f32_fn ck_resolve_ggml_vec_dot_f32 (void) static
Definition at line 396 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_vec_dot_f32_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_vec_dot_f32_fn) ck_resolve_ggml_symbol("ggml_vec_dot_f32");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_resolve_ggml_vec_soft_max_f32()
static ck_ggml_vec_soft_max_f32_fn ck_resolve_ggml_vec_soft_max_f32 (void) static
Definition at line 407 of file attention_kernels.c.
{
    static int tried = 0;
    static ck_ggml_vec_soft_max_f32_fn fn = NULL;
    if (!tried) {
        tried = 1;
        fn = (ck_ggml_vec_soft_max_f32_fn) ck_resolve_ggml_symbol("ggml_vec_soft_max_f32");
    }
    return fn;
}
References ck_resolve_ggml_symbol().
Referenced by attention_forward_full_head_major_gqa_ggml_strided().
ck_round_fp16_scalar()
static float ck_round_fp16_scalar (float x) inline static
Definition at line 51 of file attention_kernels.c.
{
    return CK_FP16_TO_FP32(CK_FP32_TO_FP16(x));
}
References CK_FP16_TO_FP32, and CK_FP32_TO_FP16.
Referenced by attention_flash_query_causal_exact_f16kv().
ck_vec_dot_f32_reverse_strict()
static float ck_vec_dot_f32_reverse_strict (const float * x, const float * y, int n) static
Definition at line 95 of file attention_kernels.c.
{
    float sumf = 0.0f;
    for (int i = n - 1; i >= 0; --i) {
        volatile float prod = x[i] * y[i];
        volatile float next = sumf + prod;
        sumf = next;
    }
    return sumf;
}
Referenced by attention_query_full_dyn_ggml_regular().
ck_vec_dot_f32_strict()
static float ck_vec_dot_f32_strict (const float * x, const float * y, int n) static
Definition at line 69 of file attention_kernels.c.
{
    float sumf = 0.0f;
    for (int i = 0; i < n; ++i) {
        volatile float prod = x[i] * y[i];
        volatile float next = sumf + prod;
        sumf = next;
    }
    return sumf;
}
Referenced by attention_query_full_exact_regular().
ck_vec_dot_f32x_f32_to_f32_via_f64()
static float ck_vec_dot_f32x_f32_to_f32_via_f64 (const float * x, const float * y, int n) static
Definition at line 82 of file attention_kernels.c.
{
    double sum = 0.0;
    for (int i = 0; i < n; ++i) {
        volatile double prod = (double) x[i] * (double) y[i];
        volatile double next = sum + prod;
        sum = next;
    }
    return (float) sum;
}
Referenced by attention_query_full_exact_regular().
ck_vec_max_f32_contig()
static float ck_vec_max_f32_contig (const float * x, int n) inline static
Definition at line 2278 of file attention_kernels.c.
{
    float max_val = -INFINITY;
    for (int i = 0; i < n; ++i) {
        if (x[i] > max_val) {
            max_val = x[i];
        }
    }
    return max_val;
}
Referenced by attention_forward_full_head_major_gqa_ggml_tiled_strict(), attention_head_full_dyn_ggml_regular_graph_out(), attention_query_full_dyn_ggml_regular(), attention_query_full_dyn_ggml_regular_matmul_out(), and attention_query_full_ggml_regular().
ck_vec_scale_f32_inplace()
static void ck_vec_scale_f32_inplace (float * x, int n, float scale) inline static
Definition at line 2271 of file attention_kernels.c.
{
    for (int i = 0; i < n; ++i) {
        x[i] *= scale;
    }
}
Referenced by attention_forward_full_head_major_gqa_ggml_tiled_strict(), attention_head_full_dyn_ggml_regular_graph_out(), attention_query_full_dyn_ggml_regular(), attention_query_full_dyn_ggml_regular_matmul_out(), and attention_query_full_ggml_regular().
convert_bf16_tensor_to_buf()
static void convert_bf16_tensor_to_buf (const uint16_t * src, float * dst, size_t count) static
Definition at line 32 of file attention_kernels.c.
{
    if (!dst || !src) return;
    bf16_tensor_to_float(src, dst, count);
}
References bf16_tensor_to_float().
Referenced by attention_backward_causal_head_major_gqa_bf16(), and attention_forward_causal_head_major_gqa_bf16().
qkv_index()
static size_t qkv_index (int h, int t, int d, int num_tokens, int aligned_head_dim) inline static
Definition at line 40 of file attention_kernels.c.
{
    return ((size_t)h * (size_t)num_tokens + (size_t)t) * (size_t)aligned_head_dim
         + (size_t)d;
}
Referenced by attention_backward_causal_head_major_gqa(), attention_forward_causal_head_major(), attention_forward_causal_head_major_exact(), attention_forward_causal_head_major_gqa(), attention_forward_causal_head_major_gqa_exact(), attention_forward_causal_head_major_gqa_flash_strided_f16kv(), attention_forward_full_head_major_gqa_exact_strided(), attention_forward_full_head_major_gqa_ggml_strided(), attention_forward_full_head_major_gqa_ggml_tiled_strict(), and attention_forward_head_major_gqa_flash_impl().
score_index()
static size_t score_index (int h, int i, int j, int aligned_context_window) inline static
Definition at line 821 of file attention_kernels.c.
{
    return ((size_t)h * (size_t)aligned_context_window * (size_t)aligned_context_window)
         + (size_t)i * (size_t)aligned_context_window
         + (size_t)j;
}
Referenced by attention_backward_causal_head_major_gqa(), attention_forward_causal_head_major(), attention_forward_causal_head_major_exact(), attention_forward_causal_head_major_gqa(), and attention_forward_causal_head_major_gqa_exact().
Variable Documentation
ck_attention_vec_dump_layer_seq
int ck_attention_vec_dump_layer_seq = 0 static
Definition at line 123 of file attention_kernels.c.
Referenced by ck_attention_vec_dump_next_layer_id().
ck_attention_vec_dump_magic
const char ck_attention_vec_dump_magic[8] = {'C', 'K', 'D', 'M', 'P', '\0', '\0', '\0'} static
Definition at line 121 of file attention_kernels.c.
{'C', 'K', 'D', 'M', 'P', '\0', '\0', '\0'};
Referenced by ck_attention_vec_dump_tensor().
ck_attention_vec_dump_version
const uint32_t ck_attention_vec_dump_version = 1u static
Definition at line 122 of file attention_kernels.c.
Referenced by ck_attention_vec_dump_tensor().