ckernel_alloc.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ckernel_alloc.h File Reference
#include <stddef.h>
Functions
void * ck_huge_alloc (size_t bytes)
void ck_huge_free (void *ptr, size_t bytes)
Function Documentation
ck_huge_alloc()
void * ck_huge_alloc (size_t bytes)
Allocate a large, contiguous memory region for model weights/activations.
Implementation strategy:
Try to allocate 2MB-aligned memory backed by huge pages where possible.
Fall back to aligned_alloc + madvise(MADV_HUGEPAGE) when explicit huge pages are not available.
Returns NULL on failure.
Definition at line 67 of file ckernel_alloc.c.
{
    size_t len = align_up_bytes(bytes, HUGE_PAGE_SIZE);
    /* First, try explicit huge pages via mmap + MAP_HUGETLB. */
    void *p = mmap(NULL, len,
                   PROT_READ | PROT_WRITE,
                   MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB,
                   -1, 0);
    if (p != MAP_FAILED) {
        if (!record_allocation(p, len, 1)) {
            munmap(p, len);
            return NULL;
        }
        return p;
    }
    /* Fallback: aligned_alloc with transparent hugepage hint. */
    void *q = aligned_alloc(HUGE_PAGE_SIZE, len);
    if (!q) {
        fprintf(stderr, "ck_huge_alloc: aligned_alloc failed for %zu bytes: %s\n",
                len, strerror(errno));
        return NULL;
    }
    /* Best-effort hint; ignore errors. */
    (void)madvise(q, len, MADV_HUGEPAGE);
    if (!record_allocation(q, len, 0)) {
        free(q);
        return NULL;
    }
    return q;
}
References align_up_bytes(), align_up_bytes(), align_up_bytes(), align_up_bytes(), HUGE_PAGE_SIZE, record_allocation(), record_allocation(), record_allocation(), and record_allocation().
ck_huge_free()
void ck_huge_free (void * ptr, size_t bytes)
Free memory allocated by ck_huge_alloc.
The bytes parameter should be the same size passed to ck_huge_alloc.
Definition at line 101 of file ckernel_alloc.c.
{
    if (!ptr || bytes == 0) {
        return;
    }
    ck_huge_alloc_entry_t *entry = detach_allocation(ptr);
    if (!entry) {
        /* Fall back to malloc/free if the allocation wasn't tracked. */
        free(ptr);
        return;
    }
    if (entry->was_mmap) {
        munmap(ptr, entry->len);
    } else {
        free(ptr);
    }
    free(entry);
}
References detach_allocation(), detach_allocation(), detach_allocation(), and detach_allocation().