deltanet_kernels.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
deltanet_kernels.c File Reference
FP32 Gated DeltaNet kernels for Qwen3.5-style recurrent attention.
#include "ckernel_engine.h"
#include <math.h>
#include <stddef.h>
Macros
#define CK_DELTANET_MAX_STACK_DIM 4096
Functions
static float ck_deltanet_l2_inv_norm_scalar (const float *x, int dim, float eps)
static void ck_deltanet_scaled_l2_norm_backward_ref (const float *x, const float *d_y, float *d_x, int dim, float inv_norm, float scale)
static float ck_deltanet_sigmoidf (float x)
void gated_deltanet_autoregressive_backward (const float *d_out, const float *d_state_out, const float *q, const float *k, const float *v, const float *g, const float *beta, const float *state_in, const float *state_out, float *d_q, float *d_k, float *d_v, float *d_g, float *d_beta, float *d_state_in, int num_heads, int state_dim, float norm_eps)
void gated_deltanet_autoregressive_backward_ref (const float *d_out, const float *d_state_out, const float *q, const float *k, const float *v, const float *g, const float *beta, const float *state_in, const float *state_out, float *d_q, float *d_k, float *d_v, float *d_g, float *d_beta, float *d_state_in, int num_heads, int state_dim, float norm_eps)
void gated_deltanet_autoregressive_forward (const float *q, const float *k, const float *v, const float *g, const float *beta, const float *state_in, float *state_out, float *out, int num_heads, int state_dim, float norm_eps)
void gated_deltanet_autoregressive_forward_ref (const float *q, const float *k, const float *v, const float *g, const float *beta, const float *state_in, float *state_out, float *out, int num_heads, int state_dim, float norm_eps)
const char * gated_deltanet_impl_name (void)
Detailed Description
FP32 Gated DeltaNet kernels for Qwen3.5-style recurrent attention.
CK-ENGINE KERNEL RULES:
NO malloc/free - memory via bump allocator, pointers passed in
NO OpenMP - parallelization at orchestrator/codegen layer
API must define: inputs, outputs, workspace, and memory layouts
Pure computation - deterministic, no side effects
After changes: make test && make llamacpp-parity-full
This file implements the single-token recurrent update used by the qwen3next / Gated DeltaNet path in llama.cpp.
Per head: q_hat = l2_norm(q) / sqrt(state_dim) k_hat = l2_norm(k) beta_s = sigmoid(beta) gate = exp(g) S = gate * S_prev kv_mem = S^T * k_hat delta = (v - kv_mem) * beta_s S_new = S + outer(k_hat, delta) out = S_new^T * q_hat
Design:
*_ref is the scalar reference implementation.
*_avx keeps a simple 1-row vector walk.
*_avx2 precomputes normalized q/k rows and unrolls the state sweep in row pairs to reduce loop overhead and layout churn.
The public dispatcher selects the best compiled ISA unless strict parity is enabled, in which case it falls back to *_ref.
Definition in file deltanet_kernels.c.
Macro Definition Documentation
CK_DELTANET_MAX_STACK_DIM
#define CK_DELTANET_MAX_STACK_DIM 4096
Definition at line 46 of file deltanet_kernels.c.
Function Documentation
ck_deltanet_l2_inv_norm_scalar()
static float ck_deltanet_l2_inv_norm_scalar (const float * x, int dim, float eps) static
Definition at line 53 of file deltanet_kernels.c.
{
    float sum_sq = 0.0f;
    for (int i = 0; i < dim; ++i) {
        sum_sq += x[i] * x[i];
    }
    return 1.0f / sqrtf(sum_sq + eps);
}
Referenced by gated_deltanet_autoregressive_backward_ref(), and gated_deltanet_autoregressive_forward_ref().
ck_deltanet_scaled_l2_norm_backward_ref()
static void ck_deltanet_scaled_l2_norm_backward_ref (const float * x, const float * d_y, float * d_x, int dim, float inv_norm, float scale) static
Definition at line 62 of file deltanet_kernels.c.
{
    float dot = 0.0f;
    for (int i = 0; i < dim; ++i) {
        dot += d_y[i] * x[i];
    }
    const float scaled_inv = scale * inv_norm;
    const float proj_scale = scale * inv_norm * inv_norm * inv_norm * dot;
    for (int i = 0; i < dim; ++i) {
        d_x[i] = scaled_inv * d_y[i] - proj_scale * x[i];
    }
}
Referenced by gated_deltanet_autoregressive_backward_ref().
ck_deltanet_sigmoidf()
static float ck_deltanet_sigmoidf (float x) inline static
Definition at line 48 of file deltanet_kernels.c.
{
    return 1.0f / (1.0f + expf(-x));
}
Referenced by gated_deltanet_autoregressive_backward_ref(), and gated_deltanet_autoregressive_forward_ref().
gated_deltanet_autoregressive_backward()
void gated_deltanet_autoregressive_backward (const float * d_out, const float * d_state_out, const float * q, const float * k, const float * v, const float * g, const float * beta, const float * state_in, const float * state_out, float * d_q, float * d_k, float * d_v, float * d_g, float * d_beta, float * d_state_in, int num_heads, int state_dim, float norm_eps)
Definition at line 809 of file deltanet_kernels.c.
{
    if (!d_out || !d_state_out || !q || !k || !v || !g || !beta || !state_in || !state_out ||
        !d_q || !d_k || !d_v || !d_g || !d_beta || !d_state_in) {
        return;
    }
    if (num_heads <= 0 || state_dim <= 0 || state_dim > CK_DELTANET_MAX_STACK_DIM) {
        return;
    }
    gated_deltanet_autoregressive_backward_ref(
        d_out,
        d_state_out,
        q,
        k,
        v,
        g,
        beta,
        state_in,
        state_out,
        d_q,
        d_k,
        d_v,
        d_g,
        d_beta,
        d_state_in,
        num_heads,
        state_dim,
        norm_eps);
}
References CK_DELTANET_MAX_STACK_DIM, and gated_deltanet_autoregressive_backward_ref().
gated_deltanet_autoregressive_backward_ref()
void gated_deltanet_autoregressive_backward_ref (const float * d_out, const float * d_state_out, const float * q, const float * k, const float * v, const float * g, const float * beta, const float * state_in, const float * state_out, float * d_q, float * d_k, float * d_v, float * d_g, float * d_beta, float * d_state_in, int num_heads, int state_dim, float norm_eps)
Definition at line 142 of file deltanet_kernels.c.
{
    const float q_scale = 1.0f / sqrtf((float)state_dim);
    const size_t vec_stride = (size_t)state_dim;
    const size_t state_stride = (size_t)state_dim * (size_t)state_dim;
    float q_hat[CK_DELTANET_MAX_STACK_DIM];
    float k_hat[CK_DELTANET_MAX_STACK_DIM];
    float kv_mem[CK_DELTANET_MAX_STACK_DIM];
    float delta[CK_DELTANET_MAX_STACK_DIM];
    float d_q_hat[CK_DELTANET_MAX_STACK_DIM];
    float d_k_hat[CK_DELTANET_MAX_STACK_DIM];
    float d_mem[CK_DELTANET_MAX_STACK_DIM];
    for (int h = 0; h < num_heads; ++h) {
        const float *d_out_head = d_out + (size_t)h * vec_stride;
        const float *d_state_out_head = d_state_out + (size_t)h * state_stride;
        const float *q_head = q + (size_t)h * vec_stride;
        const float *k_head = k + (size_t)h * vec_stride;
        const float *v_head = v + (size_t)h * vec_stride;
        const float *state_prev = state_in + (size_t)h * state_stride;
        const float *state_cur = state_out + (size_t)h * state_stride;
        float *d_q_head = d_q + (size_t)h * vec_stride;
        float *d_k_head = d_k + (size_t)h * vec_stride;
        float *d_v_head = d_v + (size_t)h * vec_stride;
        float *d_state_prev = d_state_in + (size_t)h * state_stride;
        const float q_inv_norm = ck_deltanet_l2_inv_norm_scalar(q_head, state_dim, norm_eps);
        const float k_inv_norm = ck_deltanet_l2_inv_norm_scalar(k_head, state_dim, norm_eps);
        const float beta_s = ck_deltanet_sigmoidf(beta[h]);
        const float gate = expf(g[h]);
        float qk_dot = 0.0f;
        float out_delta_dot = 0.0f;
        float beta_acc = 0.0f;
        float gate_acc = 0.0f;
        for (int i = 0; i < state_dim; ++i) {
            q_hat[i] = q_head[i] * q_inv_norm * q_scale;
            k_hat[i] = k_head[i] * k_inv_norm;
            kv_mem[i] = 0.0f;
            d_q_hat[i] = 0.0f;
            d_k_hat[i] = 0.0f;
            d_mem[i] = 0.0f;
            d_v_head[i] = 0.0f;
            qk_dot += q_hat[i] * k_hat[i];
        }
        for (int col = 0; col < state_dim; ++col) {
            float mem = 0.0f;
            for (int row = 0; row < state_dim; ++row) {
                mem += (state_prev[(size_t)row * (size_t)state_dim + (size_t)col] * gate) * k_hat[row];
            }
            kv_mem[col] = mem;
            delta[col] = (v_head[col] - mem) * beta_s;
            out_delta_dot += d_out_head[col] * delta[col];
        }
        for (int row = 0; row < state_dim; ++row) {
            const size_t row_off = (size_t)row * (size_t)state_dim;
            float dq_acc = 0.0f;
            float dk_acc = q_hat[row] * out_delta_dot;
            for (int col = 0; col < state_dim; ++col) {
                const float d_state_direct = d_state_out_head[row_off + (size_t)col];
                dq_acc += state_cur[row_off + (size_t)col] * d_out_head[col];
                dk_acc += d_state_direct * delta[col];
            }
            d_q_hat[row] = dq_acc;
            d_k_hat[row] = dk_acc;
        }
        for (int col = 0; col < state_dim; ++col) {
            float d_delta_acc = d_out_head[col] * qk_dot;
            for (int row = 0; row < state_dim; ++row) {
                d_delta_acc += d_state_out_head[(size_t)row * (size_t)state_dim + (size_t)col] * k_hat[row];
            }
            d_v_head[col] = beta_s * d_delta_acc;
            d_mem[col] = -beta_s * d_delta_acc;
            beta_acc += d_delta_acc * (v_head[col] - kv_mem[col]);
        }
        for (int row = 0; row < state_dim; ++row) {
            const size_t row_off = (size_t)row * (size_t)state_dim;
            float s_dm_acc = 0.0f;
            for (int col = 0; col < state_dim; ++col) {
                s_dm_acc += (state_prev[row_off + (size_t)col] * gate) * d_mem[col];
            }
            d_k_hat[row] += s_dm_acc;
        }
        for (int row = 0; row < state_dim; ++row) {
            const size_t row_off = (size_t)row * (size_t)state_dim;
            for (int col = 0; col < state_dim; ++col) {
                const float d_state_total = d_state_out_head[row_off + (size_t)col]
                                          + q_hat[row] * d_out_head[col]
                                          + k_hat[row] * d_mem[col];
                d_state_prev[row_off + (size_t)col] = gate * d_state_total;
                gate_acc += d_state_total * state_prev[row_off + (size_t)col];
            }
        }
        ck_deltanet_scaled_l2_norm_backward_ref(
            q_head, d_q_hat, d_q_head, state_dim, q_inv_norm, q_scale);
        ck_deltanet_scaled_l2_norm_backward_ref(
            k_head, d_k_hat, d_k_head, state_dim, k_inv_norm, 1.0f);
        d_g[h] = gate_acc * gate;
        d_beta[h] = beta_acc * beta_s * (1.0f - beta_s);
    }
}
References ck_deltanet_l2_inv_norm_scalar(), CK_DELTANET_MAX_STACK_DIM, ck_deltanet_scaled_l2_norm_backward_ref(), and ck_deltanet_sigmoidf().
Referenced by gated_deltanet_autoregressive_backward().
gated_deltanet_autoregressive_forward()
void gated_deltanet_autoregressive_forward (const float * q, const float * k, const float * v, const float * g, const float * beta, const float * state_in, float * state_out, float * out, int num_heads, int state_dim, float norm_eps)
Definition at line 769 of file deltanet_kernels.c.
{
    if (!q || !k || !v || !g || !beta || !state_in || !state_out || !out) {
        return;
    }
    if (num_heads <= 0 || state_dim <= 0) {
        return;
    }
    if (ck_strict_parity_enabled() || state_dim > CK_DELTANET_MAX_STACK_DIM) {
        gated_deltanet_autoregressive_forward_ref(
            q, k, v, g, beta, state_in, state_out, out, num_heads, state_dim, norm_eps);
        return;
    }
#if defined(__AVX512F__)
    gated_deltanet_autoregressive_forward_avx512(
        q, k, v, g, beta, state_in, state_out, out, num_heads, state_dim, norm_eps);
#elif defined(__AVX2__)
    gated_deltanet_autoregressive_forward_avx2(
        q, k, v, g, beta, state_in, state_out, out, num_heads, state_dim, norm_eps);
#elif defined(__AVX__)
    gated_deltanet_autoregressive_forward_avx(
        q, k, v, g, beta, state_in, state_out, out, num_heads, state_dim, norm_eps);
#else
    gated_deltanet_autoregressive_forward_ref(
        q, k, v, g, beta, state_in, state_out, out, num_heads, state_dim, norm_eps);
#endif
}
References CK_DELTANET_MAX_STACK_DIM, ck_strict_parity_enabled(), and gated_deltanet_autoregressive_forward_ref().
Referenced by ck_test_gated_deltanet_autoregressive().
gated_deltanet_autoregressive_forward_ref()
void gated_deltanet_autoregressive_forward_ref (const float * q, const float * k, const float * v, const float * g, const float * beta, const float * state_in, float * state_out, float * out, int num_heads, int state_dim, float norm_eps)
Definition at line 81 of file deltanet_kernels.c.
{
    const float q_scale = 1.0f / sqrtf((float)state_dim);
    const size_t vec_stride = (size_t)state_dim;
    const size_t state_stride = (size_t)state_dim * (size_t)state_dim;
    for (int h = 0; h < num_heads; ++h) {
        const float *q_head = q + (size_t)h * vec_stride;
        const float *k_head = k + (size_t)h * vec_stride;
        const float *v_head = v + (size_t)h * vec_stride;
        const float *state_prev = state_in + (size_t)h * state_stride;
        float *state_cur = state_out + (size_t)h * state_stride;
        float *out_head = out + (size_t)h * vec_stride;
        const float q_inv_norm = ck_deltanet_l2_inv_norm_scalar(q_head, state_dim, norm_eps);
        const float k_inv_norm = ck_deltanet_l2_inv_norm_scalar(k_head, state_dim, norm_eps);
        const float beta_s = ck_deltanet_sigmoidf(beta[h]);
        const float gate = expf(g[h]);
        for (int row = 0; row < state_dim; ++row) {
            const size_t row_off = (size_t)row * (size_t)state_dim;
            for (int col = 0; col < state_dim; ++col) {
                state_cur[row_off + (size_t)col] = state_prev[row_off + (size_t)col] * gate;
            }
        }
        for (int col = 0; col < state_dim; ++col) {
            float kv_mem = 0.0f;
            for (int row = 0; row < state_dim; ++row) {
                const float k_hat = k_head[row] * k_inv_norm;
                kv_mem += state_cur[(size_t)row * (size_t)state_dim + (size_t)col] * k_hat;
            }
            const float delta = (v_head[col] - kv_mem) * beta_s;
            for (int row = 0; row < state_dim; ++row) {
                const float k_hat = k_head[row] * k_inv_norm;
                state_cur[(size_t)row * (size_t)state_dim + (size_t)col] += k_hat * delta;
            }
        }
        for (int col = 0; col < state_dim; ++col) {
            float acc = 0.0f;
            for (int row = 0; row < state_dim; ++row) {
                const float q_hat = q_head[row] * q_inv_norm * q_scale;
                acc += state_cur[(size_t)row * (size_t)state_dim + (size_t)col] * q_hat;
            }
            out_head[col] = acc;
        }
    }
}
References ck_deltanet_l2_inv_norm_scalar(), and ck_deltanet_sigmoidf().
Referenced by gated_deltanet_autoregressive_forward().
gated_deltanet_impl_name()
const char * gated_deltanet_impl_name (void)
Definition at line 753 of file deltanet_kernels.c.
{
    if (ck_strict_parity_enabled()) {
        return "REF";
    }
#if defined(__AVX512F__)
    return "AVX512";
#elif defined(__AVX2__)
    return "AVX2";
#elif defined(__AVX__)
    return "AVX";
#else
    return "REF";
#endif
}
References ck_strict_parity_enabled().