memory_pool.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
memory_pool.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct CKTokenizerMemPool
Macros
#define CK_TOKENIZER_POOL_BLOCK_SIZE (1024 * 1024)
#define CK_TOKENIZER_POOL_DEFAULT_SIZE (16 * 1024 * 1024)
Functions
void * ck_tokenizer_mempool_alloc (CKTokenizerMemPool *pool, size_t size)
void * ck_tokenizer_mempool_alloc_aligned (CKTokenizerMemPool *pool, size_t size, size_t align)
size_t ck_tokenizer_mempool_alloc_count (CKTokenizerMemPool *pool)
size_t ck_tokenizer_mempool_available (CKTokenizerMemPool *pool)
void ck_tokenizer_mempool_free (CKTokenizerMemPool *pool)
int ck_tokenizer_mempool_init (CKTokenizerMemPool *pool, size_t size)
void ck_tokenizer_mempool_reset (CKTokenizerMemPool *pool)
char * ck_tokenizer_mempool_strdup (CKTokenizerMemPool *pool, const char *str)
char * ck_tokenizer_mempool_strndup (CKTokenizerMemPool *pool, const char *str, int len)
size_t ck_tokenizer_mempool_used (CKTokenizerMemPool *pool)
Macro Definition Documentation
CK_TOKENIZER_POOL_BLOCK_SIZE
#define CK_TOKENIZER_POOL_BLOCK_SIZE (1024 * 1024)
Definition at line 24 of file memory_pool.h.
CK_TOKENIZER_POOL_DEFAULT_SIZE
#define CK_TOKENIZER_POOL_DEFAULT_SIZE (16 * 1024 * 1024)
Definition at line 21 of file memory_pool.h.
Function Documentation
ck_tokenizer_mempool_alloc()
void* ck_tokenizer_mempool_alloc (CKTokenizerMemPool * pool, size_t size)
Allocate from pool.
Parameters
pool Pool to allocate from
size Size in bytes
Returns
Pointer to allocated memory, or NULL on error
Definition at line 41 of file memory_pool.c.
{
     if (!pool || !pool->memory || size == 0) {
         return NULL;
     }
     size = align_up(size, pool->alignment);
     if (pool->used + size > pool->size) {
         return NULL;
     }
     void *ptr = pool->memory + pool->used;
     pool->used += size;
     return ptr;
 }
References align_up(), CKTokenizerMemPool::alignment, CKTokenizerMemPool::memory, CKTokenizerMemPool::size, and CKTokenizerMemPool::used.
Referenced by ck_tokenizer_mempool_strndup().
ck_tokenizer_mempool_alloc_aligned()
void* ck_tokenizer_mempool_alloc_aligned (CKTokenizerMemPool * pool, size_t size, size_t align)
Allocate aligned memory from pool.
Parameters
pool Pool to allocate from
size Size in bytes
align Alignment (must be power of 2)
Returns
Pointer to allocated memory, or NULL on error
Definition at line 58 of file memory_pool.c.
{
     if (!pool || !pool->memory || size == 0) {
         return NULL;
     }
     /* Validate alignment is power of 2 */
     if (align & (align - 1)) {
         return NULL;
     }
     /* Align up the allocation size */
     size = align_up(size, align);
     /* Align the current position */
     size_t misalignment = pool->used & (align - 1);
     size_t padding = (misalignment == 0) ? 0 : (align - misalignment);
     if (pool->used + padding + size > pool->size) {
         return NULL;
     }
     pool->used += padding;
     void *ptr = pool->memory + pool->used;
     pool->used += size;
     return ptr;
 }
References align_up(), CKTokenizerMemPool::memory, CKTokenizerMemPool::size, and CKTokenizerMemPool::used.
ck_tokenizer_mempool_alloc_count()
size_t ck_tokenizer_mempool_alloc_count (CKTokenizerMemPool * pool)
Get allocation count.
Parameters
pool Pool to query
Returns
Number of allocations
ck_tokenizer_mempool_available()
size_t ck_tokenizer_mempool_available (CKTokenizerMemPool * pool)
Get available bytes in pool.
Parameters
pool Pool to query
Returns
Number of bytes available
Definition at line 123 of file memory_pool.c.
{
     if (!pool) {
         return 0;
     }
     return pool->size - pool->used;
 }
References CKTokenizerMemPool::size, and CKTokenizerMemPool::used.
ck_tokenizer_mempool_free()
void ck_tokenizer_mempool_free (CKTokenizerMemPool * pool)
Free a memory pool.
Parameters
pool Pool to free
Definition at line 28 of file memory_pool.c.
{
     if (pool->memory) {
         free(pool->memory);
         pool->memory = NULL;
     }
     pool->size = 0;
     pool->used = 0;
 }
References CKTokenizerMemPool::memory, CKTokenizerMemPool::size, and CKTokenizerMemPool::used.
Referenced by ck_tokenizer_free().
ck_tokenizer_mempool_init()
int ck_tokenizer_mempool_init (CKTokenizerMemPool * pool, size_t size)
Initialize a memory pool.
Parameters
pool Pool to initialize
size Pool size in bytes (0 = use default)
Returns
0 on success, -1 on error
Definition at line 11 of file memory_pool.c.
{
     if (size == 0) {
         size = CK_TOKENIZER_POOL_DEFAULT_SIZE;
     }
     pool->memory = (char *)malloc(size);
     if (!pool->memory) {
         return -1;
     }
     pool->size = size;
     pool->used = 0;
     pool->alignment = 8;
     return 0;
 }
References CKTokenizerMemPool::alignment, CK_TOKENIZER_POOL_DEFAULT_SIZE, CKTokenizerMemPool::memory, CKTokenizerMemPool::size, and CKTokenizerMemPool::used.
Referenced by ck_tokenizer_create().
ck_tokenizer_mempool_reset()
void ck_tokenizer_mempool_reset (CKTokenizerMemPool * pool)
Reset pool (mark all memory as free).
Parameters
pool Pool to reset
Definition at line 113 of file memory_pool.c.
{
     if (pool) {
         pool->used = 0;
     }
 }
References CKTokenizerMemPool::used.
ck_tokenizer_mempool_strdup()
char* ck_tokenizer_mempool_strdup (CKTokenizerMemPool * pool, const char * str)
Allocate and copy string (strdup equivalent).
Parameters
pool Pool to allocate from
str String to copy
Returns
Pointer to copied string, or NULL on error
Definition at line 86 of file memory_pool.c.
{
     if (!pool || !str) {
         return NULL;
     }
     return ck_tokenizer_mempool_strndup(pool, str, -1);
 }
References ck_tokenizer_mempool_strndup().
ck_tokenizer_mempool_strndup()
char* ck_tokenizer_mempool_strndup (CKTokenizerMemPool * pool, const char * str, int len)
Allocate and copy string with length.
Parameters
pool Pool to allocate from
str String to copy
len Length to copy (-1 for null-terminated)
Returns
Pointer to copied string, or NULL on error
Definition at line 93 of file memory_pool.c.
{
     if (!pool || !str) {
         return NULL;
     }
     if (len < 0) {
         len = (int)strlen(str);
     }
     char *copy = (char *)ck_tokenizer_mempool_alloc(pool, len + 1);
     if (!copy) {
         return NULL;
     }
     memcpy(copy, str, len);
     copy[len] = '\0';
     return copy;
 }
References ck_tokenizer_mempool_alloc().
Referenced by ck_tokenizer_mempool_strdup().
ck_tokenizer_mempool_used()
size_t ck_tokenizer_mempool_used (CKTokenizerMemPool * pool)
Get used bytes in pool.
Parameters
pool Pool to query
Returns
Number of bytes used
Definition at line 119 of file memory_pool.c.
{
     return pool ? pool->used : 0;
 }
References CKTokenizerMemPool::used.