murmurhash3.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
murmurhash3.h File Reference
#include <stdint.h>
#include <stddef.h>
Functions
uint32_t ck_murmurhash3 (const char *key, uint32_t len, uint32_t seed)
void ck_murmurhash3_128 (const void *key, size_t len, uint32_t seed, uint64_t *out1, uint64_t *out2)
uint32_t ck_murmurhash3_32 (const void *key, size_t len, uint32_t seed)
static uint32_t ck_murmurhash3_str (const char *str, uint32_t seed)
static uint32_t ck_murmurhash3_strn (const char *str, size_t len, uint32_t seed)
Function Documentation
ck_murmurhash3()
uint32_t ck_murmurhash3 (const char * key, uint32_t len, uint32_t seed)
MurmurHash3-32bit hash function (original HPC_Embeddings version).
Parameters
key Data to hash
len Length in bytes
seed Seed value
Returns
32-bit hash value
Definition at line 11 of file murmurhash3.c.
{
    const uint32_t c1 = 0xcc9e2d51;
    const uint32_t c2 = 0x1b873593;
    const uint32_t r1 = 15;
    const uint32_t r2 = 13;
    const uint32_t m = 5;
    const uint32_t n = 0xe6546b64;
    uint32_t hash = seed;
    const int nblocks = len / 4;
    const uint32_t *blocks = (const uint32_t *)(key);
    int i;
    for (i = 0; i < nblocks; i++) {
        uint32_t k = blocks[i];
        k *= c1;
        k = (k << r1) | (k >> (32 - r1));
        k *= c2;
        hash ^= k;
        hash = (hash << r2) | (hash >> (32 - r2));
        hash = hash * m + n;
    }
    const uint8_t *tail = (const uint8_t *)(key + nblocks * 4);
    uint32_t k1 = 0;
    switch (len & 3) {
        case 3:
            k1 ^= tail[2] << 16;
        case 2:
            k1 ^= tail[1] << 8;
        case 1:
            k1 ^= tail[0];
            k1 *= c1;
            k1 = (k1 << r1) | (k1 >> (32 - r1));
            k1 *= c2;
            hash ^= k1;
    }
    hash ^= len;
    hash ^= hash >> 16;
    hash *= 0x85ebca6b;
    hash ^= hash >> 13;
    hash *= 0xc2b2ae35;
    hash ^= hash >> 16;
    return hash;
}
Referenced by ck_murmurhash3_32(), ck_murmurhash3_str(), ck_murmurhash3_strn(), and ck_tokenizer_hash().
ck_murmurhash3_128()
void ck_murmurhash3_128 (const void * key, size_t len, uint32_t seed, uint64_t * out1, uint64_t * out2)
MurmurHash3-128bit hash function (produces two 64-bit values).
Parameters
key Data to hash
len Length in bytes
seed Optional seed value (use 0 for default)
out1 First 64 bits of hash output
out2 Second 64 bits of hash output
ck_murmurhash3_32()
uint32_t ck_murmurhash3_32 (const void * key, size_t len, uint32_t seed)
MurmurHash3-32bit hash function (alternative name).
Parameters
key Data to hash
len Length in bytes
seed Optional seed value (use 0 for default)
Returns
32-bit hash value
Definition at line 68 of file murmurhash3.c.
{
    return ck_murmurhash3((const char *)key, (uint32_t)len, seed);
}
References ck_murmurhash3().
Referenced by ck_murmurhash3_str().
ck_murmurhash3_str()
static uint32_t ck_murmurhash3_str (const char * str, uint32_t seed) inline static
MurmurHash3-32bit for string (null-terminated).
Definition at line 55 of file murmurhash3.h.
{
    return ck_murmurhash3_32(str, strlen(str), seed);
}
References ck_murmurhash3_32().
Referenced by ck_tokenizer_hash_str().
ck_murmurhash3_strn()
static uint32_t ck_murmurhash3_strn (const char * str, size_t len, uint32_t seed) inline static
MurmurHash3-32bit for string with length.
Definition at line 62 of file murmurhash3.h.
{
    return ck_murmurhash3(str, len, seed);
}
References ck_murmurhash3().