sigmoid_kernels.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
sigmoid_kernels.c File Reference
Sigmoid activation kernels with SIMD (AVX512)
#include <math.h>
#include <stddef.h>
#include <stdlib.h>
Functions
void sigmoid_backward (const float *input, const float *d_output, float *d_input, size_t n)
void sigmoid_forward (const float *input, float *output, size_t n)
float sigmoid_scalar (float x)
Detailed Description
Sigmoid activation kernels with SIMD (AVX512)
CK-ENGINE KERNEL RULES:
NO malloc/free - memory via bump allocator, pointers passed in
NO OpenMP - parallelization at orchestrator/codegen layer
API must define: inputs, outputs, workspace, and memory layouts
Pure computation - deterministic, no side effects
After changes: make test && make llamacpp-parity-full
Sigmoid: y = 1 / (1 + exp(-x))
Definition in file sigmoid_kernels.c.
Function Documentation
sigmoid_backward()
void sigmoid_backward (const float * input, const float * d_output, float * d_input, size_t n)
Definition at line 138 of file sigmoid_kernels.c.
{
#if defined(__AVX512F__)
    sigmoid_backward_avx512(input, d_output, d_input, n);
#else
    for (size_t i = 0; i < n; ++i) {
        float x = input[i];
        float s = sigmoid_scalar(x);
        float s_prime = s * (1.0f - s);
        d_input[i] = d_output[i] * s_prime;
    }
#endif
}
References sigmoid_scalar().
Referenced by sigmoid_backward_bf16().
sigmoid_forward()
void sigmoid_forward (const float * input, float * output, size_t n)
Definition at line 122 of file sigmoid_kernels.c.
{
#if defined(__AVX512F__)
    sigmoid_forward_avx512(input, output, n);
#else
    for (size_t i = 0; i < n; ++i) {
        output[i] = sigmoid_scalar(input[i]);
    }
#endif
}
References sigmoid_scalar().
Referenced by sigmoid_forward_bf16().
sigmoid_scalar()
float sigmoid_scalar (float x)
Definition at line 26 of file sigmoid_kernels.c.
{
    return 1.0f / (1.0f + expf(-x));
}
Referenced by sigmoid_backward(), sigmoid_forward(), swiglu_backward(), swiglu_backward_bf16(), swiglu_backward_exact(), swiglu_forward(), swiglu_forward_bf16(), and swiglu_forward_exact().