sigmoid_kernels_bf16.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
sigmoid_kernels_bf16.c File Reference
#include <stddef.h>
#include <stdint.h>
#include "bf16_utils.h"
#include "ckernel_engine.h"
Functions
void sigmoid_backward_bf16 (const uint16_t *input, const uint16_t *d_output, uint16_t *d_input, size_t n, float *scratch_input, float *scratch_d_output, float *scratch_d_input)
void sigmoid_forward_bf16 (const uint16_t *input, uint16_t *output, size_t n, float *scratch_input, float *scratch_output)
Function Documentation
sigmoid_backward_bf16()
void sigmoid_backward_bf16 (const uint16_t * input, const uint16_t * d_output, uint16_t * d_input, size_t n, float * scratch_input, float * scratch_d_output, float * scratch_d_input)
Definition at line 29 of file sigmoid_kernels_bf16.c.
{
    if (!input || !d_output || !d_input || n == 0) return;
    if (!scratch_input || !scratch_d_output || !scratch_d_input) return;
    bf16_tensor_to_float(input, scratch_input, n);
    bf16_tensor_to_float(d_output, scratch_d_output, n);
    sigmoid_backward(scratch_input, scratch_d_output, scratch_d_input, n);
    float_tensor_to_bf16(scratch_d_input, d_input, n);
}
References bf16_tensor_to_float(), float_tensor_to_bf16(), and sigmoid_backward().
sigmoid_forward_bf16()
void sigmoid_forward_bf16 (const uint16_t * input, uint16_t * output, size_t n, float * scratch_input, float * scratch_output)
Definition at line 11 of file sigmoid_kernels_bf16.c.
{
    if (!input || !output || n == 0) return;
    if (!scratch_input || !scratch_output) return;
    bf16_tensor_to_float(input, scratch_input, n);
    sigmoid_forward(scratch_input, scratch_output, n);
    float_tensor_to_bf16(scratch_output, output, n);
}
References bf16_tensor_to_float(), float_tensor_to_bf16(), and sigmoid_forward().