ck-kernel-inference.h File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
ck-kernel-inference.h File Reference
AUTO-GENERATED: qwen2_0.5b_decode Memory Layout.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct QWEN2_0_5B_DECODECanary
struct QWEN2_0_5B_DECODEFooterOffsets
struct QWEN2_0_5B_DECODEGlobalOffsets
struct QWEN2_0_5B_DECODEHeaderOffsets
struct QWEN2_0_5B_DECODELayerOffsets
struct QWEN2_0_5B_DECODEModel
Macros
#define QWEN2_0_5B_DECODE_ACTIVATION_BYTES 3256169984ULL
#define QWEN2_0_5B_DECODE_CANARY_COUNT 566
#define QWEN2_0_5B_DECODE_CANARY_SIZE 64
#define QWEN2_0_5B_DECODE_CANARY_VALUE 0xDEADBEEFUL
#define QWEN2_0_5B_DECODE_DTYPE_BYTES 4
#define QWEN2_0_5B_DECODE_EMBED_DIM 896
#define QWEN2_0_5B_DECODE_HEAD_DIM 64
#define QWEN2_0_5B_DECODE_INTERMEDIATE 4864
#define QWEN2_0_5B_DECODE_LAYER(layer_id) (&QWEN2_0_5B_DECODE_LAYERS[layer_id])
#define QWEN2_0_5B_DECODE_LAYER_STRIDE 0x0892CC00ULL
#define QWEN2_0_5B_DECODE_MAGIC 0x434B454EUL
#define QWEN2_0_5B_DECODE_MAX_SEQ_LEN 131072
#define QWEN2_0_5B_DECODE_NUM_HEADS 14
#define QWEN2_0_5B_DECODE_NUM_KV_HEADS 2
#define QWEN2_0_5B_DECODE_NUM_LAYERS 24
#define QWEN2_0_5B_DECODE_NUM_MERGES 0
#define QWEN2_0_5B_DECODE_PTR(model, offset) ((float*)((char*)(model)->base + (offset)))
#define QWEN2_0_5B_DECODE_PTR_BF16(model, offset) ((uint16_t*)((char*)(model)->base + (offset)))
#define QWEN2_0_5B_DECODE_TOTAL_BYTES 3573889600ULL
#define QWEN2_0_5B_DECODE_TOTAL_VOCAB_BYTES 0
#define QWEN2_0_5B_DECODE_VOCAB_SIZE 151936
#define QWEN2_0_5B_DECODE_WEIGHT_BYTES 317683328ULL
Functions
void qwen2_0_5b_decode_decode (QWEN2_0_5B_DECODEModel *model, const int *token, int token_index)
void qwen2_0_5b_decode_forward (QWEN2_0_5B_DECODEModel *model, const int *tokens, int num_tokens)
int qwen2_0_5b_decode_model_allocate (QWEN2_0_5B_DECODEModel *model)
void qwen2_0_5b_decode_model_free (QWEN2_0_5B_DECODEModel *model)
int qwen2_0_5b_decode_verify_canaries (QWEN2_0_5B_DECODEModel *model)
Variables
static const QWEN2_0_5B_DECODECanary QWEN2_0_5B_DECODE_CANARIES []
static const QWEN2_0_5B_DECODEFooterOffsets QWEN2_0_5B_DECODE_FOOTER
static const QWEN2_0_5B_DECODEGlobalOffsets QWEN2_0_5B_DECODE_GLOBALS
static const QWEN2_0_5B_DECODEHeaderOffsets QWEN2_0_5B_DECODE_HEADER
static const QWEN2_0_5B_DECODELayerOffsets QWEN2_0_5B_DECODE_LAYERS [24]
Detailed Description
AUTO-GENERATED: qwen2_0.5b_decode Memory Layout.
Generated: 2026-01-12T04:06:36.660353 UTC Total Memory: 3.57 GB
DO NOT EDIT - Regenerate with build_ir_v3.py
Definition in file v6.6/test_generated/ck-kernel-inference.h.
Macro Definition Documentation
QWEN2_0_5B_DECODE_ACTIVATION_BYTES
#define QWEN2_0_5B_DECODE_ACTIVATION_BYTES 3256169984ULL
Definition at line 39 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_CANARY_COUNT
#define QWEN2_0_5B_DECODE_CANARY_COUNT 566
Definition at line 1259 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_CANARY_SIZE
#define QWEN2_0_5B_DECODE_CANARY_SIZE 64
Definition at line 43 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_CANARY_VALUE
#define QWEN2_0_5B_DECODE_CANARY_VALUE 0xDEADBEEFUL
Definition at line 42 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_DTYPE_BYTES
#define QWEN2_0_5B_DECODE_DTYPE_BYTES 4
Definition at line 35 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_EMBED_DIM
#define QWEN2_0_5B_DECODE_EMBED_DIM 896
Definition at line 25 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_HEAD_DIM
#define QWEN2_0_5B_DECODE_HEAD_DIM 64
Definition at line 28 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_INTERMEDIATE
#define QWEN2_0_5B_DECODE_INTERMEDIATE 4864
Definition at line 29 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_LAYER
#define QWEN2_0_5B_DECODE_LAYER (layer_id) (&QWEN2_0_5B_DECODE_LAYERS[layer_id])
Definition at line 1280 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_LAYER_STRIDE
#define QWEN2_0_5B_DECODE_LAYER_STRIDE 0x0892CC00ULL
Definition at line 648 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_MAGIC
#define QWEN2_0_5B_DECODE_MAGIC 0x434B454EUL
Definition at line 41 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_MAX_SEQ_LEN
#define QWEN2_0_5B_DECODE_MAX_SEQ_LEN 131072
Definition at line 32 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_NUM_HEADS
#define QWEN2_0_5B_DECODE_NUM_HEADS 14
Definition at line 26 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_NUM_KV_HEADS
#define QWEN2_0_5B_DECODE_NUM_KV_HEADS 2
Definition at line 27 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_NUM_LAYERS
#define QWEN2_0_5B_DECODE_NUM_LAYERS 24
Definition at line 30 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_NUM_MERGES
#define QWEN2_0_5B_DECODE_NUM_MERGES 0
Definition at line 33 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_PTR
#define QWEN2_0_5B_DECODE_PTR (model, offset) ((float*)((char*)(model)->base + (offset)))
Definition at line 1274 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_PTR_BF16
#define QWEN2_0_5B_DECODE_PTR_BF16 (model, offset) ((uint16_t*)((char*)(model)->base + (offset)))
Definition at line 1277 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_TOTAL_BYTES
#define QWEN2_0_5B_DECODE_TOTAL_BYTES 3573889600ULL
Definition at line 37 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_TOTAL_VOCAB_BYTES
#define QWEN2_0_5B_DECODE_TOTAL_VOCAB_BYTES 0
Definition at line 34 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_VOCAB_SIZE
#define QWEN2_0_5B_DECODE_VOCAB_SIZE 151936
Definition at line 31 of file v6.6/test_generated/ck-kernel-inference.h.
QWEN2_0_5B_DECODE_WEIGHT_BYTES
#define QWEN2_0_5B_DECODE_WEIGHT_BYTES 317683328ULL
Definition at line 38 of file v6.6/test_generated/ck-kernel-inference.h.
Function Documentation
qwen2_0_5b_decode_decode()
void qwen2_0_5b_decode_decode (QWEN2_0_5B_DECODEModel * model, const int * token, int token_index)
Definition at line 8022 of file v6.5/test_generated/ck-kernel-inference.c.
{
    qwen2_0_5b_decode_decode_token(model, token, token_index);
}
References qwen2_0_5b_decode_decode_token(), qwen2_0_5b_decode_decode_token(), qwen2_0_5b_decode_decode_token(), qwen2_0_5b_decode_decode_token(), qwen2_0_5b_decode_decode_token(), and token.
Referenced by ck_model_decode().
qwen2_0_5b_decode_forward()
void qwen2_0_5b_decode_forward (QWEN2_0_5B_DECODEModel * model, const int * tokens, int num_tokens)
Definition at line 8013 of file v6.5/test_generated/ck-kernel-inference.c.
  {
    if (!model || !tokens || num_tokens <= 0) return;
    qwen2_0_5b_decode_forward_prefill_impl(model, tokens, num_tokens);
}
References qwen2_0_5b_decode_forward_prefill_impl(), qwen2_0_5b_decode_forward_prefill_impl(), qwen2_0_5b_decode_forward_prefill_impl(), qwen2_0_5b_decode_forward_prefill_impl(), and qwen2_0_5b_decode_forward_prefill_impl().
Referenced by ck_model_forward().
qwen2_0_5b_decode_model_allocate()
int qwen2_0_5b_decode_model_allocate (QWEN2_0_5B_DECODEModel * model)
Definition at line 88 of file v6.5/test_generated/ck-kernel-inference.c.
{
    size_t total = QWEN2_0_5B_DECODE_TOTAL_BYTES;
#ifdef __linux__
    model->base = mmap(NULL, total,
                       PROT_READ | PROT_WRITE,
                       MAP_PRIVATE | MAP_ANONYMOUS | MAP_HUGETLB,
                       -1, 0);
    if (model->base == MAP_FAILED) {
        model->base = mmap(NULL, total,
                           PROT_READ | PROT_WRITE,
                           MAP_PRIVATE | MAP_ANONYMOUS,
                           -1, 0);
    }
    if (model->base == MAP_FAILED) {
        perror("mmap failed");
        return -1;
    }
#else
    model->base = aligned_alloc(64, total);
    if (!model->base) {
        perror("aligned_alloc failed");
        return -1;
    }
#endif
    model->total_bytes = total;
    /* Initialize magic header */
    MagicHeader *header = (MagicHeader *)model->base;
    header->magic = QWEN2_0_5B_DECODE_MAGIC;
    header->version = 5;
    header->total_bytes = QWEN2_0_5B_DECODE_TOTAL_BYTES;
    header->weight_bytes = QWEN2_0_5B_DECODE_WEIGHT_BYTES;
    header->activation_bytes = QWEN2_0_5B_DECODE_ACTIVATION_BYTES;
    header->num_layers = QWEN2_0_5B_DECODE_NUM_LAYERS;
    header->embed_dim = QWEN2_0_5B_DECODE_EMBED_DIM;
    header->num_heads = QWEN2_0_5B_DECODE_NUM_HEADS;
    header->vocab_size = QWEN2_0_5B_DECODE_VOCAB_SIZE;
    header->max_seq_len = QWEN2_0_5B_DECODE_MAX_SEQ_LEN;
    header->canary_count = QWEN2_0_5B_DECODE_CANARY_COUNT;
    /* Initialize canary guards */
    for (int i = 0; i < QWEN2_0_5B_DECODE_CANARY_COUNT; i++) {
        uint32_t *ptr = (uint32_t*)((char*)model->base + QWEN2_0_5B_DECODE_CANARIES[i].offset);
        for (int j = 0; j < (QWEN2_0_5B_DECODE_CANARY_SIZE / 4); j++) {
            ptr[j] = QWEN2_0_5B_DECODE_CANARY_VALUE;
        }
    }
    return 0;
}
References QWEN2_0_5B_DECODEModel::base, MagicHeader, QWEN2_0_5B_DECODECanary::offset, QWEN2_0_5B_DECODE_ACTIVATION_BYTES, QWEN2_0_5B_DECODE_CANARIES, QWEN2_0_5B_DECODE_CANARY_COUNT, QWEN2_0_5B_DECODE_CANARY_SIZE, QWEN2_0_5B_DECODE_CANARY_VALUE, QWEN2_0_5B_DECODE_EMBED_DIM, QWEN2_0_5B_DECODE_MAGIC, QWEN2_0_5B_DECODE_MAX_SEQ_LEN, QWEN2_0_5B_DECODE_NUM_HEADS, QWEN2_0_5B_DECODE_NUM_LAYERS, QWEN2_0_5B_DECODE_TOTAL_BYTES, QWEN2_0_5B_DECODE_VOCAB_SIZE, QWEN2_0_5B_DECODE_WEIGHT_BYTES, and QWEN2_0_5B_DECODEModel::total_bytes.
Referenced by ck_model_create().
qwen2_0_5b_decode_model_free()
void qwen2_0_5b_decode_model_free (QWEN2_0_5B_DECODEModel * model)
Definition at line 141 of file v6.5/test_generated/ck-kernel-inference.c.
{
    if (!model || !model->base) return;
#ifdef __linux__
    munmap(model->base, model->total_bytes);
#else
    free(model->base);
#endif
    model->base = NULL;
    model->total_bytes = 0;
}
References QWEN2_0_5B_DECODEModel::base, and QWEN2_0_5B_DECODEModel::total_bytes.
Referenced by ck_model_free().
qwen2_0_5b_decode_verify_canaries()
int qwen2_0_5b_decode_verify_canaries (QWEN2_0_5B_DECODEModel * model)
Definition at line 152 of file v6.5/test_generated/ck-kernel-inference.c.
{
    int errors = 0;
    uint32_t *ptr;
    for (int i = 0; i < QWEN2_0_5B_DECODE_CANARY_COUNT; i++) {
        ptr = (uint32_t*)((char*)model->base + QWEN2_0_5B_DECODE_CANARIES[i].offset);
        for (int j = 0; j < 4; j++) {
            if (ptr[j] != QWEN2_0_5B_DECODE_CANARY_VALUE) {
                fprintf(stderr, "CANARY CORRUPTION: %s at offset 0x%lX\n",
                        QWEN2_0_5B_DECODE_CANARIES[i].name,
                        QWEN2_0_5B_DECODE_CANARIES[i].offset);
                errors++;
                break;
            }
        }
    }
    return errors;
}
References QWEN2_0_5B_DECODEModel::base, QWEN2_0_5B_DECODECanary::offset, QWEN2_0_5B_DECODE_CANARIES, QWEN2_0_5B_DECODE_CANARY_COUNT, and QWEN2_0_5B_DECODE_CANARY_VALUE.
Referenced by ck_model_verify_canaries().
Variable Documentation
QWEN2_0_5B_DECODE_CANARIES
const QWEN2_0_5B_DECODECanary QWEN2_0_5B_DECODE_CANARIES[] static
Definition at line 691 of file v6.6/test_generated/ck-kernel-inference.h.
{
    {0x00000040, "header_start"},
    {0x05376080, "token_emb_end"},
    {0x0538AF00, "vocab_offsets_end"},
    {0x0538AF40, "vocab_strings_end"},
    {0x0538AF80, "vocab_merges_end"},
    {0x0538BFC0, "embedded_input_end"},
    {0x0538C000, "header_end"},
    {0x0538C040, "layer_0_start"},
    {0x0538C2C0, "layer.0.ln1_gamma_end"},
    {0x0538D300, "layer.0.ln1_out_end"},
    {0x0540B340, "layer.0.wq_end"},
    {0x0540B5C0, "layer.0.bq_end"},
    {0x0541D600, "layer.0.wk_end"},
    {0x0541D700, "layer.0.bk_end"},
    {0x0542F740, "layer.0.wv_end"},
    {0x0542F840, "layer.0.bv_end"},
    {0x05430680, "layer.0.q_end"},
    {0x094306C0, "layer.0.k_end"},
    {0x0D430700, "layer.0.v_end"},
    {0x0D4AE740, "layer.0.wo_end"},
    {0x0D4AF780, "layer.0.proj_tmp_end"},
    {0x0D4B07C0, "layer.0.proj_scratch_end"},
    {0x0D4B1800, "layer.0.residual1_end"},
    {0x0D4B1A80, "layer.0.ln2_gamma_end"},
    {0x0D4B2AC0, "layer.0.ln2_out_end"},
    {0x0DA0AB00, "layer.0.w1_end"},
    {0x0DCB6B40, "layer.0.w2_end"},
    {0x0DCB7B80, "layer.0.mlp_out_end"},
    {0x0DCB8BC0, "layer.0.output_end"},
    {0x0DCB8C00, "layer_0_end"},
    {0x0DCB8C40, "layer_1_start"},
    {0x0DCB8EC0, "layer.1.ln1_gamma_end"},
    {0x0DCB9F00, "layer.1.ln1_out_end"},
    {0x0DD37F40, "layer.1.wq_end"},
    {0x0DD381C0, "layer.1.bq_end"},
    {0x0DD4A200, "layer.1.wk_end"},
    {0x0DD4A300, "layer.1.bk_end"},
    {0x0DD5C340, "layer.1.wv_end"},
    {0x0DD5C440, "layer.1.bv_end"},
    {0x0DD5D280, "layer.1.q_end"},
    {0x11D5D2C0, "layer.1.k_end"},
    {0x15D5D300, "layer.1.v_end"},
    {0x15DDB340, "layer.1.wo_end"},
    {0x15DDC380, "layer.1.proj_tmp_end"},
    {0x15DDD3C0, "layer.1.proj_scratch_end"},
    {0x15DDE400, "layer.1.residual1_end"},
    {0x15DDE680, "layer.1.ln2_gamma_end"},
    {0x15DDF6C0, "layer.1.ln2_out_end"},
    {0x16337700, "layer.1.w1_end"},
    {0x165E3740, "layer.1.w2_end"},
    {0x165E4780, "layer.1.mlp_out_end"},
    {0x165E57C0, "layer.1.output_end"},
    {0x165E5800, "layer_1_end"},
    {0x165E5840, "layer_2_start"},
    {0x165E5AC0, "layer.2.ln1_gamma_end"},
    {0x165E6B00, "layer.2.ln1_out_end"},
    {0x16664B40, "layer.2.wq_end"},
    {0x16664DC0, "layer.2.bq_end"},
    {0x16676E00, "layer.2.wk_end"},
    {0x16676F00, "layer.2.bk_end"},
    {0x16688F40, "layer.2.wv_end"},
    {0x16689040, "layer.2.bv_end"},
    {0x16689E80, "layer.2.q_end"},
    {0x1A689EC0, "layer.2.k_end"},
    {0x1E689F00, "layer.2.v_end"},
    {0x1E707F40, "layer.2.wo_end"},
    {0x1E708F80, "layer.2.proj_tmp_end"},
    {0x1E709FC0, "layer.2.proj_scratch_end"},
    {0x1E70B000, "layer.2.residual1_end"},
    {0x1E70B280, "layer.2.ln2_gamma_end"},
    {0x1E70C2C0, "layer.2.ln2_out_end"},
    {0x1EC64300, "layer.2.w1_end"},
    {0x1EF10340, "layer.2.w2_end"},
    {0x1EF11380, "layer.2.mlp_out_end"},
    {0x1EF123C0, "layer.2.output_end"},
    {0x1EF12400, "layer_2_end"},
    {0x1EF12440, "layer_3_start"},
    {0x1EF126C0, "layer.3.ln1_gamma_end"},
    {0x1EF13700, "layer.3.ln1_out_end"},
    {0x1EF91740, "layer.3.wq_end"},
    {0x1EF919C0, "layer.3.bq_end"},
    {0x1EFA3A00, "layer.3.wk_end"},
    {0x1EFA3B00, "layer.3.bk_end"},
    {0x1EFB5B40, "layer.3.wv_end"},
    {0x1EFB5C40, "layer.3.bv_end"},
    {0x1EFB6A80, "layer.3.q_end"},
    {0x22FB6AC0, "layer.3.k_end"},
    {0x26FB6B00, "layer.3.v_end"},
    {0x27034B40, "layer.3.wo_end"},
    {0x27035B80, "layer.3.proj_tmp_end"},
    {0x27036BC0, "layer.3.proj_scratch_end"},
    {0x27037C00, "layer.3.residual1_end"},
    {0x27037E80, "layer.3.ln2_gamma_end"},
    {0x27038EC0, "layer.3.ln2_out_end"},
    {0x27590F00, "layer.3.w1_end"},
    {0x2783CF40, "layer.3.w2_end"},
    {0x2783DF80, "layer.3.mlp_out_end"},
    {0x2783EFC0, "layer.3.output_end"},
    {0x2783F000, "layer_3_end"},
    {0x2783F040, "layer_4_start"},
    {0x2783F2C0, "layer.4.ln1_gamma_end"},
    {0x27840300, "layer.4.ln1_out_end"},
    {0x278BE340, "layer.4.wq_end"},
    {0x278BE5C0, "layer.4.bq_end"},
    {0x278D0600, "layer.4.wk_end"},
    {0x278D0700, "layer.4.bk_end"},
    {0x278E2740, "layer.4.wv_end"},
    {0x278E2840, "layer.4.bv_end"},
    {0x278E3680, "layer.4.q_end"},
    {0x2B8E36C0, "layer.4.k_end"},
    {0x2F8E3700, "layer.4.v_end"},
    {0x2F961740, "layer.4.wo_end"},
    {0x2F962780, "layer.4.proj_tmp_end"},
    {0x2F9637C0, "layer.4.proj_scratch_end"},
    {0x2F964800, "layer.4.residual1_end"},
    {0x2F964A80, "layer.4.ln2_gamma_end"},
    {0x2F965AC0, "layer.4.ln2_out_end"},
    {0x2FEBDB00, "layer.4.w1_end"},
    {0x30169B40, "layer.4.w2_end"},
    {0x3016AB80, "layer.4.mlp_out_end"},
    {0x3016BBC0, "layer.4.output_end"},
    {0x3016BC00, "layer_4_end"},
    {0x3016BC40, "layer_5_start"},
    {0x3016BEC0, "layer.5.ln1_gamma_end"},
    {0x3016CF00, "layer.5.ln1_out_end"},
    {0x301EAF40, "layer.5.wq_end"},
    {0x301EB1C0, "layer.5.bq_end"},
    {0x301FD200, "layer.5.wk_end"},
    {0x301FD300, "layer.5.bk_end"},
    {0x3020F340, "layer.5.wv_end"},
    {0x3020F440, "layer.5.bv_end"},
    {0x30210280, "layer.5.q_end"},
    {0x342102C0, "layer.5.k_end"},
    {0x38210300, "layer.5.v_end"},
    {0x3828E340, "layer.5.wo_end"},
    {0x3828F380, "layer.5.proj_tmp_end"},
    {0x382903C0, "layer.5.proj_scratch_end"},
    {0x38291400, "layer.5.residual1_end"},
    {0x38291680, "layer.5.ln2_gamma_end"},
    {0x382926C0, "layer.5.ln2_out_end"},
    {0x387EA700, "layer.5.w1_end"},
    {0x38A96740, "layer.5.w2_end"},
    {0x38A97780, "layer.5.mlp_out_end"},
    {0x38A987C0, "layer.5.output_end"},
    {0x38A98800, "layer_5_end"},
    {0x38A98840, "layer_6_start"},
    {0x38A98AC0, "layer.6.ln1_gamma_end"},
    {0x38A99B00, "layer.6.ln1_out_end"},
    {0x38B17B40, "layer.6.wq_end"},
    {0x38B17DC0, "layer.6.bq_end"},
    {0x38B29E00, "layer.6.wk_end"},
    {0x38B29F00, "layer.6.bk_end"},
    {0x38B3BF40, "layer.6.wv_end"},
    {0x38B3C040, "layer.6.bv_end"},
    {0x38B3CE80, "layer.6.q_end"},
    {0x3CB3CEC0, "layer.6.k_end"},
    {0x40B3CF00, "layer.6.v_end"},
    {0x40BBAF40, "layer.6.wo_end"},
    {0x40BBBF80, "layer.6.proj_tmp_end"},
    {0x40BBCFC0, "layer.6.proj_scratch_end"},
    {0x40BBE000, "layer.6.residual1_end"},
    {0x40BBE280, "layer.6.ln2_gamma_end"},
    {0x40BBF2C0, "layer.6.ln2_out_end"},
    {0x41117300, "layer.6.w1_end"},
    {0x413C3340, "layer.6.w2_end"},
    {0x413C4380, "layer.6.mlp_out_end"},
    {0x413C53C0, "layer.6.output_end"},
    {0x413C5400, "layer_6_end"},
    {0x413C5440, "layer_7_start"},
    {0x413C56C0, "layer.7.ln1_gamma_end"},
    {0x413C6700, "layer.7.ln1_out_end"},
    {0x41444740, "layer.7.wq_end"},
    {0x414449C0, "layer.7.bq_end"},
    {0x41456A00, "layer.7.wk_end"},
    {0x41456B00, "layer.7.bk_end"},
    {0x41468B40, "layer.7.wv_end"},
    {0x41468C40, "layer.7.bv_end"},
    {0x41469A80, "layer.7.q_end"},
    {0x45469AC0, "layer.7.k_end"},
    {0x49469B00, "layer.7.v_end"},
    {0x494E7B40, "layer.7.wo_end"},
    {0x494E8B80, "layer.7.proj_tmp_end"},
    {0x494E9BC0, "layer.7.proj_scratch_end"},
    {0x494EAC00, "layer.7.residual1_end"},
    {0x494EAE80, "layer.7.ln2_gamma_end"},
    {0x494EBEC0, "layer.7.ln2_out_end"},
    {0x49A43F00, "layer.7.w1_end"},
    {0x49CEFF40, "layer.7.w2_end"},
    {0x49CF0F80, "layer.7.mlp_out_end"},
    {0x49CF1FC0, "layer.7.output_end"},
    {0x49CF2000, "layer_7_end"},
    {0x49CF2040, "layer_8_start"},
    {0x49CF22C0, "layer.8.ln1_gamma_end"},
    {0x49CF3300, "layer.8.ln1_out_end"},
    {0x49D71340, "layer.8.wq_end"},
    {0x49D715C0, "layer.8.bq_end"},
    {0x49D83600, "layer.8.wk_end"},
    {0x49D83700, "layer.8.bk_end"},
    {0x49D95740, "layer.8.wv_end"},
    {0x49D95840, "layer.8.bv_end"},
    {0x49D96680, "layer.8.q_end"},
    {0x4DD966C0, "layer.8.k_end"},
    {0x51D96700, "layer.8.v_end"},
    {0x51E14740, "layer.8.wo_end"},
    {0x51E15780, "layer.8.proj_tmp_end"},
    {0x51E167C0, "layer.8.proj_scratch_end"},
    {0x51E17800, "layer.8.residual1_end"},
    {0x51E17A80, "layer.8.ln2_gamma_end"},
    {0x51E18AC0, "layer.8.ln2_out_end"},
    {0x52370B00, "layer.8.w1_end"},
    {0x5261CB40, "layer.8.w2_end"},
    {0x5261DB80, "layer.8.mlp_out_end"},
    {0x5261EBC0, "layer.8.output_end"},
    {0x5261EC00, "layer_8_end"},
    {0x5261EC40, "layer_9_start"},
    {0x5261EEC0, "layer.9.ln1_gamma_end"},
    {0x5261FF00, "layer.9.ln1_out_end"},
    {0x5269DF40, "layer.9.wq_end"},
    {0x5269E1C0, "layer.9.bq_end"},
    {0x526B0200, "layer.9.wk_end"},
    {0x526B0300, "layer.9.bk_end"},
    {0x526C2340, "layer.9.wv_end"},
    {0x526C2440, "layer.9.bv_end"},
    {0x526C3280, "layer.9.q_end"},
    {0x566C32C0, "layer.9.k_end"},
    {0x5A6C3300, "layer.9.v_end"},
    {0x5A741340, "layer.9.wo_end"},
    {0x5A742380, "layer.9.proj_tmp_end"},
    {0x5A7433C0, "layer.9.proj_scratch_end"},
    {0x5A744400, "layer.9.residual1_end"},
    {0x5A744680, "layer.9.ln2_gamma_end"},
    {0x5A7456C0, "layer.9.ln2_out_end"},
    {0x5AC9D700, "layer.9.w1_end"},
    {0x5AF49740, "layer.9.w2_end"},
    {0x5AF4A780, "layer.9.mlp_out_end"},
    {0x5AF4B7C0, "layer.9.output_end"},
    {0x5AF4B800, "layer_9_end"},
    {0x5AF4B840, "layer_10_start"},
    {0x5AF4BAC0, "layer.10.ln1_gamma_end"},
    {0x5AF4CB00, "layer.10.ln1_out_end"},
    {0x5AFCAB40, "layer.10.wq_end"},
    {0x5AFCADC0, "layer.10.bq_end"},
    {0x5AFDCE00, "layer.10.wk_end"},
    {0x5AFDCF00, "layer.10.bk_end"},
    {0x5AFEEF40, "layer.10.wv_end"},
    {0x5AFEF040, "layer.10.bv_end"},
    {0x5AFEFE80, "layer.10.q_end"},
    {0x5EFEFEC0, "layer.10.k_end"},
    {0x62FEFF00, "layer.10.v_end"},
    {0x6306DF40, "layer.10.wo_end"},
    {0x6306EF80, "layer.10.proj_tmp_end"},
    {0x6306FFC0, "layer.10.proj_scratch_end"},
    {0x63071000, "layer.10.residual1_end"},
    {0x63071280, "layer.10.ln2_gamma_end"},
    {0x630722C0, "layer.10.ln2_out_end"},
    {0x635CA300, "layer.10.w1_end"},
    {0x63876340, "layer.10.w2_end"},
    {0x63877380, "layer.10.mlp_out_end"},
    {0x638783C0, "layer.10.output_end"},
    {0x63878400, "layer_10_end"},
    {0x63878440, "layer_11_start"},
    {0x638786C0, "layer.11.ln1_gamma_end"},
    {0x63879700, "layer.11.ln1_out_end"},
    {0x638F7740, "layer.11.wq_end"},
    {0x638F79C0, "layer.11.bq_end"},
    {0x63909A00, "layer.11.wk_end"},
    {0x63909B00, "layer.11.bk_end"},
    {0x6391BB40, "layer.11.wv_end"},
    {0x6391BC40, "layer.11.bv_end"},
    {0x6391CA80, "layer.11.q_end"},
    {0x6791CAC0, "layer.11.k_end"},
    {0x6B91CB00, "layer.11.v_end"},
    {0x6B99AB40, "layer.11.wo_end"},
    {0x6B99BB80, "layer.11.proj_tmp_end"},
    {0x6B99CBC0, "layer.11.proj_scratch_end"},
    {0x6B99DC00, "layer.11.residual1_end"},
    {0x6B99DE80, "layer.11.ln2_gamma_end"},
    {0x6B99EEC0, "layer.11.ln2_out_end"},
    {0x6BEF6F00, "layer.11.w1_end"},
    {0x6C1A2F40, "layer.11.w2_end"},
    {0x6C1A3F80, "layer.11.mlp_out_end"},
    {0x6C1A4FC0, "layer.11.output_end"},
    {0x6C1A5000, "layer_11_end"},
    {0x6C1A5040, "layer_12_start"},
    {0x6C1A52C0, "layer.12.ln1_gamma_end"},
    {0x6C1A6300, "layer.12.ln1_out_end"},
    {0x6C224340, "layer.12.wq_end"},
    {0x6C2245C0, "layer.12.bq_end"},
    {0x6C236600, "layer.12.wk_end"},
    {0x6C236700, "layer.12.bk_end"},
    {0x6C248740, "layer.12.wv_end"},
    {0x6C248840, "layer.12.bv_end"},
    {0x6C249680, "layer.12.q_end"},
    {0x702496C0, "layer.12.k_end"},
    {0x74249700, "layer.12.v_end"},
    {0x742C7740, "layer.12.wo_end"},
    {0x742C8780, "layer.12.proj_tmp_end"},
    {0x742C97C0, "layer.12.proj_scratch_end"},
    {0x742CA800, "layer.12.residual1_end"},
    {0x742CAA80, "layer.12.ln2_gamma_end"},
    {0x742CBAC0, "layer.12.ln2_out_end"},
    {0x74823B00, "layer.12.w1_end"},
    {0x74ACFB40, "layer.12.w2_end"},
    {0x74AD0B80, "layer.12.mlp_out_end"},
    {0x74AD1BC0, "layer.12.output_end"},
    {0x74AD1C00, "layer_12_end"},
    {0x74AD1C40, "layer_13_start"},
    {0x74AD1EC0, "layer.13.ln1_gamma_end"},
    {0x74AD2F00, "layer.13.ln1_out_end"},
    {0x74B50F40, "layer.13.wq_end"},
    {0x74B511C0, "layer.13.bq_end"},
    {0x74B63200, "layer.13.wk_end"},
    {0x74B63300, "layer.13.bk_end"},
    {0x74B75340, "layer.13.wv_end"},
    {0x74B75440, "layer.13.bv_end"},
    {0x74B76280, "layer.13.q_end"},
    {0x78B762C0, "layer.13.k_end"},
    {0x7CB76300, "layer.13.v_end"},
    {0x7CBF4340, "layer.13.wo_end"},
    {0x7CBF5380, "layer.13.proj_tmp_end"},
    {0x7CBF63C0, "layer.13.proj_scratch_end"},
    {0x7CBF7400, "layer.13.residual1_end"},
    {0x7CBF7680, "layer.13.ln2_gamma_end"},
    {0x7CBF86C0, "layer.13.ln2_out_end"},
    {0x7D150700, "layer.13.w1_end"},
    {0x7D3FC740, "layer.13.w2_end"},
    {0x7D3FD780, "layer.13.mlp_out_end"},
    {0x7D3FE7C0, "layer.13.output_end"},
    {0x7D3FE800, "layer_13_end"},
    {0x7D3FE840, "layer_14_start"},
    {0x7D3FEAC0, "layer.14.ln1_gamma_end"},
    {0x7D3FFB00, "layer.14.ln1_out_end"},
    {0x7D47DB40, "layer.14.wq_end"},
    {0x7D47DDC0, "layer.14.bq_end"},
    {0x7D48FE00, "layer.14.wk_end"},
    {0x7D48FF00, "layer.14.bk_end"},
    {0x7D4A1F40, "layer.14.wv_end"},
    {0x7D4A2040, "layer.14.bv_end"},
    {0x7D4A2E80, "layer.14.q_end"},
    {0x814A2EC0, "layer.14.k_end"},
    {0x854A2F00, "layer.14.v_end"},
    {0x85520F40, "layer.14.wo_end"},
    {0x85521F80, "layer.14.proj_tmp_end"},
    {0x85522FC0, "layer.14.proj_scratch_end"},
    {0x85524000, "layer.14.residual1_end"},
    {0x85524280, "layer.14.ln2_gamma_end"},
    {0x855252C0, "layer.14.ln2_out_end"},
    {0x85A7D300, "layer.14.w1_end"},
    {0x85D29340, "layer.14.w2_end"},
    {0x85D2A380, "layer.14.mlp_out_end"},
    {0x85D2B3C0, "layer.14.output_end"},
    {0x85D2B400, "layer_14_end"},
    {0x85D2B440, "layer_15_start"},
    {0x85D2B6C0, "layer.15.ln1_gamma_end"},
    {0x85D2C700, "layer.15.ln1_out_end"},
    {0x85DAA740, "layer.15.wq_end"},
    {0x85DAA9C0, "layer.15.bq_end"},
    {0x85DBCA00, "layer.15.wk_end"},
    {0x85DBCB00, "layer.15.bk_end"},
    {0x85DCEB40, "layer.15.wv_end"},
    {0x85DCEC40, "layer.15.bv_end"},
    {0x85DCFA80, "layer.15.q_end"},
    {0x89DCFAC0, "layer.15.k_end"},
    {0x8DDCFB00, "layer.15.v_end"},
    {0x8DE4DB40, "layer.15.wo_end"},
    {0x8DE4EB80, "layer.15.proj_tmp_end"},
    {0x8DE4FBC0, "layer.15.proj_scratch_end"},
    {0x8DE50C00, "layer.15.residual1_end"},
    {0x8DE50E80, "layer.15.ln2_gamma_end"},
    {0x8DE51EC0, "layer.15.ln2_out_end"},
    {0x8E3A9F00, "layer.15.w1_end"},
    {0x8E655F40, "layer.15.w2_end"},
    {0x8E656F80, "layer.15.mlp_out_end"},
    {0x8E657FC0, "layer.15.output_end"},
    {0x8E658000, "layer_15_end"},
    {0x8E658040, "layer_16_start"},
    {0x8E6582C0, "layer.16.ln1_gamma_end"},
    {0x8E659300, "layer.16.ln1_out_end"},
    {0x8E6D7340, "layer.16.wq_end"},
    {0x8E6D75C0, "layer.16.bq_end"},
    {0x8E6E9600, "layer.16.wk_end"},
    {0x8E6E9700, "layer.16.bk_end"},
    {0x8E6FB740, "layer.16.wv_end"},
    {0x8E6FB840, "layer.16.bv_end"},
    {0x8E6FC680, "layer.16.q_end"},
    {0x926FC6C0, "layer.16.k_end"},
    {0x966FC700, "layer.16.v_end"},
    {0x9677A740, "layer.16.wo_end"},
    {0x9677B780, "layer.16.proj_tmp_end"},
    {0x9677C7C0, "layer.16.proj_scratch_end"},
    {0x9677D800, "layer.16.residual1_end"},
    {0x9677DA80, "layer.16.ln2_gamma_end"},
    {0x9677EAC0, "layer.16.ln2_out_end"},
    {0x96CD6B00, "layer.16.w1_end"},
    {0x96F82B40, "layer.16.w2_end"},
    {0x96F83B80, "layer.16.mlp_out_end"},
    {0x96F84BC0, "layer.16.output_end"},
    {0x96F84C00, "layer_16_end"},
    {0x96F84C40, "layer_17_start"},
    {0x96F84EC0, "layer.17.ln1_gamma_end"},
    {0x96F85F00, "layer.17.ln1_out_end"},
    {0x97003F40, "layer.17.wq_end"},
    {0x970041C0, "layer.17.bq_end"},
    {0x97016200, "layer.17.wk_end"},
    {0x97016300, "layer.17.bk_end"},
    {0x97028340, "layer.17.wv_end"},
    {0x97028440, "layer.17.bv_end"},
    {0x97029280, "layer.17.q_end"},
    {0x9B0292C0, "layer.17.k_end"},
    {0x9F029300, "layer.17.v_end"},
    {0x9F0A7340, "layer.17.wo_end"},
    {0x9F0A8380, "layer.17.proj_tmp_end"},
    {0x9F0A93C0, "layer.17.proj_scratch_end"},
    {0x9F0AA400, "layer.17.residual1_end"},
    {0x9F0AA680, "layer.17.ln2_gamma_end"},
    {0x9F0AB6C0, "layer.17.ln2_out_end"},
    {0x9F603700, "layer.17.w1_end"},
    {0x9F8AF740, "layer.17.w2_end"},
    {0x9F8B0780, "layer.17.mlp_out_end"},
    {0x9F8B17C0, "layer.17.output_end"},
    {0x9F8B1800, "layer_17_end"},
    {0x9F8B1840, "layer_18_start"},
    {0x9F8B1AC0, "layer.18.ln1_gamma_end"},
    {0x9F8B2B00, "layer.18.ln1_out_end"},
    {0x9F930B40, "layer.18.wq_end"},
    {0x9F930DC0, "layer.18.bq_end"},
    {0x9F942E00, "layer.18.wk_end"},
    {0x9F942F00, "layer.18.bk_end"},
    {0x9F954F40, "layer.18.wv_end"},
    {0x9F955040, "layer.18.bv_end"},
    {0x9F955E80, "layer.18.q_end"},
    {0xA3955EC0, "layer.18.k_end"},
    {0xA7955F00, "layer.18.v_end"},
    {0xA79D3F40, "layer.18.wo_end"},
    {0xA79D4F80, "layer.18.proj_tmp_end"},
    {0xA79D5FC0, "layer.18.proj_scratch_end"},
    {0xA79D7000, "layer.18.residual1_end"},
    {0xA79D7280, "layer.18.ln2_gamma_end"},
    {0xA79D82C0, "layer.18.ln2_out_end"},
    {0xA7F30300, "layer.18.w1_end"},
    {0xA81DC340, "layer.18.w2_end"},
    {0xA81DD380, "layer.18.mlp_out_end"},
    {0xA81DE3C0, "layer.18.output_end"},
    {0xA81DE400, "layer_18_end"},
    {0xA81DE440, "layer_19_start"},
    {0xA81DE6C0, "layer.19.ln1_gamma_end"},
    {0xA81DF700, "layer.19.ln1_out_end"},
    {0xA825D740, "layer.19.wq_end"},
    {0xA825D9C0, "layer.19.bq_end"},
    {0xA826FA00, "layer.19.wk_end"},
    {0xA826FB00, "layer.19.bk_end"},
    {0xA8281B40, "layer.19.wv_end"},
    {0xA8281C40, "layer.19.bv_end"},
    {0xA8282A80, "layer.19.q_end"},
    {0xAC282AC0, "layer.19.k_end"},
    {0xB0282B00, "layer.19.v_end"},
    {0xB0300B40, "layer.19.wo_end"},
    {0xB0301B80, "layer.19.proj_tmp_end"},
    {0xB0302BC0, "layer.19.proj_scratch_end"},
    {0xB0303C00, "layer.19.residual1_end"},
    {0xB0303E80, "layer.19.ln2_gamma_end"},
    {0xB0304EC0, "layer.19.ln2_out_end"},
    {0xB085CF00, "layer.19.w1_end"},
    {0xB0B08F40, "layer.19.w2_end"},
    {0xB0B09F80, "layer.19.mlp_out_end"},
    {0xB0B0AFC0, "layer.19.output_end"},
    {0xB0B0B000, "layer_19_end"},
    {0xB0B0B040, "layer_20_start"},
    {0xB0B0B2C0, "layer.20.ln1_gamma_end"},
    {0xB0B0C300, "layer.20.ln1_out_end"},
    {0xB0B8A340, "layer.20.wq_end"},
    {0xB0B8A5C0, "layer.20.bq_end"},
    {0xB0B9C600, "layer.20.wk_end"},
    {0xB0B9C700, "layer.20.bk_end"},
    {0xB0BAE740, "layer.20.wv_end"},
    {0xB0BAE840, "layer.20.bv_end"},
    {0xB0BAF680, "layer.20.q_end"},
    {0xB4BAF6C0, "layer.20.k_end"},
    {0xB8BAF700, "layer.20.v_end"},
    {0xB8C2D740, "layer.20.wo_end"},
    {0xB8C2E780, "layer.20.proj_tmp_end"},
    {0xB8C2F7C0, "layer.20.proj_scratch_end"},
    {0xB8C30800, "layer.20.residual1_end"},
    {0xB8C30A80, "layer.20.ln2_gamma_end"},
    {0xB8C31AC0, "layer.20.ln2_out_end"},
    {0xB9189B00, "layer.20.w1_end"},
    {0xB9435B40, "layer.20.w2_end"},
    {0xB9436B80, "layer.20.mlp_out_end"},
    {0xB9437BC0, "layer.20.output_end"},
    {0xB9437C00, "layer_20_end"},
    {0xB9437C40, "layer_21_start"},
    {0xB9437EC0, "layer.21.ln1_gamma_end"},
    {0xB9438F00, "layer.21.ln1_out_end"},
    {0xB94B6F40, "layer.21.wq_end"},
    {0xB94B71C0, "layer.21.bq_end"},
    {0xB94C9200, "layer.21.wk_end"},
    {0xB94C9300, "layer.21.bk_end"},
    {0xB94DB340, "layer.21.wv_end"},
    {0xB94DB440, "layer.21.bv_end"},
    {0xB94DC280, "layer.21.q_end"},
    {0xBD4DC2C0, "layer.21.k_end"},
    {0xC14DC300, "layer.21.v_end"},
    {0xC155A340, "layer.21.wo_end"},
    {0xC155B380, "layer.21.proj_tmp_end"},
    {0xC155C3C0, "layer.21.proj_scratch_end"},
    {0xC155D400, "layer.21.residual1_end"},
    {0xC155D680, "layer.21.ln2_gamma_end"},
    {0xC155E6C0, "layer.21.ln2_out_end"},
    {0xC1AB6700, "layer.21.w1_end"},
    {0xC1D62740, "layer.21.w2_end"},
    {0xC1D63780, "layer.21.mlp_out_end"},
    {0xC1D647C0, "layer.21.output_end"},
    {0xC1D64800, "layer_21_end"},
    {0xC1D64840, "layer_22_start"},
    {0xC1D64AC0, "layer.22.ln1_gamma_end"},
    {0xC1D65B00, "layer.22.ln1_out_end"},
    {0xC1DE3B40, "layer.22.wq_end"},
    {0xC1DE3DC0, "layer.22.bq_end"},
    {0xC1DF5E00, "layer.22.wk_end"},
    {0xC1DF5F00, "layer.22.bk_end"},
    {0xC1E07F40, "layer.22.wv_end"},
    {0xC1E08040, "layer.22.bv_end"},
    {0xC1E08E80, "layer.22.q_end"},
    {0xC5E08EC0, "layer.22.k_end"},
    {0xC9E08F00, "layer.22.v_end"},
    {0xC9E86F40, "layer.22.wo_end"},
    {0xC9E87F80, "layer.22.proj_tmp_end"},
    {0xC9E88FC0, "layer.22.proj_scratch_end"},
    {0xC9E8A000, "layer.22.residual1_end"},
    {0xC9E8A280, "layer.22.ln2_gamma_end"},
    {0xC9E8B2C0, "layer.22.ln2_out_end"},
    {0xCA3E3300, "layer.22.w1_end"},
    {0xCA68F340, "layer.22.w2_end"},
    {0xCA690380, "layer.22.mlp_out_end"},
    {0xCA6913C0, "layer.22.output_end"},
    {0xCA691400, "layer_22_end"},
    {0xCA691440, "layer_23_start"},
    {0xCA6916C0, "layer.23.ln1_gamma_end"},
    {0xCA692700, "layer.23.ln1_out_end"},
    {0xCA710740, "layer.23.wq_end"},
    {0xCA7109C0, "layer.23.bq_end"},
    {0xCA722A00, "layer.23.wk_end"},
    {0xCA722B00, "layer.23.bk_end"},
    {0xCA734B40, "layer.23.wv_end"},
    {0xCA734C40, "layer.23.bv_end"},
    {0xCA735A80, "layer.23.q_end"},
    {0xCE735AC0, "layer.23.k_end"},
    {0xD2735B00, "layer.23.v_end"},
    {0xD27B3B40, "layer.23.wo_end"},
    {0xD27B4B80, "layer.23.proj_tmp_end"},
    {0xD27B5BC0, "layer.23.proj_scratch_end"},
    {0xD27B6C00, "layer.23.residual1_end"},
    {0xD27B6E80, "layer.23.ln2_gamma_end"},
    {0xD27B7EC0, "layer.23.ln2_out_end"},
    {0xD2D0FF00, "layer.23.w1_end"},
    {0xD2FBBF40, "layer.23.w2_end"},
    {0xD2FBCF80, "layer.23.mlp_out_end"},
    {0xD2FBDFC0, "layer.23.output_end"},
    {0xD2FBE000, "layer_23_end"},
    {0xD2FBE040, "footer_start"},
    {0xD2FBE2C0, "final_ln_weight_end"},
    {0xD2FBF300, "final_output_end"},
    {0xD3053940, "logits_end"},
    {0xD3053980, "footer_end"},
    {0xD40539C0, "rope_cos_cache_end"},
    {0xD5053A00, "rope_sin_cache_end"},
};
QWEN2_0_5B_DECODE_FOOTER
const QWEN2_0_5B_DECODEFooterOffsets QWEN2_0_5B_DECODE_FOOTER static
Initial value:
= {
    .final_ln_weight = 0xD2FBE080,
    .final_output = 0xD2FBE300,
    .lm_head_weight = 0x00000080,
    .logits = 0xD2FBF340,
}
Definition at line 661 of file v6.6/test_generated/ck-kernel-inference.h.
{
    .final_ln_weight = 0xD2FBE080,
    .final_output = 0xD2FBE300,
    .lm_head_weight = 0x00000080,  /* TIED to token_emb */
    .logits = 0xD2FBF340,
};
QWEN2_0_5B_DECODE_GLOBALS
const QWEN2_0_5B_DECODEGlobalOffsets QWEN2_0_5B_DECODE_GLOBALS static
Initial value:
= {
    .rope_cos_cache = 0xD30539C0,
    .rope_sin_cache = 0xD4053A00,
}
Definition at line 677 of file v6.6/test_generated/ck-kernel-inference.h.
{
    .rope_cos_cache = 0xD30539C0,
    .rope_sin_cache = 0xD4053A00,
};
QWEN2_0_5B_DECODE_HEADER
const QWEN2_0_5B_DECODEHeaderOffsets QWEN2_0_5B_DECODE_HEADER static
Initial value:
= {
    .token_emb = 0x00000080,
    .vocab_offsets = 0x053760C0,
    .vocab_strings = 0x0538AF40,
    .vocab_merges = 0x0538AF80,
    .embedded_input = 0x0538AFC0,
}
Definition at line 57 of file v6.6/test_generated/ck-kernel-inference.h.
{
    .token_emb = 0x00000080,
    .vocab_offsets = 0x053760C0,
    .vocab_strings = 0x0538AF40,
    .vocab_merges = 0x0538AF80,
    .embedded_input = 0x0538AFC0,
};
QWEN2_0_5B_DECODE_LAYERS
const QWEN2_0_5B_DECODELayerOffsets QWEN2_0_5B_DECODE_LAYERS[24] static
Definition at line 93 of file v6.6/test_generated/ck-kernel-inference.h.
{
    [0] = {
        .ln1_gamma = 0x0538C080,
        .ln1_out = 0x0538C300,
        .wq = 0x0538D340,
        .bq = 0x0540B380,
        .wk = 0x0540B600,
        .bk = 0x0541D640,
        .wv = 0x0541D740,
        .bv = 0x0542F780,
        .q = 0x0542F880,
        .k = 0x054306C0,
        .v = 0x09430700,
        .wo = 0x0D430740,
        .proj_tmp = 0x0D4AE780,
        .proj_scratch = 0x0D4AF7C0,
        .residual1 = 0x0D4B0800,
        .ln2_gamma = 0x0D4B1840,
        .ln2_out = 0x0D4B1AC0,
        .w1 = 0x0D4B2B00,
        .w2 = 0x0DA0AB40,
        .mlp_out = 0x0DCB6B80,
        .output = 0x0DCB7BC0,
    },
    [1] = {
        .ln1_gamma = 0x0DCB8C80,
        .ln1_out = 0x0DCB8F00,
        .wq = 0x0DCB9F40,
        .bq = 0x0DD37F80,
        .wk = 0x0DD38200,
        .bk = 0x0DD4A240,
        .wv = 0x0DD4A340,
        .bv = 0x0DD5C380,
        .q = 0x0DD5C480,
        .k = 0x0DD5D2C0,
        .v = 0x11D5D300,
        .wo = 0x15D5D340,
        .proj_tmp = 0x15DDB380,
        .proj_scratch = 0x15DDC3C0,
        .residual1 = 0x15DDD400,
        .ln2_gamma = 0x15DDE440,
        .ln2_out = 0x15DDE6C0,
        .w1 = 0x15DDF700,
        .w2 = 0x16337740,
        .mlp_out = 0x165E3780,
        .output = 0x165E47C0,
    },
    [2] = {
        .ln1_gamma = 0x165E5880,
        .ln1_out = 0x165E5B00,
        .wq = 0x165E6B40,
        .bq = 0x16664B80,
        .wk = 0x16664E00,
        .bk = 0x16676E40,
        .wv = 0x16676F40,
        .bv = 0x16688F80,
        .q = 0x16689080,
        .k = 0x16689EC0,
        .v = 0x1A689F00,
        .wo = 0x1E689F40,
        .proj_tmp = 0x1E707F80,
        .proj_scratch = 0x1E708FC0,
        .residual1 = 0x1E70A000,
        .ln2_gamma = 0x1E70B040,
        .ln2_out = 0x1E70B2C0,
        .w1 = 0x1E70C300,
        .w2 = 0x1EC64340,
        .mlp_out = 0x1EF10380,
        .output = 0x1EF113C0,
    },
    [3] = {
        .ln1_gamma = 0x1EF12480,
        .ln1_out = 0x1EF12700,
        .wq = 0x1EF13740,
        .bq = 0x1EF91780,
        .wk = 0x1EF91A00,
        .bk = 0x1EFA3A40,
        .wv = 0x1EFA3B40,
        .bv = 0x1EFB5B80,
        .q = 0x1EFB5C80,
        .k = 0x1EFB6AC0,
        .v = 0x22FB6B00,
        .wo = 0x26FB6B40,
        .proj_tmp = 0x27034B80,
        .proj_scratch = 0x27035BC0,
        .residual1 = 0x27036C00,
        .ln2_gamma = 0x27037C40,
        .ln2_out = 0x27037EC0,
        .w1 = 0x27038F00,
        .w2 = 0x27590F40,
        .mlp_out = 0x2783CF80,
        .output = 0x2783DFC0,
    },
    [4] = {
        .ln1_gamma = 0x2783F080,
        .ln1_out = 0x2783F300,
        .wq = 0x27840340,
        .bq = 0x278BE380,
        .wk = 0x278BE600,
        .bk = 0x278D0640,
        .wv = 0x278D0740,
        .bv = 0x278E2780,
        .q = 0x278E2880,
        .k = 0x278E36C0,
        .v = 0x2B8E3700,
        .wo = 0x2F8E3740,
        .proj_tmp = 0x2F961780,
        .proj_scratch = 0x2F9627C0,
        .residual1 = 0x2F963800,
        .ln2_gamma = 0x2F964840,
        .ln2_out = 0x2F964AC0,
        .w1 = 0x2F965B00,
        .w2 = 0x2FEBDB40,
        .mlp_out = 0x30169B80,
        .output = 0x3016ABC0,
    },
    [5] = {
        .ln1_gamma = 0x3016BC80,
        .ln1_out = 0x3016BF00,
        .wq = 0x3016CF40,
        .bq = 0x301EAF80,
        .wk = 0x301EB200,
        .bk = 0x301FD240,
        .wv = 0x301FD340,
        .bv = 0x3020F380,
        .q = 0x3020F480,
        .k = 0x302102C0,
        .v = 0x34210300,
        .wo = 0x38210340,
        .proj_tmp = 0x3828E380,
        .proj_scratch = 0x3828F3C0,
        .residual1 = 0x38290400,
        .ln2_gamma = 0x38291440,
        .ln2_out = 0x382916C0,
        .w1 = 0x38292700,
        .w2 = 0x387EA740,
        .mlp_out = 0x38A96780,
        .output = 0x38A977C0,
    },
    [6] = {
        .ln1_gamma = 0x38A98880,
        .ln1_out = 0x38A98B00,
        .wq = 0x38A99B40,
        .bq = 0x38B17B80,
        .wk = 0x38B17E00,
        .bk = 0x38B29E40,
        .wv = 0x38B29F40,
        .bv = 0x38B3BF80,
        .q = 0x38B3C080,
        .k = 0x38B3CEC0,
        .v = 0x3CB3CF00,
        .wo = 0x40B3CF40,
        .proj_tmp = 0x40BBAF80,
        .proj_scratch = 0x40BBBFC0,
        .residual1 = 0x40BBD000,
        .ln2_gamma = 0x40BBE040,
        .ln2_out = 0x40BBE2C0,
        .w1 = 0x40BBF300,
        .w2 = 0x41117340,
        .mlp_out = 0x413C3380,
        .output = 0x413C43C0,
    },
    [7] = {
        .ln1_gamma = 0x413C5480,
        .ln1_out = 0x413C5700,
        .wq = 0x413C6740,
        .bq = 0x41444780,
        .wk = 0x41444A00,
        .bk = 0x41456A40,
        .wv = 0x41456B40,
        .bv = 0x41468B80,
        .q = 0x41468C80,
        .k = 0x41469AC0,
        .v = 0x45469B00,
        .wo = 0x49469B40,
        .proj_tmp = 0x494E7B80,
        .proj_scratch = 0x494E8BC0,
        .residual1 = 0x494E9C00,
        .ln2_gamma = 0x494EAC40,
        .ln2_out = 0x494EAEC0,
        .w1 = 0x494EBF00,
        .w2 = 0x49A43F40,
        .mlp_out = 0x49CEFF80,
        .output = 0x49CF0FC0,
    },
    [8] = {
        .ln1_gamma = 0x49CF2080,
        .ln1_out = 0x49CF2300,
        .wq = 0x49CF3340,
        .bq = 0x49D71380,
        .wk = 0x49D71600,
        .bk = 0x49D83640,
        .wv = 0x49D83740,
        .bv = 0x49D95780,
        .q = 0x49D95880,
        .k = 0x49D966C0,
        .v = 0x4DD96700,
        .wo = 0x51D96740,
        .proj_tmp = 0x51E14780,
        .proj_scratch = 0x51E157C0,
        .residual1 = 0x51E16800,
        .ln2_gamma = 0x51E17840,
        .ln2_out = 0x51E17AC0,
        .w1 = 0x51E18B00,
        .w2 = 0x52370B40,
        .mlp_out = 0x5261CB80,
        .output = 0x5261DBC0,
    },
    [9] = {
        .ln1_gamma = 0x5261EC80,
        .ln1_out = 0x5261EF00,
        .wq = 0x5261FF40,
        .bq = 0x5269DF80,
        .wk = 0x5269E200,
        .bk = 0x526B0240,
        .wv = 0x526B0340,
        .bv = 0x526C2380,
        .q = 0x526C2480,
        .k = 0x526C32C0,
        .v = 0x566C3300,
        .wo = 0x5A6C3340,
        .proj_tmp = 0x5A741380,
        .proj_scratch = 0x5A7423C0,
        .residual1 = 0x5A743400,
        .ln2_gamma = 0x5A744440,
        .ln2_out = 0x5A7446C0,
        .w1 = 0x5A745700,
        .w2 = 0x5AC9D740,
        .mlp_out = 0x5AF49780,
        .output = 0x5AF4A7C0,
    },
    [10] = {
        .ln1_gamma = 0x5AF4B880,
        .ln1_out = 0x5AF4BB00,
        .wq = 0x5AF4CB40,
        .bq = 0x5AFCAB80,
        .wk = 0x5AFCAE00,
        .bk = 0x5AFDCE40,
        .wv = 0x5AFDCF40,
        .bv = 0x5AFEEF80,
        .q = 0x5AFEF080,
        .k = 0x5AFEFEC0,
        .v = 0x5EFEFF00,
        .wo = 0x62FEFF40,
        .proj_tmp = 0x6306DF80,
        .proj_scratch = 0x6306EFC0,
        .residual1 = 0x63070000,
        .ln2_gamma = 0x63071040,
        .ln2_out = 0x630712C0,
        .w1 = 0x63072300,
        .w2 = 0x635CA340,
        .mlp_out = 0x63876380,
        .output = 0x638773C0,
    },
    [11] = {
        .ln1_gamma = 0x63878480,
        .ln1_out = 0x63878700,
        .wq = 0x63879740,
        .bq = 0x638F7780,
        .wk = 0x638F7A00,
        .bk = 0x63909A40,
        .wv = 0x63909B40,
        .bv = 0x6391BB80,
        .q = 0x6391BC80,
        .k = 0x6391CAC0,
        .v = 0x6791CB00,
        .wo = 0x6B91CB40,
        .proj_tmp = 0x6B99AB80,
        .proj_scratch = 0x6B99BBC0,
        .residual1 = 0x6B99CC00,
        .ln2_gamma = 0x6B99DC40,
        .ln2_out = 0x6B99DEC0,
        .w1 = 0x6B99EF00,
        .w2 = 0x6BEF6F40,
        .mlp_out = 0x6C1A2F80,
        .output = 0x6C1A3FC0,
    },
    [12] = {
        .ln1_gamma = 0x6C1A5080,
        .ln1_out = 0x6C1A5300,
        .wq = 0x6C1A6340,
        .bq = 0x6C224380,
        .wk = 0x6C224600,
        .bk = 0x6C236640,
        .wv = 0x6C236740,
        .bv = 0x6C248780,
        .q = 0x6C248880,
        .k = 0x6C2496C0,
        .v = 0x70249700,
        .wo = 0x74249740,
        .proj_tmp = 0x742C7780,
        .proj_scratch = 0x742C87C0,
        .residual1 = 0x742C9800,
        .ln2_gamma = 0x742CA840,
        .ln2_out = 0x742CAAC0,
        .w1 = 0x742CBB00,
        .w2 = 0x74823B40,
        .mlp_out = 0x74ACFB80,
        .output = 0x74AD0BC0,
    },
    [13] = {
        .ln1_gamma = 0x74AD1C80,
        .ln1_out = 0x74AD1F00,
        .wq = 0x74AD2F40,
        .bq = 0x74B50F80,
        .wk = 0x74B51200,
        .bk = 0x74B63240,
        .wv = 0x74B63340,
        .bv = 0x74B75380,
        .q = 0x74B75480,
        .k = 0x74B762C0,
        .v = 0x78B76300,
        .wo = 0x7CB76340,
        .proj_tmp = 0x7CBF4380,
        .proj_scratch = 0x7CBF53C0,
        .residual1 = 0x7CBF6400,
        .ln2_gamma = 0x7CBF7440,
        .ln2_out = 0x7CBF76C0,
        .w1 = 0x7CBF8700,
        .w2 = 0x7D150740,
        .mlp_out = 0x7D3FC780,
        .output = 0x7D3FD7C0,
    },
    [14] = {
        .ln1_gamma = 0x7D3FE880,
        .ln1_out = 0x7D3FEB00,
        .wq = 0x7D3FFB40,
        .bq = 0x7D47DB80,
        .wk = 0x7D47DE00,
        .bk = 0x7D48FE40,
        .wv = 0x7D48FF40,
        .bv = 0x7D4A1F80,
        .q = 0x7D4A2080,
        .k = 0x7D4A2EC0,
        .v = 0x814A2F00,
        .wo = 0x854A2F40,
        .proj_tmp = 0x85520F80,
        .proj_scratch = 0x85521FC0,
        .residual1 = 0x85523000,
        .ln2_gamma = 0x85524040,
        .ln2_out = 0x855242C0,
        .w1 = 0x85525300,
        .w2 = 0x85A7D340,
        .mlp_out = 0x85D29380,
        .output = 0x85D2A3C0,
    },
    [15] = {
        .ln1_gamma = 0x85D2B480,
        .ln1_out = 0x85D2B700,
        .wq = 0x85D2C740,
        .bq = 0x85DAA780,
        .wk = 0x85DAAA00,
        .bk = 0x85DBCA40,
        .wv = 0x85DBCB40,
        .bv = 0x85DCEB80,
        .q = 0x85DCEC80,
        .k = 0x85DCFAC0,
        .v = 0x89DCFB00,
        .wo = 0x8DDCFB40,
        .proj_tmp = 0x8DE4DB80,
        .proj_scratch = 0x8DE4EBC0,
        .residual1 = 0x8DE4FC00,
        .ln2_gamma = 0x8DE50C40,
        .ln2_out = 0x8DE50EC0,
        .w1 = 0x8DE51F00,
        .w2 = 0x8E3A9F40,
        .mlp_out = 0x8E655F80,
        .output = 0x8E656FC0,
    },
    [16] = {
        .ln1_gamma = 0x8E658080,
        .ln1_out = 0x8E658300,
        .wq = 0x8E659340,
        .bq = 0x8E6D7380,
        .wk = 0x8E6D7600,
        .bk = 0x8E6E9640,
        .wv = 0x8E6E9740,
        .bv = 0x8E6FB780,
        .q = 0x8E6FB880,
        .k = 0x8E6FC6C0,
        .v = 0x926FC700,
        .wo = 0x966FC740,
        .proj_tmp = 0x9677A780,
        .proj_scratch = 0x9677B7C0,
        .residual1 = 0x9677C800,
        .ln2_gamma = 0x9677D840,
        .ln2_out = 0x9677DAC0,
        .w1 = 0x9677EB00,
        .w2 = 0x96CD6B40,
        .mlp_out = 0x96F82B80,
        .output = 0x96F83BC0,
    },
    [17] = {
        .ln1_gamma = 0x96F84C80,
        .ln1_out = 0x96F84F00,
        .wq = 0x96F85F40,
        .bq = 0x97003F80,
        .wk = 0x97004200,
        .bk = 0x97016240,
        .wv = 0x97016340,
        .bv = 0x97028380,
        .q = 0x97028480,
        .k = 0x970292C0,
        .v = 0x9B029300,
        .wo = 0x9F029340,
        .proj_tmp = 0x9F0A7380,
        .proj_scratch = 0x9F0A83C0,
        .residual1 = 0x9F0A9400,
        .ln2_gamma = 0x9F0AA440,
        .ln2_out = 0x9F0AA6C0,
        .w1 = 0x9F0AB700,
        .w2 = 0x9F603740,
        .mlp_out = 0x9F8AF780,
        .output = 0x9F8B07C0,
    },
    [18] = {
        .ln1_gamma = 0x9F8B1880,
        .ln1_out = 0x9F8B1B00,
        .wq = 0x9F8B2B40,
        .bq = 0x9F930B80,
        .wk = 0x9F930E00,
        .bk = 0x9F942E40,
        .wv = 0x9F942F40,
        .bv = 0x9F954F80,
        .q = 0x9F955080,
        .k = 0x9F955EC0,
        .v = 0xA3955F00,
        .wo = 0xA7955F40,
        .proj_tmp = 0xA79D3F80,
        .proj_scratch = 0xA79D4FC0,
        .residual1 = 0xA79D6000,
        .ln2_gamma = 0xA79D7040,
        .ln2_out = 0xA79D72C0,
        .w1 = 0xA79D8300,
        .w2 = 0xA7F30340,
        .mlp_out = 0xA81DC380,
        .output = 0xA81DD3C0,
    },
    [19] = {
        .ln1_gamma = 0xA81DE480,
        .ln1_out = 0xA81DE700,
        .wq = 0xA81DF740,
        .bq = 0xA825D780,
        .wk = 0xA825DA00,
        .bk = 0xA826FA40,
        .wv = 0xA826FB40,
        .bv = 0xA8281B80,
        .q = 0xA8281C80,
        .k = 0xA8282AC0,
        .v = 0xAC282B00,
        .wo = 0xB0282B40,
        .proj_tmp = 0xB0300B80,
        .proj_scratch = 0xB0301BC0,
        .residual1 = 0xB0302C00,
        .ln2_gamma = 0xB0303C40,
        .ln2_out = 0xB0303EC0,
        .w1 = 0xB0304F00,
        .w2 = 0xB085CF40,
        .mlp_out = 0xB0B08F80,
        .output = 0xB0B09FC0,
    },
    [20] = {
        .ln1_gamma = 0xB0B0B080,
        .ln1_out = 0xB0B0B300,
        .wq = 0xB0B0C340,
        .bq = 0xB0B8A380,
        .wk = 0xB0B8A600,
        .bk = 0xB0B9C640,
        .wv = 0xB0B9C740,
        .bv = 0xB0BAE780,
        .q = 0xB0BAE880,
        .k = 0xB0BAF6C0,
        .v = 0xB4BAF700,
        .wo = 0xB8BAF740,
        .proj_tmp = 0xB8C2D780,
        .proj_scratch = 0xB8C2E7C0,
        .residual1 = 0xB8C2F800,
        .ln2_gamma = 0xB8C30840,
        .ln2_out = 0xB8C30AC0,
        .w1 = 0xB8C31B00,
        .w2 = 0xB9189B40,
        .mlp_out = 0xB9435B80,
        .output = 0xB9436BC0,
    },
    [21] = {
        .ln1_gamma = 0xB9437C80,
        .ln1_out = 0xB9437F00,
        .wq = 0xB9438F40,
        .bq = 0xB94B6F80,
        .wk = 0xB94B7200,
        .bk = 0xB94C9240,
        .wv = 0xB94C9340,
        .bv = 0xB94DB380,
        .q = 0xB94DB480,
        .k = 0xB94DC2C0,
        .v = 0xBD4DC300,
        .wo = 0xC14DC340,
        .proj_tmp = 0xC155A380,
        .proj_scratch = 0xC155B3C0,
        .residual1 = 0xC155C400,
        .ln2_gamma = 0xC155D440,
        .ln2_out = 0xC155D6C0,
        .w1 = 0xC155E700,
        .w2 = 0xC1AB6740,
        .mlp_out = 0xC1D62780,
        .output = 0xC1D637C0,
    },
    [22] = {
        .ln1_gamma = 0xC1D64880,
        .ln1_out = 0xC1D64B00,
        .wq = 0xC1D65B40,
        .bq = 0xC1DE3B80,
        .wk = 0xC1DE3E00,
        .bk = 0xC1DF5E40,
        .wv = 0xC1DF5F40,
        .bv = 0xC1E07F80,
        .q = 0xC1E08080,
        .k = 0xC1E08EC0,
        .v = 0xC5E08F00,
        .wo = 0xC9E08F40,
        .proj_tmp = 0xC9E86F80,
        .proj_scratch = 0xC9E87FC0,
        .residual1 = 0xC9E89000,
        .ln2_gamma = 0xC9E8A040,
        .ln2_out = 0xC9E8A2C0,
        .w1 = 0xC9E8B300,
        .w2 = 0xCA3E3340,
        .mlp_out = 0xCA68F380,
        .output = 0xCA6903C0,
    },
    [23] = {
        .ln1_gamma = 0xCA691480,
        .ln1_out = 0xCA691700,
        .wq = 0xCA692740,
        .bq = 0xCA710780,
        .wk = 0xCA710A00,
        .bk = 0xCA722A40,
        .wv = 0xCA722B40,
        .bv = 0xCA734B80,
        .q = 0xCA734C80,
        .k = 0xCA735AC0,
        .v = 0xCE735B00,
        .wo = 0xD2735B40,
        .proj_tmp = 0xD27B3B80,
        .proj_scratch = 0xD27B4BC0,
        .residual1 = 0xD27B5C00,
        .ln2_gamma = 0xD27B6C40,
        .ln2_out = 0xD27B6EC0,
        .w1 = 0xD27B7F00,
        .w2 = 0xD2D0FF40,
        .mlp_out = 0xD2FBBF80,
        .output = 0xD2FBCFC0,
    },
};