v6.6_cli.c File Reference
CK ← Back to C-Kernel-Engine Docs Doxygen Source Documentation
v6.6_cli.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include <limits.h>
#include <unistd.h>
#include "ckernel_engine.h"
Macros
#define _GNU_SOURCE
#define ANSI_BLUE "\033[0;34m"
#define ANSI_BOLD "\033[1m"
#define ANSI_CYAN "\033[0;36m"
#define ANSI_DIM "\033[2m"
#define ANSI_GREEN "\033[0;32m"
#define ANSI_RESET "\033[0m"
#define ANSI_YELLOW "\033[0;33m"
#define CK_BUILD_DATE __DATE__
#define CK_VERSION "6.0.0"
Functions
int main (int argc, char **argv)
static CLIArgs parse_args (int argc, char **argv)
static void print_banner (void)
static void print_help (const char *prog)
static void print_progress (int token_id, float token_per_sec)
static void print_version (void)
static char * read_prompt_file (const char *path)
static int sample_token (float *logits, int vocab_size, float temp, int top_k)
static int32_t * tokenize (const char *text, int *num_tokens)
Macro Definition Documentation
_GNU_SOURCE
#define _GNU_SOURCE
Definition at line 26 of file v6.6_cli.c.
ANSI_BLUE
#define ANSI_BLUE "\033[0;34m"
Definition at line 48 of file v6.6_cli.c.
ANSI_BOLD
#define ANSI_BOLD "\033[1m"
Definition at line 44 of file v6.6_cli.c.
ANSI_CYAN
#define ANSI_CYAN "\033[0;36m"
Definition at line 49 of file v6.6_cli.c.
ANSI_DIM
#define ANSI_DIM "\033[2m"
Definition at line 45 of file v6.6_cli.c.
ANSI_GREEN
#define ANSI_GREEN "\033[0;32m"
Definition at line 46 of file v6.6_cli.c.
ANSI_RESET
#define ANSI_RESET "\033[0m"
Definition at line 43 of file v6.6_cli.c.
ANSI_YELLOW
#define ANSI_YELLOW "\033[0;33m"
Definition at line 47 of file v6.6_cli.c.
CK_BUILD_DATE
#define CK_BUILD_DATE __DATE__
Definition at line 40 of file v6.6_cli.c.
CK_VERSION
#define CK_VERSION "6.0.0"
Definition at line 39 of file v6.6_cli.c.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 255 of file v6.6_cli.c.
{
     CLIArgs args = parse_args(argc, argv);
     /* Print banner */
     if (!args.verbose) {
         print_banner();
     }
     /* Validate arguments */
     if (!args.model_path) {
         fprintf(stderr, ANSI_YELLOW "Error:" ANSI_RESET " No model specified\n");
         fprintf(stderr, "Use " ANSI_BOLD "-m <model>" ANSI_RESET " or " ANSI_BOLD "--help" ANSI_RESET "\n");
         return 1;
     }
     /* Check if model file exists */
     if (access(args.model_path, F_OK) != 0) {
         fprintf(stderr, ANSI_YELLOW "Error:" ANSI_RESET " Model file not found: %s\n", args.model_path);
         return 1;
     }
     /* Read prompt */
     char *prompt = read_prompt_file(args.prompt);
     /* Set random seed */
     if (args.seed < 0) {
         args.seed = (int)time(NULL);
     }
     srand(args.seed);
     /* Print inference parameters */
     printf(ANSI_BOLD "Parameters:" ANSI_RESET "\n");
     printf("  Model:     " ANSI_CYAN "%s" ANSI_RESET "\n", args.model_path);
     printf("  Prompt:    \"" ANSI_YELLOW "%s" ANSI_RESET "\"\n", prompt);
     printf("  Tokens:    %d\n", args.max_tokens);
     printf("  Temp:      %.2f\n", args.temperature);
     printf("  Top-p:     %.2f\n", args.top_p);
     printf("  Top-k:     %d\n", args.top_k);
     printf("  Seed:      %d\n", args.seed);
     printf("  Threads:   %d\n", args.threads > 0 ? args.threads : 4);
     printf("\n");
     /* Start generation */
     printf(ANSI_BOLD "Output:" ANSI_RESET "\n");
     printf(ANSI_YELLOW);
     fflush(stdout);
     /* Placeholder inference - in real impl would load model and run */
     printf("<Model loading would happen here>\n");
     printf("<Inference would run here>\n");
     printf("\n");
     /* Demo output */
     printf(ANSI_RESET);
     printf(ANSI_BOLD "Note:" ANSI_RESET " This is v6 placeholder CLI.\n");
     printf("Full model loading and inference requires:\n");
     printf("  1. Generated model code from IR\n");
     printf("  2. All kernel implementations compiled\n");
     printf("  3. Weight loading from GGUF/BUMP\n");
     printf("\n");
     /* Cleanup */
     if (prompt != args.prompt) {
         free(prompt);
     }
     return 0;
 }
References ANSI_BOLD, ANSI_CYAN, ANSI_RESET, ANSI_YELLOW, parse_args(), print_banner(), and read_prompt_file().
parse_args()
static CLIArgs parse_args (int argc, char ** argv) static
Definition at line 113 of file v6.6_cli.c.
{
     CLIArgs args = {
         .model_path = NULL,
         .prompt = "Hello",
         .max_tokens = 100,
         .temperature = 0.7f,
         .top_p = 0.9f,
         .top_k = 40,
         .seed = -1,
         .threads = 0,
         .kv_cache = 1,
         .ignore_eos = 0,
         .verbose = 0,
     };
     for (int i = 1; i < argc; i++) {
         if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
             print_banner();
             print_help(argv[0]);
             exit(0);
         }
         if (strcmp(argv[i], "-v") == 0 || strcmp(argv[i], "--version") == 0) {
             print_version();
             exit(0);
         }
         if ((strcmp(argv[i], "-m") == 0 || strcmp(argv[i], "--model") == 0) && i + 1 < argc) {
             args.model_path = argv[++i];
         }
         else if ((strcmp(argv[i], "-p") == 0 || strcmp(argv[i], "--prompt") == 0) && i + 1 < argc) {
             args.prompt = argv[++i];
         }
         else if ((strcmp(argv[i], "-t") == 0) && i + 1 < argc) {
             args.max_tokens = atoi(argv[++i]);
         }
         else if (strcmp(argv[i], "--temp") == 0 && i + 1 < argc) {
             args.temperature = atof(argv[++i]);
         }
         else if (strcmp(argv[i], "--top-p") == 0 && i + 1 < argc) {
             args.top_p = atof(argv[++i]);
         }
         else if (strcmp(argv[i], "--top-k") == 0 && i + 1 < argc) {
             args.top_k = atoi(argv[++i]);
         }
         else if (strcmp(argv[i], "--seed") == 0 && i + 1 < argc) {
             args.seed = atoi(argv[++i]);
         }
         else if (strcmp(argv[i], "--threads") == 0 && i + 1 < argc) {
             args.threads = atoi(argv[++i]);
         }
         else if (strcmp(argv[i], "--no-kv-cache") == 0) {
             args.kv_cache = 0;
         }
         else if (strcmp(argv[i], "--ignore-eos") == 0) {
             args.ignore_eos = 1;
         }
         else if (strcmp(argv[i], "--verbose") == 0 || strcmp(argv[i], "-v") == 0) {
             args.verbose = 1;
         }
         else {
             fprintf(stderr, "Unknown option: %s\n", argv[i]);
             fprintf(stderr, "Use --help for usage\n");
             exit(1);
         }
     }
     return args;
 }
References print_banner(), print_help(), and print_version().
Referenced by main().
print_banner()
static void print_banner (void) static
Definition at line 67 of file v6.6_cli.c.
{
     printf(ANSI_CYAN);
     printf("\n");
     printf("  C-Kernel-Engine\n");
     printf("  ------------------------------\n");
     printf(ANSI_RESET);
     printf(ANSI_DIM);
     printf("  v%s - %s - Native C Implementation\n", CK_VERSION, CK_BUILD_DATE);
     printf("  " ANSI_GREEN "https://github.com/antshiv/C-Kernel-Engine" ANSI_RESET "\n");
     printf("\n");
 }
References ANSI_CYAN, ANSI_DIM, ANSI_GREEN, ANSI_RESET, CK_BUILD_DATE, and CK_VERSION.
Referenced by main(), and parse_args().
print_help()
static void print_help (const char * prog) static
Definition at line 80 of file v6.6_cli.c.
{
     printf(ANSI_BOLD "usage:" ANSI_RESET " %s [options]\n\n", prog);
     printf(ANSI_BOLD "options:" ANSI_RESET "\n");
     printf("  -m, --model <file>       Model file (GGUF or BUMP)\n");
     printf("  -p, --prompt <text>      Prompt (use @file.txt to read from file)\n");
     printf("  -t, --tokens <n>         Max tokens to generate (default: 100)\n");
     printf("  -t, --temp <float>       Temperature (default: 0.7)\n");
     printf("      --top-p <float>      Top-p sampling (default: 0.9)\n");
     printf("      --top-k <n>          Top-k sampling (default: 40)\n");
     printf("      --seed <n>           Random seed (default: random)\n");
     printf("      --threads <n>        Number of threads (default: auto)\n");
     printf("      --no-kv-cache        Disable KV cache\n");
     printf("      --ignore-eos         Ignore EOS token\n");
     printf("      --verbose            Verbose output\n");
     printf("  -v, --version            Show version\n");
     printf("  -h, --help               Show this help\n");
     printf("\n");
     printf(ANSI_BOLD "examples:" ANSI_RESET "\n");
     printf("  %s -m model.gguf -p \"Hello\"\n", prog);
     printf("  %s -m model.gguf -p @prompt.txt -t 50 --temp 0.8\n", prog);
     printf("  %s -m model.gguf --seed 42 --verbose\n", prog);
     printf("\n");
 }
References ANSI_BOLD, and ANSI_RESET.
Referenced by parse_args().
print_progress()
static void print_progress (int token_id, float token_per_sec) static
Definition at line 244 of file v6.6_cli.c.
{
     static time_t last_time = 0;
     time_t now = time(NULL);
     if (now - last_time >= 1) {
         printf(ANSI_DIM "[ %.1f tok/s ]" ANSI_RESET "\r", token_per_sec);
         fflush(stdout);
         last_time = now;
     }
 }
References ANSI_DIM, and ANSI_RESET.
print_version()
static void print_version (void) static
Definition at line 105 of file v6.6_cli.c.
{
     printf(ANSI_BOLD "C-Kernel-Engine" ANSI_RESET " v" CK_VERSION "\n");
     printf("Build: " CK_BUILD_DATE "\n");
     printf("C标准: " ANSI_YELLOW "C11" ANSI_RESET "\n");
     printf("OMP支持: " ANSI_YELLOW "Yes" ANSI_RESET "\n");
 }
References ANSI_BOLD, ANSI_RESET, ANSI_YELLOW, CK_BUILD_DATE, and CK_VERSION.
Referenced by parse_args().
read_prompt_file()
static char* read_prompt_file (const char * path) static
Definition at line 182 of file v6.6_cli.c.
{
     if (path[0] != '@') return (char *)path;
     FILE *f = fopen(path + 1, "r");
     if (!f) {
         fprintf(stderr, "Cannot open prompt file: %s\n", path + 1);
         return (char *)path;
     }
     char *content = malloc(4096);
     size_t len = fread(content, 1, 4095, f);
     content[len] = '\0';
     fclose(f);
     // Remove trailing newlines
     while (len > 0 && (content[len-1] == '\n' || content[len-1] == '\r')) {
         content[--len] = '\0';
     }
     return content;
 }
Referenced by main().
sample_token()
static int sample_token (float * logits, int vocab_size, float temp, int top_k) static
Definition at line 215 of file v6.6_cli.c.
{
     float max_val = logits[0];
     for (int i = 1; i < vocab_size; i++) {
         if (logits[i] > max_val) max_val = logits[i];
     }
     float sum = 0.0f;
     for (int i = 0; i < vocab_size; i++) {
         logits[i] = expf((logits[i] - max_val) / temp);
         sum += logits[i];
     }
     // Top-k filter
     int start = vocab_size > top_k ? vocab_size - top_k : 0;
     // Simple argmax
     float best_val = logits[start];
     int best_idx = start;
     for (int i = start + 1; i < vocab_size; i++) {
         if (logits[i] > best_val) {
             best_val = logits[i];
             best_idx = i;
         }
     }
     return best_idx;
 }
References start, and vocab_size.
tokenize()
static int32_t* tokenize (const char * text, int * num_tokens) static
Definition at line 205 of file v6.6_cli.c.
{
     static int32_t tokens[1024];
     *num_tokens = strlen(text);
     for (int i = 0; i < *num_tokens && i < 1024; i++) {
         tokens[i] = (int32_t)text[i];
     }
     return tokens;
 }
References text.